DoSomething/rogue

database/migrations/2016_07_26_175053_create_reportback_table.php, database/migrations/2016_07_27_144623_create_reportback_item_table.php, database/migrations/2016_07_27_165841_reportback_log.php, database/migrations/2016_07_27_172344_create_kudos_table.php, pull_request_template.md, readme.md
This PR adds migrations to the Rogue app to start to flush out the db structure. The goal is to have the db work just like it currently does now. 
Tables added:
* `reportback`
* `reportback_log`
* `reportback_item` formally known as `dosomething_reportback_file`
* `kudos`
Set up the app and run the migrations. The migrations should run smoothly. Compare the tables created to their corresponding tables in phoenix and the column settings should match up.
Wasn't sure about how to handle northstar ids. I decided that, like in gladiator, since the user table will be storing northstar ids, we should just call columns that store northstar ids `user_id` 
To keep things consistent, I put `user_id` wherever `uid` is stored so we can have references to the northstar user on those tables, open to …
=> Add migrations

composer.json, readme.md
Two little house cleaning things. 
* Removed a trailing comma that was causing `composer install` to bug out
* Updated the readme to include the step of running `npm install`
=> remove traling comma

app/Http/Transformers/ReportbackItemTransformer.php, tests/ReportbackApiTest.php
updates `ReportbackItemTransformer.php` to group `file_id` and `file_url` under `media` to avoid long list of file properties and mirrors RB items resource endpoint. 
Run all tests again to make sure it works, similar to https://github.com/DoSomething/rogue/pull/25
Refs #https://github.com/DoSomething/rogue/pull/25#discussion-diff-76612494
=> changes transformer to group reportbackItem info in media array

app/Services/AWS.php
Corrected the AWS URL to point to correct URL where image is stored. 
To manually test:
- Log into your local. 
- Sign up for a campaign. 
- Go to your "My Account" page. 
- See that you are signed up for that campaign.
- Post reportback via postman for that campaign and campaign run, with your `drupal_id`. 
- Refresh your "My Account" page and make sure the campaign has been moved from "YOU'RE DOING" to "YOU DID" and that your reportback photo correctly shows up instead of a broken image icon. 
Example Postman request: 
Fixes [this user story](https://trello.com/c/PV5hS3ts/9-as-a-developer-i-want-the-images-transferring-from-rogue-to-phoenix-to-not-be-broken).
=> fixes url to find correct place where image is stored

app/Services/AWS.php, tests/ReportbackApiTest.php, tests/TestCase.php
We now use the `Storage` facade to interact with AWS so we can use more laravel 🔮  and mock the call to put the uploaded files on AWS. Doing this also allowed us to delete some things.
I think the best way to test is to first try to post a reportback and make sure your file still goes to AWS. Then, remove all the aws/s3 credentials from your `.env` and make sure the tests pass. This insures that the mock is working as expected. Don't forget to add your credentials back in.
no tickets created
cc: @chloealee and shoutout to @DFurnes for his Otwellian Magic
=> use storage facade to mock sending files to aws

app/Http/Controllers/Api/ReportbackController.php, app/Jobs/SendReportbackToPhoenix.php, app/Services/ReportbackService.php, tests/ReportbackApiTest.php
- Sends updated reportback and new reportback items to Phoenix 
- Fixes bug that takes information from first reportback item instead of reportback item that was most recently created
- Updates comment and test function name to add more specificity. 
- In Postman, create a new reportback. Make sure this is in both Rogue and Phoenix. 
- Create a new reportback item. Make sure this is also in both Rogue and Phoenix. 
- Update the `why_participated` field and make sure this is reflected in Rogue and Phoenix. 
Fixes #44
With help from @katiecrane !
=> Sends updated reportback and new reportback items to phoenix

app/Jobs/SendReportbackToPhoenix.php, app/Services/AuthorizesWithPhoenix.php, app/Services/Phoenix.php
- Updates Rogue to use Gateway traits to use Transactional IDs when making and receiving requests. 
- `POST` to Rogue's `/reportbacks` endpoint and add any value for `X-Request-ID` header. 
- Check Laravel logs - Transactional ID message should be there! 
Fixes #47 
with @katiecrane !
=> Adds Transactional ID logic 

app/Http/Transformers/ReportbackItemTransformer.php, app/Models/Reaction.php, app/Models/Reportback.php, app/Models/ReportbackItem.php, app/Repositories/ReportbackRepository.php, composer.json, composer.lock, database/factories/ModelFactory.php, database/migrations/2016_10_11_200630_drop_file_id_from_reportback_items_table.php, database/migrations/2016_10_11_200952_drop_file_id_from_reactions.php, database/migrations/2016_10_11_201943_drop_reaction_reportback_table.php, database/migrations/2016_10_11_202519_create_reaction_reportback_item_table.php, database/seeds/DatabaseSeeder.php, database/seeds/ReportbackItemSeeder.php, database/seeds/ReportbackLogSeeder.php, documentation/reportbacks.md, tests/ReportbackApiTest.php, tests/TestCase.php
* Removes references to `file_id` in rogue which was referencing the `fid` as it was stored in drupal. We do not need to store this anymore since rogue does it's own file storage. 
* Updates the previously defined `Reaction` to `Reportback` many-to-many relationship to be a `Reaction` to `ReportbackItem` relationship since reactions actually live on items.
* Added a step to the `ReportbackItem` seeder that will give the item a reaction so we have some data to play with.
pull down this branch, reset, re-migrate and re-seed your database.
`php artisan migrate:refresh --seed` 
all should run well, and you should not see any `file_id` columns in your db.
You can also try out the relationship by grabbing a Reaction from the database and running something like: 
`dd($reaction->reportackItems);` …
=> Remove file_id column

app/Http/Transformers/ReportbackItemTransformer.php, app/Jobs/SendReportbackToPhoenix.php, app/Models/ReportbackItem.php, app/Repositories/ReportbackRepository.php, app/Services/ReportbackService.php, app/helpers.php, composer.json, composer.lock, config/app.php, database/migrations/2016_10_24_180026_add_cropped_image_column_to_items.php, tests/TestCase.php
* Stores the original image in S3 and also crops and rotates it and stores that new image in a new `edited_file_url` column on the item so we can have both. 
* Exposes both file urls in the response like:
* Sends the edited file back to phoenix.
I tried to make the commits clear, so you should be able to review commit by commit. 
Run the unit tests!
Post a reportback (or new item) to rogue with cropping properites (`crop_x`, `crop_y`, `crop_height`, `crop_width`, `crop_rotate`). The orginal file should get stored in `file_url` and the cropped file should be stored in `edited_file_url`
Started a helper file to start extracting some helper functions. I put the image cropping stuff in there cause it didn't feel like anything should really own that. But open to other thoughts on that. 
Also …
=> Image crop & rotate

database/factories/ModelFactory.php, database/migrations/2016_11_14_193858_remove_review_source_from_items_table.php
Mainly removes the `review_source` column from the `reportback_items`table
Also found a small small bug when trying to `db:seed` we updated the `reactions` table but didn't fix the model factory for it, so i just fixed it quick in this PR
run `php artisan migrate` 
Did the migration run? great.
Is the `remove_source` column removed from the `reportback_items` table? great. 
Fixes #69
=> Remove review source column

app/Repositories/ReportbackRepository.php, database/migrations/2016_11_14_172450_update_reportback_items_reviewer_type.php
Phoenix is already sending the reportback reviewer's northstar id (https://github.com/DoSomething/phoenix/pull/7192). This grabs the `reviewer` that was sent and saves it to the reportback item. Also includes a migration to change the type of the `reviewer` column to accept northstar ids (previously setup to accept drupal ids).
Does the reviewer get set correctly? Does the full NS id show up in the database?
Fixes #72
=> set reportback item reviewer

app/Http/Controllers/Api/ReportbackController.php, app/Http/Kernel.php, app/Http/Middleware/LogReceivedRequest.php, app/Http/routes.php, app/Jobs/SendReportbackToPhoenix.php, app/Services/ReportbackService.php, app/helpers.php
- Adds global helper function to increment transaction id. 
- Adds middleware to log incoming requests. 
- In Postman, add `X-Request-ID` header and testing value (e.g. `test-0` - important to add `-0` to the end to make sure it is incrementing correctly)
- Hit the following endpoints: 
- `POST /reportbacks`
- One to make a new reportback. 
- Second to add a new reportback item. 
- `PUT /items`
- `POST /reactions` 
- Check the laravel logs. 
- When `POST`ing a new reportback, logs should look as follows: 
```
[2016-11-16 18:50:20] local.INFO: Request received. Transaction ID: 1478814474.test-1
[2016-11-16 18:50:21] local.INFO: Request made. {"method":"POST","Transaction ID":"1478814474.test-2","Path":"//dev.dosomething.org:8888/api/v1/auth/login"}
[2016-11-16 18:50:21] local.INFO: Request …
```
=> Log transaction id when a request is received

app/Jobs/SendReportbackToPhoenix.php, app/Services/ReportbackService.php
Reportback images no longer duplicate with every single update to a reportback! 
However, there is a case where the image is still duplicated which stems from how Phoenix checks to see if a new image was added. As far as I can tell, that case is just when you:
1. create a reportback or submit an update with a new image
2. hit the permalink page
3. hit back to return to the campaign page, do not refresh and do not wait to long!
4. change the something in the form but do not add a new image
5. submit again
6. return to the campaign page to see the duplicated image
I couldn't find any differences in the `$form_state` or anything in Phoenix that would hint at it being a new image rather than a duplicated one. 
Submit a new reportback, and make sure you can make updates to the quantity and the …
=> only send newly added files to Phoenix

app/Http/Controllers/UsersController.php, app/Http/routes.php, app/Repositories/CacheRepository.php, app/Services/Registrar.php, app/helpers.php, resources/views/users/index.blade.php, resources/views/users/partials/_table_users.blade.php, tests/ReportbackApiTest.php, tests/UserTest.php
Creates the system of grabbing user information in Rogue. 
First we try to grab user information that we stored in cache, if they aren't found there we grab them directly from Northstar. 
This work is based largely on @weerd 's work in Gladiator. The Gladiator system is a little more complicated since we actually store users in Gladiator, but in Rogue we just store references to northstar ids in the reportbacks table. 
So what this sets up is a `Registrar` service that handles the logic of resolving users in northstar vs cache. We also have a `CacheRepository` class that handles the storing/grabbing cache logic [(based on this)](https://github.com/DoSomething/gladiator/blob/master/app/Repositories/CacheStorage.php) 
This also sets up a view at `/users` to just list the users in the users …
=> Get user info

app/Jobs/SendReportbackToPhoenix.php
Rogue was already [setting the `remote_addr`](https://github.com/DoSomething/rogue/blob/master/app/Http/Transformers/ReportbackItemTransformer.php#L31) it was getting from Phoenix. Now, we also send this value back to Phoenix.
Try hardcoding this address as something and make sure it makes it to Phoenix.
This works in conjunction with https://github.com/DoSomething/phoenix/pull/7243, but I don't think the order of merging/deploying matters to not break anything. Both must be merged for it to actually work as expected though.
Fixes #84
=> send remote address to Phoenix

app/Http/Controllers/Api/ReportbackController.php, documentation/endpoints/reportbackitems.md
- Updates `/items` documentation to add requirement of `reviewer`.
- Updates `/items` validation to make sure that `reviewer` is required.
Try to hit the `/items` endpoint without a reviewer. Should get error: `{"0.reviewer":["The 0.reviewer field is required."]}`
Fixes #90
=> updates documnetation and adds reviewer to requirement in validation

app/Exceptions/Handler.php, app/Http/Controllers/Api/PostsController.php, app/Http/Requests/PostRequest.php, app/Http/Transformers/PostTransformer.php, app/Jobs/SendPostToPhoenix.php, app/Models/Event.php, app/Models/Photo.php, app/Models/Post.php, app/Models/Signup.php, app/Repositories/PhotoRepository.php, app/Services/PostService.php, database/migrations/2017_01_06_185724_create_posts_table.php, database/migrations/2017_01_09_165856_remove_event_id_from_photos.php
This is a proof of concept PR that implements a [Polymorphic](https://laravel.com/docs/5.3/eloquent-relationships#polymorphic-relations) Relationship between "Posts" and a post sub-type like a `photo`. 
Before a "Post" wasn't a real thing which means we didn't have a unifying way to deal with different types of posts. While they are different content, they serve the similar purpose and we didn't have a great way of tying them together. With this work, we can do things like have a `PostTransformer` for all posts so they have a standard response regardless of type. Or, we can find all posts for a signup across all types. 
- we have a `Post` table that holds the thing that in common with all posts: `event_id`, `signup_id` 
- There is a polymorphic relationship defined on the `Post` and …
=> Polymorphic post

database/migrations/2017_01_18_193205_add_log_columns_to_events_table.php
Adds columns to the `events` table to log changes in the system. 
Run migrations, get new columns, rollback migration, lose new columns
Address #100
=> Add columns to the events table to log atomic changes

app/Http/Controllers/Api/PostsController.php, app/Http/Transformers/PostTransformer.php, app/Models/Post.php, app/Repositories/PhotoRepository.php, database/migrations/2017_01_18_205404_move_northstar_id_column_to_posts.php, database/migrations/2017_01_18_205748_drop_northstar_id_from_photos_table.php
Moves the `northstar_id` associated with posts to the `posts` table instead of it living on the item record. Also updates the functionality of storing posts, to store the `northstar_id` on the `posts` record. 
Run migrations, see that `northstar_id` is now on the `posts` table and not on the `photos` table.
Also hit the new `/posts` endpoint and the post should be created with the `northstar_id` living on the post record. 
Fixes #102
=> Move northstar_id to posts table

app/Repositories/PhotoRepository.php
Adds the missing `$signupId` as a param to the `crop` function. 
Hit the `/posts` endpoint and all should be working.
- Without this, nothing is returned as the response and the following error is thrown: `[2017-01-20 15:58:47] local.ERROR: exception 'ErrorException' with message 'Undefined variable: signupId' in /home/vagrant/DoSomething.org/rogue/app/Repositories/PhotoRepository.php:90`
=> adds missing $signupId param

app/Jobs/SendPostToPhoenix.php
- Adds the `Registrar` in `SendPostToPhoenix.php` in order to send `drupal_id` (right now it is hard coded). 
- Changes `quantity` to send `quantity_pending` instead since `quantity` will be `NULL` and we want to send user's reported quantity to Phoenix. 
Hit `/posts` endpoint and all should work correctly.
=> changes quantity to quantity_pending and removes hard coded uid

app/Http/Controllers/Api/PostsController.php, app/Http/Requests/PostRequest.php, app/Http/Transformers/PhotoTransformer.php, app/Http/routes.php, app/Jobs/SendPostToPhoenix.php, app/Jobs/SendReportbackToPhoenix.php, app/Repositories/PhotoRepository.php, app/Services/PostService.php, app/Services/ReportbackService.php, documentation/README.md, documentation/endpoints/posts.md, documentation/endpoints/reviews.md
- Adds update functionality to update a signup (`why_participated` and `quantity`)
- Adds update functionality to add a new photo post to a signup 
- Adds `/reviews` endpoint to update a photo(s)'s status when reviewed by an admin
This should be tested with [corresponding Phoenix work](https://github.com/DoSomething/phoenix/pull/7295).
1.Change Rogue API version number field to v2 in the Phoenix Rogue API settings.
2.  Run `drush ubdb` in drupal to reflect new database changes.
Make sure all information matches up between Phoenix and Rogue databases for below scenarios:
- Create a new signup (RB) and photo (reportback item) from Phoenix web.
- Add another photo (rb item).
- Add another photo (rb item) and update the signup (reportback's quantity and why_participated).
- Only update the …
=> Adds /reviews endpoint to update photo(s)'s status when it gets reviewed and updates signups/photos 

app/Http/Requests/PostRequest.php, app/Models/Event.php, app/Repositories/PhotoRepository.php, app/Services/PostService.php
- Added capability for more `event_types`. Now there are: 
- `signup`
- `post_photo`
- `update_signup`
- `review_photo` 
- When an event gets added to the `events` table, more information (columns) are filled out. 
- `why_participated` and `quantity_pending` columns are filled with an `update_signup` event.
- `caption` and `status` columns are filled with a `post_photo` event. 
- for both, `northstar_id`, `submission_type`, `remote_addr`, and timestamp columns are filled out. 
- Makes the `resolvePostRepository` function more flexible. Now, it determines which repository to use by looking at what comes after the `_` - e.g. determines a type is a `photo` if `post_photo` is sent in. This allows for `review_photo` etc. 
- Creates two separate events for when a signup is updated (for now, …
=> Adds more details in events table, makes resolvePostRepository function more flexible, and creates two events for update signup and posting a photo

app/Http/Controllers/Api/ReportbackController.php, app/Http/Controllers/Api/ReviewsController.php, app/Repositories/ReportbackRepository.php
Adds checks to make sure variables are set to determine which Service class to go to and to prevent errors. 
- Find a reportback item in the `reportback_items` table in the Rogue database that has not yet been reviewed. 
- Review the reportback item in Phoenix and make sure it gets updated in Rogue and doesn't enter into the `dosomething_rogue_failed_task_log`.
- Find a photo in the `photos` table in the Rogue database that has not yet been reviewed. 
- Review the reportback item in Phoenix and make sure it gets updated in Rogue and doesn't enter into the `dosomething_rogue_failed_task_log`,
- Make sure cron job is working properly.
Phoenix was not receiving a `$response` because it was always sending to both the Reportback Service and Post Service, even if only reportback item objects …
=> Reportback review bug take 2

app/Models/Event.php, app/Repositories/PhotoRepository.php, app/Repositories/SignupRepository.php, database/migrations/2017_02_09_165430_add_signup_id_to_events_table.php
This is several small fixes in one! These are things that were either blocking migration work, or that needed to be fixed to make sure the migration is working correctly.
1. Handles receiving broken images
2. Adds `signup_id` to `events` table and populates this field
3. Populates the `quantity`, `why_participated`, etc. fields in the `events` table for `signup` events
👀 
1. Broken images shouldn't break anything and should get `file_url` set as `default`
2. When a `signup` or `post_photo` event is created, the `signup_id` should appear in the `events` table.
3. When a `signup` event occurs, the submitted data should appear in the `events` table.
Fixes #122
Fixes #123
=> handle missing images, add signup_id to events table, populate event columns

database/migrations/2017_02_10_154746_make_signup_id_in_events_table_nullable.php
Added a new migration to allow the `signup_id` column in the `events` table to be `NULL`. Currently, we created the event first, then created the signup, and then add the signup id to the event. Now, when there is no `signup_id` set the value will be `NULL` instead of `0`.
Create a signup event without setting the `signup_id`. That column should be `NULL`.
Slack conversation starts [here](https://dosomething.slack.com/archives/rogue/p1486738492000208)
Fixes #125
=> Allow signup_id in the events table to be NULL

app/Repositories/PhotoRepository.php
If the image is broken we don't even try to set `$editedImage` because there will be no such thing, but that means we can't try to use it later!
If there is no image, does anything break? Does it try to use any variables that don't exist?
Fixes #127
=> Check if editedImage is set before we use it

app/Repositories/PhotoRepository.php, app/Repositories/SignupRepository.php
Allows for backdating of:
- posts
- photos
- events
When timestamp parameters are passed. This is so the migration has more accurate timestamps.
Make sure this still lets Laravel do the timestamps unless we pass `created_at` or `updated_at`.
Fixes #131
=> Backdating posts, photos, and events

app/Repositories/SignupRepository.php
Two small changes:
1.  For the migration, I needed to be able to set either `quantity` or `quantity_pending` on signups, and not just default to `quantity_pending`. I can't think of any case where the system sending signups to Rogue does not know whether or not the value is the `quantity` or the `quantity_pending`.
2. Fixed some logic to make sure even signup events with timestamps get their `signup_id` put in that column.
Make sure 1. above is a change that makes sense for the future. Otherwise, I can do some more hacking to make it work for the migration! The signups documentation already reflects this behavior though.
Fixes #137
=> Allow post to /signups to set quantity

app/Http/Controllers/Api/ReactionController.php, app/Http/Requests/ReactionRequest.php, app/Http/Transformers/ReactionTransformer.php, app/Http/routes.php, app/Models/Post.php, app/Models/Reaction.php, database/migrations/2017_02_22_210956_update_reactions_table_to_include_postable_id_and_postable_type.php, documentation/README.md, documentation/endpoints/reactions.md
- Moves `/reactions` endpoint to v2
- Updates Reaction Model to accept `postable_id` and `postable_type` instead of `reportback_item_id`
- Updates Reaction equest validation.
- Updates Reaction relation to Post Model.
- Creates a migration to update the `reactions` table with `postable_id` and `postable_type`
- Updates Reaction Controller to:
- include `postable_id` and `postable_type` in logic
- include a query to find total reactions for a post 
- Updates Reaction Transformer to return `postable_id` and `postable_type` instead of `reportback_item_id`. Also returns total reactions in `meta` data.
- Hit `/reactions` endpoint and response should look like the following:
```
{
"data": {
"reaction_id": "21",
"northstar_id": "8888",
"postable_id": "352", …
```
=> Reactions tally

app/Services/AWS.php
Included a hash of the image in the photo url to avoid duplicate filenames. The filename already included the timestamp, but during the migration those could be too similar!
👀  should be good!
During the migration I noticed that some photos that were all under the same signup all showed the same image, even thought they were different in Phoenix. Some digging showed the the script was sending over different images.
=> Include hash of image data in file name

tests/SignupApiTest.php
Added the first test for `/signup`! It tests creating a new signup with the bare minimum parameters (I figure this is what this endpoint will mainly be used for as things stand now). 
See if this test tests what I said it does and if you think there are any more tests that could be applied to `/signups`.
I didn't test the functionality of passing a photo with the signup because that will not be used outside of data migration. I thought about doing a test with `why_participated` and things, but I don't think that would ever all be passed at one time in the wild.
Fixes #109
=> Add test for creating a new signup

database/migrations/2017_03_09_192255_add_signup_id_index_to_events_table.php
Added a signup_id index on the events table!
I tested by migrating and rolling back and migrating and making sure the index appeared and disappeared and appeared. You can probably just 👀 
Somewhere deep in the guts of what happens in Rogue when we migrate, this query happens:
```
select * from `events` where `events`.`signup_id` = ? and `events`.`signup_id` is not null`
```
So with no index, as the events table grew, everything got slower. This should help with that! Plus, with how we now will want to get events per signup, we are going to want this anyway.
=> Add migration to make a signup_id index on the events table

app/Http/Controllers/Api/ApiController.php, app/Http/Transformers/SignupTransformer.php, app/Http/Transformers/UserTransformer.php, documentation/endpoints/activity.md
Adds the ability to include an optional parameter to bundle the user info with the request. As of now, the user info provided is just the first name. To have this included, just put `include=user` in your request.
I'm not crazy about having to pass the empty array here `return $this->transform($resource, $code, [], $include)` in `ApiController.php`, but I couldn't figure out any other way to pass the `include` info to the transformer. Is anyone else bothered by this or have any thoughts on how to avoid this weirdness?
This is to be used in the gallery 📸 !
Fixes #157
=> Optionally embed user info in activity response

app/Models/Post.php
Somehow, I accidentally pushed up the `withReactionCount` model function in Post.php. This removes this code that we don't use. 
👀
=> removes withReactionCount model function

app/Http/Controllers/CampaignsController.php, resources/assets/components/InboxItem/index.js, resources/assets/helpers.js
Pulls the user information at the same time that we get the signup and posts for a certain campaign run. The user info is nested under each post. Then, the following are displayed on the front end:
- `first_name`
- `last_name`
- age (there is a helper to calculate this from the `birthdate` returned by Northstar)
- `email`
- `mobile` phone number
It looks like this (my account doesn't have a mobile number so there is a blank where the phone number would be):
👀  See if it looks okay and if I am calculating age correctly.
There's nothing being conditionally displayed right now, so if a member doesn't have a mobile number stored with us, there is still a blank space for it instead of shifting everything up.
Fixes #183
=> Pass user info to the front end and display it

resources/assets/components/InboxItem/index.js
- Adds a tertiary "Delete" button to delete a post so it's not stored in the database. 
👀 
The button should look like this (is it ok it's off center?):
Another option I think could be cool and be extra obvious to not click is the `-danger` button as seen in Aurora:
Would we prefer the `-danger` button instead? A couple thoughts:
- This is no longer in Forge - does this mean we don't want to use it anymore? 
- The `-danger` button has more clickable area than the `-tertiary` button. Since it's located right under the `ACCEPTED` button, it might cause more room for error, making it easier for an admin to accidentally hit `Delete` instead. 
Fixes #186
=> adds tertiary button to delete a post 

app/Http/Controllers/Api/PostsController.php, app/Http/Requests/PostRequest.php, app/Http/Transformers/PhotoTransformer.php, app/Http/Transformers/PostTransformer.php, app/Http/Transformers/SignupTransformer.php, app/Models/Event.php, app/Models/Post.php, app/Providers/ModelServiceProvider.php, app/Repositories/PhotoRepository.php, app/Repositories/SignupRepository.php, app/Services/PostService.php, config/app.php, tests/ActivityApiTest.php, tests/PostApiTest.php, tests/SignupApiTest.php
Moves out all the manual event creation logic out of the `SignupRepository` and `PhotoRepository`  and moves it into a service provider that automatically creates events when the model is saved (which is triggered on creation and update).
Updates tests to work with this new logic/event schema. NOTE: reviews tests still fail but wanted to work on that separately to keep this contained. 
This can probably be reviewed commit by commit. It's a little hairy to read because there was a lot of deletions. 
We also need a lot of testing on this to make sure everything still works as expected. The testing will be easier when this is deployed on QA.
Fixes #167
=> New event logic

app/Http/Controllers/Api/ReportbackController.php, app/Http/Transformers/ReportbackTransformer.php
Added a `select` statement to our query to make sure the `id` column is the `post` id, which meant that I also needed to include every other field that we need.
Also grabs the `url` instead of `file_url` since the column is `url` now.
Make sure you have the right `id`s in the right places. Make sure the `url` is not `null`.
Because we were joining `signups` and `posts` on `signups.id` = `posts.signup_id`, the `id` that ended up in the response belonged to the `signup`. 
Fixes #204
=> /reportbacks - Use new schema and return correct post id

database/factories/ModelFactory.php, database/seeds/ActivitySeeder.php
Now that we have removed the `photos` table, this PR removes the seeder logic to populate that table. 
Instead we create 20 signups and create one post for each one. 
Commit by commit
We can certainly build on what exactly we want the seeded data to look like. For example, should we vary the amount of posts each signup has to make it more realistic? But that doesn't seem like a priority at the moment. 
Fixes #196
=> Update activity seeder

resources/assets/components/InboxItem/InboxTile.js, resources/assets/components/InboxItem/index.js, resources/assets/helpers.js
On the inbox page, underneath a post, we now show all the other posts under that signup. They are tiny and adorable. I made a new component called `InboxTile` and they are all arranged in to a [quartet gallery](http://forge.dosomething.org/#gallery-quartet).
Does it visually look right and does the way I handled the data make sense?
Fixes #211
=> Show all posts underneath the current post

app/Http/Controllers/CampaignsController.php, app/Models/Post.php, app/Services/CampaignService.php, app/Services/Phoenix.php, resources/assets/components/CampaignTable/index.js, resources/assets/components/Table/Row.js, resources/assets/components/Table/index.js
Creates a `CampaignService` that first looks for campaigns in cache, if it finds them then loads them from there, if it doesn't find them then it makes a request to phoenix for the campaign info. 
Grabs a set of campaign ids for each signup we have in rogue. Gets their full campaign object, groups them by cause, and passes it to the frontend to render overview tables. 
We could probably think of better ways to grab the campaigns we are interested in. I will be looking into this when trying to figure out post counts based on status. For now, I am just grabbing them directly from the DB. 
The `CampaignService` class and the `Registrar` class are very similar and I would like to look into how to extract some of the shared logic. 
Fixes #151
=> Campaign overview with data

app/Http/Controllers/Api/ReportbackController.php, app/Http/Transformers/ReactionTransformer.php, app/Http/Transformers/ReportbackTransformer.php, documentation/endpoints/reactions.md, documentation/endpoints/reportbacks.md
Updated `GET /reportbacks` endpoint to activate reaction buttons in gallery for posts that the logged in user has liked. In order to do so, the `/reportbacks`endpoint now includes:
- adds `as_user` param to return if the logged in user has liked the post or not.
- `reacted` in response to be `true` or `false` if logged in user has reacted to post.
- adds `exclude` param to exclude posts in response.
- updates documentation
Response from this endpoint should now look as follows and you should be able to use `filter=[exclude]`:
```
{
"data": [
{
"id": 2,
"status": "approved",
"caption": "post 2",
"event_id": 4,
"media": {
"uri": "https://s3.amazonaws.com/ds-rogue-prod/uploads/reportback-items/1-676c9c02029df581d3668ae869d937b8-1491250786.jpeg",
"type": "image"
},
"created_at": …
```
=> Update /reportbacks endpoint for reaction gallery work

app/Repositories/PostRepository.php
Orient an uploaded file using [Intervention Image's `Orientate()`](http://image.intervention.io/api/orientate) method before storing to s3. 
Full disclosure, I am not sure this is needed. I have uploaded various photos via the `/posts` api endpoint, including a photo that was tagged as rotating incorrectly before, and it seems to working fine in rogue. 
However, this should safe guard us if something is weird. 
Also, this is very hard to test. I haven't been able to fine a photo that is uploading/displaying incorrectly so it is hard to tell if this is working as expected. 
Fixes #220
=> Auto-Orient photo

app/Http/Controllers/CampaignsController.php, app/Http/routes.php, app/Models/Signup.php, app/Services/CampaignService.php, composer.lock, resources/assets/components/CampaignInbox/index.js, resources/assets/components/CampaignTable/index.js, resources/assets/components/Table/Row.js, resources/assets/components/Table/index.js, resources/views/layouts/nav.blade.php
Adds the number of pending, accepted, and rejected posts there are for each campaign on the campaign overview page. 
* Creates new relationships on `Signup` to define relationships to posts with a particular status.
* Adds some local query scopes to `Signup` to define some commonly used queries including one that will include the number of accepted, rejected, and pending posts on each signup retrieved.
* Adds a method on the `CampaignService` that sums up the status counts for a campaign
* Passes this info to the frontend and display it.
* Links the pending count to the inbox page
- *Note on this* - dealing with campaign runs was becoming increasingly difficult. For one, we only get the current run from the phoenix API so we would have to do some work on that end to get all runs back. …
=> Overview aggregates

app/Http/Controllers/Api/ApiController.php, app/Http/Controllers/Api/ReportbackController.php, app/Http/Transformers/PaginatorForPhoenixAshesGallery.php, documentation/endpoints/reportbacks.md
Adds customization in order for Rogue to power the gallery and more closely mimic Phoenix's `/reportbacks` response. 
- In the response, Phoenix expects `next_uri` instead of just `uri` for the `/reportbacks` endpoint - this adds this just to this endpoint. 
Hit `/reportbacks` and check out the pagination. It should look like this: 
```
"meta": {
"pagination": {
"total": 24,
"count": 4,
"per_page": 20,
"current_page": 2,
"total_pages": 2,
"links": {
"previous_uri": "http://rogue.dev:8000/api/v1/reportbacks?as_user=5589c991a59dbfa93d8b45ae&page=1"
}
}
}
```
Relates to work here: https://github.com/DoSomething/phoenix/pull/7356
=> Pagination For Phoenix Gallery 

app/Http/Requests/PostRequest.php, app/Repositories/PostRepository.php
1. Updated 2 validation rules:
- `status` - fixed it to make sure that the status is any of `pending`, `accepted`, `rejected`
- caveat: potentially in the future when posts come in, they will all be `pending`, so we may want to remove this rule and have Rogue automatically assign `pending` to incoming posts
- `remote_addr` - updated to make sure it is a string, since it is sometimes a list of IPs 
2. When checking for an image, we can't just check if `data['file']` is empty, because broken images will come over with that value as `null`, so we get false negatives using `empty`. Instead, check if the `$data` array has a key `file` to see if the requester tried to send a file at all.
👀 
These fixes were necessary for the keeper upper script.
=> Some /posts fixes that are needed for keeper upper and also life

app/Http/Transformers/PostTransformer.php, app/Http/Transformers/SignupTransformer.php, app/Repositories/PostRepository.php, app/Services/PostService.php, tests/PostApiTest.php, tests/UserTest.php
Makes some updates in the code base so that `quantity` is stored in the `quantity` column on the `signups` table. 
We have two columns on the `signups` table: `quantity` and `quantity_pending`. We originally discussed storing quantity in the "pending" column until an admin reviewed it but that was proving more complicated and also wasn't inline with recent thinking. So we are only going to utilize the `quantity` column for now. Anything previously stored in `quantity_pending` will be migrated to `quantity` at a later time. 
Fixes #177
=> Quantity pending

database/migrations/2017_04_27_183942_drop_unique_northstar_id_index_reactions_table.php
Drops the unique key in the `reactions` table for the `northstar_user` column.
👀 
When we renamed the table from `kudos` to `reactions` we forgot to drop indexes (more info. [here](https://dosomething.slack.com/?redir=%2Farchives%2FC0YGXUE01%2Fp1493318041448517))
We need to fix this for Reactions to work when Rogue is powering the Phoenix-Ashes gallery to allow a user to react to more than one post. https://github.com/DoSomething/phoenix/pull/7366
=> drops unique key in reactions table for northstar_user

app/Repositories/PostRepository.php
Allow capability to backdate updates to signups, meaning when the quantity or why gets updated. These updates will be coming in through the keeper upper script so we will want to preserve the original signups for this type of update. It only backdates the signup if it comes in with an `updated_at` parameter.
I made sure the events stuff all still worked properly, but that's the part I'd be most worried about I think.
=> Allow backdating signup updates

app/Http/Controllers/Api/ReviewsController.php, app/Http/Requests/ReviewsRequest.php, app/Models/Review.php, app/Providers/ModelServiceProvider.php, app/Repositories/PostRepository.php, database/migrations/2017_04_28_180204_update-reviews-table.php, database/migrations/2017_04_28_180204_update-reviews_table.php, documentation/endpoints/reviews.md, tests/ReviewsApiTest.php
Updates `/reviews` endpoint and reviews tests. 
-Hit the `/reviews` endpoint
- The post you reviewed should have the updated status in the `posts` table.
- The information should be added in the `reviews` table with all expected info. 
- Two events should be logged - one for the review and one for updated post. 
- Run `vendor/bin/phpunit --filter=Reviews` to make sure all tests are passing and/or `vendor/bin/phpunit` to make sure all tests are still passing! 
Fixes #171
=> Update /reviews endpoint and reviews test 

package.json, resources/assets/components/CampaignInbox/index.js, resources/assets/components/InboxItem/index.js
- Adds @dosomething/babel-config package.
- Brings individual post state to top level of campaign inbox.
- Adds pseudo code to set up RestApiClient and make call to `/reactions` endpoint.
- Click `Accepted` or `Rejected` button in campaign inbox page. 
- In React dev tools, you should be able to see updated status for each post: 
First part to organize data to review a post and save it in the database (setting up the state so we know what state is and can refresh the page).
Refs #242
=> First part to save review of post in the database

app/Http/Middleware/VerifyCsrfToken.php, documentation/README.md, documentation/endpoints/reviews.md, resources/assets/components/CampaignInbox/index.js, tests/PostApiTest.php
- Passes CSFR token in request
- Updates `/reviews` documentation
- Makes API call to `/reviews` when a post is reviewed to update the post's status and create a review in the reviews table 
- Irrelevant to this issue but saw that the `PostApiTest` was broken because we are no longer sending Posts to Phoenix. Got rid of that mocked job to make sure all tests are still passing! 
- Go to a campaign inbox page. 
- Accept a post and see in the database that the post's status has been updated and a review has been created. 
- On the same post, reject the post - you should again see the post status has been updated and a new review has been created. 
- Make sure all tests still pass. 
Just a note - we have functionality to send a comment to the `/reviews` endpoint and enter in the reviews table …
=> Apply status to post once reviewed

resources/assets/components/CampaignInbox/index.js, resources/assets/components/HistoryModal/index.js
This is a magical time. When an admin opens the history modal, they can update the quantity and hit "Save" to see the quantity update on the post (and all other posts under that same signup). Gif ⬇️ 
Questions:
1. @sbsmith86 mentioned that we should disable the save button until the admin has entered something into the new quantity form. I think this is a good idea, but I'm not sure if that's out of scope for this or not?
2. We should probably have some validation on the form so admins can't enter "platypus" for quantity because currently they are able to. Is that in scope?
3. I believe in grooming on Wednesday we will talk about how to deal with logging events of admins updating quantity and sending the admin's Northstar ID to `/posts`.
4. On the card it says to write tests for this, but …
=> Let admins update quantity

resources/assets/components/CampaignInbox/index.js, resources/assets/components/InboxItem/index.js
Hooked up the "delete" button to the backend so it makes a request to delete the post. Works the same way as opening the history modal, except instead of `showHistory` it calls `deletePost` when the button is clicked.
Click the delete button and see the post leave the page. If you refresh the page, the post should not reappear (meaning that it is really soft deleted in the db).
Fixes #262
=> Hook up the delete button to the backend

resources/assets/components/CampaignInbox/index.js
Adds logic to only send the request to delete the post if the admin confirms that they want to delete it.
Could anyone accidentally delete a post without hitting "OK" in the confirmation pop-up?
[Trello card](https://trello.com/c/ui1DljOC/335-2-as-a-rogue-user-i-want-to-be-asked-to-confirm-deleting-the-post-so-that-my-actions-are-questioned)
=> Confirm intent to delete before deleting

app/Http/Controllers/Api/PostsController.php, app/Http/Controllers/Api/ReactionController.php, app/Http/Controllers/Api/SignupsController.php, app/Http/Controllers/PostController.php, app/Http/routes.php, documentation/endpoints/posts.md, resources/assets/components/CampaignInbox/index.js, tests/PostApiTest.php, tests/PostTest.php, tests/ReactionsApiTest.php, tests/SignupApiTest.php, tests/TestCase.php
So, apparently we already had `AuthenticatAPI` middleware but we just were not using it. This PR:
* Uses the `auth.api` middleware on all the api routes. We were using the `api` middleware but this wasn't defined and did nothing. 
* moves the posts `DELETE` endpoint to the web route group and splits out it's functionality into it's own `PostController` that authenticates the request and deletes the post
* Updates tests accordingly 
commit by commit should work!
Fixes #236
=> Auth API middleware

app/Models/Post.php, app/Models/Reaction.php, app/Models/Review.php, database/factories/ModelFactory.php, tests/PostTest.php, tests/ReactionsApiTest.php, tests/ReviewsTest.php
- Adds `touches` to Post Model, Reaction Model, and Review Model to update their parents' `updated_at` timestamp when they are updated. 
- Writes tests to make sure everything is working. 
- Updates `Reaction` model factory.
- Make sure all tests pass! 
When a post is tagged or untagged, the post's nor the signup's `updated_at` will not change. Do we want this to happen? Not sure if this is applicable to Quasar/Looker. Also, we would have to change the model in laravel-tagging to do this as well as the `tagging_tagged` table to include timestamps.
cc @ngjo @sheyd @jamjensen 
Fixes #271
=> Signup timestamp updates when posts, reviews, or reactions are made. 

resources/assets/components/StatusButton/index.js
We want the button names to be actionable (Accept, Reject) instead of showcasing AcceptED or RejectED. This is a stupid hack that just removes the last two letters from the button text without messing up the actual prop.
Literally all it does is slice a string
Check the button text in Rogue reviewing, and then check the database to make sure it's still creating "accepted' and "rejected" entries.
This is a uh....short term solution.
=> Slices the last two characters off the button text

documentation/endpoints/activity.md
Updates the `post` part of the response to have the same `signup_id` as the parent signup.
cc: @sheyd
=> Consistent signup_id

app/Http/Controllers/Traits/FiltersRequests.php, app/Models/Signup.php, database/migrations/2017_05_30_184559_add_updated_at_index_to_signups_table.php, documentation/endpoints/activity.md, tests/ActivityApiTest.php
- Adds the `updated_at` param to the `/activity` endpoint so you can now filter results to only return signup's whose `updated_at` time is after the value of the `updated_at` param. 
- Adds test. 
- Make sure all tests are passing! 
- You can also manually test this endpoint by itself and with other query params and expected results should be returned. 
Fixes #274
=> Adds updated_at param to /activity endpoint

app/Http/Controllers/Api/SignupsController.php, app/Http/Requests/SignupRequest.php, documentation/endpoints/signups.md
Adds some validation to `/signups`! Makes the required fields enforced, and enforces the correct type on all fields.
Also, it seems that generally in Rogue when we throw a validation error it returns a `500` instead of a `422` (here included). I've done some digging on this and found that it does hit the code in Laravel to return a validation error, but somehow doesn't end up returning that (at least that is not what I am seeing in Postman). Here is the issue: https://github.com/DoSomething/rogue/issues/276
Will this let you create a signup without any of the required fields or with the wrong type for any field?
Trust no one.
Fixes #178
=> Add validation to /signups

composer.lock, resources/assets/components/HistoryModal/index.js, resources/views/layouts/master.blade.php
Added `quantity` to the state of `HistoryModal` to keep an eye on if the admin has input anything in the form. Once there is something in the form, the button becomes active. If everything is removed from the form, the button becomes inactive again.
1. Go to any reportback inbox that is not at inbox zero
2. Click "Edit | See History." The "Save" button should be gray.
3. Click "Save." Nothing should happen!
4. Enter something into the quantity box. As soon as you enter it, the "Save" button should turn blue.
5. Remove what you entered from the box. The "Save" button should go back to gray.
6. Enter something into the box again and this time hit "Save". The modal should disappear.
Please note that the bug spotted by @chloealee in which the quantity does not actually update when you hit …
=> Disable save button when no quantity is entered

resources/assets/components/InboxItem/index.js, resources/assets/components/StatusButton/index.js
Removes comments from status buttons. 
👀 
I know we said that we wanted to not use this method but I haven't looked at the code in awhile and changed from what I thought it was! I think this is okay since it's just the label and we want to keep `accepted` and `rejected` in the database? Or do we want conditional logic like this pseudo code 
```
if (props.type === 'accepted') {
button label ACCEPT
} else {
button label REJECT
}
``` 
@lkpttn @DFurnes @sbsmith86 
Fixes https://trello.com/c/JTrKV3Z6/468-3-%F0%9F%90%9B-the-luke-problem-%F0%9F%90%9B
=> Removes Luke's comments from status buttons 

app/Models/Signup.php, documentation/endpoints/activity.md
Adds the ability to filter `/activity` response by `northstar_id`. 
👀  and test endpoint with `northstar_id` filter (and a combination or those with other filters). 
This is needed to fix [the bug](https://trello.com/c/wshiB68W/470-6-as-a-developer-figuring-out-how-we-want-to-know-if-someone-is-signed-up-for-a-campaign-already-and-then-doing-it) to not show pitch page when a user signsup in Phoenix when Rogue is on. Right now, the pitch page is shown if a signup doesn't exist. 
@DFurnes @sbsmith86 will this suffice to fix [this issue](https://trello.com/c/wshiB68W/470-6-as-a-developer-figuring-out-how-we-want-to-know-if-someone-is-signed-up-for-a-campaign-already-and-then-doing-it)?
=> Adds northstar_id filter to /activity endpoint

resources/assets/components/InboxItem/index.js
This just involves a simple css class change to display thumbnails of additional reportbacks to display as 2 thumbnails per row (previously 4 thumbnails per row)
Checkout the branch, build assets (`npm run build`) and go to /campaigns/1631/inbox, to the pikachu reportbacks. You should see that the gallery of thumbnails displays in rows of two (rather than four).
- I'm not sure if I should add any tests or anything like that. 
- Also is this all that was needed? I wonder if I'm missing something.
Fixes [As a campaign lead, I want the thumbnails to be bigger so that I can see what's in them](https://trello.com/c/1qAoKkRb/451-3-as-a-campaign-lead-i-want-the-thumbnails-to-be-bigger-so-that-i-can-see-whats-in-them)
=> Change Reportback gallery thumbnail items to 2/row

resources/assets/app.scss, resources/assets/components/CampaignInbox/index.js, resources/assets/components/InboxItem/index.js, resources/assets/components/StatusButton/index.js, resources/assets/components/StatusButton/status-button.scss, resources/assets/components/Tags/index.js
Provides visual indicators that the status and tags applied to a post have been saved. 
1) When you first come to the inbox, status are greyed out
2) When you click Accept, it becomes Green
3) When you click Reject, it becomes Red
4) When you click Accept, the tags show up grey (this is how it works already)
5) When you click a tag, it turns blue (this is how it works already)
Test out all of the above! 
Fixes https://trello.com/c/xf0O6xRA/479-5-as-a-campaign-lead-i-want-a-visual-indicator-that-the-status-and-tags-applied-to-a-post-have-been-saved
=> Save indicators

app/Http/Controllers/Api/PostsController.php, app/Http/Controllers/PostController.php, app/Http/Controllers/Traits/PostRequests.php, app/Http/routes.php, resources/assets/components/CampaignInbox/index.js, tests/CampaignTest.php
Creates a new endpoint at `POST /posts` that lives under the web middleware so we can make requests that get authenticated based on the logged in user from the frontend, instead of the API headers. 
Also - sidebar - fixes a failing CampaignService test. 
When updating quantity from the history modal in Rogue, I was getting authentication errors because we were not using the API headers. We don't want to use the API routes for requests from the frontend, we want to use web routes that authenticate based on the logged in user.
=> Web signup api route

resources/assets/components/CampaignInbox/index.js, resources/assets/components/CampaignSingle/index.js, resources/assets/components/HistoryModal/index.js, resources/assets/components/InboxItem/index.js, resources/assets/helpers.js
This updates how we are handling state on the `CampaignInbox` and `CampaignSingle` components. Before, we were extracting all of the posts from the signups passed via the `window.state` object and then looping over all of them to re-embed the signup object inside of the post so we could do things like show signup fields on a post or update the quantity.
This PR updates how we handle the signup data by adding the signups to the component's state so that when we need to do anything, like update quantity, or display `why_participated` we use the `signup_id` on the post to look up the individual signup in the `signups` object and update that. What that means is all posts related to that sign up will immediately get the update. 
This should make thing easier to work with on the frontend. 
I …
=> State refactor

app/Http/Controllers/Api/SignupsController.php, app/Services/SignupService.php
Adds check to see if signup exists before creating a new one. 
- Hit the `/signups` endpoint.
- Hit it again with the exact same information. 
- Check the `signups` table and make sure that there is not a duplicate signup. 
In order to keep our pattern consistent, I added a small function to the Signup Service to then forward on to the Signup Repository to check if there is an existing signup (since repository is supposed to deal with database and service is supposed to deal with business logic). I wanted to keep it consistent but if it isn't needed, LMK!). 
Fixes https://trello.com/c/YRabtbG4/495-2-%F0%9F%90%9B-when-rogue-is-on-and-if-you-create-a-signup-it-doesnt-check-to-see-if-it-exists-already-it-just-creates-one-every-time-so-we
=> Adds check to see if signup exists before creating a new one

app/Http/Transformers/PostTransformer.php, documentation/endpoints/activity.md
- Adds a post's reaction(s) in the Post Transformer 
- Updates documentation 
👀 
This is needed in order to merge this PR: https://github.com/DoSomething/phoenix/pull/7414
Helps to fix https://trello.com/c/S7cjnFL1/482-3-when-rogue-is-turned-on-user-cannot-sign-up-via-sms
=> Add post's reaction(s) in Post Transformer 

resources/assets/components/CampaignInbox/index.js
1. Refactored how a Post is updated to be consistent with our other calls (only update state if request is successful)
2. Use a different function to remove a Post from the state
Does reviewing work? Does reviewing work after deleting a post?
The bug that this aimed to solve was tags not showing up after accepted is clicked after a post has been deleted. The real problem was that you couldn't review ANY posts after a post was deleted. That is, clicking accepted and rejected did nothing (which is why the tags weren't showing up). This is because the format of the Posts in the state changed after a Post was deleted. The change I've made removes the Post from the state and maintains the structure of the state as well.
[Trello Card](https://trello.com/c/znpEftNs/438-5-%F0%9F%90%9B-tags-dont-sh …
=> Fix post deletion

app/Http/Controllers/Api/ReportbackController.php, app/Http/Controllers/Traits/TransformsRequests.php, app/Http/Transformers/ReportbackTransformer.php
- Add tags to reportbacks endpoint 
- Only return Posts that don't have "Hide In Gallery" tag so these don't show up in the Phoenix Ashes gallery
- Hit `/api/v1/reportbacks` endpoint 
- You should now be able to see the Post's tags
- There shouldn't be any posts with the "Hide In Gallery" tag
- In Phoenix Ashes gallery, posts that are tagged "Hide In Gallery" should not be in gallery
Fixes #249 
Fixes https://trello.com/c/ZunwuNfb/496-might-not-be-needed-as-a-campaign-lead-and-phoenix-i-dont-want-posts-w-the-tag-hide-in-gallery-to-show-up-in-the-gallery-and-the
Fixes https://trello.com/c/59LxTGPN/416-3-as-a-developer-i-want-to-update-the-reportbacks-endpoints-to-include-post-tags-so-that-the-gallery-can-get-this-tag-informatio
=> Add tags to reportbacks endpoint and only return posts that don't have "Hide In Gallery" tag

app/Models/Signup.php, documentation/endpoints/activity.md
- Adds an `id` filter to the `GET /activity` endpoint to allow to filter by signup id(s)
Hit `/api/v2/activity?filter[id]=121,122` (or any combination of signup ids and only those should be returned. 
We need this in order to create a proxy for Pheonix Ashes' `GET /signup/:sid` 
Needed in order to fix [this ticket](https://trello.com/c/QYdM5vVN/485-as-a-developer-i-want-to-make-sure-phoenixs-signups-sid-endpoint-has-a-rogue-proxy-for-gladiator-to-still-work-when-rogue-is-tur) and for https://github.com/DoSomething/phoenix/pull/7441 to work
=> adds signup id filter to /activity endpoint

app/Http/Controllers/CampaignsController.php
There was a bug where sometimes on inbox pages, previously reviewed posts would show up. I tracked it down to 
```
$signups = Signup::campaign([$campaignId])->has('pending')->with('pending')->get();
```
in [`showInbox`](https://github.com/DoSomething/rogue/blob/master/app/Http/Controllers/CampaignsController.php#L62-L73) in `CampaignsController` in Rogue. This would get all signups for the given campaign that own pending posts. Off to a great start! However, later on, we never remove the posts that are not pending (we get all signups that have `pending` posts, but those same signups may also have `accepted` or `rejected` posts). My solution was to replace the posts with the pending posts when we are looping over the posts to include the user with the post.
Peruse some campaign inboxes and …
=> Use only pending posts for the inbox page

app/Models/Event.php, app/Models/Review.php, app/Providers/ModelServiceProvider.php, database/migrations/2017_06_29_194312_add_user_column_to_events_table.php
*Adds a `user` column to the `events` table that will hold the `northstar_id` of the user that did the event.
* Stores the authenticated user if coming from the web API (admins), stores the user passed in the request if coming from the API (i.e if posting a signup from Phoenix, we store the user that was sent in that signup request as the user responsible for the event).
* Removes the touch property on the `Review` model that would cause two Post events to be created when something got reviewed. When something gets reviewed, we create a new review record but we also update the post with the new status and that update the `updated_at` timestamp for the post and will also will touch the parent Signup to update the `updated_at` timestamp.
Post to `/signups` or `/posts`, or review something …
=> Tracking the user that did a thing

app/Exceptions/Handler.php, app/helpers.php
Wouldn't it be nice if when you tried to post something to Rogue, but had something wrong in your request, you got a helpful message in response instead of a `500`? Very soon, that will be the reality that we all live in.
This PR steals a bunch of code from Northstar to make that a reality. Taken from Northstar:
[`has_middleware` helper](https://github.com/DoSomething/northstar/blob/4a4b46482652e3e683837867af9ca32a3fcf1759/app/helpers.php#L54-L73) 
[unauthenticated function in `Handler.php`
](https://github.com/DoSomething/northstar/blob/ef9679e89e0aed0af470d9ac93f44e95b4265ca4/app/Exceptions/Handler.php#L115-L129)
[this real nice `buildJsonResponse` function
](https://github.com/DoSomething/northstar/blob/ef9679e89e0aed0af470d9ac93f44e95b4265ca4/app/Exceptions/Handler.php#L131-L157)
[and …
=> Return specific errors

app/Console/Commands/EditImagesCommand.php, app/Console/Kernel.php, app/Services/AWS.php
This adds a `artisan rogue:images` command that we can use to resize a shit ton of images super quickly. This doesn't _do_ anything with these new images, or overwrite any existing data that the app currently relies on.
We added a new `storeImageData` to the AWS client to store the in-memory version of the file and not do all the crazy MD5 timestampy business.
LET'S DO THIS.™
Fixes :scream:.
=> Add command to bulk resize images.

app/Console/Commands/EditImagesCommand.php
This pull request adds some simple error handling so we don't stop the whole dang process if a single image can't be processed. We can then look over the log from running the command for specific errors afterwards.
👀
This error occurred on Thor when it hit a post with `default` as the URL:
```
Saved edited image for post 1175
Saved edited image for post 1176
Saved edited image for post 1177
Saved edited image for post 1178
Saved edited image for post 1179
Saved edited image for post 1180
[Intervention\Image\Exception\NotReadableException]  
Image source not readable          
```
Fixes 🐛.
=> Handle exceptions when cropping images.

app/Console/Commands/EditImagesCommand.php
Added another `catch` to the image command to catch all `\Exception` and print out an error.
👀 Will this catch 'em all?
At least one image gave an error that we did not catch.
=> Catch all exceptions in image command

app/Http/Transformers/PostTransformer.php, app/Http/Transformers/ReportbackTransformer.php
In `PostTransformer` (used by activity and other endpoints) and `ReportbackTransformer` (used by Phoenix gallery), we return the edited image instead of the original. The edited one is a square center crop. 
The urls will look something like this:
`https://s3.amazonaws.com/ds-rogue-qa/uploads/reportback-items/edited_1.jpeg`
My local data is kind of wonky so I will want to test this on Thor to make sure it's working.
Is there anywhere else that we return urls that needs to be updated?
This was way easier than doing it on the Phoenix side!!!
[Trello card](https://trello.com/c/bo4mBuN5/516-gallery-frontend-work-to-make-things-look-like-squares)
=> Always return edited images

app/Repositories/PostRepository.php, app/helpers.php
1. Save the edited image after the post is created so we can use the post id in the url
2. Use `storeImageData` to save images that came with cropping information, and use `->encode('jpg', 75);` on them so we can rebuild the urls reliably later (everything ends in `.jpeg`)
3. Save a center cropped image for images that aren't sent to Rogue with cropping information. We want to have a square crop version of everything.
Will this create a square cropped image for all new images sent to rogue with a filename of `{post_id}.jpeg`?
We need to make sure that we can find cropped images for all new posts.
Takes care of this [Trello card](https://trello.com/c/bQcbThcr/510-%F0%9F%90%9B-photos-that-arent-square-are-breaking-the-gallery-when-rogue-is-turned-on-%F0%9F%90%9B) for all future images
=> Save a cropped jpeg for all images submitted

app/Repositories/PostRepository.php, app/helpers.php
All images, will be made into 400x400 squares, whether we have the cropping information or not. The `edit_image` helper has also been removed because everything has been moved into `crop` in `PostRepository.php`. 
Do all the things to upload images to Rogue!
1. Step 4 Prove It
- everything should work as normal and your images should end up in Rogue
2. Hit the Rogue `POST /posts`
- everything should work as normal and your images should end up in Rogue
Make sure the edited images for the ones you uploaded are 400x400. They live at `{bucket_for_environment_you're_using}/edited_{post_it}.jpeg`.
We always cropped, but we didn't always resize so we ended up with some pretty big squares.
=> Make sure to resize all cropped images to 400x400

app/Http/Transformers/ReportbackTransformer.php
Phoenix Ashes relies on `kudos_id` to determine whether to fill in the ❤️ in the interface, so we can't just hardcode that to a `1` or else they all show as filled. (I think we did it this way to work around a Phoenix Ashes bug with the `reacted` property? I'm not sure...)
👀
🤷‍♂️
Fixes 💔
=> Make sure we only set kudos_id if there's a reaction.

app/Http/Transformers/ReportbackTransformer.php
We return IDs as strings in Phoenix Ashes (and Phoenix Next validates against it, oy). This just casts ID properties to strings so hopefully those errors quiet down.
🔢
🔥 🚒 
Fixes 🤐
=> Ensure IDs are strings.

app/Http/Transformers/PostTransformer.php, app/Http/Transformers/ReportbackTransformer.php
Previously we were returning the edited image url even for images whose original url was `default`. This stops that! We still return `default` if the original url is `default`.
👀  Make sure I didn't make a dumb typo!
This should fix the broken image in the Phoenix gallery.
=> Don't return edited images for broken images

app/Http/Transformers/ReportbackTransformer.php
Since we need `post_id` and `northstar_id` to delete a reaction in Rogue, we need to make these easily available on the front-end. This updates the reportbacks endpoint to return a string formatted as `<post_id>|<northstar_id>` so we can easily grab those two values in Phoenix's "delete kudos" endpoint without having to change any client code.
👀
Here's the corresponding Phoenix PR: DoSomething/phoenix#7471
Fixes 🐞
=> Return compound post_id|northstar_id format for kid.

app/Http/Controllers/CampaignsController.php, resources/assets/components/CampaignSingle/index.js, resources/assets/helpers.js
1. Only load 100 posts on the single view campaign page
2. Update the default image
3. Add copy on the single view campaign page to warn everyone
new broken image example:
👀
=> Lighten the load on the single view campaign page

resources/assets/components/CampaignSingle/index.js, resources/assets/components/StatusCounter/index.js
Removes the filtering on the single campaign view page.
Looks like this now: 
👀 
Removing this because we are only pulling 100 signups with posts to show on this page and we don't know how many of these are pending, reject, approved. 
Fixes 🐛
=> Remove filtering on single campaign view

resources/assets/components/InboxItem/index.js, resources/assets/helpers.js
Adds an "edited photo" link next to the "original photo" link on inbox items. 
👀 . Verify my string logic makes sense. 
Admins might need to smaller edited version of an image.
=> Show a link to the edited photo on the inbox item

app/Http/Controllers/Api/ReportbackController.php, documentation/endpoints/reportbacks.md
Adds `northstar_id` query param for `/reportbacks` endpoint for user profile work. 
👀
=> adds northstar_id as param for reportbacks endpoint

app/Http/Controllers/CampaignsController.php, app/Services/CampaignService.php, resources/assets/components/CampaignTable/index.js, resources/assets/components/Table/Row.js, resources/assets/components/Table/index.js
Tries to tackle the slow performance we are seeing on `/campaigns` trying to tally up the counts for each status is a heavy operation because we don't store campaigns in the DB so we have to iterate over signups and posts to get counts.
In order to lighten the load a little bit, I am only pulling pending post totals for each campaign. This is a quick win to run a simpler query and cuts the load time for the page to around 2.5 seconds instead of the 11secs we were seeing. 
I also am caching campaign objects for longer, upping the time we store it in cache to 1 day instead of 15 mins. 
I also made a bit of a change to the frontend, where instead of linking the pending count number, we have a separate link to the inbox next to it. I did this because I heard some feedback that it was …
=> Overview refactor

app/Http/Controllers/CampaignsController.php, resources/assets/app.scss, resources/assets/components/CampaignSingle/index.js, resources/assets/components/PagingButtons/index.js, resources/assets/components/PagingButtons/paging-buttons.scss, resources/assets/helpers.js
1. Use `->paginate` on the query to get the signups to display on the single view campaign page. I set it at 50, but we can increase or decrease that depending on the performance we see and what works best for people.
2. Remove the 🐼  message because all posts can be accessed now
3. Add back in sorting
4. Add a new component `PagingButtons` to display the links to the adjacent pages (I figured we'll end up having pagination elsewhere too eventually)
Bottom of the page looks like this:
Caution: I did write some css. See if the way this is organized makes sense. It works, but I don't want to introduce any debt!
We need to paginate these pages so we aren't trying to load thousands and thousands of posts at once.
[Pivotal card? did I do this …
=> Paginate the single view campaign page

app/Http/Controllers/Api/ReportbackController.php
__Reverts DoSomething/rogue#329.__ This ended up breaking the `filter[campaign_id]` and `filter[northstar_id]` query params. Working on making this work better in an upcoming pull request.
References DoSomething/rogue#325.
=> Temporarily revert reportback query optimizations.

app/Http/Controllers/CampaignsController.php, resources/assets/components/CampaignSingle/index.js
This will I think let us push campaign single view pagination live. The page will only include accepted posts and does not allow filtering. I also added copy to let admins know that this page only shows accepted posts.
Is this the interim state that we want for this? 👀 
Currently, we can't have pagination and filtering because the pagination happens before the filtering, so if there are no `accepted` posts on the first page and the filter is set to `accepted` it will be a blank page with a `next >` button which is not what we want.
=> Turn filtering off and only show accepted posts

app/Http/Controllers/Api/ReportbackController.php, app/Models/Post.php, app/Repositories/PostRepository.php, config/debugbar.php, database/migrations/2017_07_31_153255_add_campaign_id_to_posts.php, tests/CampaignTest.php, tests/PostApiTest.php
This pull request hopefully wraps up the performance work on the reportbacks endpoint for now:
🤔 I tried a couple approaches to avoid having to duplicate the `campaign_id` column but neither seemed to work all that well. From what I can tell, joins on big tables are just inherently not good. (2bd00f8, 4ca02f4)
🆔 The best solution, at least for now, seems to be copying the `campaign_id` into the posts table so that we can just query against the indexed column directly. This runs in ~130ms rather than the 12 or 15 seconds I was seeing with joins and subqueries. (d281c7a)
🚥 I made some updates to the `PostApiTest` since it hadn't been updated with the "edited URL" change we made pre-launch (2a06a64), and updated `PostRepository` to set `campaign_id` on new posts (1058eee). More tests are …
=> Move `campaign_id` into posts table & re-apply #329.

app/Http/Controllers/Api/ReportbackController.php
This should allow requests to continue running successfully while #334 deploys.
👀 
Capistrano runs builds & database migrations while the old codebase is still serving web requests. Unfortunately our migration in #334 made the `campaign_id` in this query ambiguous (since both `posts` and the joined `signups` now have columns with that name).
This change should allow us to continue serving requests while the migration runs on Thor/prod.
References #334, #325.
=> Make campaign_id query unambiguous for #334.

app/Services/CampaignService.php
Adds `signups.campaign_id` in `getPostTotals` function to get rid of ambiguous query error. 
Hit `/campaigns/:id` page and all should work as expected.
=> gets rid of ambiguous query in getPostTotals function

resources/assets/helpers.js
Key by post id in `extractPostsFromSignups`. I took that out while I was working on pagination, I think it had something to do with ordering the posts from most recent to least recent, but it had unintended bad side-effects! Adding it back in here so that reviewing works as expected and tagging shows up. @chloealee wanted to make sure you pull this in to your branch for pagination to make sure ordering from most recent to least recent works with this (since I believe I was having trouble with that).
Check out both types of campaign pages on Rogue (inbox and single view) and make sure that the reviewing works as expected and that everything looks normal.
I made a 🐛  and this will hopefully crush it.
=> Key by post id in extractPostsFromSignups

app/Services/CampaignService.php
One more query that got confused!
👀
Rogue campaign index is still showing this bad boy:
```
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'campaign_id' in where clause is ambiguous (SQL: select signups.campaign_id, count(posts.id) as pending_count from `signups` left join `posts` on `signups`.`id` = `posts`.`signup_id` where `status` = pending and `campaign_id` in (4, 6, 7, 8, 9, 10, 13, 14, 15, 17, 18, 19, 21, 22, 24, 28, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 52, 53, 54, 55, 56, 57, 58, 61, 62, 63, 66, 69, 73, 74, 75, 76, 84, 345, 362, 689, 819, 822, 830, 832, 836, 839, 842, 843, 850, 854, 876, 886, 946, 955, 958, 1144, 1357, 1476, 1508, 1516, 1524, 1526, 1536, 1538, 1662, 1819, 1820, 1822, 1826, 2003, …
```
=> Fix another ambiguous query with joined tables.

app/Http/Controllers/PostController.php, app/Http/Controllers/Traits/FiltersRequests.php, app/Http/Controllers/Traits/PostRequests.php, app/Http/routes.php, app/Models/Post.php, documentation/endpoints/posts.md
Creates `GET /api/v2/posts` (API requests) and `GET /posts` (app requests) endpoint that returns a set of posts given the query params it is passed. 
This works exactly like the `GET /reportbacks` endpoint but returns response formatted for the new rogue data schema. 
Also should note that I update the logic for the filtering to use the `FiltersRequest` trait instead of doing it separately as we are doing in the `ReportbackController`. Now that we have made some updates to the `posts` table, I think this is a little easier to use. 
👀 , commit-by-commit, Make sure the updates to `FiltersRequests` seem ok. 
Will help the app do some of the filtering, pagination and sorting it needs to do by making an api request for posts directly. 
Also make things more RESTful :) …
=> GET /posts endpoint

app/Http/Controllers/Api/TagsController.php, app/Http/Controllers/TagsController.php, app/Http/Controllers/Traits/TagsRequests.php, app/Http/Transformers/PostTransformer.php, app/Http/routes.php, app/Providers/ModelServiceProvider.php, documentation/endpoints/activity.md, documentation/endpoints/tags.md, resources/assets/components/CampaignInbox/index.js, resources/assets/components/InboxItem/index.js, resources/assets/components/Tags/index.js, resources/assets/helpers.js
- Added `Api/TagsController.php` to handle posts getting tagged (or untagged) via the api
- Added a new route: `POST api/v2/tags`
- For tag or untag events via the API (or anytime there is no `auth()->user()`), store `null` for the user column on the event
- Updated documentation
👀 Hit the endpoint and make sure you get a response like one provided in the documentation. Send the same request again and the tag you just added should disappear 🎱 
We need this endpoint to migrate over the tags that live in Phoenix (excluded = Hide in Gallery, promoted = Good Photo).
[Pivotal card](https://www.pivotaltracker.com/n/projects/2019429/stories/149658211)
=> Add POST /tags endpoint

documentation/endpoints/activity.md, tests/Http/Api/ActivityApiTest.php, tests/Http/Api/ReactionsApiTest.php, tests/Http/PostTest.php, tests/Http/ReviewsTest.php, tests/Models/PostModelTest.php, tests/Services/CampaignServiceTest.php
Last general purpose cleanup pull request!
🗃 Moves non-HTTP tests (models and services) to their own directories. f8a7933, 26e4046
🐎 Adds some more tests to the activity endpoint, since before we were mostly just testing the built-in paginator (rather than actual JSON results). 555188c
🆕 Makes sure to re-fetch from database before making assertions, and swaps order of arguments so PHPUnit outputs the correct things in the "expected" and "actual" columns. 813e40c
👉 Updates `TODO`s for broken "touching". It turns out that Laravel only touches immediate parents for the `$touches` property, so a reaction would update post timestamp but _not_ the signup timestamp. We should prioritize this and fix in a future sprint. aca684d
🚥 👀 
☔️
[#149662237](https://www.pivotaltracker.com/story/show/1496622 …
=> Test Cleanup, Part III

.env.example, phpunit.xml
This will always override PHPUnit to use the local "public" storage adapter, rather than creating images on our shared S3 bucket.
👀
References #349.
N/A
=> Force tests to run with local storage adapter.

app/Http/Controllers/Api/ActivityController.php, app/Http/Controllers/CampaignsController.php, app/Http/Controllers/Traits/TransformsRequests.php, app/Http/Transformers/PostTransformer.php, app/Http/Transformers/UserTransformer.php, app/Models/Post.php, documentation/README.md, documentation/endpoints/activity.md, documentation/endpoints/posts.md, package.json, resources/assets/components/CampaignInbox/index.js, resources/assets/components/CampaignSingle/index.js, resources/assets/components/InboxItem/InboxTile.js, resources/assets/components/InboxItem/index.js, resources/assets/helpers.js, tests/Http/Api/ActivityApiTest.php, tests/Models/PostModelTest.php
- Changes Campaign Single Index page's initial state to be powered by API instead of sending signups from backend (`GET /posts`). 
- Powers filtering by status via the API (`GET /posts`).
- Adds relation to Post model of other related posts under the same signup (siblings).
- Updates Post Transformer to optionally include related posts (siblings) and signup object for `GET /posts`).
- Returns more information about the user in the User Transformer (user's last name, birthdate, email address, mobile number).  
- Returns the original photo url in the Post Transformer. 
- Updates `$include` param to allow for multiple values (e.g. `$include=signup,siblings`).
- Updates Post tests.  
- BONUS: 
- Adds some missing things to README file for documentation.
- Test `campaigns/:nid` to make sure …
=> Filters posts powered by the API

.env.example, app/Exceptions/Handler.php, app/Http/Controllers/ImagesController.php, app/Http/routes.php, app/Models/Post.php, composer.json, composer.lock, config/features.php, phpunit.xml, tests/Http/Api/ReactionsApiTest.php
This pull request adds [Glide](http://glide.thephpleague.com) to allow us to create cropped images for posts on-demand. This removes the need for costly image processing when a user uploads an image, and means we can ask for differently formatted images in different places (perhaps small square images for a gallery, but a larger un-cropped image on a permalink page).
If you pull this branch down to your local and add `DS_ENABLE_GLIDE=true` to your `.env`, you can experiment [with the included filters](http://glide.thephpleague.com/1.0/api/quick-reference/). For example:
```php
'http://rogue.dev/images/1' // default small crop
'http://rogue.dev/images/1?w=500&h=500&fit=crop' // larger square crop
'http://rogue.dev/images/1?w=250&h=400&fit=crop&filt=sepia' // woah, crazy!
```
When we want …
=> Add Glide for on-demand image processing.

app/Http/Controllers/Api/CampaignsController.php, app/Http/routes.php, app/Services/CampaignService.php, composer.lock, documentation/endpoints/campaigns.md, resources/assets/components/SignupCard/index.js, resources/assets/components/SignupCard/signup-card.scss, resources/assets/components/UserOverview/index.js, resources/views/search/search.blade.php, resources/views/users/partials/_table_users.blade.php, resources/views/users/show.blade.php, tests/Http/UserTest.php
This PR flushes out the User page showing all of a users signups. 
* Implements layout, style, and functionality for a `SignupCard` component that show info for each signup. 
- One thing to note: we grab the campaigns for each signup after the signups have been set on the state. We don't render signups on the page until everything is available, in the meantime we display a spinner indicating we are grabbing data.
* Creates a proxy endpoint at `/api/v2/campaigns` that grabs campaign info from the phoenix api 
I think i messed up a lot of the commit history when rebasing since I started this branch off of a branch that wasn't merged in yet. 
Best bet is to pull down this branch and test that you can load a user page and see data on the page. 
Most of the code for the layout and …
=> List user signups

app/Models/Post.php, app/Models/Tag.php, database/migrations/2017_08_15_150325_create_tags_and_post_tag_tables.php
This adds new things, but doesn't change how anything works currently.
Added:
- Tag model
- Database migration to add tags table and pivot table with posts. Includes timestamps only on the Tags table and not on the pivot table. On the current tagging tables (`tagging_tagged`, `tagging_tags`) we do not have timestamps either.
- Posts relationship with Tag model
Where do we want timestamps? Nowhere? Both tables?
Background discussion can be found in this issue: https://github.com/DoSomething/rogue/issues/353.
[Pivotal card](https://www.pivotaltracker.com/n/projects/2019429/stories/150239872)
=> Add Tag model, relationship with posts, table and pivot table

app/Services/AWS.php
This fixes an issue where we were storing file URLs with an extra `/` in them, since c9bece96fbaff284da37a8f789491d9c2e0c13f2 got deployed earlier today.
👀
We can fix the (relatively few) affected database records by hand. Images were still saved correctly.
Fixes N/A.
=> Fix issue where extra '/' was added to URL.

.gitignore, resources/assets/components/CampaignInbox/index.js, resources/assets/components/CampaignSingle/index.js, resources/assets/components/HistoryModal/index.js
- Allows reviewing (change quantity, tags, and status) of posts on the campaign single view page. 
- Visit campaign single view page. You should now be able to update any post on this page exactly how you're able to in the campaign inbox page. 
- Note: there are some duplicate functions from CampaignInbox `index.js` in Campaign Single `index.js` (`deletePost`, `updatePost`), and some that are almost the same but slightly tweaked because of the different states on the different pages (`updateQuantity`, `updateTag`). Once we update the CampaignInbox `index.js` to initally load all posts via API similar to the Campaign Single `index.js` view, we should update and combine these functions to live in one place for DRY code. 
- When a post is rejected and you change it to accepted, the post will …
=> Update post on campaign single page

.env.example, app/Models/Post.php, app/Models/Signup.php, app/Providers/AppServiceProvider.php, app/Repositories/PostRepository.php, app/Repositories/SignupRepository.php, app/Services/PostService.php, app/Services/SignupService.php, config/features.php, config/services.php, phpunit.xml, tests/Http/Api/PostApiTest.php, tests/Http/Api/SignupApiTest.php
This pull request adds support for persisting new signups & reportbacks in Customer.io, via Blink. This is handled using a feature flag, so that we can disable it when running Rogue locally.
I've added assertions that the relevant Blink methods are called in relevant test suites.
📮
[#149209459](https://www.pivotaltracker.com/story/show/149209459), [#149862583](https://www.pivotaltracker.com/story/show/149862583)
=> Transform and send signups & posts to Blink.

app/Repositories/CacheRepository.php, app/Services/CampaignService.php, app/Services/Registrar.php, composer.lock, tests/Services/CampaignServiceTest.php
Store campaigns in cache with the prefix `campaign:` to fix this issue: 
```
[2017-08-21 14:48:25] thor.ERROR: ErrorException: Cannot use a scalar value as an array in /var/www/rogue/releases/20170821143532/app/Services/CampaignService.php:246
```
👀  and `/campaigns` and `/campaigns/:nid` pages should work exactly the same when hit. 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/150409500
=> Save campaigns in cache with prefix in ID

composer.json, composer.lock, storage/framework/testing/.gitignore, tests/BrowserKitTestCase.php, tests/Http/Api/PostApiTest.php, tests/Http/PostTest.php, tests/TestCase.php
This pull request is just a little grab-bag of test touch ups:
7️⃣ Adds a PHP version constraint to our `composer.json`. This will prevent us from accidentally running Composer with a different PHP version and getting the wrong dependencies.
🚥 Updates `PostTest` and `PostApiTest` to use the new Laravel 5.4 test syntax, including the [`UploadedFile` fake](https://laravel.com/docs/5.4/mocking#storage-fake) and [`assertSoftDeleted` assertion](https://laravel.com/docs/5.4/database-testing#available-assertions) (each replacing our own homegrown implementations).
🗄 Fakes the storage adapter for tests so we don't keep writing files to the disk every time we run the test suite (otherwise the `public/storage` directory keeps growing and growing).
👀
I'm gonna make a card to update the rest of our …
=> Some little test updates.

database/migrations/2017_08_21_212932_move_tagging_tagged_to_post_tag.php
Quick fix to this migration!
👀 
Deleted posts can still have tags, so we want to make sure the post exists before trying to apply a tag.
:cowboy_hat_face:
=> Only tag post if it exists

app/Exceptions/Handler.php
The Handler's `invalidated` method was changed to `convertValidationExceptionToResponse` in one of the Laravel updates. This should allow us to actually render validation errors, rather than dying.
👀
We can probably simplify this further in the future so we don't have to handle so many cases specially ourselves. Let's make a backlog refactor ticket!
N/A
=> Fix 500 on validation error.

app/Services/Registrar.php
Unsets prefix in` resolveMissingUsers` method before trying to find them. 
👀 
Fixes 🐛
=> Remove prefix before trying to find the user in cache

app/Repositories/CacheRepository.php, app/Services/Registrar.php, resources/views/users/partials/_table_users.blade.php
Fixes some issues I was seeing on QA when grabbing users from the cache
* In `CacheRepository.php` we were always assuming things were keyed with the "campaign:" prefix but users are stored with the "user:" prefix. [change here](https://github.com/DoSomething/rogue/compare/user-cache-fix?expand=1#diff-963df936abc332d74d55c56a3dc9e2fcR116)
* The `$users` array was keyed with prefixes but we were trying to store a value using a non-prefixed key. [change here](https://github.com/DoSomething/rogue/compare/user-cache-fix?expand=1#diff-4cf63b529baa5ae9c5b6aa21e80856a4R84)
* There was a user on QA that is truly not being found. I can't find them in aurora QA either (id: 5543c0cf469c64ec7d8b45f3) . So this checks for the user before trying to render them in the template. [Change …
=> Fixes a few issues with grabbing users from cache

app/Http/Requests/SignupRequest.php
This pull request includes a quick fix for signups not working on Phoenix.
I ran out of time to add a test case, but if we decide this is expected behavior we should add one!
Laravel now requires the [`nullable` validator](https://laravel.com/docs/5.4/validation#rule-nullable) now if you want JSON fields to be optional, so this broke as a result of that upgrade. It's also worth thinking if we want to provide a fallback value for this [in Phoenix](https://github.com/DoSomething/phoenix/blob/6e80ae77499c1fd8b30508c1bad7ab6e8dd6d192/lib/modules/dosomething/dosomething_northstar/dosomething_northstar.auth.inc#L168).
(And in the future, we could set `source` by the Northstar client in the token!)
Fixes 🐛
=> Allow null values to be provided for source.

app/Repositories/PostRepository.php
This first checks to see if `why_participated` is present before overriding the existing value in the database. 
Hit `POST /api/v2/posts` endpoint with `why_participated` value blank. Make sure it doesn't wipe the value out in the database and that the `why_participated` value returned in the JSON is from the original answer. 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/150341552
=> only updates why_participated if it is present

app/Http/Transformers/PostTransformer.php
I goofed this when I did the new tagging stuff, but in the documentation we have `tagged` so we should return that.
👀 
This didn't break the tagging script, but it wouldn't work as expected.
=> Return "tagged" not "tags"

app/Http/Transformers/PostTransformer.php, documentation/endpoints/posts.md
- Updated documentation
- Use `tags` instead of `tagged` (frontend expects this currently)
👀 
This will require a small update to the Rogue image tagging script in Phoenix.
=> Reverse! Use "tags" not "tagged"

app/Providers/AppServiceProvider.php, config/app.php
Fixes an issue where debugbar seems to be running on production sometimes. 
This is an issue that has been reported by other devs and the suggested fix is to just only register the service provider on non-production environments explicitly: https://github.com/barryvdh/laravel-debugbar/issues/635#issuecomment-306058405
👀  
On my local, I changed my `APP_ENV` to `production` to make sure that it didn't load in debugbar on requests. 
Fixes https://www.pivotaltracker.com/story/show/150442834
=> Do not register debugbar on production

resources/assets/app.js, resources/assets/utilities/MountContainer.js, resources/views/pages/campaign_inbox.blade.php, resources/views/pages/campaign_overview.blade.php, resources/views/pages/campaign_single.blade.php, resources/views/signups/show.blade.php, resources/views/users/show.blade.php
Refactors how we were adding React components to the server rendered paged. 
Before we were looking for the element to add a react container component to by searching for an `id` prop on the server rendered HTML. This ended up being a lot of conditional statements to see if the element was on the page before adding the component. 
Now, in the server rendered HTML, we add a `data-container` attribute and set the value to equal the name of the component to add to the page. And then, when we load in the JS we look for the `data-container` attribute and use it's value to add the correct element to the page.
👀  commit-by-commit should be easy to follow. 
Right now, this only assumes that there one HTML element on the page to add a react container component to. This is because we really are …
=> App Container refactor

app/Http/Controllers/Traits/PostRequests.php, app/Services/PostService.php
We were only making the blink request in the post->create method and not in the post->update method. 
This surfaced a weird logic issue we have in our post creation code where we consider an "update" when a user submits a new post to an existing signup. We only consider it a "create" when we are creating both the signup and the post at the same time. So what ended up happening was we were only sending to blink when we sent over the signup and the post content at the same time (or created the signup on the fly with the post). 
This logic seems flawed and we should look at it, but in an interest to unblock the messaging team, I have added the blink integration to both update and create methods. 
👀 
See above. 
Fixes https://www.pivotaltracker.com/story/show/150827279
=> Send payload to blink even when updating a post

resources/assets/components/Signup/index.js, resources/assets/components/UserOverview/index.js, resources/assets/components/Users/UserInformation.js, resources/assets/helpers.js
- Fixes user birthdate bug (if no birthdate, displays age as 47)
- Changes `displayName` to `displayUserInfo`
- Now takes in birthdate as well. If there is a birthdate, it will calculate the user's age and add ", [age]" following display name. 
- Cleans up and deletes helpers from files where we no longer use them. 
- Check out all pages that list user information (name and age on post). Make sure that if there is no birthdate, the age 47 doesn't appear (also shouldn't have a comma after the name). 
- Did I break any pages that use the user information?
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/149209251
=> Fixes user birthdate bug (if no birthdate, displays age as 47)

app/Http/Controllers/Traits/FiltersRequests.php, app/Models/Post.php, app/helpers.php, documentation/endpoints/posts.md
- Adds ability to filter by multiple tags (to both include and exclude). 
- e.g. `/api/v2/posts?filter[tag]=good-quote,good-for-storytelling`
Commit by commit and/or by testing the above endpoint with multiple variations of tags! Make sure the results are what is expected. 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/150713655
=> Filter by multiple tags

app/Http/Transformers/PostTransformer.php, documentation/endpoints/posts.md
Added reaction information to the `PostTransformer`. The information included is the number of reactions on the post and and `reacted`. `Reacted` tells whether or not the `as_user` included in the request has reacted to the post. It is `false` if the user did not react or if no user was provided.
👀  This includes additional information in the response (as opposed to altering existing data) so shouldn't break anything.
This was needed to get the correct reaction data on the user profile in Phoenix.
I went a little bit down a rabbit hole because my local reaction data was funky so wasn't showing up.
[Pivotal card](https://www.pivotaltracker.com/story/show/151011784)
=> Include reaction information with GET /posts

app/Http/Controllers/CampaignsController.php
After some refactoring work, we grab post data, with embedded signups and user information on the frontend via the `/posts` endpoint so we no longer need to grab it on the server side and pass it to the frontend via the  `state` object. 
👀 
Should fix a bug on rogue-thor where looping through the users was failing. I'm not quite sure why it was failing but we don't need to be doing that anyway. 
Fixes 🐛
=> Removed unused code from CampaignsController

app/Models/Post.php
Added 2 more fields to the payload we sent to Blink for Posts (quantity and why_participated) that we grab off of the signup.
Will this send the correct information to Blink?
Nope!
[Pivotal card](https://www.pivotaltracker.com/n/projects/2019429/stories/150860659)
=> Include quantity and why_participated in Blink payload

app/Http/routes.php
Hitting the homepage didn't behave as expected (never thought anyone was logged in so always showed the "Log In" view) because that route was not in the `web` group. My understanding is that only routes in the `web` group will have access to session information, which is needed to call `Auth::guard($guard)`, which is what we check to see if anyone is logged in in the [`RedirectIfAuthenticated.php`](https://github.com/DoSomething/rogue/blob/master/app/Http/Middleware/RedirectIfAuthenticated.php#L20) middleware.
👀  Make sure the behavior is the same as always for anyone not logged in. Once you are logged in (as an admin), you should be able to hit the homepage or click the DoSomething logo in the top left corner and be redirected to the `/campaigns` page.
The middleware was fine, the route …
=> Move homepage into web group

resources/assets/components/Post/index.js, resources/assets/helpers.js
I introduced a bug in my last PR where I updated `getImageUrlFromProp()` to return the "edited" url, or the URL we process separately to make it smaller and cropped. This caused us to use the edited image wherever we called `getImageUrlFromProp()` which messed up the "original photo" link.
This updates the logic to pull large tile image in a Post from `getEditedUrl()` so we are using that to render the image and grabbing the actual original image url for the "original photo" link.
👀 
When we turn on Glide, we can then use the Glide API to grab the correct image for display, but for now, I am using the edited image URL. 
Fixes 🐛
=> Show edited image

app/Http/Controllers/Traits/PostRequests.php, documentation/endpoints/posts.md, resources/assets/components/CampaignInbox/index.js, resources/assets/components/CampaignSingle/index.js, resources/assets/components/WithReviewing/index.js
All `GET /posts` endpoints return newer posts first. Anywhere using `keyBy` or `map` or anything like that on this data that doesn't have the changes made below shouldn't see any change in the order of the posts. This endpoint needed to return the posts in order because otherwise they will end up sorted per page and not overall.
Then, instead of mapping over all the posts and then creating a `<Post>` for each one, we map over an array of the correctly ordered post IDs and then grab the corresponding information from the list of full posts to build the `<Post>`.
Also, for some reason `this` was out of scope once I made these changes so I declared `props = this.props` as well. That seemed a little weird to me.
Is everything in the right order? Did that break anything else?
[Pivotal …
=> Newer posts first on single view page

resources/assets/components/WithReviewing/index.js
The data I tested this with locally wasn't the best example because the correct order for it was also numerical order! I was mistakenly getting the order of posts based on the already `keyBy`-ed `posts`. Instead, use the API Response itself which will be in the correct order.
👀 
Just a little oopsie.
=> Don't keyBy before getting the order

resources/assets/components/CampaignSingle/index.js
Changes case of `campaign_id` filter to be in expected case (instead of camelCase). This fixes the bug we were seeing where the filters would return ALL pending posts instead of just pending posts (and other filters) for a specific campaign. 
👀  and make sure that filtered results are for only the campaign page you're on. 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/151224000
=> Fixes filter bug and returns value only for specified campaign 

resources/assets/components/Post/index.js, resources/assets/components/Post/post.scss, resources/assets/components/Tags/tags.scss
Fixes bugs around tagging.
These bugs were introduced with the rotation work. 
We pass in a `post` prop to the `Post` component and everytime a tag gets clicked we re-render the post based on the `post` property. 
The issue was after the rotation work, I set a `state.props` property so that we can update the media url when the rotation was finished. 
Now, when the `post` prop was updated, the state never got the change, so the tags did not update their active/inactive styles.
This uses `componentWillReceiveProps` to update `state.post` when we send in new props. 
Also fixing some styling things that seemed weird with the loading/not-loading states.
commit-by-commit 👀 
It might be worth a little refactor of the `Post` and `Tags` components so this is a little bit more understandable, but …
=> Tag loading state bug

resources/assets/components/FilterBar/filter-bar.scss, resources/assets/components/FilterBar/index.js
Noticed a very small bug where all of our buttons were floated to the right. 
It looks like we needed that for that style for the `FilterBar` component but were accidentally applying it to all buttons. This PR just scopes all the filter bar styles to the component. 
👀 
visual bug 🐛
=> Filter bar style

app/Http/Controllers/ImagesController.php, app/Http/Transformers/PostTransformer.php, resources/assets/components/CampaignSingle/index.js, resources/assets/components/Post/index.js, resources/assets/components/Post/post.scss, resources/assets/components/WithReviewing/index.js, resources/assets/helpers.js
This PR does two things: 
1) [Adds a cache-busting timestamp](https://github.com/DoSomething/rogue/commit/bf2b0196054cfe6390a34566f35922e6461e64b4)
to image urls in the response we return in the Post transformer so that we always get the new image on page reloads. 
* I'm not sure if this is the best approach since we do really want the cached image for better performance. 
- One option could be to only return the image with the query string if it is updated. This would require us to actually update the post record to know if it has been updated or not. We currently don't do that. Also that brings up another issue where any updates we make to Post records will cause an event log in the `events` table. So we can talk through what we really want. 
2) A little refactoring of the `Post` …
=> Add query string to posts

resources/assets/components/CampaignInbox/index.js, resources/assets/components/Post/index.js, resources/assets/components/Users/UserInformation.js
Adds a prop to the `UserInformation` component to decide of it should link to a signup or not. The prop should pass the signup id to link to and then link to it. 
Also fixes a little bug where I didn't pass the rotation functionality to `Posts` on inbox pages.
👀 
Cause it just makes sense.
Fixes https://www.pivotaltracker.com/story/show/151141191
=> Link user name to signup, if specified

database/factories/ModelFactory.php
In the Signup factory we want to add some `details` to the signups. Each signup gets `details` assigned at random from the following list:
`[null, null, 'fun-affiliate-stuff', 'i-say-the-tails']`
I put `null` twice because I figure it is closer to reality to have at least 50% `null`, but if we don't care that much about that I can remove it so it is only there once.
When you seed your database, does this fill some values (or some `null`s) into your `signups` database for `details`?
[Pivotal card](https://www.pivotaltracker.com/story/show/151225172)
=> Add signup details to factory

app/Http/Controllers/Traits/TransformsRequests.php, resources/assets/components/CampaignSingle/index.js, resources/assets/components/WithReviewing/index.js
Allows the API to accept an `include` parameter in a `GET` request as an array _and_ a comma-separated set of strings. 
Gateway JS will parse the passed array and add `&include[]=signup&include[]=siblings` to the query string. 
Apparently, when grabbing query string values, laravel will parse that as an array so we end up with `['signup','siblings']` on the server. 
So all this does is check if we got an array in the query param, if so just use that, else parse the comma separated list. 
commit-by-commit?
I feel like I am lacking a little bit of context on this one, so if there was something else that needed to be done, let me know!
Also, i decided to leave support for the comma-separated version of the parameter just in case anything was using it. …
=> Include param as array

resources/assets/components/CampaignInbox/index.js, resources/assets/components/CampaignSingle/index.js
When you click on the "X" in the History Modal, the modal wouldn't close. This PR fixes that bug. 
Go to campaign inbox and single page. Make sure you can close the History Modals when opened for a post. 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/151529616
=> fixes history modal close bug

app/Http/Controllers/Api/ActivityController.php, documentation/endpoints/activity.md, resources/assets/components/SignupCard/index.js, resources/assets/components/UserOverview/index.js
- On the user page, the `campaign_id`, `campaign_run_id`, and campaign run start date (if we have it) is exposed to provide the admin with more information: 
- The signups are now returned by signups with the most recently created posts at the top in descending order. 
- The card wanted to sort by more recent campaigns first, and then of the more recent campaigns, sort the ones that the member has RB on first (campaign leads said that they just want to see these first as it's most important to see what they've RB for over everything they've signed up for). However, I was unable to do this because the `/activity` endpoint returns signups (not campaigns). I started to return by most recent signups in descending order but of those results, couldn't figure out a way to then filter by signups …
=> Individual signup page order change and added information 

app/Http/Controllers/Api/ActivityController.php, app/Http/Controllers/Traits/TransformsRequests.php, documentation/endpoints/activity.md, tests/Http/Api/ActivityApiTest.php
Fixes my previous PR that assumed we could just change the pagination by default. 
That wasn't great because it was a breaking change. 
Updates the `/activity` endpoint to allow a client to specify `cursor` pagination to make for quicker pagination queries. 
👀 
Fixes 🐛
=> Optin to cursor pagination instead of doing it by default

app/Http/Controllers/Api/EventController.php, app/Http/Transformers/EventTransformer.php, app/Http/routes.php, app/Models/Event.php, documentation/README.md, documentation/endpoints/events.md
- Adds `GET /events` endpoint 
- Returns either paginated results of all events or all events per signup (`/events?filter[signup_id]=:sid`
- Updates documentation
- Hit `/api/v2/events` and you should get paginated list of all events 
- hit `/api/v2/events?filter[signup_id]=18`and you should get non-paginated results of all events that are signup events for signup 18 (or any :sid)
Not sure if this is the best way to do this or not for the future (when we want to grab all events associated by a post or a different type of post in the future) but figured we can start with this? 
First part in this [Pivotal card](https://www.pivotaltracker.com/n/projects/2019429/stories/150986550). Wanted to break this up so it didn't turn into a monster PR!
=> Adds GET /events endpoint

app/Http/Controllers/Api/EventController.php
Capitalizes the "T" in "Transformer" to fix this bug I was getting on Thor when trying to hit the `/events` endpoint: 
```
[2017-10-02 15:52:18] thor.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Rogue\Http\transformers\EventTransformer' not found in /var/www/rogue/releases/20171002154015/app/Http/Controllers/Api/EventController.php:16
```
👀 
I _think_ this is the fix for this bug! Couldn't reproduce on my local environment and noticed that it was a lowercase t - might be causing issues? 
Fixes typo in this PR: #433
=> capitalizes the T

app/Http/Controllers/UsersController.php
Added `auth` and  `role:admin,staff` middlewares (middlesware?) to the `UsersController` so that only logged in admins can hit the `/users` and `/user/{id}` routes. Unauthenticated users could only hit those routes directly, and were unable to search.
1. Don't log in.
2. Go here: `/users/5589c991a59dbfa93d8b45ae`.
3. Go here: `/users`.
4. Both of those should take you to the login page.
[Pivotal Card](https://www.pivotaltracker.com/story/show/151605532)
=> Add auth and admin middleware to UsersController

app/Http/Controllers/CampaignsController.php, app/Http/Controllers/ExportController.php, app/Http/routes.php, app/Services/ExportService.php, app/helpers.php, composer.json, composer.lock, resources/assets/components/CampaignSingle/index.js, resources/assets/components/StatusCounter/index.js, resources/assets/components/UserExport/index.js, resources/assets/components/UserExport/user-export.scss
- Added new `ExportController` with a `show` function to trigger a download of the signup details csv for the given Campaign. Also includes corresponding route.
- New helper on the backend `getAgeFromBirthdate` to calculate ages based on birthdays.
- In `CampaignsController.php`, check to see if any signups on the given campaign have `details`. This has to be on the backend because we need to check ALL signups, not just ones on the current page. Then, conditionally display the export button (only show if there is something to export).
The button:
The part that I'm least sure about is how the front-end decides how to display the button each time. Seems a little wild to run the 
```
$export = Signup::whereNotNull('details')->where('campaign_id', $id)->get();
``` 
query every time a single …
=> Signup details file exports

app/Http/Controllers/ExportController.php
For this first pass, We only want to export signups that have no details. PN only sends over details if the user _opts out_ of third party messaging. Otherwise we assume they are opted-in. For the pass at thisexport, we only want to see opt-INs not opt-OUTs.
👁 
If we do use this export functionality for more things, we should really think about refactoring this so that we can pass in options about what to actually export. 
Fixes https://www.pivotaltracker.com/story/show/151767351
=> Export signups with null details

app/Http/Middleware/AuthenticateApi.php, composer.json, composer.lock, config/auth.php, config/services.php, storage/keys/.gitignore
This pull request adds support for [Northstar tokens](https://github.com/DoSomething/northstar/blob/dev/documentation/authentication.md) to Rogue, via [an update to Gateway](https://github.com/DoSomething/gateway/pull/83).
Authenticating API requests via the `X-DS-Rogue-API-Key` header should still work, but you should also be able to provide a valid Northstar JWT (for now, requiring the `admin` scope) as well!
In the future, it makes sense to use people's Northstar tokens when making requests to Rogue from Phoenix Ashes/Next so these requests are made on behalf of individual users - and then we can use `auth()->id()` or `token()->role` to get their real authentication details.
[#150224528](https://www.pivotaltracker.com/story/show/150224528)
=> Accept Northstar JWT tokens, via Gateway server middleware/guard.

config/deploy.rb
We need Northstar's [public key](https://aurora.dosomething.org/clients) for each environment to be able to accept JWTs. To do this, we want to symlink the `storage/keys` directory to a persistent version kept in `/var/www/rogue/shared` between deploys.
👀
References #403.
N/A
=> Symlink persistent keys directory when deploying.

app/Http/Controllers/ExportController.php, app/Services/ExportService.php
Uses eloquent [`cursor`](https://laravel.com/docs/5.5/eloquent#chunking-results) method to iterate through all signups more efficiently. 
👀 
Fixes 🐛
=> Use a cursor to grab signups to lessen the load on memory

app/Http/Controllers/Three/SignupsController.php, app/Http/Controllers/Traits/TransformsRequests.php, app/Http/Transformers/Three/SignupTransformer.php, app/Http/routes.php, documentation/README.md, documentation/endpoints/activity.md, documentation/endpoints/events.md, documentation/endpoints/signups.md, tests/Http/Three/SignupTest.php
- Adds functionality for the `GET /api/v3/signups/:signup_id` endpoint
- Adds functionality to optionally include posts e.g. `GET /api/v3/signups/:signup_id?include=posts`
- Adds tests for `GET /api/v3/signups`, `GET /api/v3/signups/:signup_id`, and `GET /api/v3/signups/:signup_id?include=posts`
- Hit the `GET /api/v3/signups/:signup_id` and you should see all the correct information for the signup you specified! 
- If you do something like `GET /api/v3/signups/z`, you should get this error message: 
`{"error":{"code":500,"message":"Class 'Rogue\\Http\\Controllers\\Three\\ModelNotFoundException' not found"},"debug":{"file":"\/home\/vagrant\/DoSomething.org\/rogue\/app\/Http\/Controllers\/Three\/SignupsController.php","line":58}}`
- In your vagrant box, run `vendor/bin/phpunit` and make …
=> GET /api/v3/signups/:signup_id endpoint

app/Http/Transformers/EventTransformer.php
While parsing through content column of Events tables, checks if value is set first before trimming to fix 🐛 
Make sure you can open and update history modal (usually with more recent entries). 
For some reason, the content column of the Events table is not getting stored in the same manner as older events (some have spaces of `\` in the response). I'll make another card for this to check out to make sure all of our data is being stored in a normalized manner. 
Fixes this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/152039043).
=> Fixes History Modal & Update Quantity Bug

app/Http/Controllers/Api/ActivityController.php, documentation/endpoints/activity.md, resources/assets/components/UserOverview/index.js
- Removes logic for `limit=all`.
- Updates the user page to grab `80` signups instead of `all`.
- Visit a user page. All signups should be listed and it should work! 
We wanted to change this manually to a large number in order to see all user signups on their overview page. We don't want to have the `limit=all` logic any longer in case of a "busy" edge case or a malicious call so it doesn't kill our servers.
We'll revisit this problem once we build more RESTful API endpoints. 
Fixes this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151566633).
- [ x ] Documentation added for new features/changed endpoints.
=> Changes limit to 80 instead of all on user page 

app/Http/Requests/PostRequest.php, app/Http/Requests/SignupRequest.php, app/Repositories/SignupRepository.php, composer.lock, database/factories/ModelFactory.php, database/faker/FakerContentfulCampaignId.php, database/migrations/2017_10_17_143249_store_campaign_id_as_string.php, database/migrations/2017_10_17_144601_make_campaign_run_nullable.php, documentation/endpoints/posts.md, documentation/endpoints/signups.md, tests/Http/Api/PostApiTest.php, tests/Http/Api/SignupApiTest.php
Allows Rogue to support Contentful Campaigns directly. Contentful Campaign IDs are strings in the vain of `6LQzMvDNQcYQYwso8qSkQ8`. So this PR updates the DB and some logic to support that. Also Contentful campaigns do not have runs, so this PR removes the requirements around `campaign_run_id`. Also adds tests for sending a request from Contentful. 
I think you can go commit-by-commit. 
@DFurnes would love for you to check out the tests to make sure I am making the correct assumptions about what the request would look like. Mainly that PN would only send over a `campaign_id` with no run. 
This will help PN talk directly to Rogue without needing a PA proxy endpoint. 
Fixes https://www.pivotaltracker.com/story/show/151853719
=> Support Contentful Campaign Ids

config/deploy.rb, lib/capistrano/tasks/laravel.rake
Fixes a deploy bug I introduced in #454 where I defined the task to restart the queue in the wrong place. 
👀 
We're using capistrano 3 for Rogue so this fix updates our configuration to work with that. 
Fixes 🐛
=> Move restart task

lib/capistrano/tasks/laravel.rake
One more change to the deploy. Removes the `:on_error` param (task?) which is not supported by Cap 3. 
Fixes 🐛
=> remove :on_error

app/Services/ExportService.php, app/helpers.php
Add more columns to the signup export. 
New columns are: Last Name, Zip, and DOB.
Also update the age helper to return `null` if we don't give it a birthdate because we returning "0" by default which was odd. 
👀 
These new columns were requested by Truth. See the ticket for the email they sent requesting this. 
Fixes https://www.pivotaltracker.com/story/show/152201483
=> add more columns to signup export

resources/views/errors/403.blade.php
When a user tries to log in to Rogue but doesn't have the proper permissions, they just get a [simple "You don't have permission" page](https://user-images.githubusercontent.com/583202/31959036-9a5a45a8-b8c1-11e7-82ec-72c1247def16.png). Unfortunately we need to ask them to refresh their Rogue session to get access and there's no "Log Out" button.
This pull request just copies over the same page from Aurora.
👀
This is necessary because we embed the user's Northstar role in their access token, and so there's a time delay on the new role being "propagated" over to Rogue.
References [this slack convo](https://dosomething.slack.com/archives/C0YGXUE01/p1508855325000078).
Fixes 🐛
=> Add a more user-friendly 403 page.

app/Http/Requests/PostRequest.php, app/Repositories/PostRepository.php, documentation/endpoints/posts.md
- Previously, we didn't required posts to provide `caption`, `source`, `remote_addr`, but if they WERE provided, they couldn't be `null`. Lots of old data is missing these values, so we want to allow `null` values to be submitted. 
- Update how we use timestamps for migrated posts. Previously, we set the `created_at` and `updated_at` to both be what was sent as `created_at` in the script. Now, we want to allow `updated_at` to be set if we have it.
👀 This won't mess up any non-migration related functionality, will it?
[Pivotal](https://www.pivotaltracker.com/story/show/151761727)
=> Signupless reportback updates (let some fields be nullable, timestamps)

app/Services/PostService.php, app/Services/SignupService.php, documentation/endpoints/posts.md, documentation/endpoints/signups.md
Added the ability to send `dont_send_to_blink` flag with Post and Signup requests. If the flag is true, we do not send anything to Blink. If the flag is false or not included, the data will be set to Blink as long as the other already existing conditions are true (ex. Blink feature flag is true).
Is the logic right?
We don't want to send a bunch of events to Blink when we run the upcoming Signupless Reportback migration.
[Card](https://www.pivotaltracker.com/story/show/152320855)
=> Allow requests to include flag to not send data to Blink

composer.lock, resources/assets/components/ReportbackUploader/index.js, resources/assets/components/Signup/index.js, resources/assets/components/UploaderModal/index.js
- Adds `updateQuantityOrWhyState` function so when we update the quantity or why participated when uploading a post on behalf of the user, the state on the signup page also updates.
- This function is needed because we only need to update the state, not make a new call since the submit button in the modal already makes that API call. 
- This fixes the bug that we have right now of when you upload a post with a quantity and/or why, the signup page doesn't reflect this information until the page is refreshed. 
- Go to a user's signup page `/signups/:signup_id`
- Upload a photo with a quantity and/or why participated
- You should see these reflected at the top of the signup page when you close the modal without refreshing the page
- No additional events should be created in the events table …
=> Refresh Bug on Uploader Modal 

app/Providers/ModelServiceProvider.php, tests/Http/EventTest.php
- Only creates a signup event if `why_participated`, `quantity`, `quantity_pending`, or `deleted_at` has changed. 
- This prevents creating unnecessary/redundant signup events in the events table when a post is updated but nothing about the actual signup is updated.
- Adds tests to make sure:
- An event gets created when a signup is created
- An event gets created when a signup is updated
- An event gets created when a post is created
- An event gets created when a post is updated, but a signup event does not get created when this happens.
- Go to a user's signup page. 
- Upload a new post for the user. 
- You should only see one event added in the events table for the new post. 
- Update the quantity of the signup. 
- You should then see a new signup event in the events table. 
- If you …
=> Refactors Event Logic 

.eslintrc.js, package.json, webpack.config.js
This PR adds JS linting. For linting we are using [eslint](https://eslint.org/) and uses DoSomething.org's shared [eslint configuration](https://github.com/DoSomething/eslint-config) package to define our style standards. 
* We are adding this late into the life of the project so there are many errors. This adds the eslint package and dependencies. It also adds the `eslint-loader` to our webpack config so that it will check for errors when compiling a build. 
However this **will not fail** the build. There will be many errors as we start to clean up these files, so we want to surface them, but we want to continue to be able to work in the meantime. 
👁 
I suggest installing [SublimeLinter](http://www.sublimelinter.com/en/latest/) so that your files can be linted in the editor for a better …
=> JS Linting

app/Http/Controllers/Three/PostsController.php, app/Http/routes.php, documentation/README.md, documentation/endpoints/posts.md, tests/Http/Three/PostTest.php, tests/Http/Three/SignupTest.php
- Creates the `POST /api/v3/posts` endpoint
- Creates tests for this endpoint
- Adds tests to make sure an unauthenticated user/app can't update posts
- Hit the `POST /api/v3/posts` endpoint and make sure a signup and post are created if a signup didn't exist yet or a post is created if the signup already exists
- Make sure all tests pass! 
Fixes this [Pivotal Ticket](https://www.pivotaltracker.com/n/projects/2019429/stories/152482999)
=> Creates POST /api/v3/posts

app/Console/Commands/ImportPreGambitSignupsCommand.php, app/Console/Commands/ImportSignupsCommand.php, app/Console/Kernel.php, tests/Console/ImportSignupsCommandTest.php, tests/Console/example-signups.csv
Includes a script to import signups from a csv! The csv will include ALL pre-Gambit signups. The script checks if a signup already exists for the given user, campaign, and campaign run before creating a new one so there are no duplicates.
Will this run right?
This is gonna make Rogue the source of truth!!
[Pivotal](https://www.pivotaltracker.com/story/show/151064896)
=> Artisan command to load in pre-Gambit (or any!) signups from CSV

database/migrations/2017_11_09_193724_drop_tagging_tags_table.php, database/migrations/2017_11_09_193847_drop_tagging_tagged_table.php, database/migrations/2017_11_09_193937_drop_tagging_tag_groups_table.php, database/migrations/2017_11_09_194027_drop_password_resets_table.php
I've been sussing out some strange issues with migrations and Laravel's new `migrate:fresh` command, and happened to notice we have a few tables that we don't need!
This pull request removes `tagging_tag_groups`, `tagging_tagged`, `tagging_tags` from the old tagging package we used, and `password_resets` from Laravel's default migrations.
🥞
🍴
[#152601905](https://www.pivotaltracker.com/story/show/152601905)
=> Remove taggable & password reset tables.

app/Http/Controllers/UsersController.php, resources/views/search/search.blade.php
- If a name is searched or an invalid email address (either spelled incorrectly or we don't have a member with that email address), the page is redirected to the search page with a "No user found!" message at the top: 
👀 
@ngjo I actually think that this will work for the other case you mentioned in the [Pivotal Card](https://www.pivotaltracker.com/story/show/151136337/comments/181993342) too that Pili flagged! 
Fixes this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151136337).
=> User Search Failure Page

resources/assets/components/Users/UserInformation.js
If a user doesn't have a first name, their mobile number will link to their signup page.
👀 
The mobile number will only link to their signup page if there is no user name. If there is a user name, the mobile number will not be a link. Do we want the first name AND the mobile number to always link to the signup page, even if the user has both for more consistency? 
Fixes this [Pivotal Ticket](https://www.pivotaltracker.com/n/projects/2019429/stories/151462735).
=> Mobile Link to Signup Page

.env.example, app/Http/Kernel.php, app/Http/Middleware/TrimStrings.php, app/Http/Middleware/TrustProxies.php, composer.json, composer.lock, config/trustedproxy.php
Since we have Heroku running behind a load balancer, we need to configure [Trusted Proxies](https://laravel.com/docs/5.5/requests#configuring-trusted-proxies) so that Heroku knows that we're running over HTTPS. This will allow it to create the proper `https://` URLs.
This should make no difference on AWS or local environments, where we'll leave the `TRUSTED_PROXY_IP_ADDRESSES` environment variable empty.
This reflects the same implementation in [Northstar](https://github.com/DoSomething/northstar/pull/572) & [Phoenix Next](https://github.com/DoSomething/phoenix-next/pull/35).
DoSomething/devops#341
=> Configure trusted proxies for Heroku.

app/Http/Middleware/TrustProxies.php, config/trustedproxy.php
Whoops – two updates to our trusted proxy settings:
🗃 Only parse the `TRUSTED_PROXY_IP_ADDRESSES` environment variable into an array if it has commas, otherwise use as a string. This is required for the `*` option [that Heroku requires](https://devcenter.heroku.com/articles/getting-started-with-laravel#trusting-the-load-balancer).
🔥 Discards the `Forwarded` and `X-Forwarded-Host` headers, as instructed in [Heroku's documentation](https://devcenter.heroku.com/articles/getting-started-with-laravel#trusting-the-load-balancer) because they are not sent by (or sanitized) by Heroku or AWS.
👀
I tested #492 after deploying it and it didn't work, turns out this is why!
DoSomething/devops#341
=> Updates to Trusted Proxy settings.

resources/assets/components/Quantity/index.js, resources/assets/components/WithReviewing/index.js
I was testing some stuff to make sure I was writing the correct tests 😂 
I found two small issues: 
* The `Quantity` component seems to be getting the `quantity` prop as a number and sometimes as a string. So I updated the validation to allow both with a `@TODO` to figure out why. 
* Delete functionality was broken because we were removing the post from the state but not the `postId` so when the page tried to re-render and sort, we were was using the wrong set of postIds and crashing. This PR removes the deleted post's id as well. 
Fixes 🐛
=> Small bug fixes

resources/assets/components/WithReviewing/index.js, resources/assets/utilities/RogueClient.js
Adds a new class `RogueClient` that extends the Gateway-JS `RestApiClient`. 
Right now the class doesn't do much but I did add a method that is a bit of a higher-level method for getting posts. So when you need to get posts via the api, you can call `getPosts(options)` where the `options` param is the filter configuration and query params you would like to use. 
Only using this in the `WithReviewing` component for now to keep changes contained. See background context for why. 
👀 
It is proven to be pretty hard to mock dependency classes in Jest.
When testing the `WithReviewing` component we need to mock calls to the api via the `RestApiClient`. 
Jest does not run test code through webpack so we can't easily mock the `RestApiClient`. By adding a new class, `RogueClient`, we can just extend …
=> Rogue JS API Client

wercker.yml
This pull request uses our [updated Docker box](https://github.com/DoSomething/ds-docker-php/pull/2), which includes ChromeDriver, Node 8, and npm 5.3. This gets us deterministic npm installs using the `package.lock` file & faster builds (2 minutes 22 seconds, down from 4 minutes on the old box).
🚥 👀 
~We can remove the `:box-updates` tag if we decide to merge this in to `latest`.~ We did!
References #490.
=> Use updated Wercker box.

app/Repositories/PostRepository.php
- Explicitly state which fields should be shoved into the signup when we get a request to create a new post. This prevents us from overwriting any existing fields on the signup by accident.
Questions that might be completely out of scope:
When I was working on this, the timestamps weren't behaving as I expected them to. As the code stood, the signup would be set to have the dates passed in with the post, but would then be touched by the post when the new post was created. It just didn't make sense to me to change the `updated_at` of the signup when it will end up being `now`
- If we pass timestamps with a post, do we want to apply those to the **existing** signup? 
- I think that we don't because adding a new post doesn't change when the existing signup was created or updated.
- If we …
=> Do not update signup source with post source

app/Repositories/PostRepository.php
In the first pass at this I assumed that each new post comes with a `quantity` and `why_participated`, but that is not the case! This fix makes no assumptions about receiving either of those fields, and maintains the signup source not getting overwritten.
Does this work with reportbacks from ALL sources? Gambit?
We are not guaranteed a `why_participated` with a new post from Gambit.
[Card](https://www.pivotaltracker.com/story/show/152979109)
cc: @ngjo this would benefit from some additional testing love
=> Don't assume we are passed a quantity or why_participated when a new post is added

resources/assets/components/HistoryModal/index.js
If there are no events under a signup, instead of not opening the history modal at all (which means there would be no way to update quantity either), show a blank state!
Blank:
Not blank:
Does it look okay? Is the copy okay?
[Card](https://www.pivotaltracker.com/story/show/152851215)
=> Blank state if there are no events to show in the History Modal

app/Exceptions/Handler.php
I applied this as a hotfix last night since Blink was hammering Rogue with 3,426+ retries for a single reportback with a `video/3gpp` upload attached. In order to prevent Blink from doing this, let's catch this type of exception and return a `422` error.
👀
- [Slack conversation](https://dosomething.slack.com/archives/C4VN7J0SE/p1511228107000049)
- [New Relic exception page](https://rpm.newrelic.com/accounts/108038/applications/24971199/filterable_errors#/show/e8c56dfc-ce5d-11e7-9600-0242ac110008_2864_12792/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&filters=%5B%7B%22key%22%3A%22error.class%22%2C%22value%22%3A%22Intervention%5C%5CImage%5C%5CException%5C%5CNotReadableException%22%2C%22like%22%3Afalse%7D%5D&_k=4ape37)
N/A
=> Return 422s for invalid filetypes.

database/migrations/2017_11_20_202525_add_quantity_column_to_posts_table.php
Added a `quantity` column to the `posts` table.
- column is after `northstar_id`
- defaults to `null`
- is nullable
- is an integer
Is that where we want the column to be? Are there different qualities we want it to have?
[Card](https://www.pivotaltracker.com/story/show/152900013)
=> Add quantity column to posts table

package-lock.json, package.json
Sinon seemed to be pulling in old versions of [these modules](https://github.com/DoSomething/rogue/network/dependencies#7641431) as well.
```sh
$ ag 'uglify-js' package-lock.json
4821:        "uglify-js": "2.8.29"
4858:        "uglify-js": {
4860:          "resolved": "https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.29.tgz",
10519:        "uglify-js": "2.8.29",
10546:        "uglify-js": {
10548:          "resolved": "https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.29.tgz",
$ ag 'js-yaml' package-lock.json
2014:        "js-yaml": "3.10.0",
2022:        "js-yaml": {
2024:          "resolved": "https://registry.npmjs.org/js-yaml/-/js-yaml-3.10.0.tgz",
2913:        "js-yaml": "3.10.0",
2967:        "js-yaml": {
2969:          "resolved": …
```
=> Update sinon.js for js-yaml & uglify-js dependency.

app/Http/Transformers/ReportbackTransformer.php, app/Models/Post.php
When hitting `v1/reportbacks`, if the particular post we are returning has a quantity of `null` (indicating that we have not yet added the quantity values into the posts table), we return the `quantity` from the signup that the post is associated with. Otherwise, if the post _does_ have a quantity (including `0`), sum up the quantities of that post and all the other posts under the same signup and return that.
Does any documentation need to be updated with this?
[Card](https://www.pivotaltracker.com/story/show/153073306)
=> Return sum of post quantities or signup quantity

app/Http/Transformers/ReportbackTransformer.php, app/Http/Transformers/SignupTransformer.php, app/Models/Post.php, app/Models/Signup.php, tests/Http/Api/ActivityApiTest.php
- Updates `SignupTransformer` to return quantity as a summed total of quantity across all posts under a signup, if `$signup->quantity` doesn't exists.
- Combines `getTotalQuantity()` into `getQuantity()`
- Adds a test to make sure quantities are returned correctly. 
- Does the logic in the test and code make sense? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/153032066) Pivotal card.
=> Quantity update to GET /api/v2/activity

app/Http/Controllers/Three/PostsController.php, app/Http/Controllers/Three/SignupsController.php, documentation/README.md, documentation/endpoints/posts.md, documentation/endpoints/v3/posts.md, tests/Http/Three/PostTest.php
This is just a quick demo of what we can do with OAuth now on our v3 routes! This pull request adds some rudimentary access control to the `v3/posts` index:
🤺 Users will now automatically see their own reaction count based on their OAuth token, rather than having to send an `as_user` parameter with a user ID.
✋ Users will not see other people's posts until they've been approved (unless they're an admin)!
I'd check commit-by-commit since e29b6a5 just extracts the `index` method out of the trait.
This is just to demonstrate the cool things we can do with OAuth tokens (and because I want to use this as part of my GraphQL demo 😁), I'll work with @ngjo to put together some cards with other places we can do things like this in Rogue!
[#152602162](https://www.pivotaltracker.com/story/show/1526021 …
=> Some example stuff we can do with OAuth on v3 routes!

app/Console/Commands/PostQuantity.php, app/Console/Kernel.php, app/Models/Post.php, app/Models/Signup.php
Here it is!
What it does:
1. Takes in an argument of the Signup ID to start with. If none given, starts at the very beginning (ID=1).
2. Grabs all the signups (with their posts their posts) in chunks of 100.
3. Check if the signup has posts. If not, move on to the next signup.
4. See if any of the posts have quantity. If they do, see if it's ALL of them. If it's all of them, move on to the next signup. If it's only some of them, subtract the quantity on the posts from the quantity on the signup. If some of the posts are `accepted`, grab the most recently submitted `accepted` one and give it the difference in quantity. If there are no accepted posts, grab the most recently submitted post and give it the quantity from the signup. Give all other posts with no quantity `0`.
5. If none of the …
=> Artisan command to move quantity from Signup to Post

composer.json, composer.lock, documentation/README.md
- Updates Gateway version to v1.12.0
- Updates documentation to give info. that v3 endpoints use OAuth 2 instead of `X-DS-Rogue-API-Key`
👀 
@katiecrane @sbsmith86 @DFurnes once this is merged, you should run `composer update`!
=> Updates Gateway version and documentation re: v3 endpoints using OAuth 2

.env.example, config/app.php
Updates our logging configuration to write to the `syslog` by default, unless otherwise specified by the `APP_LOG` environment variable.
👀 
Also- any suggestions about how to confirm this is working on other environments?
I am setting `APP_LOG=daily` on my local to continue getting daily log files for my development work, but using `syslog` on our other environments should allow us to see logs in heroku, logstash, etc.
Fixes https://www.pivotaltracker.com/story/show/153261132
=> Syslog default

app/Http/Controllers/Three/SignupsController.php
Just a tiny update! I wanted to be able to `filter[id]=1,2,3,4` & noticed it wasn't hooked up.
👀
This allows other services to batch up requests for a handful of signups.
N/A
=> Allow filtering signup index.

app/Models/Post.php, app/Repositories/PostRepository.php, resources/assets/helpers.js
If a post has a default image, send `null` instead of `default` to Blink. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/152517900) Pivotal Ticket.
=> Send null instead of 'default' to Blink if post has default image 

composer.lock, database/migrations/2017_12_08_203149_add_indexes_to_posts.php
This pull request significantly boosts the performance of the `v3/posts` index – dropping the time spent on the database query from 1500-2500ms (using a Thor dump on my local) to 17-30ms when using `?pagination=cursor`. That's like... 100x faster? 🐎
With "normal" pagination, this speeds things up from ~1500ms to ~700ms... still not great, but better!
Things should happen a lot faster.
I've been drilling down into our GraphQL query performance, and noticed a lot was being spent here.
N/A
=> Improve performance of 'v3/posts' endpoint.

app/Http/Controllers/Three/PostsController.php, tests/Http/Three/PostTest.php
- Removes middleware so OAuth works correctly with a non-admin user (and any user can use v3 endpoints).
- Removes tests that only allow admins to make these requests (except for `DELETE /v3/posts`).
👀
=> Removes middleware so OAuth works correctly with a non-admin user

app/Models/Post.php, app/Models/Signup.php
Blink is sending us a bunch of validation errors because we are sending `null` quantity over to it now. This is related to the most recent deploy, but I am not clear on how to rollback the deploy on jenkins. This is a hotfix that will just send over 0 if quantity is `null` which should clear up the errors. 
👀 
https://dosomething.slack.com/archives/C0YGXUE01/p1513010104000973
=> Quantity validation bug

app/Console/Commands/PostCleanup.php, app/Console/Kernel.php
This PR adds a command `php artisan rogue:postcleanup {date}` that will go through all the posts we received on the given date, find the duplicate submissions (by checking for duplicate `captions`) and then delete all but the most recent submission from the DB. 
👀 
Definitely double check the deletion logic: 
I used `$post->forceDelete()` to truly delete the record from the DB because we don't want a record of these bad posts. 
I used `Storage::delete({path_to_file})` to delete the image from storage. 
This script is meant to clean up the duplicate posts we receive because of this bug: 
https://github.com/orgs/DoSomething/teams/team-bleed/discussions/5
Fixes 🐛
=> Add script that will clean up extraneous posts we received

public/.user.ini
We're seeing errors whenever users try to upload files above ~1MB:
```
Dec 12 14:16:19 rogue-thor app/web.1:  [12-Dec-2017 22:16:18 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) in /app/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php on line 136 
Dec 12 14:16:19 rogue-thor app/web.1:  [12-Dec-2017 22:16:18 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /app/vendor/symfony/debug/Exception/FatalErrorException.php on line 1 
Dec 12 14:16:26 rogue-thor app/web.1:  [12-Dec-2017 22:16:25 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) in /app/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php on …
```
=> Increase PHP memory limit.

tests/Browser/FilterPostsTest.php, tests/Browser/ReviewPostTest.php, tests/Browser/UserSearchTest.php, tests/Browser/pages/CampaignInboxPage.php, tests/DuskTestCase.php
Adds Dusk test to test user flow of:
- accepting and tagging a post
- rejecting a post
- rejecting then accepting a post 
- Any other scenarios I'm missing?
- All tests should pass when running `php artisan dusk --group=ReviewPost`!
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/153223089) ticket
=> Reviewing Dusk test

app/Http/Controllers/Three/PostsController.php, app/Http/Transformers/Three/PostTransformer.php
- Fixed bug to get `GET /v3/posts?include=signup` working again.
- Hit `GET /v3/posts?include=signup` and you should receive posts with their associated signup. 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/153458101) Pivotal ticket
=> GET /v3/posts?include=signup bug

config/database.php
This pull request allows us to use the configured [Heroku Redis](https://devcenter.heroku.com/articles/heroku-redis) addons on each of our applications, which automatically set a `REDIS_URL` environment variable that needs to be parsed into the expected `REDIS_HOST`, `REDIS_PASSWORD`, and `REDIS_PORT`.
👀
We were connecting both production & Thor environments to the same ElastiCache instance which is like, very not ideal. This will let us quickly get Thor on it's own instance, and we can consider pushing this up to production tomorrow as well.
N/A
=> Parse REDIS_URL into corresponding environment vars.

app/Console/Commands/MakeDefaultURLsNull.php, app/Console/Kernel.php
This is a shiny new artisan command to go through all of our posts with a `url` of `default` and set that to `null` instead. We probably do not want to run this until we are storing incoming borked images as `null` or we will have to run it twice (running it twice is no problem technically though).
Will this do what I said it would?
[card](https://www.pivotaltracker.com/story/show/153491711)
=> Script to make default urls null

documentation/endpoints/posts.md
Removes `DELETE /api/v2/posts/{post_id}` from documentation because this doesn't exist (this is a web route!) 
👀 
Should we add web routes to the documentation?
=> Removes endpoint from documentation that doesn't exist

app/Services/CampaignService.php, resources/assets/components/Table/CampaignRow.js
- This PR fixes the bug we were seeing with inconsistent Pending Post counts on the Campaign Overview page (the Pending number would be 2 but then when clicking review, there would be no posts to review in the inbox). 
- This was because it was counting posts that had been soft deleted when making the count query. However, when pulling the actual posts that needed to be reviewed in the campaign inbox page, it did not include posts that have been soft deleted.
- This PR adds a line in the query to only count those posts whose `deleted_at = NULL`
👀 
- To test on local, find a campaign that has 0 pending posts to review. 
- Change a post's status to pending (that has been soft deleted). 
- You should still see the Pending count on the Campaign Overview page for the campaign to say 0. 
Fixes …
=> Excludes soft deleted posts in count for pending posts per campaign 

app/Http/Controllers/Api/ReviewsController.php, app/Http/Controllers/ReviewsController.php, app/Listeners/SendTaggedNotification.php, app/Services/PostService.php, app/Services/SignupService.php, app/Services/Three/PostService.php, app/Services/Three/SignupService.php
Adds some low level log messages to rogue so we know when the basic significant events happen. 
Logs when a signup is created, a post is created, a post is reviewed, a post is tagged, a post is deleted. 
I standardized the log message format to be in the form of `resource_action` (i.e `signup_created`) 
This will allow us to do some easy searching in log aggregators like Papertrail and create some easy charts/alerts that will show us trends in how many of these events happen each day. 
👀 
I do most logging in the Service classes since it is sort of business logic and I don't want to pollute other functionality with log messages. However, for things such as tagging and reviewing, it had to be done in-line with where tagging and reviewing happen. 
We want to be able to see if we see dips or …
=> Log resource actions 

app/Services/PostService.php, app/Services/SignupService.php, app/Services/Three/PostService.php
Just a small update to follow up on my previous PR (#559 )
We need to send the `post_created` event when we move through the update functionality even though we are creating a post. This follows the logic of when we send posts to blink.
👀 
We have a card in our backlog to work through this logic. When we create a new post we shouldn't consider it an update.
=> Log post event anytime we send to blink

app.json
the `scripts`, `addons`, and `buildpacks` properties should be at the same level as `env` not embedded in it. 
👀
=> Move properties to correct level in JSON object

app/Console/Commands/PostQuantity.php
🍔  We now chunk by 1000!
🦃  There is another argument that gives admins the option to sleep for a time after saving an updated post. The admin gives the time in microseconds. A microsecond is one millionth of a second.
Does this pause at the appropriate times?
The script was hogging up the database!
=> Bigger chunk, option to sleep after saving post

resources/assets/components/Post/__snapshots__/test.js.snap, resources/assets/components/Post/test.js, resources/assets/components/ReviewBlock/__snapshots__/test.js.snap, resources/assets/components/ReviewBlock/index.js, resources/assets/components/ReviewBlock/test.js, resources/assets/components/Tags/index.js, resources/assets/components/Tags/tags.scss
- Adds the following new tags: 
- Irrelevant
- Inappropriate
- Unrealistic Quantity
- Test
- Incomplete Action
- Adds ability to tag both accepted and rejected posts
- Tag button will be disabled until a post's status is accepted or rejected 
- Once a post's status is accepted or rejected, tag buttons become enabled and when you hover over the tags, they will be highlighted in blue 
👀 
**Does all the above make sense? Those scenarios should work!** 
Approved and tagged post:
**Rejected and tagged post:**
**Reviewed post with enabled tags vs unreviewed post with disabled tags:**
Fixes these Pivotal Cards:
- https://www.pivotaltracker.com/n/projects/2019429/stories/150443391 
- https://www.pivotaltracker.com/n/projects/2019429/stories/152892878
=> Adds New Tags and Ability to Tag on Accepted and Rejected Posts 

app/Providers/AppServiceProvider.php, app/helpers.php, composer.lock
This pull request includes two updates for logging:
🆙 Updates to [Gateway 1.14.1](https://github.com/DoSomething/gateway/releases/tag/v1.14.1) w/ simplified request ID logic.
🆔 Also adds a `client_id()` helper (inspired by the same thing in Northstar's codebase), and attaches it to all log messages so we can quickly figure out where something came from. For web (or anonymous) requests, it attaches Rogue's specified Client ID.
Here's an example API request & web request in the logs:
```
[2018-01-12 19:25:07] local.INFO: post_created {"id":153,"signup_id":141} {"user_id":"5571f4f5a59dbf3c7a8b4569","client_id":"phoenix-oauth","request_id":"754546b2-a67f-47d1-9eda-203c8f989601"}
[2018-01-12 19:25:14] local.INFO: post_reviewed {"id":35,"admin_northstar_id":"5571f4f5a59dbf3c7a8b4569","status":"r …
```
=> Upgrade to Gateway 1.14.1 & attach 'client_id' to logs.

app/helpers.php
I'm a real dummy and didn't commit a fix I'd made to #578 on my local! Sorry! 🙃 This updates the ternary to check whether or not the token actually exists (`token()` itself is always a thing), and uses the correct [getter](https://github.com/DoSomething/gateway/blob/3126df34d278548b72cb924409419fe60f72be4f/src/Server/Token.php#L66-L74)).
😩
🤦‍♂️
🙅‍♂️
=> Fix an issue with grabbing client ID.

app/Providers/AppServiceProvider.php, app/helpers.php
One last change and I'm done! I was looking at #578/#579 on Thor and noticed that this is very confusing to default it to the OAuth client name... it makes it look like legacy API key requests are coming from `rogue-oauth`. Bleh!
```
Jan 12 11:54:17 rogue-thor app/web.1:  [12-Jan-2018 19:54:12 UTC] [2018-01-12 19:54:12] thor.INFO: signup_created {"id":8496462,"northstar_id":"5a59126110707d215f46fd0a"} {"user_id":null,"client_id":"rogue-oauth","request_id":"2558d4af-a520-44df-b987-0248809d646a"} 
Jan 12 11:55:42 rogue-thor app/web.1:  [12-Jan-2018 19:55:37 UTC] [2018-01-12 19:55:37] thor.INFO: Request made. {"method":"POST","uri":"https://blink-staging.dosomething.org/api/v1/events/user-signup-post","request_id":"c7b0f03b-c243-4765-a62d-23e2d42b2ee0"} …
```
=> Only return a client_id on OAuth requests.

app/Http/Transformers/PostTransformer.php, app/Http/Transformers/Three/PostTransformer.php, app/Models/Post.php
This pull request pulls the hackified timestamp query-string into the `getMediaUrl` method on the model, so that we can only apply it if Glide is disabled.
Note: The part where we return Glide URLs (without the timestamp querystring) is hidden in the diff!
We can probably clean up all these code paths in a future PR.
N/A
=> Don't append query-string to Glide URLs.

app/Console/Commands/MakeSourceSms.php
Updates query in source script to also grab soft deleted signups/posts.
When you run the script, even soft deleted signups/posts should have an updated source from `sms-mobilecommons` to `sms` 
We want this so **no** records in the database have `sms-mobilecommons` as the source.
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154410187) Pivotal Card.
=> Updates query in source script to also grab soft deleted signups/posts

database/migrations/2018_01_18_191700_add_columns_to_categorize_posts.php
Adds columns to the `posts` table to store `type`, `action_bucket`, and `details`
the `details` column should be `JSON` but our current DB version doesn't support that column type so it is `TEXT` for now.
👀 
A full thread on how we decided to add these columns: https://github.com/orgs/DoSomething/teams/team-bleed/discussions/12
**Question** 
* Should we have a default value for `action_bucket`? Old posts won't have a value in it, but it is not nullable because we want it to be required. 
Fixes https://www.pivotaltracker.com/story/show/154212087
=> Add action columns

app/Http/Controllers/Three/ReactionController.php, app/Http/Controllers/Three/SignupsController.php
- Allows anyone to store, update, or delete signups. 
- Allows anyone to store a reaction. 
- Updates `/reactions` endpoint to use `auth()->id()` to get Northstar ID instead of requiring it to be passed as a param. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154524951) Pivotal Card.
=> Update to v3/signups and v3/reactions endpoints

app/Console/Commands/PostQuantity.php
Turns out I don't know how to estimate how much storage stuff takes up in PaperTrail! We need to log less! Going to try doing this by chunking by 10,000.
Can anything bad happen in production if we chunk 10x as many things? 5000 would be another option to chunk by.
=> Log less in the PostQuantity script by chunking by 10,000

app/Console/Commands/ImportSignupsCommand.php
1. Removed progress bar because that is not useful with Heroku
2. Add an argument to only log every so many signups imported. Defaults to 1000. 
Is this a reasonable way to log every X signups imported?
We most likely can't log every single signup imported when running this script because it will fill our logs right up!
[Card](https://www.pivotaltracker.com/n/projects/2019429/stories/152608407)
=> Signup Import script updates: Remove progress bar, log at given frequency

database/migrations/2016_07_27_172344_create_kudos_table.php, database/migrations/2016_10_11_200952_drop_file_id_from_reactions.php, database/migrations/2017_04_06_174417_drop_reportbacks_items.php, database/migrations/2017_04_27_183942_drop_unique_northstar_id_index_reactions_table.php, database/migrations/2017_06_29_194312_add_user_column_to_events_table.php, database/migrations/2017_11_09_193724_drop_tagging_tags_table.php
I forgot I'd done this! This was from sorting through a bunch of fatal errors that'd occur when running `php artisan migrate:refresh` (back when I thought that was causing issues with the Laravel 5.4+ test runner). It turns out that wasn't the issue, but it's also nice to be able to rollback migrations again. 😅 
If you pull down this branch, you should be able to safely run `php artisan migrate` and then `php artisan rollback` without getting errors!
🥞 🤷‍♂️ 
N/A
=> Fix inconsistencies between up & down migrations.

app/Services/CampaignService.php
- Doesn't include posts that have been soft deleted (where `deleted_at` is not `null`) when summing accepted, pending, and rejected posts. 
:eyes:
On the campaign single page, the pending post count was inaccurate. Aki flagged when he was reviewing, it said "18 Pending" posts but when he clicked to review them, there were none. This is because it was counting posts that had been soft deleted.
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154804464) Pivotal Card.
=> Disregards posts that have been soft deleted in query for post totals

app/Models/Signup.php, tests/Http/Api/PostApiTest.php
This fixes a bug that was flagged by @weerd .
There was a bug in how we return quantity on a signup in `Signup::getQuantity()`
in  `Signup::getQuantity()` we made a decision on how to return `quantity` based on three things: 
1) If `features.v3QuantitySupport` was *not* true, then we were *not* supporting the splitting of quantity across posts and we should just return the quantity as stored in the `signup` table.
2) If there were no `posts` under a signup then we return the quantity as stored in the `signup` table.
3) If the first post under a signup did not have a quantity on it, then we made the assumption that it was an old post from before we split quantity on the post and returned the quantity as stored in the `signup` table.
- This is where the issue was! If someone submitted a …
=> Update to how we return signup quantity

app/Http/Controllers/ImportController.php
When testing the turbovote csv import on thor I was getting this error:
```
Feb 01 13:52:44 rogue-thor app/web.1: [01-Feb-2018 21:52:43 UTC] [2018-02-01 21:52:43] thor.ERROR: fstat() expects parameter 1 to be resource, object given {"exception":"[object] (ErrorException(code: 0): fstat() expects parameter 1 to be resource, object given at /app/vendor/league/flysystem/src/Util.php:271)"} {"user_id":"5550f8ec469c64bf3d8b6a63","client_id":null,"request_id":"82d06f9b-a921-41ae-8b97-5552f4e5c66e"}
```
`Storage::put()` expects the second parameter to be a string but we were sending it the CSV object. So this casts the csv as a string before storing it. 
👀 
Fixes 🐛
=> Storage::put expects the file to be sent as a string

app/Http/Transformers/Three/PostTransformer.php, app/Http/Transformers/Three/SignupTransformer.php, documentation/endpoints/v3/posts.md, documentation/endpoints/v3/signups.md, tests/Http/Three/PostTest.php, tests/Http/Three/SignupTest.php
- Updates SignupTransformer and PostTransformer to only return sensitive info. to admins and owners: 
- Only admins and signup owners will get `why_participated` returned in the response
- Only admins and post owners will get `tags`, `source`, and `remote_addr` returned in the response
- Updates tests
- Updates documentation
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154611572) Pivotal Card.
=> Updates SignupTransformer and PostTransformer to only return sensitive info. to admins and owners

app/Http/Transformers/Three/SignupTransformer.php, documentation/endpoints/v3/signups.md, tests/Http/Three/SignupTest.php
- Gates details in SignupTransformer for only admins and owners of signup to see 
- Updates tests
- Updates documentation 
👀 
Relevant work in #608
=> Gates details in SignupTransformer for only admins and owners of signup to see 

app/Http/Controllers/Three/PostsController.php, app/Repositories/Three/PostRepository.php, app/Services/Three/PostService.php, documentation/endpoints/v3/posts.md, tests/Http/Three/PostTest.php
This touches `v3/posts` `delete` and `patch`. Documentation is updated to reflect changes.
Delete:
- Call the existing `destroy` method in `PostService`
- No changes to `PostService` or `PostRepository`
Patch:
More changes here!
- Do not accept `status` because those changes will come in through `v3/reviews`
- Hit the `update` method of `PostService`
- In `PostService`, assume that we are always working with a Post and never a Signup
- In `PostRepository`, same deal, only update the Post and don't mess with Signups
Does this contain any breaking changes? See a better way to do anything?
We need to always do alterations through the service classes to be sure that any business logic happens.
[Card](https://www.pivotaltracker.com/story/show/154877666)
=> Hit PostService when updating or deleting posts through v3 endpoints

app/Http/Controllers/Three/PostsController.php, app/Http/Requests/Three/PostRequest.php, app/Http/Transformers/Three/PostTransformer.php, app/Repositories/Three/PostRepository.php, documentation/endpoints/v3/posts.md, tests/Http/Three/PostTest.php
This updates the `POST /api/v3/posts` API endpoint to validate, store, and return the new `type`, `action`, and `details` columns that we added to support multiple actions. 
Updates the `Three\PostTransformer` to return these new columns, but only returns them for admins and post-owners. *Thoughts on gating all of these columns?*
Updates V3 PostAPITest. 
👀 
Going to go through each endpoint individually to see how it could be updated to support these new columns. This is just the first one but I think updating `PostTransformer` gets us most of the way there. 
Fixes https://www.pivotaltracker.com/story/show/154154145
=> POST /api/v3/posts - Update to store new post columns

app/Models/Post.php
1. Adds `campaign_id` (which was supposed to be there all along!)
2. Added some signup fields that were needed to ingest posts which were previously retrieved from the signup portion of the `/activity` response.
1. Is the signup reloaded each time we call `$this->signup`? I want to make sure this isn't too bad performance wise.
2. The signup fields were already sent with the signup, but this is how data currently expects it and it is a large lift on their side to alter that, while on our side we just need to add 5 easy lines.
3. From @sheyd : Next sprint, Team Storm will discuss changing Quasar data model to not necessitate sending signup data on posts anymore (as part of MySQL -> Postgres).
[Card](https://www.pivotaltracker.com/story/show/154725135)
=> Add additional fields to post Quasar payload

app/Http/Controllers/ReviewsController.php, app/Http/Controllers/Three/ReviewsController.php, app/Http/Controllers/Three/SignupsController.php, app/Jobs/SendDeletedPostToQuasar.php, app/Jobs/SendDeletedSignupToQuasar.php, app/Repositories/Three/SignupRepository.php, app/Services/PostService.php, app/Services/Three/PostService.php, app/Services/Three/SignupService.php
1. `PATCH v3/signups` now calls new `update` method in `SignupService`, which in turn calls new `update` method in `SignupRepository`. This mirrors `PATCH v3/posts`.
- `SignupService` also triggers the `SendSignupToQuasar` job.
2. `DELETE v3/signups` now calls new `destroy` method in `SignupService`, which in turn calls new `destroy` method in `SignupRepository`. This mirrors `PATCH v3/posts`.
- `SignupService` also triggers the new `SendDeletedSignupToQuasar` job.
Do both of these flows make sense?
[Card](https://www.pivotaltracker.com/story/show/154968896)
=> Use Review & Signup Service & Repository for Patch and Delete and send that to Quasar

app/Http/Controllers/Three/SignupsController.php, app/Models/Signup.php, app/Repositories/Three/PostRepository.php, database/migrations/2018_02_09_150930_add_quantity_index_to_signups_table.php, documentation/endpoints/activity.md, documentation/endpoints/v3/signups.md, tests/Http/Three/PostTest.php, tests/Http/Three/SignupTest.php
- Adds the `orderByQuantity` filter for `GET /v3/signups` 
- Choose to return results with quantity in ascending or descending order
- Adds logic to update and save summed quantity on the signup when a post is created or updated via the v3 endpoints
- Adds tests for:
- `?filter[northstar_id]`, `?filter[campaign_id]`, and `?filter[campaign_run_id]`
- `?orderByQuantity=desc` and `?orderbyQuantity=asc`
- updates PostTests to check for summing of quantity on signup
- Updates documentation 
- All filters should work in Postman/Paw! 
- Did I miss any logic for updating the total quantity on the signup? Does this need to happen anywhere else outside of the `POST /v3/posts` and `PATCH `/v3/posts/{post}` endpoints?
Fixes the first task in …
=> Adds orderBy filter for v3 Signup Index and tests & updates logic to save summed quantity on signup when post is created or updated

database/migrations/2018_02_09_150930_add_quantity_index_to_signups_table.php
- Fixes the mistake made in [this PR](https://github.com/DoSomething/rogue/pull/614) where I accidentally made the `quantity` column a unique index instead of just an index. 
👀
=> updates migration for quantity to not be unique 

app/Jobs/ImportTurboVotePosts.php, app/Repositories/Three/PostRepository.php, app/Services/Three/PostService.php
Updated the import CSV logic to run status updates through the `PostService@update` method so that all business logic is executed with the post update. That means that c.io should get the updated post status on their end. 
👀 
Found this bug with @rapala61 and @ngjo . We did a test CSV import to rogue-thor with registration records from Rafa. We saw that while the initial signups and posts got into c.io successfully, one of the posts had an updated status that was not being sent to c.io. 
This fixes it so that post updates during an import will be sent to blink successfully.
Fixes https://www.pivotaltracker.com/story/show/155090650
=> Send updates through PostService

app/Http/Transformers/Three/UserTransformer.php
- `/api/v3/signups?orderBy=quantity,desc&include=user,posts` was breaking on thor with this error:
```
Feb 13 12:58:21 rogue-thor app/web.1:  [13-Feb-2018 17:58:14 UTC] [2018-02-13 17:58:14] thor.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /app/app/Http/Transformers/Three/UserTransformer.php:24)"} {"user_id":null,"client_id":null,"request_id":"98aca44d-28ca-40e8-9fff-cb9a6a4ea29c"} 
```
- This PR fixes it by wrapping the check for `$user->id` in the `if ($user)` conditional so it doesn't break if there is no user.
👀 
Fixes error from #619
=> Fixes /api/v3/signups?include=user

app/Http/Controllers/CampaignsController.php, resources/assets/components/CampaignTable/index.js, resources/assets/components/Table/CampaignRow.js
Removes the "Pending" count on the Campaign Overview page. 
👀 
Should help with some performance issues we have been seeing on the `/campaigns` page.
Fixes https://www.pivotaltracker.com/story/show/155047732
=> No pending count on Campaign Overview page

app/Models/Post.php
When a user submits a post, we send the updated post to Quasar. However, while the quantity lives on the signup, they don't get that updated quantity! For now, let's send the quantity on the post only if it is not null, otherwise grab the quantity from the signup.
👀
=> If quantity is not stored on post, send Quasar quantity from signup

app/Jobs/SendDeletedPostToQuasar.php, app/Jobs/SendDeletedSignupToQuasar.php, app/Jobs/SendPostToQuasar.php, app/Jobs/SendSignupToQuasar.php, app/Repositories/Three/PostRepository.php, app/Services/PostService.php, app/Services/SignupService.php, app/Services/Three/PostService.php, app/Services/Three/SignupService.php
1. Update the send signup and post to Quasar jobs to check for the sending to quasar feature flag in the job itself so locally you can still get (altered to say that they WOULD HAVE BEEN sent to Quasar) log messages and know that you are hitting the job. This has been a pain point for me when working on these jobs.
2. There are two times in the `PostService` where we go on to alter a signup, so we should be calling the signup job alongside the post job.
Passing tests? Feature flags still working?
When testing it became evident that we were missing some signup updates!
[Card](https://www.pivotaltracker.com/story/show/155199023)
=> Fixing edge cases where the signup is updated in Post Repository and not sent to Quasar

app/Http/Transformers/Three/PostTransformer.php, app/Jobs/ImportTurboVotePosts.php, app/Models/Post.php, app/Repositories/Three/PostRepository.php, database/migrations/2018_02_20_193349_add_source_details_column_to_posts.php
Adds a `source_details` column to the `posts` table so we can store things like newletter ID there instead of in the json stored in the `details  column. 
:eyes:
Before this, I was extracting `source_details` from the TV referral code and adding it to the JSON object that we stored in the `details` column. After talking with the team, we decided to store this separately. 
Fixes https://www.pivotaltracker.com/story/show/155132110
=> Post source details

app/Console/Commands/PostQuantity.php
- Anywhere that we call `save()` on something, we send it to Quasar!
- We do this in three spots when we alter the quantity on the post, and that's the only time we update anything
Does this make sure that Quasar gets all the updates that this script makes?
This is needed since we now push updates to Quasar.
[Card](https://www.pivotaltracker.com/story/show/154979182)
=> In the quantity update script, if we save a post, send it to Quasar

resources/assets/components/Post/index.js
- Box shows `0` if there is no quantity on the post (instead of the box not showing up all together)
Before:
After:
👀 
This shouldn't matter for most of the posts, only those posts that were created before we turned on the flag to support quantity on post. 
The only posts that should show this `0` are the posts that the script turns to `0` and puts the signup quantity on the latest post. 
Relevant to [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154347334) pivotal card.
=> Box shows 0 if there is no quantity on the post 

app/Jobs/SendReviewedPostToCIO.php, app/Jobs/SendReviewedPostToCustomerIo.php, app/Services/PostService.php, app/Services/Three/PostService.php, tests/Http/ReviewsTest.php, tests/Http/Three/ReviewsTest.php
- Added `SendReviewedPostToCIO.php` which works like our other jobs to send data along. It hits `v1/events/user-signup-post-review` in Blink and sends the same payload that we sent to Blink when a post is created.
- The job is dispatched in the `review` methods of both the original and the v3 `PostService`
- In the reviews tests, call `Bus::fake()` and `        Bus::assertDispatched(SendReviewedPostToCIO::class)` to make sure the job is getting dispatched (but don't actually call it)
All the tests are passing, but are there other tests where the job should be getting dispatched?
[Card](https://www.pivotaltracker.com/story/show/149862801)
=> Send reviews to Customer.io

app/Console/Commands/TagPosts.php, app/Console/Kernel.php
Adds a command that lets you programatically tag a group of posts. 
To run the command: 
`php artisan rogue:tagposts --tag=1 --posts=1,3,6`
which would tag posts 1, 3, and 6 as `hide-in-gallery`
👀 
So we can quickly tag some posts for a campaign when we need to. 
Needed to fix some posts on prod.
=> Tag posts command

app/Console/Commands/UpdateSignup.php, app/Console/Kernel.php
Adds a command to update a target field/value on the signup record given a set of query contraints.
Here is an example for updating `campaign_run_id` to `8044` for all signups where `campagin_run_id = 7669` (currently) and that were created after 3/1/18 
`php artisan rogue:updatesignup --target=campaign_run_id --campaign_run=7669 -targetValue=8044 --date=2018-03-01`
:eyes:
This is a command to help with a specific use case outlined in this [slack thread](https://dosomething.slack.com/archives/C2BLZGBPH/p1520264003000003)
I tried to make it flexible if we need it for other things, but this should at least take care of this use case and we can flush it out if more requests like this come in. 
Also this moves through the `SignupService` so it will send the signup update to quasar. 
Fixes 🐛
=> Update signup field command

app/Console/Commands/EditImagesCommand.php, app/Repositories/PostRepository.php, app/Repositories/Three/PostRepository.php
Moves the cropping we do under the glide feature flag so that, if glide is on, we don't do it.
The hope is that this won't cause any weird issues with images being oriented or cropped incorrectly. 
👀 
Detailed background on this issue: https://github.com/orgs/DoSomething/teams/team-bleed/discussions/16
addresses https://www.pivotaltracker.com/story/show/154979852
=> 154979852 Turn off image editing

app/Http/Controllers/Three/PostsController.php, app/Http/Requests/Three/PostRequest.php, app/Http/Transformers/PostTransformer.php, app/Http/Transformers/ReportbackTransformer.php, app/Http/Transformers/Three/PostTransformer.php, app/Models/Post.php, app/Repositories/PostRepository.php, app/Repositories/Three/PostRepository.php, database/factories/ModelFactory.php, database/migrations/2018_03_12_202842_rename_caption_to_text_in_posts_table.php, documentation/endpoints/v3/posts.md, tests/Http/Three/PostTest.php
- Rename `caption` column in `posts` table to `text`
- `v3` now uses `text` instead of `caption` everywhere
- `v2` still takes in and validates `caption`, but saves to and retrieves from the `text` attribute on the post
- adds additional `text` field to Blink (c.io) and Quasar payloads (still sends `caption` too)
Tests passing? Test updates look good? `v2` still works?
Words aren't always a caption.
[Card](https://www.pivotaltracker.com/story/show/155822916)
=> Re-naming `caption` to `text`

app/Http/Controllers/ImagesController.php, app/Http/Kernel.php, phpunit.xml, tests/Http/ImagesTest.php
- Added throttling (at 15 requests/minute) to the `/images` route
- Added a test to make sure that a user gets a `Too Many Attempts` response after 15 images
👀  Is there anything else we should be testing for? Do we need to test with more than one image?
[Card](https://www.pivotaltracker.com/n/projects/2019429/stories/155853452)
=> Throttle /images route

app/Http/Transformers/Three/PostTransformer.php
We need these `type` and `action` fields to be able to decide how to display a post (e.g. "show this as a photo" vs. "show this as a text block"). In the future, we may also separate different actions into different galleries.
👀
These are needed in order to display content correctly to users.
[#155944555](https://www.pivotaltracker.com/story/show/155944555)
=> Make 'type' and 'action' fields public.

app/Console/Commands/ReviewSignup.php
I created a command to review all posts under a signup with a given status and when I went to run it, I ran into errors that `admin_northstar_id` was `null`.
In order to get that working I had to update the `review` method to optionally allow us to pass the user that reviewed these post. In order for that to work, I need to actually pass all the params, even the optional ones so it knows which values to pass to which param. 
👁 
🐛
=> Fix Review Signup Command

resources/assets/components/Post/__snapshots__/test.js.snap, resources/assets/components/Post/index.js, resources/assets/components/Signup/index.js, resources/assets/components/WithReviewing/index.js, resources/views/signups/show.blade.php
- Fixes rotation bug on campaign inbox page (more details in [this card](https://www.pivotaltracker.com/n/projects/2019429/stories/155955162))
- Adds rotation feature on signup page (`/signups/:signup_id`)
- Removes any reference to `edited url` because it is no longer being used with Glide on. 
- Rotate an image.
- The image should rotate on the front end. 
- Click the "Original Photo" link - this should also be updated to the new rotation.
- Refresh the page and the new rotation should be on the image. 
@sbsmith86 and I saw some weirdness - we're not sure why all the reviewing was showing up _except_ for the rotation button without this fix 👻 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/155955162) Pivotal Card except for the `503` error @ngjo - I couldn't …
=> Rotation bug on Rogue Admin

app/Http/Requests/Three/PostRequest.php, docs/endpoints/v3/posts.md, resources/assets/components/Post/__snapshots__/test.js.snap, resources/assets/components/Post/index.js, resources/assets/components/Post/test.js, tests/Browser/FilterPostsTest.php, tests/Browser/UserSearchTest.php, tests/Http/Three/SignupTest.php
This updates the front end so Rogue admins understand that they're reviewing a text post versus other post.
Specifically, this PR: 
- Changes "Photo Caption" to "Text" in the Post component if the post is a `text` post (if it is a photo post, it remains as "Photo Caption"!)
- Extends the width of the Post component if this the Post type is text 
- Changes the validation to show up to 256 characters
**Signup page text Post:** 
**Signup page photo Post:** 
**Inbox page text Post:**
**Inbox page photo Post:**
👀 
Is this clear that this is a text post and not that the photo is missing? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156173991) Pivotal card.
s/changed endpoints.
=> Text Reportback Updates 

app/Http/Controllers/Three/PostsController.php, app/Repositories/Three/PostRepository.php, app/helpers.php
While working on [Chompy](https://github.com/DoSomething/chompy) I noticed that when we made a post request to Rogue from Chompy it wasn't creating posts/signups with the correct NS ID. 
This was because we were using the NS ID of the authenticated user. 
In the case of Chompy, we are authenticated as the application, chompy, and we are create posts/signups on _behalf_ of the user in the CSV. 
So this PR updates the helper to grab NS ID from the authenticated user to also check if it is a client submitting the post and if it has the correct scope that allows it to store posts with a custom status.
=> Allow client with correct scopes to store posts with NS ID and Status

app/Console/Commands/ImportSignupsCommand.php, app/Jobs/SendSignupToBlink.php, composer.lock, phpunit.xml, tests/Console/ImportSignupsCommandTest.php
- Added business logic into `ImportSignupsCommand` which happens after we create a signup (`SendSignupToQuasar`, `SendSignupToBlink`)
- updated `SendSignupToBlink` to be local dev friendly (you are able to hit it regardless of if you are sending to Blink and it will log accordingly, so you can be sure it is getting hit at the right times)
- `ImportSignupsCommand` no longer requires a `created_at` and will use `now()` if one is not given
- updated our test `.env` to not send to Blink
- lock file is updated because I had to run `composer update`
- updated script to use source `phoenix-next` instead of `sms`
Is the update to our test `.env` okay? 
[Card](https://www.pivotaltracker.com/story/show/156354146)
=> Update import signups command to use for RRR imports

app/Http/Controllers/PostsController.php, app/Http/Transformers/PostTransformer.php, app/Models/Post.php, tests/Http/PostTest.php
We were previously only loading the `reacted` and `reaction_count` properties on the [post index](https://github.com/DoSomething/rogue/blob/b0af355ddb2e29c126a71aa5d55a13bceda7453c/app/Http/Controllers/PostsController.php#L64-L97), which means the same posts ran through `PostTransformer` on `posts/{postId}` (or anywhere else) would appear to have no reactions. 🙅‍♂️ 
This pull request updates the `Post` model to always eager-load the `reaction_count` property on posts, and adds an (also eager-loaded) `reaction` has-one relationship to get the current user's reaction if it exists. This simplifies logic in that index method a bit & makes everything consistent!
I added a failing test in f207c79, which [shows how the response is incorrect](https://app.wercker.com/dosomething/rogue/runs/build/5a …
=> Fix reaction counts & boolean on `v3/posts/:id` route.

tests/Console/ImportSignupsCommandTest.php, tests/Http/PostTest.php, tests/Http/ReactionTest.php, tests/Http/SignupTest.php, tests/Http/TagsTest.php
- Cleans up Signup, Post, Reaction, and Tags Tests to use `withAdminAccessToken()` where possible and deletes unneccessary params in some `withAccessToken()` cases. 
- Comments back in incomplete Signup Tests that are now passing (this was a wercker config issue)!
- Explicitly sets rejected posts' to a new `northstar_id` variable to get `testPostsIndexAsOwner` tests to pass every time
- Fixes the `testImportingSignupsWithNoDuplicates` test
- Wercker was using [`rogue-qa-client`](https://aurora-qa.dosomething.org/clients/rogue-qa-client) in [Aurora](https://aurora-qa.dosomething.org/clients). This for some reason isn't allowing us to update this client and it is stuck on Authorization code grant instead of Machine (Client Credentials grant). Other clients aren't …
=> Cleans up tests and makes sure AsOwner tests are always passing 

package-lock.json, package.json, resources/assets/components/Signup/index.js, resources/assets/components/Tags/index.js
- Not all api requests in the `SignupComponent/index.js` need to be sent with `Content-Type: multipart/form-data`. This moves this to only the `submitPost` method. 
- Updates the v3 tagging endpoint to either send a `POST` or `DELETE` request when clicking the tags depending on if it has it yet or not. 
- Note: you'll need to run `npm install` since this also updates the gateway-js version we're using! cc @sbsmith86 @katiecrane @DFurnes 
👀 
Cleans up bugs from [this](https://github.com/DoSomething/rogue/pull/660) PR. 
=> Update Signup Component to use v3 endpoints bug

app/Console/Commands/SendToQuasar.php, app/Console/Kernel.php, app/Jobs/SendPostToQuasar.php, app/Jobs/SendSignupToQuasar.php, tests/Console/SendToQuasarCommandTest.php
- New command to send posts and signups within a given date range (or all, if none given) to Quasar
- Dates are based on the `updated_at` timestamps on the posts and signups
- Adds 3 tests for each scenario that the command can be run with (no arguments, start date given, and start and end date both given)
Does using `updated_at` make sense? Is it okay to assume we always want to send both posts and signups?
[Card](https://www.pivotaltracker.com/n/projects/2019429/stories/155196205)
=> Command re-send posts and signups to Quasar

app/Console/Commands/SendToQuasar.php, app/Jobs/SendPostToQuasar.php, app/Jobs/SendSignupToQuasar.php
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥  
- `SendPostToQuasar` and `SendSignupToQuasar` now accept a parameter to suppress logging (if nothing is passed, they still log)
- `SendToQuasar` command now takes in an option (defaults to 1) for how often we should log that a Post or Signup has been sent to Quasar (aka how often we should NOT suppress logging)
Will this keeps the logging to a reasonable volume when running this command over all Posts and Signups?
Without a change like this, we would way overflow our logs.
[Card](https://www.pivotaltracker.com/n/projects/2019429/stories/155196205)
=> Allow sending posts/signups to Quasar without logging

app/Http/Requests/PostRequest.php
We are adding 5 new statuses that can be applied to `voter-reg` posts. 
This updates the validation rule on the post `status` field so that we can pass them via the API
I think there might be a way to lock down the validation even more. Like if `type=voter-reg`, validate it one way. If `type=photo` validate it another way. But this is a first pass.
👀 
https://github.com/DoSomething/chompy/wiki/TurboVote-Imports#status-translation-rules
Addresses a need for our importer app to send TurboVote statuses to rogue. 
=> Update status validation to allow for new voter-reg statuses

app/Models/Post.php
We want to query a user's posts by `type` and `action` for the submission gallery on You've Got The Power (so we can show separate galleries for a user's text and photo submissions). This pull request adds those columns to the `Post` model's `$indexes` array so they can be filtered.
👀
Both columns are already indexed in the database.
[#155866191](https://www.pivotaltracker.com/story/show/155866191)
=> Add 'type' and 'action' to Post indexes.

Procfile
Updates the Procfile so that we limit failing jobs to only try 3 times at most before moving it into the `faild_jobs` table and moving on. 
👀 
This has been causing our logs to clog. See thread here: https://dosomething.slack.com/archives/C0YGXUE01/p1524058904000801
🐛 
=> Limit queue retries

README.md, app/Console/Commands/ForceDeleteTestRecords.php, app/Console/Kernel.php, docs/endpoints/posts.md, docs/endpoints/signups.md
- Force deletes test records created by Ghost Inspector and Runscope
- Signups and Posts from runscope are found by `source` (either `runscope` or `runscope-oauth`). 
- Signups from Ghost Inspector are found by `why_participated` (`Why! I love to test! Team Bleed for the win! Tongue Cat forever!`)
- Posts from Ghost Inspector are found by `text` (`Caption! I love to test! Team Bleed for the win! Tongue Cat forever!`)
- Updates some documentation irrelevant to this but wanted to just sneak in here!
👀 
@sheyd re: [sending deleted events to the queue](https://dosomething.slack.com/archives/C6J24ADQW/p1523391687000195), since this is just working directly with the database and force deleting, I don't think it will actually send any notifications when this is deleted. Can you explain a little …
=> Force delete test records

app/Jobs/SendPostToCustomerIo.php, app/Jobs/SendPostToQuasar.php, app/Jobs/SendSignupToCustomerIo.php, app/Jobs/SendSignupToQuasar.php
checks to see if object exists before sending to quasar/blink
👀 
We were seeing some errors in the logs that described runscope tests trying to send objects to quasar/blink that didn't exist. The tests automatically delete the records after creation and could do this before sending to the services. This PR adds a check to only send if the records still exists to avoid these errors. 
=> checks to see if object exists before sending to quasar/blink

composer.json
Removes `"@php artisan cache:clear"` from `composer.json` file. 
👀 
We don't need to do this every deploy - just needed to make sure #679 didn't break anything! Removing per @DFurnes 's [suggestion](https://github.com/DoSomething/rogue/pull/684#issuecomment-383659004).
Fixes #684 
=> removes cache:clear from composer.json

resources/assets/components/Post/__snapshots__/test.js.snap, resources/assets/components/Post/index.js, resources/assets/components/Post/test.js, resources/assets/helpers.js
- Re-adds `displayCaption` helper method back in that was removed from #686 
- I realized we actually do need this because this is how we display on the signup page! 
- Renames the `displayCaption` helper method to `displayPostText` so it is more reflective of the data schema. 
- Updates Jest test. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156813946) Pivotal card (for real this time!)
=> Re-adds text helper back in and re-names 

app/Http/Controllers/SignupsController.php, app/Http/Transformers/SignupTransformer.php, app/Models/Signup.php, resources/assets/components/Signup/index.js, tests/Http/SignupTest.php
- This PR fixes the bug when you hit `/v3/signup/:signup_id?include=posts`, it returns the incorrect signup (without the `?include=posts`, everything works fine).
- This is because `withVisiblePosts()` returns a collection and it was grabbing the first post from this collection and always returning that instead of the one specified in the endpoint! 
- This fix explicitly grabs the correct signup from the collection. 
- Also adds tests to make sure this is returning properly!
- Also fixes bug @aaronschachter pointed out that was introduced in #688 that deleting signup no longer works (we were sending `signup.signup_id` instead of `signup.id` which was changed when we changed to using v3 endpoint).
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157064679) Pivotal …
=> v3/signups/:signup_id?include=posts bug

app/Http/Requests/PostRequest.php
- Adds `max_width` and `max_height` to Post Request. 
- We were seeing a lot of errors in Papertrail saying these images didn't exist when they actually do. 
- All these images were fairly large - we are thinking if we limit them to be smaller then this won't break anymore. 
- More context [here](https://github.com/orgs/DoSomething/teams/team-bleed/discussions/27). 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157050126) Pivotal Card.
=> adds max width and max height to Post Request

app/Http/Controllers/PostsController.php, app/Models/Post.php, docs/endpoints/posts.md
- Updates `/v3/posts` index to not return posts tagged "Hide In Gallery" by default
👀 
- Hit this endpoint
- No posts that are tagged "Hide In Gallery" should be returned! 
The You've Got The Power gallery was showing posts that were tagged "Hide In Gallery" because it is using the `v3` endpoint and it hasn't been updated to not include these! 
Update [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157411893) Pivotal Card. 
=> v3 posts index to not return posts tagged "Hide In Gallery" by default

app/Models/Post.php, tests/Http/PostTest.php
- Changes to `hide-in-gallery` which is what it actually is in the database so that #693 works!
- Adds tests. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157411893) Pivotal Card.
=> Adds test for scopeWithHiddenPosts and updates typo so it actually works! 

app/Http/Controllers/TagsController.php, composer.lock, docs/endpoints/README.md, docs/endpoints/tags.md, resources/assets/components/Post/index.js, resources/assets/components/Signup/index.js, resources/assets/components/Tags/index.js, resources/assets/components/WithReviewing/index.js, routes/api.php, tests/Http/TagsTest.php
- Updates `v3/tags` endpoint to toggle (instead of having a separate `POST /v3/posts/{post}/tags` and `DELETE /v3/posts/{post}/tags` endpoints.
- Updates front end to use `v3/tags` endpoint instead of `tags` endpoint.
- Fixes bug where post's text/caption disappears when tagging. 
Fixes these Pivotal cards: 
- [When you apply any tag it seems, the caption disappears](https://www.pivotaltracker.com/n/projects/2019429/stories/157204400)
- [Update v3 tags endpoint to function more like a toggle (similar to v3 reactions)](https://www.pivotaltracker.com/n/projects/2019429/stories/156656870)
=> Updates v3/tags endpoint to toggle and updates front end to use this endpoint

app/Services/CampaignService.php
- If there is no `campaign_id`, mock campaign array we would get from Ashes to handle error gracefully and prevent entire page from crashing. 
👀 
This is related to #700 when we saw an error in production where `/campaigns` was throwing a `500` error. This was because there was a signup record with no `campaign_id` and caused the page to crash. If this happens in the future, we want to handle this error in a more graceful manner.
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157673595) Pivotal card.
=> if there is no campaign id, handles error gracefully

app/Http/Controllers/PostsController.php, app/Managers/PostManager.php, app/Repositories/PostRepository.php, app/Services/AWS.php
During the recent outage on 5/19/18 we adding a bunch of log messages around the `POST api/v3/posts` route to see if there was an issue there. 
This is just some clean up since that was not the issue. 
👀 
https://github.com/DoSomething/devops/issues/408
Clean up
=> Remove detailed logging of POST api/v3/posts endpoint

app/Http/Transformers/Legacy/Two/PostTransformer.php, app/Http/Transformers/PostTransformer.php, app/Policies/PostPolicy.php
Adds "view" logic to Post Policy (that should have been added in #702 !) 
- Only admins / owners should be able to see a Post's `tags`, `source`, `source_details`, `remote_addr`, and `details` via the API.
I noticed that for `v2`, anyone gets `tags` and `source` - should we update this as well? Since we don't use access tokens though I'm not sure if this is possible? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156700437) Pivotal Card and finishes up #702 
=> Adds "view" logic to post policy

EU_members_local.csv, app/Console/Commands/GDPRComplianceCommand.php, app/Managers/PostManager.php, app/Services/AWS.php, tests/Http/PostTest.php
Fixes bug to actually delete from s3 when a post is deleted and adds fastly purge to GDPR script in #709 
Delete a post (via API or by running GDPR script) - the url should also be deleted from s3! 
@DoSomething/team-bleed since this wasn't working before, do we need to do any work to delete images for posts that have been soft deleted? Is this even possible to find the file names again? 
More work to fix [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157709055) Pivotal Card.
=> Fixes bug to actually delete from s3 when a post is deleted and adds fastly purge to GDPR script

app/Console/Commands/UpdateSignupAndOrPostField.php
Adds logic to `rogue:updatefield` command to only log if signup or post id is divisible evenly by `logfreq` option.
👀 
There are 1,796,212 signups alone with the `source` equal to `NULL` - this is going to make us go over our Papertrail limit if we log each record that is being updated! 
Updates #711 
=> adds logic to only log if signup or post id is divisible evenly by logfreq option

app/Policies/PostPolicy.php
Removes `Authenticatable` type-hint so non-user apps can use update post policy method.
👀 
We need to remove this so Chompy can finish updating! 
Slack thread [here](https://dosomething.slack.com/archives/C0YGXUE01/p1527701337000521).
=> Removes type-hint so non-user apps can use update post policy method

app/Models/Post.php, tests/Http/Legacy/Web/TagsTest.php, tests/Http/TagsTest.php
- When running the script on thor, I was getting this error: 
```thor.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '470884-1' for key 'PRIMARY' (SQL: insert into `post_tag` (`created_at`, `post_id`, `tag_id`, `updated_at`) values (2018-06-05 17:53:51, 470884, 1, 2018-06-05 17:53:51)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '470884-1' for key 'PRIMARY' (SQL: insert into `post_tag` (`created_at`, `post_id`, `tag_id`, `updated_at`) values (2018-06-05 17:53:51, 470884, 1, 2018-06-05 17:53:51)) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint …
```
=> Update to BulkReviewPosts script

app/Console/Commands/BulkReviewPosts.php
changes `type` option to mandatory argument in `BulkReviewPosts` command 
👀 
For some reason, this query wasn't only looking for the `text` type when we ran in Thor (but worked as intended on local, even when I dumped out the thor db to my local). For extra safety measure, we decided to change the `type` option to a mandatory argument in the command.
Updates command made in #720 
=> changes type option to mandatory argument in BulkReviewPosts command 

resources/assets/components/WithReviewing/index.js
Delete unneeded line that was breaking rotate function - on the signup page, when trying to rotate, I got this error:
```
app-ab704991ec4dd340b523.js:25 Uncaught TypeError: Cannot read property '331804' of undefined
```
This line doesn't seem to do anything though so lets delete it! 
👀 
Fixes error in #729 
=> delete unneeded line that was breaking rotate function

app/Console/Commands/BulkReviewPosts.php
Adds `setEagerLoads` to query to disable eager relations in `BulkReviewPosts` command. 
👀 
When I ran this on Prod, I was getting this error:
```
Jun 08 07:41:31 rogue-prod app/run.5993: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php on line 701
Jun 08 07:41:31 rogue-prod app/run.5993: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 122
```
@DFurnes suggested to add this to clear this! More context [here](https://dosomething.slack.com/archives/C0YGXUE01/p1528469204000469).
Updates command created …
=> Disable eager relations in BulkReviewPosts command

app/Managers/Legacy/Two/PostManager.php, app/Managers/Legacy/Two/SignupManager.php, app/Managers/PostManager.php, app/Managers/SignupManager.php
- Explicitly logs `signup_created_source` and `post_created_source` when a signup/post is created from either v2 or v3 endpoints so we can set up StatHat alerts for when we aren't receiving new signups/post from our top referrals (Phoenix, Ashes, Gambit). 
👀 
Continues work done in #727 
=> Logs signup_created_source and post_created_source to set up StatHat Alerts 

app/Http/Controllers/PostsController.php
This PR updates the `PostController` to use the `SignupManager` when creating signups for a post that doesn't have one. 
👀 
This came from [a bug that we found in chompy](https://github.com/DoSomething/chompy/issues/20) where there was a set of signups that were missing from quasar. This was because, in chompy, we just send posts over and then if a signup isn't found we allow rogue to do the work of creating a signup for it. 
The issue was that the logic to create the signup did not go through the `SignupManager` which handles all the business logic of sending the signup record to quasar. 
Fixes 🐛 in :chompy:
=> Use the SignupManager instead of using the SignupRepository directly

app/Http/Requests/PostRequest.php, docs/endpoints/Legacy/Two/posts.md, docs/endpoints/posts.md, tests/Http/PostTest.php
- Adds share-social as a valid post type
- Adds tests to make sure you can create a `voter-reg` and `share-social` post.
- Adds a test to make sure you can't create a post if it isn't one of the following types: `voter-reg`, `share-social`, `photo`, `text`
- Adds `assertPostStructure` helper function in Post tests to DRY up code.
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/158870385) Pivotal Card.
=> adds share-social as a valid post type

app/Repositories/PostRepository.php, tests/Http/PostTest.php
- It was flagged that the `why_participated` was not being saved when a post was submitted. 
- It seems this was overlooked when we built out the `v3` endpoint and we lost all of the `why_participated` data when a signup existed and a post was submitted (if a signup was created at the same time as the post, then we would have this info. However, any new `why_participated` data sent with the post was not saved the the database). 
- This PR fixes that to make sure any `why_participated` sent with a new post submission is saved to the signup. 
- This PR also updates the test to make sure this is happening. 
- All tests should pass. 
- If a `why_participated` is sent with a new post submission, this data should be saved on the signup record. 
- This was flagged first in …
=> Saves why_participated to signup if included with new post 

app/Http/Controllers/PostsController.php, app/Models/Post.php, docs/endpoints/posts.md, resources/assets/components/WithReviewing/index.js
Limits post siblings to only return up to 10 siblings and updates documentation.
👀 
Inboxes were not loading because there were some posts that had many siblings and the page would time out. Now, we only return up to 10 post siblings so this doesn't happen! 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/159406186) Pivotal Card.
=> Limit post siblings to only return up to 10 siblings 

app/Http/Controllers/SignupsController.php, composer.lock, docs/endpoints/signups.md, package-lock.json, tests/Http/SignupTest.php
- Updates `GET /signups/{signup}` to be able to parse by included post types when hitting something like `api/v3/signups/1?include=posts:type(voter-reg)` to only return `voter-reg` type posts.
- Updates tests and documentation.
Hit that endpoint - only posts with the type `voter-reg` should be returned! 
This is needed to Hide Voter Reg Posts in Rogue (work started in #746) and to hide these posts on the signup page in Rogue admin
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/158011726) Pivotal Card.
=> fixes GET /signups/{signup} to parse by included post types

app/Http/Requests/PostRequest.php, app/Repositories/PostRepository.php, docs/endpoints/posts.md
Allows for post to have a custom `created_at when` a post is made in Rogue.
👀 
I'm currently working on a job in Chompy to ingest historical FB share posts. We [would like](https://github.com/DoSomething/chompy/wiki/How-Historic-FB-Share-Records-are-Imported) for the `created_at` dates to match the `keen.created_at` date from the data sent in. In order to do this, we need to update on the Rogue side to have this ability! 
This is needed in order to merge [this PR](https://github.com/DoSomething/chompy/pull/34) in Chompy.
Needed to complete [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156165836) Pivotal Card.
=> Allows for post to have a custom created_at when a post is made

app/Http/Controllers/EventsController.php, app/Http/Controllers/PostsController.php, app/Http/Controllers/SignupsController.php, tests/Http/EventTest.php
- Fixes bug where staff weren't able to delete signups or posts or update posts in Rogue admin.
- Allows staff to delete posts and signups.
- Allows staff to get events (breaking the `Edit | Show History` link bc this hit `GET /v3/events` first). 
- Make sure staff are able to delete signups and posts and can update the quantity in Rogue admin! 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/159005372) Pivotal Card.
=> Fixes bug where staff weren't able to delete signups or posts or update posts in Rogue admin

app/Repositories/PostRepository.php, docs/endpoints/posts.md, tests/Http/PostTest.php
- Auto-accepts `share-social` posts when they are created (unless an admin sets a custom `status` for the post). 
- Updates/adds tests. 
- Updates documentation. 
👀 
Fixes the first task in [this](https://www.pivotaltracker.com/n/projects/2019429/stories/159629479) Pivotal Card.
=> Auto-accept share-social posts when they are created 

app/Models/Post.php, docs/endpoints/posts.md
Adds ability to filter by `created_at` for the v3/posts index.
👀 
Try to use `api/v3/posts?filter[created_at]=2018-08-13 15:10:03` and only posts that were created at `2018-08-13 15:10:03` should be returned. 
We want to update the [Import Facebook Share Posts](https://github.com/DoSomething/chompy/blob/master/app/Jobs/ImportFacebookSharePosts.php)  job  in Chompy to first check if a post exists in Rogue before creating it. 
In order to make sure that the job doesn't create duplicate posts, we will search by `campaign_id`, `northstar_id`, `action`, and `created_at` date. This adds the ability to do so. 
Related to [this](https://www.pivotaltracker.com/n/projects/2019429/stories/160102193) Pivotal Card.
=> Adds ability to filter by `created_at` for the v3/posts index 

app/Console/Commands/ForceDeletePosts.php, app/Repositories/PostRepository.php
- creates script to force delete posts by type and source
- Run this query before running script to see how many posts we start with that have the `type` = `share-social` and created by chompy: 
```
SELECT COUNT(*) FROM posts where type = 'share-social' and source = 'importer-client'; 
```
- Run the script: `php artisan rogue:forceDeletePosts share-social importer-client`
- Run the query again and it should be `0`
- We started importing Historic FB shares from chompy on prod but realized there was a bug and it created dupes! 
- We now plan to get rid of all the dupes and re-start the script. 
- This script takes in the arguments `type` and `source` since this is what we need in this case but can be modified in the future if we need it. 
- I decided to not expand on [this …
=> creates script to force delete posts by type and source

app/Console/Commands/ForceDeletePosts.php
removes confirmation message in force deleting script because we have [a hunch](https://dosomething.slack.com/archives/C0YGXUE01/p1535663505000100?thread_ts=1535661920.000100&cid=C0YGXUE01) this won't fun on heroku
👀 
Fixes #762 
=> removes confirmation message in force deleting script

app/Console/Commands/ForceDeletePosts.php
Adds `chunk` to force delete posts script to save memory when dealing with a lot of records. 
👀 
When running on thor, there were 35,550 records that needed to be force deleted. This cause a memory issue: 
Using `chunk` should help this problem. 
Updates script created in #762 
=> adds chunking to force delete posts script

app/Http/Controllers/Legacy/Web/ImagesController.php, tests/Http/ImagesTest.php
Increases image throttling to allow 30 images per minute.
👀 
Papertrail Rate-Limited Requests alerts were very noisy because of this threshold. @DFurnes had a [great idea](https://dosomething.slack.com/archives/C0YGXUE01/p1539096182000100?thread_ts=1539091395.000100&cid=C0YGXUE01) to increase this throttle to avoid false alarms. 
=> Increases image throttling to allow 30 images per minute

app/Http/Controllers/Legacy/Web/CampaignsController.php, resources/assets/components/CampaignTable/index.js, resources/assets/components/Table/CampaignRow.js
adds pending count back into main campaign overview page that Shae removed in #622 - this was a request from admins and we'd like to try adding this back in and see how it affects performance! 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/160619280) Pivotal Card.
=> adds pending count back into main campaign overview page

package-lock.json, package.json, resources/assets/app.js
This pull request adds the [environment-badge](https://github.com/DoSomething/environment-badge) package I whipped up this morning, which adds a "local", "dev, or "QA" badge to each respective environment to make it easier to tell them apart:
<br/>
Feel free to peek at the [environment-badge](https://github.com/DoSomething/environment-badge) source as well! I also removed some imports that weren't being used in this file, and moved the `babel-polyfill` import up above the app code in `mountContainer` to clear up some linter warnings.
I had originally tried this out on our GraphQL explorer at the end of last year, but never rolled it out elsewhere. I remembered it when I was brainstorming opportunity assessments, and decided to just knock it out!
References DoSomething/infrastructure#47. …
=> Use environment-badge package.

app/Http/Controllers/Legacy/Web/CampaignsController.php
Adds `orderBy` to index page to have most recently created campaign at top of table on `/campaign-ids`. I think this is a better user experience when creating campaigns - going to the index page, you want to see the most recently created campaign at the top of the table instead of having to click through to the last page.
👀 
=> adds orderby to index page

app/Http/Controllers/Legacy/Two/SignupsController.php, app/Http/Controllers/SignupsController.php, app/Managers/Legacy/Two/SignupManager.php, app/Managers/SignupManager.php, app/Repositories/Legacy/Two/SignupRepository.php, app/Repositories/SignupRepository.php, tests/Http/SignupTest.php
This pull request updates Rogue's `POST v2/signups` and `POST v3/signups` to always update the latest run if it exists for a campaign, rather than making a new one where the `campaign_run_id` is null. This will allow us to stop sending Campaign Run IDs (and run the script in #787) without breaking this functionality for applications that rely on it.
I added a failing test in 3e5590a which demonstrates the issue (we create a new signup when we shouldn't), and you can see the issue is fixed in e51a989. This doesn't break any other tests, and I don't believe we rely on the prior unexpected behavior anywhere.
This was flagged by @weerd when testing Phoenix's new sans-runs signup logic.
Fixes [#162426572](https://www.pivotaltracker.com/story/show/162426572). …
=> Always update signup for latest (or empty) run, if it exists.

app/Console/Commands/ImportAshesCampaigns.php, app/Console/Commands/UpdateSignupAndPostCampaignIds.php, tests/Console/UpdateSignupAndPostCampaignIdsCommandTest.php
- Adds script to update signup and post campaign ids after legacy campaign migration
- Grabs all campaigns from the `campaigns` table
- Gets all signups by `campaign_run_id` and updates the signup's `campaign_id`to the campaign's `id`
- Gets all signup's posts and updates the post's `campaign_id` to the campaign's `id`
- Adds a test to make sure this logic is working as we expect 
👀 
Is this the most efficient way to do this?
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/162309728) Pivotal Card.
=> Script to update signup and post campaign ids after legacy campaign migration

app/Http/Controllers/Legacy/Two/SignupsController.php, app/Http/Controllers/SignupsController.php, app/Managers/Legacy/Two/SignupManager.php, app/Managers/SignupManager.php, app/Repositories/Legacy/Two/SignupRepository.php, app/Repositories/SignupRepository.php, tests/Http/SignupTest.php
This pull request reverts the update made in DoSomething/rogue#788 to (try to) assign signups to the latest `campaign_run_id` if that parameter is omitted from the request. In doing so, however, we'd unintentionally started applying signups to the latest run the user had participated in (not the latest for the whole campaign), and so if a user had participated in a prior run of a campaign they'd not be able to sign up for the new run.
=> Revert "Always update signup for latest (or empty) run, if it exists."

composer.json, composer.lock
This pull request moves `fzaninotto/faker` to our production dependencies so we can run the database seeder on our development instance, and updates dependencies:
```
Package operations: 0 installs, 11 updates, 0 removals
- Updating symfony/debug (v3.4.19 => v3.4.20)
- Updating symfony/console (v3.4.19 => v3.4.20)
- Updating symfony/finder (v3.4.19 => v3.4.20)
- Updating symfony/http-foundation (v3.4.19 => v3.4.20)
- Updating symfony/contracts (v1.0.1 => v1.0.2)
- Updating symfony/event-dispatcher (v4.2.0 => v4.2.1)
- Updating symfony/http-kernel (v3.4.19 => v3.4.20)
- Updating symfony/process (v3.4.19 => v3.4.20)
- Updating symfony/routing (v3.4.19 => v3.4.20)
- Updating symfony/var-dumper (v3.4.19 => v3.4.20)
- Updating symfony/translation (v4.2.0 => v4.2.1)
```
👀
References [this Slack …
=> Move Faker to production deps & update dependencies.

app/Models/Signup.php
This pull request removes the ability to query signups based on `campaign_run_id` (forgot in #798). Without this change, Ashes was still able to query based on that field when checking if a signup exists in the `ActivityController` & would always return "false" for new signups.
👀
References [this failing Ghostie test](https://app.ghostinspector.com/tests/56d8a9691a6744a446a04bf4).
References #798.
=> Remove ability to query on campaign_run_id.

resources/assets/components/Table/index.js, resources/assets/components/Table/table.scss, resources/views/campaign-ids/index.blade.php
I noticed some styling issues when looking at Campaign IDs on production:
This pull request collapses Impact URLs into "Read" links & snags table styles from Aurora:
👀
🎨
N/A
=> Fix up some table styling issues.

app/Http/Controllers/Legacy/Two/PostsController.php
This pull request fixes up a few issues from my cleanup in #799.
🐞 Imports `Illuminate\Http\Request` to `PostsController`, fixing these errors we were seeing:
```
[10-Dec-2018 18:48:12 UTC] [2018-12-10 18:48:12] production.ERROR: Class Rogue\Http\Controllers\Legacy\Two\Request does not exist {"exception":"[object] (ReflectionException(code: 0): Class Rogue\\Http\\Controllers\\Legacy\\Two\\Request does not exist at /app/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:25)"} {"user_id":null,"client_id":null,"request_id":"e72291ea-cdd8-4b90-a9b1-a55b3d86ff8a"} 
```
🗄 Removes unnecessary `FiltersRequests` trait from `PostsController`, since this is [already imported in the `Legacy\Two\ApiController` that we're extending …
=> Fix some bugs introduced during cleanup.

resources/assets/components/CampaignOverview/index.js
This pull request fixes a little display issue in the inbox for cause-less campaigns. Before:
And after:
👀
Long-term, we'll probably want to categorize or delete these causeless campaigns… but until that time this makes the admin panel a wee bit less confusing!
N/A
=> Fix missing heading for cause-less campaigns.

resources/views/campaign-ids/create.blade.php
Missed this when renaming `CampaignsController` to `CampaignIdsController` in #799. I've swapped this to use the named route `campaign-ids.store` instead for a little readability boost, as well.
I confirmed that I ran into this bug on my local as well & changing this line fixed it!
👔 
References [this Slack bug report](https://dosomething.slack.com/archives/C0YGXUE01/p1544631056018100).
=> Fix reference to old classname.

resources/views/campaign-ids/show.blade.php
This pull request fixes up a [fatal error](https://dosomething.slack.com/archives/C0YGXUE01/p1544633480025200) when viewing imported campaigns without an `impact_doc` set, and adds a "Campaign ID" field for a lil' better admin UX.
👀
This was dying because we'd send `null` through `url()` and that would return the `UrlGenerator` instance rather than a string – since this is already a fully formed URL, I just removed that helper! I've also added a fallback so we show a `–` here if it's empty.
References this [Slack conversation](https://dosomething.slack.com/archives/C0YGXUE01/p1544633480025200).
=> Fixes fatal issue on the campaign "show" page.

database/migrations/2016_10_11_200952_drop_file_id_from_reactions.php
This pull request fixes [an issue running migrations in MariaDB](https://dosomething.slack.com/archives/C0YGXUE01/p1544116303023600?thread_ts=1544115869.023000&cid=C0YGXUE01). This made it impossible to spin up a new Rogue database without a database dump made in MySQL, and therefore pretty unhelpful to run MariaDB in development.
Specifically, the issue was because we were trying to delete this constraint once the column it depended on was already removed in the line above, and so we'd get this error:
```
SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'file_id' doesn't exist in table (SQL: alter table `reactions` drop `file_id`)
```
Take a peek at the changed migration. For extra credit, follow the updated directions in DoSomething/communal-docs#20 to update your …
=> Fix order of constraint/column deletion in old migration.

app/Console/Commands/ImportAshesCampaigns.php, app/Http/Controllers/Traits/AuthorizesWithToken.php, app/Http/Transformers/Legacy/Two/PostTransformer.php, app/Http/Transformers/PostTransformer.php, app/Models/Campaign.php
- If there is no `$signup` (it has been soft deleted and we don't have cascading deletes yet) when hitting the` /posts?include=signup`, don't call `SignupTransformer`
- Lots of StyleCi cleanup!
- Test endpoint that doesn't work in [this](https://www.pivotaltracker.com/n/projects/2019429/stories/158442898) Pivotal card and it should work! 
We're getting a lot of Papertrail errors for this and we want to prevent false alarms!
```
Jul 05 14:19:32 rogue-prod app/web.1: [05-Jul-2018 21:19:32 UTC] [2018-07-05 21:19:32] production.ERROR: Type error: Argument 1 passed to Rogue\Http\Transformers\Legacy\Two\SignupTransformer::transform() must be an instance of Rogue\Models\Signup, null given, called in /app/vendor/league/fractal/src/Scope.php on line 338 {"exception":"[object] …
```
=> Doesn't pass $signup to SignupTransformer if it has been soft deleted when hitting GET /posts?include=signup

composer.json, composer.lock, public/.user.ini
This pull request configures the New Relic extension in code. This will allow us to disable New Relic on our QA instances and still have the extension built when promoting that Heroku slug into production.
Also, updated Composer dependencies:
```
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
- Updating itsgoingd/clockwork (v3.1 => v3.1.1)
- Updating aws/aws-sdk-php (3.81.0 => 3.81.3)
- Updating spatie/db-dumper (2.11.1 => 2.12.0)
```
Builds should pass!
Also, a reminder to [update your Homestead environment](https://git.io/fpdne) if you haven't already (since Composer will now start checking whether `ext-newrelic` is around when running installs/updates). If you don't have time for a rebuild right now, you can run the agent install …
=> Configure New Relic extension in code & update dependencies.

app/Repositories/PostRepository.php, app/helpers.php
Fixes Bug to Allow Staff to Upload Photos for Users and Post is Attributed to User. 
- Before, only admins were able to do this so when a staff user tried to do this, it would upload a photo but would create a post under the staff's `northstar_id`.
- Use a staff account to upload a photo for a user on the `/signups/:signup_id` page.
- You should see the new post in the "Accepted" section. 
- Refresh the page. 
- The post should still be in the "Accepted" section and in the database, have a `northstar_id` of the user, not of the staff user. 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156852601) Pivotal Card.
=> Fixes Bug to Allow Staff to Upload Photos for Users and Post is Attributed to User

app/Repositories/PostRepository.php
adds check to see if `auth()->user()` after `||` conditional in PostRepository to make sure it exists before checking to avoid errors we saw [here](https://dosomething.slack.com/archives/C0YGXUE01/p1546537309014400)
👀 
Fixes work done in #815 
=> adds check to see if auth()->user() after or conditional in PostRepository

resources/assets/components/UserOverview/index.js
Adds arbitrary limit to when grabbing campaigns to avoid pagination. I updated some things in [this](https://github.com/DoSomething/rogue/pull/814/files) PR to fix the bug to grab campaign names. However, after testing, it seemed like only some campaign names were showing up on the user page. This is because of pagination! The front end would make a call to `/campaigns` and filter by campaign id according to a user's signup. If a user had many signups, only the first 20 campaign names would show up. This adds a limit of `1000` to hopefully do a quick fix for this. 
In the future, I think we should add something like `limit=all` to the API to avoid this and return all records instead of a paginated collection.
Do all the campaign names in the user profile page in …
=> Adds arbitrary limit to when grabbing campaigns to avoid pagination

app/Services/CampaignService.php
- Fixes bug that shows 11 pending posts for Grab the mic run 1 when the inbox is empty.
- This is happening because the query isn't omitting signups that are deleted - there was a deleted signup that had pending posts and the pending count thus returned 11 because it didn't omit these posts.
- This PR updates the `getPostTotals` query to remove any signups that have been deleted.
👀 
On prod, is the Grab the mic run one pending count 0? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/162968074) Pivotal Card.
=> Fixes bug that shows 11 pending posts for Grab the mic run 1 when the inbox is empty

database/migrations/2019_01_07_181343_make_deleted_at_index_signups_table.php
Adds migration to make `deleted_at` an index in `signups` table
👀 
Needed for changes in #818 so the query doesn't timeout.
=> Makes deleted_at an index in signups table

app/Services/CampaignService.php, database/migrations/2019_01_08_215314_creates_compound_index_in_posts_table_with_campaign_id_status_and_deleted_at.php, tests/Unit/Services/CampaignServiceTest.php
After chatting with @DFurnes (see dialogue below), we realized the the query isn't running efficiently for only a few campaigns (including `8017` that have [a ton of posts](https://github.com/DoSomething/rogue/pull/820#issuecomment-452441479)! This query should run more efficiently then the previous query and returns the same information. 
Former approach: 
~~Gets rid of `groupBy` in getPostTotals` query.~~ 
- ~~From #819 and #818 , `campaigns/:campaign_id` pages were timing out in QA.~~ 
- ~~Per @DFurnes 's advice, I used clockwork and `[EXPLAIN`](https://www.sitepoint.com/using-explain-to-write-better-mysql-queries/) to improve this SQL statement so it doesn't timeout.~~ 
- ~~From this, I saw that the query was `Using temporary` and according to the article, this can indicate a …
=> Updates the `getPostTotals` query to run more efficiently

app/Services/CampaignService.php
Updates `getPostTotals` query to only count `photo` and `text` posts so pending count is accurate and bug #818 is properly fixed (was incorrect about why this was happening in #818, discovered in [this comment](https://github.com/DoSomething/rogue/pull/820/files#issuecomment-453563430)). 
👀
On prod, is the Grab the mic run one pending count 0?
Note: if we ever start showing accepted or rejected count in Rogue admin, we will want to rework this query since this will only count accepted/rejected photo and post counts. 
Also, there are 11 `voter-reg` posts that are `pending` - I believe this is a bug since they should all be `accepted`. We should run an update script to accept these (this is probably the real fix for the bug if we don't want to update this query).
Fixes issue in …
=> Makes sure pending count query only counts photo and text posts

app/Console/Commands/ImportPrePostMetaDataActions.php
Removes updating `active` column in ImportPrePostMetaDataActions.php. We decided in groom today we didn't need this data anymore. 
👀 
We'll still keep the `active` column in the `actions` table and remove later if we need to.
Updates changes made in #825
=> Removes updating active column in ImportPrePostMetaDataActions.php

app/Console/Commands/ImportPrePostMetaDataActions.php
When testing on QA, not all the actions from the csv were imported to the `actions` table. This is because the query only matched by `campaign_id` and `name` of the action, but not the `post_type`. We need to also query by the `post_type` because a campaign can have multiple actions with the same name (e.g. "default") but should be considered different if the post types are different. 
E.g. There should be one action for `text` post with the action name `default` for `campaign_id` = `123` and a separate action for a `photo` post with the action name `default` for `campaign_id` = `123`.
👀 
Fixes query in `rogue:prepostmetadataactionsimport` script created in #825 
=> Updates query to see if an action exists

app/Http/Requests/PostRequest.php, app/Http/Transformers/PostTransformer.php, app/Models/Post.php, app/Providers/AppServiceProvider.php, app/Repositories/PostRepository.php, composer.json, composer.lock, database/factories/ModelFactory.php, database/migrations/2019_02_20_162039_add_location_to_posts.php, docs/endpoints/posts.md, resources/assets/components/Post/__snapshots__/test.js.snap, resources/assets/components/Post/index.js, tests/Http/PostTest.php
This pull request adds an optional [ISO-3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) location field to posts (e.g. `US-NY`, [etc.](https://en.wikipedia.org/wiki/ISO_3166-2:US)). We'll be using this when creating posts in Phoenix for the upcoming "prom" campaign, based on [Fastly's geolocation service](https://github.com/DoSomething/infrastructure/pull/156).
Feel free to review commit-by-commit. I've added tests for new functionality.
N/A
[#163728657](https://www.pivotaltracker.com/story/show/163728657)
=> Add ISO-3166-2 location field to posts.

app/Http/Requests/PostRequest.php, app/Repositories/PostRepository.php, database/factories/ModelFactory.php, database/seeds/DatabaseSeeder.php
This pull request fixes some things that caught me off guard when working in Phoenix:
🗺 Instead of throwing a 404 error if an action isn't created, throw a standard 422. (Throwing a 404 is confusing because it indicates that the `v3/posts` API resource doesn't exist, which is not true).
🌱 Add a `default` action to the model seeder so these exist for the dev environment (to match up with what we set in Contentful), and fixes issue where we'd create a fresh action for _every_ single seeded post.
📄 Finally, adds a default "text" action and posts so we can use the Text Submission Action on these seeded campaigns without doing any more manual setup steps.
👀
N/A
References [this Slack conversation](https://dosomething.slack.com/archives/C3ASB4204/p1550695423014100). …
=> Fix some bugs with Action IDs.

app/Http/Controllers/Legacy/Web/ActionsController.php, resources/assets/components/Action/index.js, resources/views/actions/create.blade.php
Updates frontend with anonymous post details:
- Adds ability to create an anonymous action: 
- Updates `Action` component to show if an action is anonymous or not: 
@lkpttn this looks pretty ugly. Should I move the "ANONYMOUS POST" section to be on a separate line and keep the thirds alignment?
Fixes frontend for [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164088666) Pivotal Card.
=> Updates frontend with anonymous post details 

database/migrations/2019_02_20_184538_add_anonymous_column_to_actions_table.php
Updates to the correct able in the latest migration (was referencing `posts` instead of `actions` table).
Thanks for catching this, @DFurnes !
👀 
=> updates to correct table in migration

app/Http/Transformers/PostTransformer.php, app/Models/Post.php, docs/endpoints/posts.md
This pull request adds a `location_name` computed field that we can use to fill in the "anonymous gallery" in the upcoming Prom campaign, where posts will be "attributed" to the user's state:
This turns out to be way more time-consuming than I would've imagined (40-60ms each lookup):
Since that ends up accounting for quite a bit of time on an "index" page with 20+ results, I decided to cache these lookups. Since a state's region code is never (rarely? haha) going to change & takes up very little memory, these are cached forever. Much better:
The best I can tell, that first 80ms lookup is just from initializing the Redis connection. (Either that, or it just has a hard time remembering Minnesota. Dunno what Redis has against the Land of 10,000 Lakes!)
👑
References …
=> Add 'location_name' computed field.

app/Models/Post.php, docs/endpoints/posts.md
- Adds `filter[action_id]` to `GET api/v3/posts`.
Make sure you can filter by `action_id` when hitting the `GET /api/v3/posts` endpoint.
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164121438) Pivotal Card
=> Adds filter[action_id] to GET api/v3/posts 

docs/endpoints/posts.md
Adds optional `northstar_id` param in payload to `POST /api/v3/posts`
👀 
This is missing from the documentation. 
=> adds northstar_id into posts documentation

app/Http/Controllers/PostsController.php, app/Http/Controllers/SignupsController.php, app/Http/Requests/PostRequest.php, app/Managers/SignupManager.php, app/Models/Campaign.php, app/Repositories/PostRepository.php, app/Repositories/SignupRepository.php, app/helpers.php, docs/endpoints/posts.md, docs/endpoints/signups.md, tests/Http/PostTest.php
- Removes `campaign_id` requirement when creating a signup or post when there's an `action_id`.
- Adds test to create a signup and post without `campaign_id` but has `action_id`.
- Fixes tests to use `$action->name` and `$action->post_type` instead of custom string for `action` when creating the post. 
- Deletes `testCreatingAVoterRegPost` because this was a duplicate test.
- Updates documentation. 
cc @rapala61 and @aaronschachter on this too since we were discussing this in [Slack](https://dosomething.slack.com/archives/C0YGXUE01/p1551291369075400?thread_ts=1551285205.065200&cid=C0YGXUE01)! 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164121341)Pivotal Card
=> Removes `campaign_id` requirement when creating a signup or post when there's an `action_id`

app/Http/Transformers/PostTransformer.php, docs/endpoints/posts.md
This pull request adds an `action_details` field to the Post response, with the contents of the `action` that post was created for. (Named `action_details` since sadly `action` is already taken!)
👀
I decided to add this to the base response since we're already eagerly-loading this relationship (and so it won't incur any further database queries), and this way we don't have to make a separate round-trip to fetch the relationship in our GraphQL resolver. (And we'll often want this, since we need to know whether an action is `anonymous` or not & noun/verb for the gallery!)
References [#164214415](https://www.pivotaltracker.com/story/show/164214415).
=> Include full "action" in the Post response.

database/migrations/2019_03_06_165023_add_callpower_campaign_id_to_actions_table.php
Adds `callpower_campaign_id` to `actions` table.
Does the `actions` table have this new column? 
We want to be able to add the CallPower campaign id to an action in Rogue in order to map go-forward CallPower records to a campaign/action.
The user will create a CallPower campaign. Using this CallPower campaign id, a user in Rogue will add this to the associated action when creating in Rogue.
When a post is created from CallPower, we'll use this column to find the action to create the Post.
Fixes (this)[https://www.pivotaltracker.com/n/projects/2019429/stories/164436959] Pivotal Card.
=> Adds callpower_campaign_id to actions table

app/Http/Controllers/Legacy/Web/ActionsController.php, app/Http/Requests/PostRequest.php, app/Models/Action.php, docs/endpoints/posts.md, resources/assets/app.scss, resources/assets/components/Action/index.js, resources/views/actions/create.blade.php
- Adds `phone-call` post `type` and post `type` validation. 
- Adds CallPower campaign id to action creation form (front end and backend): 
- Adds CallPower campaign id to campaign id show page: 
Are you able to create a new action with a CallPower campaign id? Does this save in the db correctly? 
@ngjo @lkpttn can we add this to the campaign creation playbook? LMK if you have any questions! 
Fixes (this)[https://www.pivotaltracker.com/n/projects/2019429/stories/164436959] Pivotal Card.
=> Adds CallPower campaign id to action creation

app/Http/Controllers/Legacy/Web/ActionsController.php
-Updates validation so `callpower_campaign_id` is an integer and has a unique action `id` so a CallPower campaign can only belong to one action.
- You shouldn't be able to add a `callpower_campaign_id` that isn't an integer.
- There should only be one action associated to one CallPower campaign - you should not be able to make two actions for the same CallPower campaign. 
**Question**: Is this the correct logic that we want? I think we'll need to put this rule in place in order to find the `action_id` but is it ok if we only have one action per CallPower campaign? Would we ever want multiple? cc @sohaibhasan @mjain-1 @ngjo 
Fixes validation in #849 
=> Updates callpower_campaign_id validation

resources/views/campaign-ids/create.blade.php
Updates placeholder start and end date formatting for campaign creation - changes `MM-DD-YYYY` to `MM/DD/YYYY` because validation was breaking. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164287377) Pivotal Card.
=> Updates placeholder start and end date formatting for campaign creation

app/Http/Requests/PostRequest.php, app/Policies/PostPolicy.php, app/Repositories/PostRepository.php, tests/Http/PostTest.php
This pull request allows updating a post's location via the `PUT v3/posts/:id` endpoint, which is necessary for backfilling the location of posts submitted for the "Prom For All" broadcast.
I also noticed an authorization bug on this endpoint – any user can use that same endpoint to self-approve their own post! Yikes!! 😱 That's definitely not by design, so I fixed that and added a test to ensure we don't re-introduce that issue again in the future.
Once we remove the old `v1` and `v2` endpoints, it'd be worth doing a close pass over the remaining logic in this application to make sure there aren't other things like this lurking about! 🦈 (For example, we currently allow _waaay_ too many things to be mass-assignable).
Yikes!! We should do a once-over and make sure we don't do this anywhere …
=> Allow updating a posts location, and an authorization logic fix.

app/Http/Requests/PostRequest.php, tests/Http/PostTest.php
This pull request just includes a quick fix to make sure that the `PUT v3/posts/:id` route validates text length consistently with the rules we use for `POST v3/posts`. References #845.
I updated the behavior in 0b18958 & the associated test in fb499c9. 🚥
I also cleaned this test up to use Laravel's `assertJsonValidationErrors` assertion, so we don't end up with a fatal error if the validation error doesn't fire & avoid having to copy-paste validation messages into our tests. I made similar touchups to two other nearby tests in 5c91d18.
I noticed this while in this file earlier this morning for #859.
N/A
=> Update text validation length to be consistent.

app/Models/Post.php, database/migrations/2019_03_08_204743_adds_callpower_campaign_id_unique_index_in_actions_table.php, database/migrations/2019_03_22_203851_add_location_index_to_posts_table.php
This PR adds an index to the `location` column on the `posts` table.
👀 
This update is needed for work related to allowing the post gallery to be filtered by the location.
Refs [PivotalTracker ID #164737236](https://www.pivotaltracker.com/story/show/164737236)
=> Adds an index to the location column on posts table.

app/Http/Controllers/Legacy/Web/ActionsController.php
Force deletes action instead of soft deletes.
Make sure that the action is no longer in the database when deleted. 
@ngjo wanted to create CallPower actions in the database and there was a mistake with one of them. We deleted it but the functionality only soft deletes actions when deleted via the web route. When she tried to create a new action with that soft deleted action's same `callpower_camapign_id, she wasn't able to because of the unique validation rule. 
We only allow users to delete actions if the campaign has not yet started. Because of this, the main functionality of deleted actions is if it really shouldn't be there. Thus, I think it actually makes sense to force delete these actions instead of soft deleting. 
https://github.com/DoSomething/rogue/blob/master/docs/development/de …
=> force deletes action instead of soft deletes

app/Models/Action.php, database/migrations/2019_04_01_212826_remove_deleted_at_column_from_actions_table.php
Removes unused SoftDeletes Trait and deleted_at column in Action model and actions table
:eyes: 
Fixes suggestion in [this comment](https://github.com/DoSomething/rogue/pull/864#discussion_r271057340) 
=> Removes unused SoftDeletes Trait and deleted_at column in Action model and actions table

resources/assets/components/CampaignIdSingle/index.js, resources/assets/components/PagingButtons/index.js
Adds pagination for actions on the campaign id single page if there are more than 20 actions (before only showed first 20 actions so user could not view/edit/delete all actions if there are more than 20 actions for the campaign). 
This is how the pagination buttons look (zoomed in) on the campaign id single page: 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/165027544) Pivotal Card.
=> Paginate actions

resources/assets/components/CampaignIdSingle/index.js, resources/assets/components/Post/__snapshots__/test.js.snap, resources/assets/components/Post/index.js
Whoops! This was a silly mistake in #869 – I accidentally linked to `/campaign-ids/{post.action_id}`, which like, isn't the right place at all! This pull request updates that to link to the campaign, and adds a `#actions` anchor so the user is automatically scrolled down to the relevant part of the page.
👁 
🙈
[#165188977](https://www.pivotaltracker.com/story/show/165188977)
=> Fix action link & add anchor to section.

tests/Http/PostTest.php
This pull request fixes occasional test failures in `testPostsIndexWithAnonymousPosts` and `testPostsIndexAsOwnerHiddenPosts`, both caused when the user IDs generated by Faker would unexpectedly collide. This will make our CI tests for this app more trustworthy.
✅ 👀
If you ever want to "battle test" a particular test, you can use the `--repeat` argument! For example, this runs the `testPostsIndexAsOwnerHiddenPosts` test 100 times to catch those flaky failures:
```
$ phpunit tests/Http/PostTest.php --filter PostsIndexAsOwnerHiddenPosts --repeat 100
.............F...............F...................F.............  63 / 100 ( 63%)
.....................................                           100 / 100 (100%)
Time: 46.03 seconds, Memory: 32.00MB
There were 3 failures:
...
```
N/A …
=> Fix two flaky tests.

app/Http/Controllers/Legacy/Web/CampaignsController.php, app/Models/Campaign.php, resources/assets/components/CampaignOverview/index.js, resources/assets/components/CampaignTable/index.js, resources/assets/components/Table/CampaignRow.js
This pull request updates the Campaign Overview page to group & sort campaigns by status & pending post count, rather than by cause (since in a multi-cause world, that's a confusing thing to do). I've also added a little search box so users can filter for a campaign based on ID, name, or cause.
👀
↕️
[#165160940](https://www.pivotaltracker.com/story/show/165160940)
=> Update campaign overview for our brave new world of multi-cause campaigns.

app/Http/Controllers/Legacy/Web/CampaignsController.php, app/Models/Campaign.php, package-lock.json, resources/assets/components/Table/CampaignRow.js
This pull request swaps `CampaignsController` back to using the ol' campaign service, which has some pretty gnarly but better optimized queries for gathering these pending post counts.
👀
I'd forgotten how much work we had to do to get this query working smoothly in `CampaignService`! 
[#165160940](https://www.pivotaltracker.com/story/show/165160940)
=> Swap back to using optimized queries from CampaignService.

app/Http/Controllers/Legacy/Web/ActionsController.php, app/Http/Controllers/SignupsController.php, app/Models/Action.php, app/PostType.php, resources/assets/app.scss, resources/assets/components/Action/index.js, resources/views/actions/create.blade.php, resources/views/actions/edit.blade.php, resources/views/forms/option.blade.php, resources/views/forms/select.blade.php, resources/views/forms/text.blade.php, routes/web.php, tests/Http/ActionTest.php
This pull request includes some cleanup to the actions controller & form markup, extracted from my upcoming pull request to add additional metadata fields to this resource.
🕵 Shares common validation rules between store & update methods, so we don't need to keep two different versions of this in sync. This also fixes a teeny bug where you could unset required fields from an actions "edit" page. 21acabb
☑️ Simplifies how we handle checkboxes by using the model's `$casts` array to automatically fill in missing boolean values on the form. 242ae49
📃 Adds partials for text, select, and checkbox field markup. This means less work to add new fields, and cleans up some inconsistencies in how we were handling these. 4a90e4c
💅 Fixes some tiny visual issues …
=> Actions controller cleanup!

docs/development/installation.md, resources/assets/components/CampaignOverview/index.js
This PR updates the `CampaignOverview` component to handle the scenario where no campaigns are available per category, rendering a simple message instead of attempting to still filter the (`null`) campaigns value.
https://github.com/DoSomething/rogue/commit/0841bf3ecf4f2be7ee83e35390d5565454dcb6df then tentatively refactors some of the logic into a method. This felt DRYer to me, but if this seems too egregious I can just roll this back! (Also, should such a thing be in a method as opposed to its own functional component?)
And finally, https://github.com/DoSomething/rogue/pull/882/commits/e05bcdb755c15ea8a26800338ccedfcbff2ec6ab adds a step to our installation instructions to cover seeding the DB!
Delete all the campaigns from Rogue or review all pending posts and see what happens 😁 
While …
=> Handle Rendering Campaigns Overview with empty/null Categories

app/Console/Commands/UpdatePostsWithActionIds.php, app/Services/GraphQL.php
This PR Updates the GraphQL service's `query` method to:
- safely catch & log any errors thrown when querying GraphQL via the client.
- parse out the data result fields into a flat Array of said fields (or `null` result).
Also adds a `getCampaignWebsiteByCampaignId` method (As @katiecrane [predicted](https://github.com/DoSomething/rogue/pull/888#discussion_r291398099)) which utilizes this new `query` format to (and you probably didn't see this coming) get a Campaign Website (Contentful campaign) from GraphQL queried by the `campaignId` (`legacyCampaignId` on Contentful) field.
I made some architectural decisions here which I'd love to be validated/torn apart!
- ~`try/catch`ing the client errors - This felt like a good move so that a single query error wouldn't completely break the site, …
=> GraphQL Service Updates (& new CampaignWebsite query)

app/Models/Campaign.php
It seems that accessing the `Campaign->cause` attribute for a Campaign with `null` or empty string `cause` value returns an array with a single empty string value. 
This is because our `getCauseAttribute` accessor method always `explode`s the value, expecting a comma separated string.
This PR adds some logic to just output an empty array for an [`blank`](https://laravel.com/docs/5.5/helpers#method-blank) value.
Does this make sense at all or am I just completely off the mark about this observation / solution? Is the idea perhaps that since valid Campaigns require a Cause, an 'empty' cause is indeed what we desire?
I bumped into this while testing out adding the `cause` attribute to `Post`/`Signup` blink payloads. While testing for cases where the attribute was unset or null or an empty …
=> Update Campaign->cause attribute accessor method

resources/assets/components/Signup/index.js
Allows a dev or admin to view a signup's `source_details` without querying the database.
:eyes:
We're looking to save a new `referrer_user_id` property into `source_details` for the [Refer A Friend build.](https://docs.google.com/document/d/1hzw8eBNLTwFFG2KQFdEHdljJbDpgW1awjG3wYjy_A_Q/edit?usp=sharing) As I'm exploring building this out, it'd be swell to see this within the Rogue UI instead of querying the DB.
=> Display Signup source_details

app/Console/Commands/DeleteUsersCommand.php
This pull request updates the `northstar:delete` command to write data to the application's logs so that we can refer back to it in Papertrail after running this command.
This is basically a carbon-copy of DoSomething/northstar#905! 👀 
I keep getting mixed up on how this works! When running a command in "detached" mode, all standard output [is written to the logs](https://devcenter.heroku.com/articles/one-off-dynos#running-tasks-in-background), but "normal" one-off dynos [only log startup & shutdown](https://devcenter.heroku.com/articles/one-off-dynos#formation-dynos-vs-one-off-dynos).
Since we're piping standard input into this command, we can't run in detached mode & so we'll need to make sure we're explicitly writing these to the log. 🎋 …
=> Write `rogue:delete` command output to logs.

app/Http/Controllers/Legacy/Web/CampaignsController.php, app/Http/Transformers/CampaignTransformer.php
Fixes missing Proof Of Impact link from a `/campaigns-id/:id` page by returning it from the API response. Is this URL ok to make public?
Example response of a **GET** `/api/v3/campaigns/9003` request:
```
{
"data": {
"id": 9003,
"internal_title": "Assimilated Zerodefect Projection",
"start_date": "2019-04-25T03:12:15+00:00",
"end_date": "2020-01-24T21:10:45+00:00",
"is_open": true,
"impact_doc": "https://www.google.com/",
...
}
}
```
👀 
https://www.pivotaltracker.com/n/projects/2019429/stories/166356076
=> Add campaigns.impact_doc to API response

app/Console/Commands/DeleteUsersCommand.php, tests/Console/DeleteUsersCommandTest.php
Based on a conversation with @mjain-1, we've decided to keep the `location` field on these deleted records, since it's no longer able to be tied to a particular individual and could be useful for overall demographic data.
👀
References [this Slack thread](https://dosomething.slack.com/archives/C8P2VSF32/p1564759454002100).
[#167624495](https://www.pivotaltracker.com/story/show/167624495)
=> Quick tweak before running the "rogue:delete" script.

package-lock.json, package.json, resources/assets/components/Signup/index.js, resources/assets/components/Users/UserInformation.js, resources/assets/components/WithReviewing/index.js, resources/assets/helpers.js
This pull request updates Rogue's admin interface to remove sensitive fields (like birthdate or mobile number) in favor of the new "preview" fields. It also updates dependencies & fixes a strange bug due to not returning a Promise and trying to `then` it later (dunno why it worked in the first place, or why we have the same method in two different files).
I'd recommend peeking commit-by-commit.
I moved two helper functions into the `UserInformation` component since they're only used in that one place (and so extracting them into `helpers.js` made for unnecessary jumping around & contributed to the helper file just becoming a catch-all).
[#167596656](https://www.pivotaltracker.com/story/show/167596656)
=> Update Rogue admin interface to use preview fields.

app/Jobs/RejectPost.php, app/Providers/ModelServiceProvider.php
To effectively prevent runscope tests from appearing in a campaign lead's inbox, this PR adds a RejectPost function to delay the appearance of a 'test' post for 15 minutes after it's created and then marks the status of the post as 'rejected'.
In rogue.test, click on upload a photo. 
Add a photo and for the caption add 'test runscope upload' and click submit. 
In terminal and inside of rogue in vagrant  `cd` into the /storage/logs folder and `tail -f` the most current log file. 
In a separate tab in terminal run `php artisan queue:listen`. This will watch the files for any changes made 
You should see an update to the log file 15 minutes after creating the post
what else?
We want to delay the test posts so that the test experience would mimic the normal user experience 
Fixes …
=> Adds Reject Post Function to Hide Display of Runscope Posts

resources/views/users/partials/_table_users.blade.php
This pull request updates the list of users to display the `email_preview` and `mobile_preview` fields, since `email` and `mobile` aren't included by default (and aren't something we want to show unless necessary).
:eyes:
🔒
[#167596656](https://www.pivotaltracker.com/story/show/167596656)
=> Update users table for new preview fields.

app/Http/Controllers/Legacy/Web/UsersController.php, package-lock.json, package.json, resources/assets/app.js, resources/assets/components/Application.js, resources/assets/components/Post/index.js, resources/assets/components/PostTile/index.js, resources/assets/components/PostTile/post-tile.scss, resources/assets/components/Signup/index.js, resources/assets/components/SignupCard/index.js, resources/assets/components/SignupCard/signup-card.scss, resources/assets/components/UserOverview/index.js, resources/assets/components/Users/UserInformation.js, resources/assets/graphql.js, resources/assets/helpers.js, resources/views/layouts/master.blade.php, resources/views/users/show.blade.php
This pull request adds a link to a user's Aurora profile on the "user overview" page, which is useful if you [need to lookup their email or mobile](https://dosomething.slack.com/archives/C09ANFQLA/p1570026635041100?thread_ts=1570026476.040100&cid=C09ANFQLA). However.... rather than add logic to Rogue to know about different Aurora URLs, I decided to build off the work I did yesterday in DoSomething/graphql#136 by reworking this to use GraphQL! 🙈
This pull request adds a "modern" application shell in c9fb6df which uses [Reach Router](https://reach.tech/router) & [Apollo Client](https://www.apollographql.com/docs/react/) to fetch data for this interface. It also sets us up for using client-side routing (rather than having to hard-code a container for each page). (c9fb6df)
I then refactored …
=> Link to Aurora on user overview page.

app/Http/Controllers/Web/ImagesController.php, app/Models/Post.php, app/Providers/AppServiceProvider.php, composer.json, composer.lock, routes/api.php, tests/Http/ImagesTest.php
This pull request updates our `images/{post}` endpoint to use a deterministic (but hard to guess) hash based on the post's ID, using [`hashids`](https://hashids.org/php/). This prevents a curious user from looking at unapproved post's images (while still letting us cache those in Fastly).
👀
We can't simply apply authorization logic to the `images/{post}` endpoint (like we do for originals in #918) because we want to cache these generated Glide responses in Fastly (and so most requests won't ever hit our servers). That means we want the image to be public but not easily enumerable.
Users are only able to view `posts/{id}` once a post has been approved (or if it's theirs), and so they would not be able to guess the URL for `images/{hash}` until then. This allows admins and users themselves …
=> Use short hashes for image URLs.

composer.json
The [BCMath](https://www.php.net/manual/en/book.bc.php) extension, which includes fancy math tools, isn't [included by default on Heroku](https://devcenter.heroku.com/articles/php-support#extensions) and so we need to add that dependency to our `composer.json`. This didn't show up on Homestead or Wercker since both of those have that extension included.
👀
From [our Heroku logs](https://my.papertrailapp.com/systems/dosomething-rogue-dev/events?focus=1121548484760842243&selected=1121548484760842243) for `dosomething-rogue-dev`:
```
Oct 17 14:00:18 dosomething-rogue-dev app/web.1 [17-Oct-2019 18:00:18 UTC] [2019-10-17 18:00:18] development.ERROR: Missing BC Math or GMP extension. {"exception":"[object] (RuntimeException(code: 0): Missing BC Math or GMP extension. at …
```
=> Install 'bcmath' extension to support #920.

app/Http/Controllers/CampaignsController.php, app/Models/Campaign.php, database/factories/ModelFactory.php, docs/endpoints/campaigns.md, tests/Http/CampaignTest.php
This pull request allows us to filter the `v3/campaigns` API via the computed `is_open` field, using new `whereOpen` and `whereClosed` query scopes. This will allow us to group open vs. closed campaigns on the "campaign overview" page without loading all 700+ campaigns in-memory.
Here's how this would look via the REST API:
```
https://activity.dosomething.org/api/v3/campaigns?filter[is_open]=true
```
🚥 👀
📂
[#169233808](https://www.pivotaltracker.com/story/show/169233808)
=> Add `filter[is_open]` to Campaigns API.

app/Events/PostTagged.php, app/Listeners/SendTaggedNotification.php, app/Models/Post.php, app/Notifications/SlackTagNotification.php
This pull request fixes two issues with the notifications in `#notify-badass-members`: images were no longer showing up after DoSomething/infrastructure#213 removed public access to this app's S3 bucket & captions had not been showing up since we renamed `caption` to `text` [last year](https://github.com/DoSomething/rogue/pull/636). Yikes!
I also took this opportunity to fill in missing information about the user & campaign, since we've claimed we'd be "adding member info. in Slack soon" and it's been, well, a while:
I'd recommend reviewing commit-by-commit to get the context of each change.
📸
[#169324963](https://www.pivotaltracker.com/story/show/169324963)
=> Fix Slack notification bugs & add some missing information.

app/Console/Commands/ImportSignupsCommand.php, tests/Console/ImportSignupsCommandTest.php, tests/Console/example-signups.csv
- Change column header from `campaign_node_id` to `campaign_id` because `campaign_node_id` is a thing of the distant past now!
- Don't hardcode the source as `phoenix-next`, but instead allow the signup's `source` to be set by the `source` column of the csv
- Update the test cases so that now one of them uses source `phoenix-next` and one of them uses source `sms` so we can be sure the sources are updating properly
- Wipe out some old data/columns that are not used anymore from the csv file used for the unit tests
Do the unit tests updates test the right things? Will this allow us to import signups and set user, campaign, source, and created_at?
[Card](https://www.pivotaltracker.com/story/show/169095237)
=> Signup import command updates

app/Http/Controllers/CampaignsController.php, app/Http/Controllers/Traits/FiltersRequests.php, app/Http/Controllers/Traits/TransformsRequests.php, app/Http/Transformers/CampaignTransformer.php
This pull request adds some API support for DoSomething/graphql#142:
👇 Adds a `cursor` field to the campaign transformer, which is just the Base-64 encoded ID of the campaign. This is suggested in GraphQL's documentation, and makes sense to me:
> Using cursors for pagination gives additional flexibility if the pagination model changes in the future. As a reminder that the cursors are opaque and that their format should not be relied upon, we suggest base64 encoding them.
↪️ Adds an experimental `?after=` query parameter to `/api/v3/campaigns`, which accepts the cursor that we generate in the transformer. This allows us to say "get me all the items after this one" and sidestep some bugs we could encounter with traditional `?page=#` pagination.
tell us, how can we review, to test that this …
=> Add `cursor` and experimental `?after=` query param to Campaigns API.

.styleci.yml, app/Http/Controllers/CampaignsController.php, app/Http/Controllers/Traits/FiltersRequests.php, app/Http/Transformers/CampaignTransformer.php, app/Models/Campaign.php, tests/Http/CampaignTest.php
This pull request fixes an issue with cursor pagination (introduced in #930). That implementation didn't take into account results that have `orderBy` (and so the ID alone wouldn't get us the proper position in the sorted results).
I did some refactoring in 9313d2f, 01059be, and 9af53c4. I added a passing test for `?after=` with a standard non-sorted response in 582b69e and a failing test in 04231d5. Finally, I fixed the issue with using `after` & `orderBy` together in c8749e7.
Finally, I renamed `after` to `cursor[after]` for clarity in 5792139.
This [Shopify Engineering blog post](https://engineering.shopify.com/blogs/engineering/pagination-relative-cursors) includes a good explanation & visualization of this issue under the "Sorting and Skipping Records" heading. (Cursor pagination is …
=> Fixes an issue with cursor pagination & sorted results.

app/Http/Controllers/TagsController.php
This pull request adds support for sending the machine-name for a tag (e.g. `good-photo` instead of `Good Photo`) to the `api/v3/post/{id}/tags` endpoint.
👀
I think it's worth spending a little time to clean up this endpoint in the future:
- It should deal in machine-friendly identifiers (in this case, the "slugs"), rather than human-friendly formatted labels (that could change in the future).
- It probably doesn't make sense to store the human-friendly names for every single tag (since it takes up unnecessary space & makes it harder to change the tag's human-friendly name later).
- It should validate input! We should have a list of allowed tags (like we do for causes, etc).
[#169512736](https://www.pivotaltracker.com/story/show/169512736) …
=> Support using machine-name to tag/untag a post.

app/Http/Controllers/RotationController.php, app/Http/Controllers/Web/ImagesController.php, app/Services/ImageStorage.php, routes/api.php
This pull request updates our image rotation endpoint to live under the API namespace and require the `staff` or `admin` role (previously anyone could rotate posts). 🔒 I've tested this with the local filesystem driver & S3 driver and both seem to work swimmingly now.
👀
I have not updated Rogue's admin interface to use this new `/api/v3/posts/{id}/rotate` endpoint, since I'm going to be swapping these out to use the new GraphQL powered component very soon.
[#169346181](https://www.pivotaltracker.com/story/show/169346181)
=> Fix issues with rotation API.

app/Http/Controllers/Web/ImagesController.php
This pull request fixes an issue where Glide images would be cached in user's browsers indefinitely and so edits wouldn't appear without clearing cache or force-reloading the page.
This was happening because Glide uses `Cache-Control: max-age=31536000, public` by default, which tells Fastly _and_ everything else, like the user's browser, to cache that resource for up to a year. Instead, we should use `s-max-age` to tell Fastly to cache the resource without also telling browsers to do the same.
👀
Here's [some documentation](https://docs.fastly.com/en/guides/cache-control-tutorial) from Fastly explaining how each of these headers can be used. We could have used `Surrogate-Control` instead of `s-max-age`, but then we'd have to also wipe the existing `Cache-Control` header.
Fixes # …
=> Fix issue where rotated images would still load from cache.

app/Http/Controllers/TagsController.php, resources/assets/app.scss, resources/assets/components/Application.js, resources/assets/components/ReviewablePost.js, resources/assets/components/ShowPost.js, resources/assets/components/utilities/Chrome.js, resources/assets/components/utilities/DeleteButton.js, resources/assets/components/utilities/PostCard.js, resources/assets/components/utilities/ReviewButton.js, resources/assets/components/utilities/TagButton.js, routes/web.php
This pull request adds a `post/{id}` view that shows an individual post. This interface fetches (and mutates!) data via GraphQL, allowing us to sidestep some of the complexity that's built up around doing this with REST & a custom in-memory store.
This relies on the mutations and field added in DoSomething/graphql#153. I've split this into individual commits for each feature, which may be helpful while reviewing.
This adds a feature I've wanted for a long time (since otherwise the best we can do is link to a signup and say "look at the Nth one") and also makes it super-simple to build the campaign inbox!
[#169512736](https://www.pivotaltracker.com/story/show/169512736)
=> Add "individual post" permalink (powered by GraphQL).

app/Http/Controllers/Web/ImagesController.php, package-lock.json, package.json, resources/assets/app.scss, resources/assets/components/Quantity/index.js, resources/assets/components/ReviewablePost.js, resources/assets/components/utilities/LazyImage.js, resources/assets/components/utilities/Modal.js, resources/assets/components/utilities/PostCard.js, resources/assets/components/utilities/QuantityForm.js
This pull request adds the "edit quantity" modal to the GraphQL-powered post interface, which can currently be found at `/posts/:id`. This uses [react-useportal](https://github.com/alex-cory/react-useportal) to handle rendering the modal, and the new `updatePostQuantity` GraphQL mutation to update this field on the backend. (f4c8d2a)
It also includes two tiny fixes to the "rotate" functionality:
💤 Adds a (hook-powered) `LazyImage` component which lets us lazy-load images! f968ad7
💣 Removes the `Expires` header from Glide images so browsers don't cache them! I missed this in #934 but hopefully this should sort everything out for us! 5b77545
👀
This gets us pretty much to feature-parity with the old implementation, nice!
[#169512736](https://www.pivotaltracker.com/story/show/169512736), …
=> Add "edit quantity" modal to GraphQL-backed post interface.

app/Http/Controllers/PostsController.php, app/Http/Transformers/PostTransformer.php, app/Models/Campaign.php, app/Models/Post.php, app/Models/Traits/HasCursor.php
This pull request extracts the experimental cursor methods from #930 into a `HasCursor` trait so that we can try it out for posts as well. I also ran into a bug with the "sorted" cursor logic and fixed it up in b262123 (see below).
I'd recommend reviewing this one commit-by-commit (mainly because extracting the trait adds a lot of noise that's not "really" there).
The bug in c6ff2ba occurs when the "sorted" column (e.g. `created_at` or `pending_posts`) has items with the same value. In that case, we want either items after the primary sort column (so `created_at < cursor.created_at` for example) or, if the primary sort has duplicates, after the secondary sort (so `created_at == cursor.created_at && id > cursor.id`).
Previously, I'd been checking for `created_at <= cursor.created_at && id …
=> Add 'cursor[after]' support to 'api/v3/posts'.

app/Http/Controllers/Web/ImagesController.php
This header was getting defaulted to `Cache-Control: no-cache, private`, which [disables Fastly caching even when `Surrogate-Control` is provided](https://docs.fastly.com/en/guides/cache-control-tutorial#do-not-cache):
> Except for when the `Cache-Control` header is set to `private`, the `Surrogate-Control` header takes priority over `Cache-Control`, but unlike `Cache-Control` it is stripped so the browsers don't see it.
Hopefully this looks better on QA!
This fixes a new issue introduced in #939 where all responses became cache misses.
Will create one momentarily!
=> Don't default Cache-Control to 'private'.

app/Http/Controllers/Web/ImagesController.php
This pull request… hopefully… fixes the caching issues I've been wrestling with today.
I think the easiest thing will just be testing this on QA! 🙃
Frustratingly, Symfony (which Laravel's HTTP stack is built on) [forces certain `Cache-Control` headers](https://github.com/symfony/http-foundation/blob/d8f1bf9f099852ddd0c009589634ecadb7e4a9d8/ResponseHeaderBag.php#L255-L285), so we can't follow [Fastly's instructions](https://docs.fastly.com/en/guides/cache-control-tutorial#applying-different-cache-rules-for-fastly-and-browsers) without it being overridden with a `private` at the end (which disables Fastly caching).
I'm still not certain why #940 didn't solve our issues, but I've tested these headers in a [Fastly Fiddle](https://fiddle.fastlydemo.net/fiddle/bd6771fc) and confirmed that given …
=> Fix Fastly caching issues.

app/Console/Commands/RecountPostsCommand.php, app/Console/Commands/RefreshCampaignCounts.php, app/Http/Controllers/CampaignsController.php, app/Http/Transformers/CampaignTransformer.php, app/Models/Campaign.php, app/Models/Post.php, app/Models/Traits/HasCursor.php, app/Providers/ModelServiceProvider.php, database/migrations/2019_11_14_203229_add_pending_count_to_campaigns.php, resources/views/layouts/master.blade.php, tests/Http/CampaignTest.php
~This pull request (hopefully) fixes an issue introduced in #946. That pull request fixed the problem where campaigns with zero pending posts wouldn't be shown in the results, but introduced a new issue (only on QA! 🤔) where the list would "loop" around to the beginning like this:~
This pull request instead fixes the issue introduced in #946 by side-stepping it entirely!
This was all caused because `pending_count` would be null if there weren't yet any posts for a campaign (because we're applying this by doing a big old `SELECT COUNT(*)` on the posts table and left-joining it to campaigns). I tried a couple different ways to get `NULL` column cursors to work ([harder than you think!](https://github.com/DoSomething/rogue/pull/946)), and just couldn't get it to work. So instead I took a …
=> Use "counter caches" for pending count instead of heavy query.

app/Console/Commands/RecountPostsCommand.php, app/Http/Controllers/CampaignsController.php, app/Models/Traits/HasCursor.php, resources/assets/components/CampaignsTable.js, resources/assets/components/ReviewButton.js
This pull request fixes some issues with the new counter caches added in #947:
🔃 Fixes an issue where paginated lists would continually loop back to the beginning. This turned out to be a frustratingly simple bug – we were checking if the cursor was "truthy" (rather than just whether it existed), and so a cursor value of `0` was the same as saying "no cursor". 68c682e
🐎 The "recount" query for each campaign takes about a second to run, which is not too bad when re-calculating this for a single campaign when someone reviews a post… but [quite slow](https://my.papertrailapp.com/events?focus=1131997651941478401&q=program%3Aapp%2Fscheduler.7334&selected=1131997534979104772) when trying to do it for over 700 campaigns on a schedule!
🍃 It also removes the heavy query to include a on-demand …
=> Fix some issues with counter cache.

resources/assets/app.scss, resources/assets/components/CampaignsTable.js, resources/assets/components/utilities/OrderableHeading.js, resources/assets/components/utilities/SortableHeading.js
This pull request adds the ability to choose the order that campaigns are sorted on the index (either by ID, pending count, or accepted count). This makes it easy to find, say, the newest campaigns (by sorting `id,desc`) or most popular campaigns (by sorting `accepted_count,desc`).
👀
This was quick to add & should help address some of the issues campaign leads have raised with finding campaigns that aren't near the top of the list.
N/A
=> Allow users to choose how to sort campaigns.

routes/web.php
I hadn't set the `signups.show` named route on the new client-side route, and so [this line](https://github.com/DoSomething/rogue/blob/9cb78fcdb83b39a91633c486e7749ac6b2223664/app/Notifications/SlackTagNotification.php#L96) was erroring out (and erroring out the tag request, even though the database write was completed).
```
Route [signups.show] not defined. at /app/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:305)
```
👀
👻
Fixes [pre-deploy bug report](https://dosomething.slack.com/archives/C0YGXUE01/p1573840773110000?thread_ts=1573837842.107300&cid=C0YGXUE01) from @ngjo.
=> Fix issue with Slack notification & permalink.

app/Http/Requests/PostRequest.php, app/Http/Transformers/PostTransformer.php, app/Models/Post.php, app/Repositories/PostRepository.php, database/migrations/2019_11_18_101100_add_school_id_to_posts.php, docs/endpoints/posts.md, tests/Http/PostTest.php
Adds a new `school_id` column, to the Posts table as well as API support to write, update, and view.
Create a post with `school_id` to verify it works. What was really tripping me up is that I can't get `PATCH /v3/posts` to work within Postman at all, but the tests are passing.
I've been thinking about adding a field to the Actions table to indicate whether the post should collect `school_id`. It seems like the better place to save this information vs anywhere in Phoenix. This gets me thinking that perhaps the Post create/update requests would lookup the Action and only save the `school_id` value if `should_collect_school_id` is set to true ... and that way Phoenix or any other client could send `school_id` without needing to make the lookup to see if the action accepts a `school_id`. …
=> Add school_id to posts

resources/assets/Application.js, resources/assets/components/ReviewablePost.js, resources/assets/pages/ShowSchool.js, routes/web.php
This PR adds a  `schools/:id` view that shows an individual school, and links to it from a post view if the post has a school ID set (refs #951). 
* Edit existing post with a valid `school_id` e.g. `'600022'`
* Verify expected result for school permalink (e.g. rogue.test/schools/600022)
Eventually this page can allow us to view the school's aggregate quantity per action, which we need to display in v2 School Finder (refs https://www.pivotaltracker.com/n/projects/2401401/stories/169659230)
https://www.pivotaltracker.com/story/show/169549658
https://www.pivotaltracker.com/n/projects/2401401/stories/169659230
=> Add school permalink

resources/assets/Application.js, resources/assets/app.scss, resources/assets/components/CampaignsTable.js, resources/assets/components/utilities/SortableHeading.js, resources/assets/pages/CampaignIndex.js
This pull request includes a few quality-of-life improvements to the campaign index:
📑 Automatically loads all results when filtering, rather than stopping at the first page. This probably means we'll "over-query" more often, but fixes an awkward UX issue where it might seem like there are no results until you click "view more" a few times. 7c9db12
➖ Adds an "underline" to the table headings to better indicate that they're clickable. 08f1d67
📂 Moves the "open/closed" toggle to the top of the screen so it's not so easy to miss. 976b28c
💡 Adds a "new" callout for column sorting. Fixes [#169852017](https://www.pivotaltracker.com/story/show/169852017). 65ca1a3
✏️ Fixes a typo'd Tailwind-style classname. 445d5b6
👀
Hopefully this makes this a bit more user-friendly for folks. …
=> A few quality-of-life improvements for the campaign index.

resources/assets/components/CampaignsTable.js, resources/assets/pages/CampaignIndex.js
This fixes an issue I'd introduced in #955 where the `useEffect` hook would fire _while_ we were still loading campaigns, so we'd load results after the same cursor twice. (bba0c84)
After more testing, I also realized that I didn't need separate `CampaignsTable` components for the "open" and "closed" list after all, since Apollo will maintain both these separately paginated queries for us. (02fc96f)
👀
🙈
N/A
=> Fix automatic pagination of campaigns.

app/Http/Controllers/Web/CampaignIdsController.php, app/Http/Controllers/Web/ImagesController.php, app/Models/Post.php, routes/web.php
This pull request fixes some exceptions that were cluttering up our logs:
↪️ Adds a redirect from the removed `campaign-ids/` to `campaigns/`. ~e54aba2~ Tricky! The built-in `Route::redirect` captures on _any_ HTTP method, so this was messing up campaign creation. I swapped to a normal `redirect()` in the controller instead in 92cb651.
💥 Throw a "not found" exception instead of returning `null` when an invalid hash is provided. This fixes up the `Call to a member function getMediaPath() on null` errors we've been seeing. b975444
✏️ Renames `fromHash` to `findByHashOrFail` to make functionality clearer. a3dbc3e
👻 Check if a post is a photo before trying to render. If not, 404! 02dad2e
👀
This should reduce some noise from these alerts! …
=> Fix some exceptions.

app/Models/Post.php, app/Services/GraphQL.php, database/factories/ModelFactory.php, tests/Unit/Models/PostModelTest.php, tests/WithMocks.php
This PR modifies the Post `toBlinkPayload` to query GraphQL for a school's name if the post `school_id` is set, to add field into Customer.io as `school_name`.
A new (minimal) automated test! 👀 
Coming soon: we need to abstract this GraphQL client into our PHP Gateway to get the school name over to a Customer.io user profile in Northstar.
https://www.pivotaltracker.com/story/show/169745644
=> Adds school name to Blink payload for campaign posts

app/Http/Controllers/Web/ActionsController.php, resources/assets/Application.js, resources/assets/components/Action/index.js, resources/assets/pages/NotFound.js, resources/assets/pages/ShowAction.js, resources/assets/pages/ShowPost.js, resources/views/actions/edit.blade.php, routes/web.php
Adds a web `/actions/:id` route and a `ShowAction` page component to render a permalink view of an action. I kept navigating to this path to spot check which action I was selecting while creating different submission content types over in Phoenix for testing `school_id` collection.
👀 
It'd be useful to add an `Action.campaign` nested property over in GraphQL to display the campaign's internal title as well as ID
https://www.pivotaltracker.com/story/show/169549621/comments/209139906
=> Add action permalink

app/Http/Controllers/Web/ActionsController.php, app/Http/Controllers/Web/CampaignsController.php, routes/web.php
This pull request includes some cleanup & adds redirects for the old `/campaign-ids` and `/campaign-ids/:id` routes that were refactored in #960. (They're still linked from Contentful & folks may have bookmarks saved on their machines).
I did some cleanup in 0d2d5d0 (moving exclusively client-side routes so they're solely in `routes/web.php` and grouping the few remaining server-side routes). I also updated this file to use Laravel's standard `Route` facade to match the framework documentation.
Then the bug fix is in c0f333b! 🐞
I wanted to use Laravel's [`Route::redirect`](https://laravel.com/docs/5.5/routing#redirect-routes) here, but it doesn't support route arguments (for the `/campaign-ids/:id` to `/campaigns/:id` redirect). Bummer!
References [Pivotal …
=> Add redirects for old `/campaign-ids` routes.

app/Providers/RouteServiceProvider.php, database/factories/ModelFactory.php, database/faker/FakerSchoolId.php, resources/assets/components/ReviewablePost.js, resources/assets/components/utilities/UserInformation.js, resources/assets/pages/ShowCampaign.js, resources/assets/pages/ShowSchool.js, routes/web.php, tests/WithMocks.php
This pull request fixes some few bugs and adds a few enhancements:
* Adds missing `/actions/:id` route - removed in #965 
* Removes deprecated `Route::model` for `campaign_id`, fixes Post links to campaigns - removed in #960 
* Adds link to the Action permalink to a Post view 
* Removes `school` field from our Post gallery GraphQL and checks for `post.schoolId` instead
* Display `NotFound` component for Campaign, School pages when invalid ID
* Adds a `FakerSchoolId` to use valid school ID's from GraphQL when creating fake posts
* Adds a `userId` prop to the `UserInformation` to use if the `user` prop is empty. The posts we generate are using fake user ID's from our dev Northstar database, but we may not have those ID's locally when working in GraphQL.
👀 
The `/signup/:id` permalink also …
=> Rogue Admin cleanup

app/Http/Controllers/ActionStatsController.php, app/Http/Transformers/ActionStatTransformer.php, app/Models/ActionStat.php, database/migrations/2019_12_05_131200_add_compound_index_to_action_stats_with_accepted_quantity.php, docs/endpoints/README.md, docs/endpoints/action-stats.md
This pull request adds documentation for the newly added `GET /action-stats` endpoint in #964, and makes a few tweaks:
* Returns the `id` auto-incrementing primary key. We need this for GraphQL to do its thing.
* Adds support to order by `id` and `accepted_quantity`
* Adds an index for `action_id` and descending `accepted_quantity`, which we'll want to display Action leaderboards 
👀 
Will open a GraphQL PR shortly that makes use of these changes.
References [Pivotal #169659230](https://www.pivotaltracker.com/story/show/169659230).
=> Action Stats cleanup

resources/assets/app.scss, resources/assets/pages/ShowAction.js, resources/assets/pages/ShowCampaign.js, resources/assets/pages/ShowPost.js, resources/assets/pages/ShowSchool.js
This pull request uses the `schoolActionStats` GraphQL queries introduced over in https://github.com/DoSomething/graphql/pull/182 to display a School Leaderboard for Actions, and an Aggregate Impact section for Schools.
It also gets started on changing the HTML document title for the different page views, to help remember why you have 13 tabs that say "Rogue" open.
👀 
Action permalink:
School permalink:
Eventually want to add fake `ActionStat` data into our `db:seed` Artisan command, which will make it a lot easier to 👀 locally. (I've been manually reviewing reportbacks locally to populate the `action-stats` table)
References [Pivotal #169659230](https://www.pivotaltracker.com/story/show/169659230).
=> Display action stats on School, Action permalinks

app/Providers/ModelServiceProvider.php, app/Repositories/PostRepository.php, tests/Http/ReviewsTest.php
This pull request makes changes per https://github.com/DoSomething/rogue/pull/964#discussion_r354011950 to update aggregate campaign information in the same place we update aggregate school impact -- which is after the reviewed post's status has been updated.
It also adds unit tests for both aggregate calculations.
👀 
🌵 
References [Pivotal #170111820](https://www.pivotaltracker.com/n/projects/2328687/stories/170111820).
=> Fix order of operations for updating Campaign post counts

app/Console/Commands/ReviewSignup.php
This pull request updates the `rogue:reviewsignup` command to support bulk-reviewing posts for a signup that has been soft-deleted. Otherwise, the script fails with this error:
```
In Builder.php line 331:
No query results for model [Rogue\Models\Signup] 11303803
```
👀
This is a quick fix to fix an issue caused by [an overwhelming number of Cobalt submissions to a sponsored campaign](https://dosomething.slack.com/archives/C09ANFQLA/p1576519120019900). Unfortunately, the signup was soft-deleted as an attempt to "bulk review" these posts, which meant the script as-is wouldn't work.
References [Pivotal #170320843](https://www.pivotaltracker.com/story/show/170320843).
=> Allow bulk-reviewing trashed signups.

app/Http/Controllers/SignupsController.php, app/Http/Transformers/SignupTransformer.php, app/Models/Signup.php
This pull request adds support for using `?cursor[after]=` to paginate through signups.
This is a pre-requisite for DoSomething/graphql#185, which in turn is a pre-requisite for adding pagination to a user's list of signups here. 🐢
This follows the same pattern established in #930 and #937.
The [GraphQL Pagination RFC](https://github.com/DoSomething/rfcs/pull/6) has more context on why we're approaching pagination in this way.
References [Pivotal #170503307](https://www.pivotaltracker.com/story/show/170503307).
=> Add cursor support to signups index.

resources/assets/components/SignupCard/index.js, resources/assets/components/SignupGallery.js, resources/assets/pages/ShowUser.js
This pull request adds a "load more" button to request additional signups on a user's profile. This builds on the work done in #976 and DoSomething/graphql#185.
I extracted a `SignupGallery` to handle the display of this interface element (following the patterns used in `ReviewablePostGallery`).
This is particularly helpful when viewing staff or power-user accounts, since otherwise folks were having to look up signup IDs in Looker in order to get to them from Rogue.
References [Pivotal #170503307](https://www.pivotaltracker.com/story/show/170503307).
=> Extract signup "gallery" with pagination support.

app/Models/Campaign.php, database/factories/ModelFactory.php, tests/Http/CampaignTest.php
This pull request updates the seeding for our faker factory to set the time to midnight when creating new campaign dates, as well as add getters for the start and end dates. These getters get our formatting set up and in the correct time zone.
👀 
Originally we approached this by updating our data type query in Graphql, but making the update here helps us to be more consistent and accurate in the dates and time zones we are using for both campaigns and scholarships.
References [Pivotal # 170090422](https://www.pivotaltracker.com/story/show/170090422).
=> Updates timezone definition in campaign getter

database/factories/ModelFactory.php, database/faker/FakerPostUrl.php, database/seeds/DatabaseSeeder.php, tests/Http/EventTest.php, tests/Http/ImagesTest.php, tests/Http/PostTest.php, tests/Http/ReviewsTest.php, tests/Unit/Models/PostModelTest.php
This pull request modifies the Model Factory to cleanup a few TODO's in the codebase:
* Creates a base Post factory class, and different factory states for post type + post status per https://github.com/DoSomething/rogue/pull/836#discussion_r365419349
* Modifies the Action factory to collect School ID by default, making it applicable to include a School ID by default in our Post factory
👀 
There's still an outstanding cleanup issue to create `action_stat` records for all approved posts with school id's, but that will be addressed in a future PR if there's time.
References [Pivotal #170693976](https://www.pivotaltracker.com/story/show/170693976).
=> Cleanup post factory

database/factories/ModelFactory.php, database/seeds/DatabaseSeeder.php
This pull request modifies the Database Seeder to calculate running totals for all schools when creating approved photo posts, and then adds ActionStat records accordingly.
* **Example Action view**
* **Example School view**
👀 
This beats manually needing to review posts with schools in order to verify the ActionStat views on the School/Action views are working properly.
References part 2 of line 10 in the [Q1 2020 Running Cleanup List](https://docs.google.com/document/d/1XYaTS_uptSva2hYunhHT2O2E1fq0wTE_UTlqLtTMcF8/edit).
=> Create ActionStats for seed data

database/migrations/2020_01_30_155905_add_contentful_campaign_i_d_to__campaign_table.php
This pull request creates the migration for adding the contentfulCampaignId to the Campaigns table!
Does making this column nullable make sense? Or should it be required? 
Is the campaignID stored as a string or a number? How could one check this in the future? 
Doing some prep work for getting filters set up in Phoenix on the explore campaigns page.
References [Pivotal #170987264](https://www.pivotaltracker.com/story/show/170987264).
=> Adds migration for the Contentful campaign id column in campaigns table

tests/Http/CampaignTest.php
This pull request adds testing for the patch endpoint added to our `campaigns/:id` route. Includes a test for a valid request and invalid request
Making sure this is thorough enough coverage for this endpoint! 
Follow similar patterns to the [post endpoint tests](https://github.com/DoSomething/rogue/blob/c1673a9b73c32d4bb16884a1d1619523c0d64054/tests/Http/PostTest.php#L1201).
References [Pivotal #](https://www.pivotaltracker.com/story/show/170987264).
=> Adds test for valid and invalid Update to a campaign

app/Http/Controllers/CampaignsController.php, app/Models/Campaign.php, docs/endpoints/campaigns.md, tests/Http/CampaignTest.php
This pull request adds a filter to the Campaigns index API endpoint to scope out campaigns with/without an assigned `contentful_campaign_id`
How's the naming?
Does it make sense to have both scopes for with/without? (It seemed like a logical way to apply this filter).
Now that we have this new column 'linking' to associated 'Campaign Websites' in Contentful (#450), this filter will allow us to properly scope out these campaigns via the API
References [Pivotal #171027117](https://www.pivotaltracker.com/n/projects/2401401/stories/171027117).
=> Campaign Has-Website Filter

app/Http/Controllers/CampaignsController.php, app/Models/Campaign.php, docs/endpoints/campaigns.md, tests/Http/CampaignTest.php
This pull request adds a filter to the `/campaigns` index API endpoint & Campaign model to allow filtering by included cause.
**Updated** as per our conversation [in Slack](https://dosomething.slack.com/archives/C0YGXUE01/p1580861249011600) to allow filtering by multiple causes with some more reliable sanitization.
How's the filtering Regex? 
How's the filter name? (I thought `cause` implied a singular cause, as opposed to _included_ cause. I wasn't quite sure between `has_cause` and `includes_cause` though)
Does the test logic make sense?
I went with a `regexp` operator instead of a `LIKE` so that we obtain more precise matches. I couldn't think of an elegant way to allow fuzzy matching without being -in my view- way too generous about the filter. (Some of our cause words overlap, like …
=> Campaign Cause Filter

database/migrations/2020_02_12_154805_add_index_to_campaign_start_date.php
This pull request adds a migration for an index to be added to the start date in the campaigns table. We are doing this as a precaution since we'll be using this property to sort in phoenix via graphql.
👀 
See note about why we are adding above ^^
References [Pivotal # 170823697](https://www.pivotaltracker.com/story/show/170823697).
=> Adding an index to the start date in campaigns

app/Console/Commands/StandardizeCauses.php, tests/Console/StandardizeCausesCommandTest.php
This pull request creates an artisan command to clean up causes! It grabs all campaigns with `cause` set, then it takes that cause and makes it lowercase and also replaces spaces with hyphens. This operation is performed even if the cause is already in that format, so messed up causes will be fixed and ones that are already formatted correctly will remain as they are.
Will this clean up all the funky causes?
We don't want to have to worry about transforming these causes in other places, let's store them all the same!
References [Pivotal #171159859](https://www.pivotaltracker.com/story/show/171159859).
=> Script to clean up causes

app/Http/Controllers/Web/CampaignsController.php, resources/assets/components/Campaign/index.js, resources/views/campaigns/create.blade.php, resources/views/campaigns/edit.blade.php
This pull request surfaces the `contentful_campaign_id` in Rogue admin when a campaign is created, edited, or viewed.
Creating:
Editing:
Viewing:
Is there anywhere else this field needs to be surfaced? Does this correctly show and edit the field? Is the validation good to go?
References [Pivotal #171026928](https://www.pivotaltracker.com/story/show/171026928).
=> Surface Contentful campaign ID in Rogue admin

docs/endpoints/posts.md, tests/Http/PostTest.php
This pull request updates the `/posts` documentation to indicate ability to filter posts by multiple statuses and adds a test for filtering by status.
👀 
References [Pivotal #171455035](https://www.pivotaltracker.com/n/projects/2401401/stories/171455035).
=> Posts Endpoint Status Filter Docs/Test

app/Http/Controllers/Web/ActionsController.php, app/Repositories/PostRepository.php, app/helpers.php, resources/assets/components/Action/index.js, resources/views/actions/create.blade.php, resources/views/actions/edit.blade.php
This pull request adds the `volunteer_credit` field to the Action forms for admins & exposes the field on Action views.
commit-by-commit!
- https://github.com/DoSomething/rogue/commit/20b80057149c408233e770c856e78e6121dec766 adds a new `is_admin_user` helper method to determine admin role status.
- https://github.com/DoSomething/rogue/commit/a9592f151a90d45c3f8881a0612625ab054338ea does a touch of refactoring to those helpers since we're now repeating logic
- https://github.com/DoSomething/rogue/commit/c273cf80fdd10509a6567efcab0b893064ea7932 adds the form field to Action create/edit forms for admins
- https://github.com/DoSomething/rogue/commit/5d3edad70812f6eaf27779c77911ef5fc729dc3b adds the field to the Action view component
- …
=> Action Volunteer Credit Field on the Front End

app/Http/Controllers/PostsController.php, app/Models/Post.php, database/factories/ModelFactory.php, docs/endpoints/posts.md, tests/Http/PostTest.php
This pull request adds a new `filter[volunteer_credit]=true/false` filter to the `/posts` API endpoint to filter for posts un/qualified for volunteer credit.
Feel free to weigh in [on this conversation](https://www.pivotaltracker.com/story/show/171455085/comments/212433853):
We deliberated over implementing this as more of a direct filter on the Action itself, allowing us to filter by multiple Action fields as positive includes. e.g. `/posts?filter[action_model]=volunteer_credit,quiz...`
The downside is that this does not allow for the negative include (where posts are _not_ anonymous for example. Though admittedly, there isn't a use case for the `volunteer_credit` negative scoping as of yet...), and is more direct to the feature we're filtering by. (This also _doesn't_ negate the …
=> Posts API Index Endpoint - Volunteer Credit Filter

resources/views/actions/edit.blade.php
This pull request fixes #996 to include the actual `volunteer_credit` field in an Actions edit form.
=> Include Volunteer Credit value in Action edit form

app/Types/TimeCommitment.php
This pull request adds another option for `time_commitment` on actions, <5 minutes. For the numerical value that is stored in the database, we store those in terms of hours. So we have like `3.0+` for "more than 3 hours" and we have `<0.5` for "less than 30 minutes. `5/60` is `0.083333333` so we store `<0.083`. Is that too specific? Should we do `<0.08` instead? None of them look particularly "nice" to me so I chose going with `0.083` since it's closer to `5/60` 🤷‍♀ 
Does this add <5 minutes as an option for time commitment for actions? Any tests needed?
We want to add this for some quicker actions. We have <30 but that makes people think it might take 30 minutes, saying <5 shows them that it really will be quick!
References [Pivotal …
=> Add <5 minute time commitment

app/Http/Transformers/PostTransformer.php, app/Http/Transformers/SignupTransformer.php, app/Models/Post.php, app/Models/Signup.php, app/Repositories/PostRepository.php, app/Repositories/SignupRepository.php, database/migrations/2020_03_23_000000_add_referrer_user_id_to_signups_and_posts_tables.php, docs/endpoints/posts.md, docs/endpoints/signups.md, tests/Http/PostTest.php, tests/Http/SignupTest.php, tests/Unit/Models/PostModelTest.php
This pull request adds a new `referer_user_id` text column to the `signups` and `posts` tables. 
👀 
We'll eventually use this field for calculating the total number of voter registrations referred by a user on their OVRD, by adding support to filter the `/v3/posts` index endpoint by `referrer_user_id`. Saving that for a future PR to help keep this reviewable. 
References [Pivotal #170775705](https://www.pivotaltracker.com/story/show/170775705), [Slack thread](https://dosomething.slack.com/archives/CP2D7UGAU/p1584987535004000).
=> Adds referrer_user_id field to Signups and Posts

database/factories/ModelFactory.php, docs/endpoints/posts.md
This pull request documents that the `/v3/posts` index supports filtering by `referrer_user_id`, per the addition to the `$indexes` property in #1003. Also populates the field in our database seeder to make it easier to test.
👀 
To find the total number of voter registration referrals for a user, our query will look like this:
```
GET /api/v3/posts?filter[referrer_user_id]=:userId&filter[type]=voter-reg
```
References [Pivotal #170775705](https://www.pivotaltracker.com/story/show/170775705).
=> Add referrer_user_id filter to Posts endpoint documentation

resources/assets/components/ReviewablePostGallery.js, resources/assets/helpers.js
This pull request updates the `status` field in our `ReviewablePostsQuery` query to be a `ReviewStatus` enum list per this change in our GraphQL schema https://github.com/DoSomething/graphql/pull/207
How's the implementation? I feel like there were a few ways to approach this. Am I missing any edge cases here that would complicate things?
I went with leaving the [`STATUS` values](https://github.com/DoSomething/rogue/blob/f98c79808a51930d8dd507be3f6200c18a007573/resources/assets/helpers.js#L5-L12) as they are since they're used in the [route params](https://github.com/DoSomething/rogue/blob/f98c79808a51930d8dd507be3f6200c18a007573/resources/assets/pages/ShowCampaign.js#L24) and so the logic to just upcase the values within our component felt more contained. But lmk if you disagree!
The …
=> ReviewablePosts query - status field update

tests/Unit/Models/PostModelTest.php
This pull request ensures the Post unit test will pass, by setting the expected values for `referrer_user_id`. This is a bug introduced by #1004, where we made the `referrer_user_id` property optional on the Post factory. The commits in #1004 passed because the factory generated `referrer_user_id` values as expected, but the merge commit into master did not.
👀 
🐦 
References [Pivotal #170775705](https://www.pivotaltracker.com/n/projects/2417735/stories/170775705).
=> Fixes intermittent failure in Post test

resources/assets/components/ReviewablePost.js, resources/assets/pages/ShowSignup.js
This pull request displays the `referrerUserId` introduced in https://github.com/DoSomething/graphql/pull/208 and https://github.com/DoSomething/rogue/pull/1003.
👀 
👕 
References [Pivotal #170775705](https://www.pivotaltracker.com/story/show/170775705).
=> Display referrer on signups and posts

resources/assets/Application.js, resources/assets/components/ReferralsTable.js, resources/assets/pages/ShowUser.js, routes/web.php
This pull request adds a `user/:id/referrals` route to view all referral posts for a user (refs https://github.com/DoSomething/graphql/pull/212)
👀 
Eventually we can add pagination, and lists of signups and users that the user has referred -- but for now it will be extremely helpful to have this to spot check voter registration referrals.
References [Pivotal #170775705](https://www.pivotaltracker.com/story/show/170775705).
=> Adds user referrals view

app/Http/Requests/PostRequest.php, app/Models/Post.php, composer.lock, tests/Http/PostTest.php
This pull request updates our validation logic to discard invalid `location` values, rather than triggering a 422 validation response & preventing submission. This will allow users whose provided geolocation data does not match [our location database](https://github.com/sokil/php-isocodes) to submit posts.
I updated tests to reflect this new behavior.
We validate this data before persisting it to the database because we'll later need to parse it, for example to provide user-friendly location names in Rogue's admin panel & some Phoenix galleries.
References [Pivotal #171613477](https://www.pivotaltracker.com/story/show/171613477).
=> Don't return a validation error for invalid ISO-3166-2 region.

resources/assets/graphql.js
This pull request simply attaches this application's name to our GraphQL requests, so that we can segment these out in Apollo Engine when looking at metrics:
👀
Support for this was added in DoSomething/graphql#213.
I made a similar change to Phoenix in DoSomething/phoenix-next#2011.
References [Pivotal #171001230](https://www.pivotaltracker.com/story/show/171001230).
=> Attach client identifier to requests.

app/Http/Kernel.php, routes/api.php
This pull request (experimentally) adds a new `asset` middleware group for public `/images/{hash}` routes to enable assigning the https://github.com/fruitcake/laravel-cors handler to this route specifically since it doesn't fall into our `api` or `web` groups.
To be completely honest, I've been floundering, trying to figure this one out. I haven't been able to validate that this will work locally beyond assuming this should work logically! (For some reason, I'm unable to replicate the CORS issues I'm seeing on the dev environment related to the issue below locally).
Does this make sense? Is the middleware name ok?
See https://dosomething.slack.com/archives/CUQMU4Q6B/p1588343622106600
References [Pivotal #172624016](https://www.pivotaltracker.com/story/show/172624016).
=> Public Images & CORS

app/Http/Kernel.php, routes/api.php
Reverts DoSomething/rogue#1013
In my conflagrated state of mind, I failed to properly investigate and realize that the `/images/{hash}` route _is_ in the `api` middleware group by its very existence within the `routes/api.php` file, and thus already had the CORS Handler.
> The routes in routes/api.php are stateless and are assigned the api middleware group.
(https://laravel.com/docs/5.5/routing#basic-routing)
I also failed to properly test this locally https://github.com/DoSomething/rogue/pull/1013#issuecomment-622482285
In any case, happy Friday, we figured out that there's something afoot in general with this CORS issue and have some time set aside to investigate on Monday! https://github.com/DoSomething/rogue/pull/1013#issuecomment-622496295
=> Revert "Public Images & CORS"

app/Models/Post.php, database/factories/ModelFactory.php, tests/Http/PostTest.php
This pull request modifies the `scopeWhereVisible` function in our `Post` model to allow a referrer to see completed voter registrations they have referred. This fixes a [bug found while testing the new Alpha OVRD "Get 3 friends to register" section](https://www.pivotaltracker.com/story/show/172417306/comments/213979491) -- staff users can see their referrals but non-staff users cannot, without these changes in place. I've tested my local Phoenix against this branch locally and confirmed a non-staff can now see their referrals.
👀 
We may eventually want to display more statuses than our completed statuses if we get around to building out displaying a [list of non-completed voter registration referrals to the alpha](https://www.pivotaltracker.com/story/show/171043026) - -but we can change …
=> Make voter-reg referrals visible to the referrer

app/Http/Kernel.php, app/Http/Middleware/HandleCors.php, composer.json, composer.lock, tests/Http/ImagesTest.php
_Pair Programmed with @DFurnes_ 🎩 💁‍♂️ 
This pull request replaces the [`barryvdh/laravel-cors`](https://github.com/fruitcake/laravel-cors) package with a dead-simple piece of in-house middleware to ensure we always attach an `Access-Control-Allow-Origin` header allowing any (`*`) domain to make requests to Rogue.
👀 
I added a test for kicks in https://github.com/DoSomething/rogue/commit/473008e324ae979953ba7760334c49f7ef781c1a. This header really should exist across _all_ API requests, but figured it might be nice to have this test somewhere, and this was the place whence our woes arose, so why not 🤷?
This relates to the ills we discussed in https://github.com/DoSomething/rogue/pull/1013, with some inconsistent CORS issues on Rogue image requests made via `XMLHttpRequest`.
In a nutshell, …
=> Adjust CORS middleware for API requests

.env.example, app/Jobs/CreateCustomerIoEvent.php, app/Managers/PostManager.php, app/Models/Post.php, app/Services/CustomerIo.php, app/Services/GraphQL.php, config/services.php, database/factories/ModelFactory.php, tests/Http/PostTest.php, tests/Http/SignupTest.php, tests/Unit/Models/PostModelTest.php, tests/WithMocks.php
This pull request sends two new events, `referral_post_created` and `referral_post_updated` to Customer.io when a post with a `referral_user_id` is created or updated. Each event is created on behalf of the referrer -- so we can send email or SMS notifications to an alpha if a beta completes a voter registration from their OVRD page.
It's passing along a minimal set of attributes for now to keep this easier to maintain and review. The majority of the changes in this PR are for new classes for a Customer.io API client and the new `CreateCustomerIoEvent` job that will be used to create these events.
👀 
Once this is merged,it should be straight forward enough to manually test this out with QA Test Import form in Chompy - verifying the events are created when a referral voter reg post is …
=> Adds referral_post_created and referral_post_updated Customer.io events

resources/views/campaigns/edit.blade.php
This pull request hides the Contentful Campaign ID field on the edit campaign view to everyone except admins! It does NOT hide this field on the view campaign page.
As admin:
As staff:
Will this prevent anyone who is not an admin from editing this field? Can admins still edit this field?
If we link to a Contentful page in Rogue that's not published, it'll take down `/campaigns`! So we want to make sure this field is only being added when it really should be.
References [Pivotal #172383488](https://www.pivotaltracker.com/story/show/172383488).
=> Only allow admins to edit Contentful Campaign ID field

resources/views/campaigns/create.blade.php
This pull request is an update to https://github.com/DoSomething/rogue/pull/1017 which turns out to be an unfinished job. I only removed the field on the campaign edit form but missed the campaign create form! This hides the `contentful_campaign_id` field unless the user is an admin.
As staff:
As admin:
Did I miss anywhere else this time?
If we link to a Contentful page in Rogue that's not published, it'll take down /campaigns! So we want to make sure this field is only being added when it really should be.
References [Pivotal #172383488](https://www.pivotaltracker.com/story/show/172383488).
=> Hide contentful campaign id from non admins on CREATE form

config/posts.php
This pull request lowers the minimum image size required for posts from 400 by 400 to 50 by 50.
Image I can submit now but couldn't before:
Image I still can't submit:
Any flags?
There's a whole incident channel linked from the card but something happened and Gambit images were coming in real small so we want to lower this limit so we can push them through so we don't lose them!
References [Pivotal #172939835](https://www.pivotaltracker.com/story/show/172939835).
=> Change post minimum dimensions to 50x50

config/scout.php
This pull request simply adds a Scout Prefix for the indexes related to Rogue.
I'm still figuring out what the ideal setup for all this is, but for the time being I've decided on setting up platform specific API Keys and for each platform having 3 keys per environment. So for Rogue we have:
- Rogue[Development]: handles indexes prefixed by either `local_*` or `development_*`
- Rogue[QA]: handles indexes prefixed by`qa_*`
- Rogue[Production]: handles indexes prefixed by`production_*`
GraphQL will have its own keys but will handle the same prefixed indexes. What this means is that, for example, there will be a "GraphQL[Production]" API Key, that will allow requests to create/update records in any indexes that are prefixed by `production_*`. So Rogue and GraphQL can both work with production …
=> Updating to use app env as prefix.

app/Models/Action.php, app/Models/Campaign.php
This pull request helps include campaign Action data to each campaign when it is indexed. It also enables updating the index when a change is made to an action entry attached to a campaign.
👀 
I tested this a bit locally and seems to work fine!
References [Pivotal #172660182](https://www.pivotaltracker.com/story/show/172660182).
=> Add Acion relationship to Campaign data.

app/Models/Action.php
This pull request removes the use of the `Searchable` trait. I realized that by adding this Scout would also create an index for `*_actions` which is not what we want. We solely want actions within campaign record in the `*_campaigns` index!
The Action model still specifies the `$touches` property which lets the Campaign model know when an action is updated, etc.
👀 
References [Pivotal #172660182](https://www.pivotaltracker.com/story/show/172660182).
=> Keep Actions from indexing themselves.

app/Http/Controllers/GroupTypesController.php, app/Http/Transformers/GroupTypeTransformer.php, app/Models/GroupType.php, database/factories/ModelFactory.php, database/migrations/2020_05_27_000000_create_group_types_table.php, docs/endpoints/README.md, docs/endpoints/group-types.md, routes/api.php, tests/Http/GroupTypeTest.php
This pull request starts on a `GroupType` resource, which will be used as a lookup table for the upcoming `Groups` resource needed for [Group OVRD campaigns](https://www.pivotaltracker.com/epic/show/4570244).
Going commit by commit, we can see this PR adds:
* `app/models/GroupType` -- our `fillable` property determines which fields are editable
* `database/migrations/[datetime]_create_group_types_table` - this migration will:
* create the new `group_types` SQL table - Laravel will know this corresponds our `GroupType` model based on the [table/class names](https://laravel.com/docs/5.5/eloquent#eloquent-model-conventions)
* add a unique index on `name` field (two group types should not have the same name)
* add `created_at` and `updated_at` fields via calling the `timestamps()` method
At …
=> Adds GroupType model and GET /api/v3/group-types endpoint

app/Models/GroupType.php, resources/assets/Application.js, resources/assets/pages/GroupTypeIndex.js, resources/assets/pages/ShowGroupType.js, routes/web.php
This pull request adds front-end UI for the `groupTypes` and `groupType(id)` GraphQL queries added in https://github.com/DoSomething/graphql/pull/234, displaying a list of all `group_types` records, or a single `group_type` entity.
:eyes:
Web forms for adding/editing to be added in a future PR to help keep this reviewable.
References [Pivotal #172541916](https://www.pivotaltracker.com/story/show/172541916).
=> Index + show views for Group Types

app/Models/Campaign.php, database/migrations/2020_06_02_204137_add_group_type_id_to_campaigns_table.php
This pull request creates a migration to add the `group_type_id` as a foreign key on the campaigns table! It also adds the property as fillable so we are able to edit it later on.
👀 
We are going to allow admins the ability to add a group type id on a campaign so that it can be associated with a particular group. (right now this is specific to our OVRD campaigns for Voter Registration)
References [Pivotal # 173101101](https://www.pivotaltracker.com/story/show/173101101).
=> Adding group_type_id to the campaigns table

app/Http/Controllers/Web/GroupTypesController.php, app/Http/Controllers/Web/GroupsController.php, resources/assets/Application.js, resources/assets/pages/ShowGroup.js, resources/assets/pages/ShowGroupType.js, resources/views/group-types/create.blade.php, resources/views/groups/create.blade.php, resources/views/groups/edit.blade.php, routes/web.php
This pull request adds support for staff and admins to create, view, and edit a Group (added in #1031) via the admin UI, by first navigating to the Group Type page to create/edit a Group for.
👀 
* This is missing tests for now, to help keep this 👹 of a PR this reviewable.
* I mentioned this in https://github.com/DoSomething/rogue/pull/1030#discussion_r434707291, but couldn't figure out how to add form validation to prevent the server error if you try to create/edit a group with a duplicate name within the group type. Because this is an internal tool, I think we'll be fine to fix this up in a future PR, again to cut down on complexity / review time.
References [Pivotal #172541916](https://www.pivotaltracker.com/story/show/172541916).
=> Create + edit Groups via web

app/Http/Transformers/SignupTransformer.php, app/Models/Signup.php, app/Repositories/SignupRepository.php, database/factories/ModelFactory.php, database/migrations/2020_06_03_000000_add_group_id_to_signups_table.php, docs/endpoints/signups.md, tests/Http/SignupTest.php
This pull request adds a `group_id` field to the Signup resource, referencing the Groups resource added in #1031.
👀 
Related changes coming up for future PR's:
* Include `group_type_name` and `group_name` in a Customer.io `campaign_signup` event
* Add `group_id` to Posts
References [Pivotal #172541936](https://www.pivotaltracker.com/story/show/172541936).
=> Adds group_id field to Signups 

resources/assets/pages/ShowGroup.js
This pull request displays a Group's Group Type name instead of the Group Type ID per https://github.com/DoSomething/graphql/pull/239.
👀 
Last thing left to do on this ShowGroup page is displaying the list of signups whose `group_id` matches the current group, but that's for another PR. 
References [Pivotal #172541916](https://www.pivotaltracker.com/story/show/172541916).
=> Display groupType name on ShowGroup page

app/Http/Transformers/PostTransformer.php, app/Models/Post.php, app/Repositories/PostRepository.php, database/migrations/2020_06_05_000000_add_group_id_to_posts.php, tests/Http/PostTest.php
This pull request adds a group_id field to the Posts resource, referencing the Groups resource added in #1031.
👀 
We'll eventually need a compound index to the `posts` table on `group_id`, `status`, and potentially `action_id` -- but holding off on adding this, as we'll likely want to deploy that migration while the website is in maintenance mode to avoid timeouts (which happened when we deployed #1034)
References [Pivotal #172541936](https://www.pivotaltracker.com/story/show/172541936), #1034
=> Adds group_id field to Posts

resources/assets/components/ReviewablePost.js, resources/assets/helpers.js, resources/assets/pages/ShowGroup.js, resources/assets/pages/ShowSignup.js
This pull request adds front end changes per https://github.com/DoSomething/graphql/pull/238 that will come in handy for testing https://github.com/DoSomething/phoenix-next/pull/2200:
* Display a signup's Group ID on a Signup page (`/signups/:id`)
* Display a list of a Group's most recent signups on a Group page (`/groups/:id`)
Also adds a `formatDateTime` helper and fixes a Collective Freezer bug.
👀 
We'll eventually want to paginate through the list of a group's signups, or potentially add a filter by the `campaignId` but for now this will help us test OVRD groups while we're actively in development/QA.
* [#172541936](https://www.pivotaltracker.com/story/show/172541936)
* [#172084266](https://www.pivotaltracker.com/story/show/172084266)
=> Display Group's signups, Signup's Group ID

app/Models/Post.php, database/migrations/2020_06_08_000000_add_compound_index_to_posts_with_group_id.php, docs/endpoints/posts.md, tests/Http/PostTest.php
This pull request adds a compound index referred to in #1038, and allows filtering a `GET /posts` index query by `group_id`. This should improve performance when we eventually regularly query the database to get a count of the total completed voter registration posts for a specific `group_id`.
It also modifies the visible scope of the `Post` model to return all completed voter-reg posts, to simplify the logic needed for the calculation (it'd be complicated and more costly to try to join on `signups` to determine whether the authenticated user has signed up with the `group_id` we're running the calculation for)
👀 
A reason to show any voter-reg referral regardless of status is that we eventually want to show a referrer ALL referrals broken down by different status (including non-completed …
=> Adds index to posts table on group_id, action_id, status

.env.example
This pull request sets the default `SCOUT_DRIVER` to `'null'`. This fixes an issue where we'd pass the _actual_ `null` value (from the empty value in `.env`) when trying to create a driver and it'd explode whenever the application tried to boot:
```
Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed
```
When running this application with a fresh `.env`, things should no longer error out.
This was a bug introduced in #1022.
References [Pivotal #173252821](https://www.pivotaltracker.com/story/show/173252821).
=> Set the default SCOUT_DRIVER to 'null'.

app/Models/Campaign.php
This pull request transforms any dates in the Campaign's `toSearchableArray` payload into UNIX timestamps, which allows us to [filter on those fields using Algolia](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-date/).
👀 
I considered creating `start_date_timestamp` and `end_date_timestamp` fields, like shown in Algolia's docs, but that seems like something that'd just unnecessarily increase our index size.
Can you think of any reasons we might want or need the ISO date in Algolia?
References [Pivotal #172922602](https://www.pivotaltracker.com/story/show/172922602).
=> Algolia requires UNIX timestamps to filter by dates.

resources/assets/components/Campaign/index.js, resources/assets/pages/ShowCampaign.js
This pull request adds `groupTypeId` to ShowCampaign component.
👀 
We are going to allow staff the ability to add a group type id on a campaign, this will allow it to be associated with a specific group, regards OVRD campaigns on Voter Registration
References [Pivotal # 173101101](https://www.pivotaltracker.com/story/show/173101101).
=> add groupTypeId to Campaign component

resources/assets/components/GroupTypeCampaignList.js, resources/assets/pages/ShowGroupType.js
This pull request modifies the `ShowGroupType` page to display a list of campaigns that have their `groupTypeId` set to the current group type being viewed.
👀 
At least locally, the `paginatedCampaigns` query seems awfully slow, which is why I wanted to move it into a separate component to avoid blocking loading the entire page. I'm wondering if I'm missing anything in the query that would speed things up. (Also could be worth caching it on the GraphQL side, but nothing needed for this PR -- which is all admin facing)
Last item in [Pivotal #173101101](https://www.pivotaltracker.com/story/show/173101101).
=> Display a Group Type's campaigns

app/Console/Commands/ImportMfolGroupsCommand.php
This pull request follows the [`ImportSignupCommand`](https://github.com/DoSomething/rogue/blob/master/app/Console/Commands/ImportSignupsCommand.php) by example to add a new `ImportMfolGroupsCommand` console command that finds or creates a Group Type with name `March For Our Lives`, and creates a group in this group type for each row in a given csv, if it doesn't exist already. I've uploaded the CSV as a Github gist, and been using the URL to test this locally.
👀 
🍰 
References [Pivotal #172541978](https://www.pivotaltracker.com/story/show/172541978).
=> Adds command to import March For Our Lives groups

app/Http/Controllers/GroupsController.php, app/Models/Group.php, docs/endpoints/groups.md, tests/Http/GroupTest.php
This pull request modifies the `filters[name]` in a `GET /groups` index request to return all groups that have names that contain the filter value, instead of looking for an exact match.
Example response:
```
// http://rogue.test/api/v3/groups?filter[name]=new
{
"data": [
{
"id": 1,
"group_type_id": 1,
"name": "New York City",
"goal": 200,
"created_at": "2020-03-24T18:33:56+00:00",
"updated_at": "2020-06-03T17:40:52+00:00"
},
{
"id": 114,
"group_type_id": 1,
"name": "Newark, OH",
"goal": null,
"created_at": "2020-06-18T18:10:41+00:00",
"updated_at": "2020-06-18T18:10:41+00:00"
},
{
"id": 222,
"group_type_id": 1,
"name": "The New School, NY",
"goal": null,
"created_at": "2020-06-18T18:10:41+00:00",
"updated_at": "2020-06-18T18:10:41+00:00"
},
...
```
👀 
We'll be asking users to begin …
=> Use regexp for Groups name filter instead of equals

app/Http/Controllers/GroupsController.php, app/Http/Transformers/GroupTransformer.php, app/Models/Group.php, tests/Http/GroupTest.php
This pull request adds support for using `cursor[after]=` to paginate through groups, following PR's like https://github.com/DoSomething/rogue/pull/976 by example.
👀 
Example response:
```
// http://rogue.test/api/v3/groups?cursor[after]=MjM3LkRlZXJpbmcgSGlnaCBTY2hvb2wsIE1F
{
"data": [
{
"id": 58,
"group_type_id": 1,
"name": "Denver Metro, CO",
"goal": null,
"created_at": "2020-06-18T18:10:40+00:00",
"updated_at": "2020-06-18T18:10:40+00:00",
"cursor": "NTguRGVudmVyIE1ldHJvLCBDTw=="
},
{
"id": 92,
"group_type_id": 1,
"name": "Des Plaines, IL",
"goal": null,
"created_at": "2020-06-18T18:10:41+00:00",
"updated_at": "2020-06-18T18:10:41+00:00",
"cursor": "OTIuRGVzIFBsYWluZXMsIElM"
},
{
"id": 205,
"group_type_id": 1,
"name": "Dickinson College, PA",
"goal": null,
"created_at": …
```
=> Add cursor support to groups index

app/Models/Post.php, tests/Unit/Models/PostModelTest.php
This pull request adds the `post->action->volunteer_credit` attribute to the Post Model's Blink payload to inform us on the messaging side regarding Volunteer Creditworthy Reportbacks.
👀 
I wasn't sure about the test. I always feel confused about whether to add tests for what might be built-in or extremely straightforward steps such as an attribute in a payload. My logic ended up being - and correct me here - that in the interest of ensuring that _generally_, action attributes are making it over to the payload (which would e.g. catch instances where the post-action relationship is somehow borked), we could test one example attribute.
References [Pivotal #173110670](https://www.pivotaltracker.com/story/show/173110670).
=> Action->Volunteer Credit field in Post's Blink Payload

database/migrations/2020_06_24_000000_move_group_type_id_on_campaigns_table.php
This pull request drops the `group_type_id` column from the `campaigns` table and recreates it so it doesn't appear last in the table... which is something we missed in the migration added in #1032. This is a cosmetic change, but I do think it makes it easier to scan the SQL data. 
I tried both of the top answers in this [SO thread](https://stackoverflow.com/questions/20340778/laravel-migration-re-organising-column-order), but ran into errors with both conflicts around the foreign key. Because we currently only have one `campaign` that has this field populated, and it's not live yet -- we're in a good spot to wipe the column and re-add the correct `group_type_id` for [campaign 9075](https://activity.dosomething.org/campaigns/9075) has completed.
:eyes:
I've been back and forth on whether …
=> Move position of group_type_id field on campaigns table

resources/assets/components/Campaign/index.js, resources/assets/components/CampaignsTable.js, resources/assets/components/GroupTypeCampaignList.js, resources/assets/components/GroupsTable.js, resources/assets/components/utilities/EntityLabel.js, resources/assets/pages/GroupTypeIndex.js, resources/assets/pages/ShowGroup.js, resources/assets/pages/ShowGroupType.js
This pull request adds a search filter and pagination to the list of a group type's groups, using the `paginatedGroups` query added in https://github.com/DoSomething/graphql/pull/248, as well as some additional tweaks:
* Displays group type name on campaign page if set, per https://github.com/DoSomething/graphql/pull/246
* Renders the group type campaign list as a `ul` (refs #1046)
* Adds a `EntityLabel` utility component to DRY displaying an entity's label and ID within a `code` element
👀 
📄 
References [Pivotal #173275849](https://www.pivotaltracker.com/story/show/173275849).
=> Groups pagination

resources/assets/components/SignupsTable.js, resources/assets/pages/ShowGroup.js, resources/assets/pages/ShowSignup.js
This pull request fixes the TODO of paginating the list of signups displayed on a Group page in the admin UI, borrowing from the paginated `GroupsTable` added in #1052. 
It also adds a check into the Signup page for a null user, which can happen when seeding the DB.
👀 
🛩️ 
References [Pivotal #173275849](https://www.pivotaltracker.com/story/show/173275849).
=> Add pagination to Group signups

app/Console/Commands/ImportMfolGroupsCommand.php, app/Console/Commands/ImportNasspGroupsCommand.php, resources/assets/components/GroupsTable.js
This pull request adds a console command to import a CSV from the National Association of Secondary School Principals (NASSP) as three different Group Types and their respective Groups. It also displays the `city` and `state` fields added in #1055 in our GroupsTable component, to help verify imported NASSP data.
👀 
The NCES code is used as an ID for NASSP, so we save it to our `external_id` field. The file does not provide a "universal ID" -- if it did, we could that field to link these groups to their respective School in GraphQL. 
References [Pivotal #173408737](https://www.pivotaltracker.com/story/show/173408737).
=> Adds command to import NASSP groups

app/Console/Commands/ImportNasspGroupsCommand.php, app/Http/Controllers/Web/GroupTypesController.php, app/Http/Transformers/GroupTypeTransformer.php, app/Models/GroupType.php, database/factories/ModelFactory.php, database/migrations/2020_06_25_000000_add_filter_by_state_to_group_types.php, docs/endpoints/group-types.md, resources/views/group-types/create.blade.php, resources/views/group-types/edit.blade.php, tests/Http/Web/GroupTypeTest.php
This pull request adds a boolean `filter_by_state` attribute to the `GroupType` model. If this is set, a group finder for the group type should display a "Select State" dropdown first, in order to filter the groups search by state as well as name.
We'll want to set this field to `true` in the NASSP import per https://github.com/DoSomething/rogue/pull/1056#discussion_r445749156.
👀 
☑️ 
References [Pivotal #173231765](https://www.pivotaltracker.com/story/show/173231765).
=> Adds filter_by_state field to Group Types

package-lock.json, package.json, resources/assets/components/GroupsTable.js, resources/assets/pages/ShowGroupType.js
This pull request adds support to mimic a Phoenix Group Finder search (https://github.com/DoSomething/phoenix-next/pull/2238) by filtering a group type's group list by the `state` field if the group type is configured to filter by state (refs #1057).
👀 
* We don't have any dev or QA group types with `filter_by_state` yet, still working on getting final import files in https://www.pivotaltracker.com/story/show/173408737. I've been testing locally with data I added via executing the first pass of the import in #1056 
* Once we do have live group types that filter by state, it'll be convenient for staff to filter by state through Rogue to mimic a user's search (vs visiting the campaign's group finder anonymously, which will only work as long as the campaign is open for)
* I was curious to …
=> Add state select to Groups list if Group Type filters by state

app/Console/Commands/ImportNasspGroupsCommand.php, resources/assets/Application.js, resources/assets/pages/ShowGroup.js, resources/assets/pages/ShowGroupType.js, resources/assets/pages/ShowSchool.js, routes/web.php
This pull request makes a few tweaks to the admin UI to make the spot checking the NASSP import (#1059) easier:
* Displays Group `state`, `city` attributes if present, links to the School page if `schoolId` is present
* Displays Groups associated with a School on a School page
* Adds a `/groups` route on web that renders the group-types list (available at `/group-types`, which is longer to type!)
Group page:
School page:
👀 
🦉 
References [Pivotal #173408737](https://www.pivotaltracker.com/story/show/173408737).
=> Groups admin cleanup

resources/assets/pages/ShowGroup.js
This pull request uses the `voterRegistrationsCountByGroupId` query added in https://github.com/DoSomething/graphql/pull/252 (and fixed in https://github.com/DoSomething/graphql/pull/253) to display a group's total number of voter registrations, beginning to DRY the logic of finding that count within this repo and Phoenix.
👀 
🤿 
References [Pivotal #172541916](https://www.pivotaltracker.com/story/show/172541916).
=> Use voterRegistrationsCountByGroupId

app/Console/Commands/ImportRhodeIslandGroupsCommand.php, tests/Console/ImportRhodeIslandGroupsCommandTest.php, tests/Console/example-rhode-island-groups.csv
This pull request adds a new console command to create groups for a `Rhode Island` group type from a CSV, similar to commands added in #1056 and #1047. I've uploaded the source file as a [gist](https://gist.githubusercontent.com/aaronschachter/79d0d78289d4d9ee09287155d84a5d39/raw/ba602f249e1562a2b04b206dcb0da0ba83fd5dd5/groups.csv) and have been using that for testing (as well as to use for the import in each environment upon merge).
👀 
⚓ 🦞 ⛵ 
References [Pivotal #173687221](https://www.pivotaltracker.com/story/show/173687221).
=> Adds command to import Rhode Island Dept of Education groups 

app/Observers/PostObserver.php, app/Providers/AppServiceProvider.php, database/factories/ModelFactory.php, tests/Unit/Models/PostModelTest.php
This pull request adds a new [Laravel observer](https://laravel.com/docs/5.5/eloquent#observers) on the Post model with a `creating` hook, which populates the post `school_id`  field with a group's `school_id` field if the post `school_id` wasn't provided, but a `group_id` was.
This will make it easier to find all `voter-reg` posts for a school, vs having to SQL join on groups to find their associated school IDs. 
👀 
I went with adding a new Observer vs adding the logic into the `PostRepository`, because it seemed to make sense for this rule to be applied globally (e.g. when creating model factories), vs only when posting via API. I followed by example from the Northstar's UserObserver, which made auto-updating users' various subscription fields based on other values easy to maintain and …
=> Save group's school_id when creating post if school_id not given

app/Models/Group.php, app/Models/GroupType.php, app/Models/Post.php, app/Models/Signup.php, app/Observers/PostObserver.php, tests/Unit/Models/PostModelTest.php, tests/Unit/Models/SignupModelTest.php
This pull request adds `group_id`, `group_name`, `group_type_id`, and `group_type_name` attributes to Customer.io events for signups and posts. This enables support for displaying a group's info within Customer.io message templates.
Example message template: 
`Thanks for signing up with your {{event.group_name}} chapter of {{event.group_type_name}}!`
Example message text:
`Thanks for signing up with your Monmouth County, NJ chapter of March For Our Lives!`
👀 
This PR also modifies `PostObserver` from #1064 to use the new `$post->group` attribute added in this PR, to DRY.
References [Pivotal #173481072](https://www.pivotaltracker.com/story/show/173481072).
=> Adds group attributes to Customer.io events

app/Models/Group.php, app/Models/Post.php, app/Models/Signup.php
This pull request adds a static `toBlinkPayload` method to our `Group` model to DRY sending over group attributes for signups and posts to Customer.io, per @mendelB's great suggestion in https://github.com/DoSomething/rogue/pull/1066#discussion_r452853443
👀 
⛱️ 
References [Pivotal #173481072](https://www.pivotaltracker.com/n/projects/2417735/stories/173481072).
=> Adds Group toBlinkPayload method 

resources/assets/components/ReferralsTable.js, resources/assets/pages/ShowUser.js
This pull request fixes the datetime display on the User Referrals page (/users/:id/referrals), changing it from `7/13/2020 7:12:9` to `7/13/2020 7:12 PM`.
Also updates the headline to clarify that this page currently on displays Referral Posts.
👀 
The `formatDateTime` helper was introduced in https://github.com/DoSomething/rogue/pull/1039. 
References [Pivotal #172084266](https://www.pivotaltracker.com/n/projects/2441250/stories/172084266).
=> Cleanup referrals page

app/Http/Requests/Legacy/Two/SignupRequest.php, app/Http/Requests/PostRequest.php
This pull request validates that incoming Post & Signup `referrer_user_id`s are valid MongoDB Object IDs.
https://github.com/DoSomething/rogue/commit/ed3f84cb302e3fc8dd9f1e9c48e4a6ce1e833b82 updates the validation rule for the SignupRequest since we added this one before our custom `objectid` rule in https://github.com/DoSomething/rogue/commit/54347b5e0fc3d09dd21fb89621a1e1705f6d87bf
👀 
I suppose the one thing to be considered is that we're now _rejecting_ posts/signups with invalid ID's (and not silently rejecting the ID's as we do for web registrations https://github.com/DoSomething/northstar/pull/1039). 
I don't anticipate this causing much disruption since we shouldn't really be seeing any _innocent_ invalid ID's, but perhaps something to keep an eye on in case it does disrupt, and we …
=> Validate referrer_user_ids on Signup & Post Requests

resources/assets/Application.js, resources/assets/components/PostsTable.js, resources/assets/components/SignupsTable.js, resources/assets/pages/PostIndex.js, resources/assets/pages/ShowCampaign.js, resources/assets/pages/ShowGroup.js, resources/assets/pages/ShowUser.js, routes/web.php
This pull request refactors the `ReferralsTable` as a `PostsTable`, continuing the work done in #1070 to build out better admin views to spot check voter registration data by paginating through the results of `GET /posts` index queries. 
It also adds new web views for:
* All posts (/posts)
* A group's posts (/group/:id/posts)
* A user's posts (/users/:id/posts)
* A campaign's posts (/users/:id/posts)
👀 
The `ReviewablePost` component doesn't display voter registration data very well, it doesn't show the post status, nor should it be reviewable. This PR adds simple table views to spot check that posts are being created with group ID's (when users are registering via a group OVRD page)
References [Pivotal #173927241](https://www.pivotaltracker.com/story/show/173927241).
=> Refactors ReferralsTable as PostsTable and adds additional web views

.styleci.yml, app/Http/Transformers/ActionStatTransformer.php, app/Models/ActionStat.php, app/Models/Post.php, app/Notifications/SlackTagNotification.php, app/Repositories/PostRepository.php, database/factories/ModelFactory.php, database/migrations/2020_07_27_000000_rename_accepted_quantity_to_impact_on_action_stats_table.php, database/seeds/DatabaseSeeder.php, docs/endpoints/action-stats.md, tests/Http/ReviewsTest.php
This pull request adds a migration to rename the `accepted_quantity` int column on the `action_stats` table to `impact`. For voter registration, we'd like to store the total number of voter-reg posts with status starting with `register-` here -- so I figured it'd be simplest to rename the field to something more generic that can be re-purposed for various post types.
It also fixes the same newfound StyleCI error we saw pop up in https://github.com/DoSomething/phoenix-next/pull/2298, and then fixes new style errors that popped up after that change.
:eyes:
Was debating on whether to add a separate field instead of renaming `accepted_quantity`, but the TLDR from this [Slack discussion](https://dosomething.slack.com/archives/CP2D7UGAU/p1595881689011800) made me think two separate fields would …
=> Rename ActionStats accepted_quantity to impact 

app/Observers/PostObserver.php, tests/Http/PostTest.php
When a post is being created, we'll check to see if its signup has a `group_id` set and if it does, we'll save the same `group_id` to the post as well.
I wrote the test failing test first, added the logic in the `PostObserver`, made sure the test was passing as well as testing manually. Did I miss anything? Does this mess with the `school_id` logic at all?
It's all in the ticket!
References [Pivotal #173750109](https://www.pivotaltracker.com/story/show/173750109).
=> If signup has a group_id, save it on the post as well

app/Managers/SignupManager.php, app/Models/Signup.php, tests/Http/PostTest.php, tests/Http/SignupTest.php, tests/Unit/Models/SignupModelTest.php
This pull request follows the excellent #1018 by example to dispatch a `referral_signup_created` event to customer.io when a Signup is created with a `referral_user_id` so that we can send a dedicated email to the referrer.
commit-by-commit. You can refer to #1018 for slightly more context, but hopefully, this is super straightforward as-is!
See the Pivotal Ticket for the list of requested payload attributes.
References [Pivotal #173563077](https://www.pivotaltracker.com/story/show/173563077).
=> Adds referral_signup_created Customer.io Event

app/Models/Post.php, app/Observers/PostObserver.php, app/Repositories/PostRepository.php, tests/Unit/Models/PostModelTest.php
This pull request creates or updates an `ActionStat` for a school upon creating or updating a completed `voter-reg` post. We'll eventually use this data to display a leaderboard of voter registrations by school (details in #[2417735](https://www.pivotaltracker.com/n/projects/2417735)).
It implements this by refactoring the existing Post `getAcceptedQuantitySum` method as `updateOrCreateActionStats`, and by calling it from newly added `created` and `updated` hooks in the PostObserver.
Also adds a static `getCompletedVoterRegStatuses` method to the Post model to DRY getting list of statuses considered completed.
👀 
* We have existing test coverage for creating ActionStats for approved posts in test for the Reviews endpoint, so didn't add it into our model test for now. Might be worth moving …
=> Create ActionStats for completed voter registrations

app/Http/Transformers/ActionStatTransformer.php, app/Http/Transformers/GroupTransformer.php, app/Models/ActionStat.php, app/Models/Group.php, app/Models/Post.php, database/migrations/2020_07_30_000000_add_location_to_action_stats_and_groups_tables.php, docs/endpoints/action-stats.md, docs/endpoints/groups.md, tests/Unit/Models/PostModelTest.php
This pull request adds a migration to add `location` column to the `action_stats` and `groups` tables, and populates the `location` field with the `state` values as  ISO-3166-2 codes, to keep consistent with the `location` field values found on the `posts` table (refs https://github.com/DoSomething/rogue/pull/1079#issuecomment-666484121).
It also modifies the `updateOrCreateActionStats` method introduced in #1079 to write a post group's location to the related action stat, and adds support to filter to the `action_stats` table by `location`. This will be used to display leaderboards by US state.
```
// http://rogue.test/api/v3/action-stats?filter[location]=US-TX
{
"data": [
{
"id": 72,
"action_id": 11,
"school_id": "4809500",
"location": "US-TX",
"impact": 7,
"created_at": …
```
=> Adds location field to Group and ActionStat resources

app/Http/Controllers/ActionStatsController.php, app/Http/Transformers/ActionStatTransformer.php, app/Models/ActionStat.php
This pull request adds support for using `?cursor[after]=` to paginate through action stats, following #976 by example.
👀 
```
// http://rogue.test/api/v3/action-stats?cursor[after]=NjA=
{
"data": [
{
"id": 61,
"action_id": 72,
"school_id": "4825422",
"location": null,
"impact": 46,
"created_at": "2020-06-25T21:22:31+00:00",
"updated_at": "2020-06-25T21:22:31+00:00",
"cursor": "NjE="
},
{
"id": 62,
"action_id": 72,
"school_id": "3401166",
"location": null,
"impact": 19,
"created_at": "2020-06-25T21:22:31+00:00",
"updated_at": "2020-06-25T21:22:31+00:00",
"cursor": "NjI="
},
...
```
We'll eventually use this to allow users to incrementally load a full list of action stats for school leaderboards of voter registration posts.
References [Pivotal …
=> Adds cursor support to action stats index

database/factories/ModelFactory.php, database/seeds/DatabaseSeeder.php
This pull request simplifies seeding the `action_stats` table, starting by reverting the original code added in #984 to do this.
In #1079, we added a `PostObserver` that calculates stats upon creating or updating a post. This PR changes the seeder to create approved photo posts for groups that have schools, seeding the `action_stats` table with what we'd expect per the seeded `posts`.
👀 
🧑‍🌾 
=> Fixes DatabaseSeeder ActionStats

resources/assets/Application.js, resources/assets/components/ActionStatsTable.js, resources/assets/pages/ActionStatIndex.js, resources/assets/pages/ShowAction.js, resources/assets/pages/ShowSchool.js, routes/web.php
This pull request adds an `ActionStatTable` component and fixes the TODOs of paginating through action stats, now that we've added support in https://github.com/DoSomething/graphql/pull/264. 
It also adds a general `/action-stats` index web view, to help spot check that action stats get created and updated correctly (refs #1084).
👀 
TODO: Add an `orderBy` prop to sort the Action page stats by descending impact.
=> Adds ActionStatsTable component

resources/views/forms/select.blade.php
This pull request fixes a quick bug that is caused due to having missed replacing the `or` operator in a select form input to use the `??` instead. The `or` operator was removed from Laravel in favor of the `??` null coalescing operator which essentially does the same behavior but is native to PHP.
👀 
This was causing a bug on a form in the admin side of things on Rogue.
References [Pivotal #172383643](https://www.pivotaltracker.com/story/show/172383643).
=> Removing deprecated or operator.

app/Http/Controllers/ActionStatsController.php
This pull request fixes a `GET /api/v3/action-stats` request --  there was an astray `array_get` 🐛  that likely got lost in the mix of rebasing for the Laravel update in #1080. 
👀 
🐞 
#1080
=> Fix GET /api/v3/action-stats

app/Http/Transformers/GroupTypeTransformer.php, app/Models/GroupType.php, database/migrations/2020_08_06_000000_add_filter_by_location_to_group_types_table.php, docs/endpoints/group-types.md
This pull request adds a `filter_by_location` field, to eventually deprecate the `filter_by_state` field once it's added into GraphQL and Phoenix/Rogue pull from it. Refs renaming the Group `state` field to `location` conversation from  #1079 and #1082.
👀 
🪔 
=> Adds filter_by_location field to GroupType resource

app/Console/Commands/ImportNasspGroupsCommand.php, app/Console/Commands/ImportRhodeIslandGroupsCommand.php, database/factories/ModelFactory.php, database/migrations/2020_08_06_000100_alter_unique_indexes_on_groups_table.php, resources/assets/components/ActionStatsTable.js, resources/assets/components/GroupsTable.js, resources/assets/helpers.js, resources/assets/pages/ActionStatIndex.js, resources/assets/pages/ShowAction.js, resources/assets/pages/ShowGroupType.js, tests/Console/ImportNasspGroupsCommandTest.php, tests/Console/ImportRhodeIslandGroupsCommandTest.php
This pull request adds a filter to the `ActionStatsTable` component to allow filtering by `location`, and modifies the `GroupsTable` component to filter by `location` (instead of `state` -- which we'll soon drop as a column completely once we make the same corresponding changes in the [Phoenix Group Finder](https://github.com/DoSomething/phoenix-next/blob/5673c030db0525da0ee0639ad037bc7b5a83955e/resources/assets/components/CampaignSignupForm/GroupFinder/GroupFinder.js#L15)).
It also adds some cleanup around migrating from the `state` to `location` field:
* Modifies the NASSP and RIDE imports to populate `location` and `filter_by_location` instead of `state` and `filter_by_state`, should we ever need to run those imports again (I do often for database seeding / local testing)
* Modifies …
=> Filter Action Stats, Groups by location

.circleci/config.yml, app/Http/Controllers/EventsController.php, app/Models/Signup.php, composer.json, composer.lock
This pull request updates Rogue to use PHP 7.4. This allows us to use new language features, like arrow functions, and prepares us for the end of PHP 7.3's [active support window](https://www.php.net/supported-versions.php).
I've split this work into separate commits for each change & bug fix.
Here's the high-level [PHP 7.4 release announcement](https://www.php.net/releases/7_4_0.php) and [migration guide](https://www.php.net/manual/en/migration74.php).
References [Pivotal #173629223](https://www.pivotaltracker.com/story/show/173629223).
=> Update Rogue to PHP 7.4.

app/Models/Post.php
This pull request fixes an exception thrown if a campaign doesn't have a website configured:
```
production.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /app/app/Models/Post.php:353)
```
This is happening because the campaign these posts are created for doesn't have a website, and so it's trying to read a property `'title'` and `'slug'` off of a null response from `campaignWebsiteByCampaignId`.
👀
This is due to the [new way PHP 7.4 treats array-access on null](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access).
References [Pivotal #173629223](https://www.pivotaltracker.com/story/show/173629223).
=> Fixes exception if campaign doens't have a website.

app/Models/Signup.php
This pull request follows up on #1096 with another two spots where a GraphQL query may return null (and thus trying to access one of the properties from the query response would [now explode](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access)).
👀
❗
References [Pivotal #173629223](https://www.pivotaltracker.com/story/show/173629223).
=> Fix two more places where a query may return null.

resources/assets/pages/ShowGroup.js, resources/views/groups/create.blade.php, resources/views/groups/edit.blade.php
This pull request makes the `location` field editable instead of `state` on the Group create/edit form, since our Group Finder now queries by `location` instead of `state` as of https://github.com/DoSomething/phoenix-next/pull/2324.
I didn't realize admins are adding new groups, but they do. And as of  https://github.com/DoSomething/phoenix-next/pull/2324., those new groups won't show up in the group finder because we need `location` populated instead of `state` (which is so close to being deprecated/dropped)
👀 
📬 
References [Slack thread](https://dosomething.slack.com/archives/CTVPG6L4R/p1597349671361400), [#174327055](https://www.pivotaltracker.com/n/projects/2417735/stories/174327055)
=> Change Group page/form to view/edit location instead of state

app/Console/Commands/SetupCommand.php
This pull request updates the `SetupCommand()` to fix an issue I ran into when running `php artisan rogue:setup` after a complete reset of my Homestead.
Seems like the signature of the `runCommand()` has changed and now requires passing a class that implements the `OutputInterface` as the third argument.
I figured the simplest way to resolve this would be to use the `call()` command before hand and precede it with calling the `line()` command to write the message to the console.
👀 
It may be that we'll need to update the other projects that have their own Artisan `setup` command, since they likely also call the `runCommand()` as well.
🌵
=> Fixing setup command.

composer.json, composer.lock
This pull request adds Faker package out of `require-dev` and into the main `require` within our `composer.json`, so that we're able to run the `DatabaseSeeder` on our dev Rogue DB. This makes will make it possible for staff to fully test an `ActionStatsBlock` in Phoenix, because the current production DB doesn't have enough action stats to paginate through. 
👀 
We could revert this PR once the dev DB is seeded with action stats, if we'd prefer to keep production un-Faker-able.
=> Moves faker out of dev dependencies

app/Http/Controllers/Web/ClubsController.php, database/factories/ModelFactory.php, resources/views/clubs/create.blade.php, resources/views/clubs/edit.blade.php, routes/web.php, tests/Http/Web/ClubTest.php
This pull request adds create/edit forms for clubs for admins and staff.
commit-by-commit if helpful. I tried to follow by example from existing work, but 👀  if I missed anything!
We still don't have the show/index pages ([#174301487](https://www.pivotaltracker.com/story/show/174301487)) since we postponed that work to post-launch. So we simply redirect to the edit page with a flash message upon successful form submission.
We don't seem to have a consistent standard for testing these so I tried to copy from the tests in [`GroupTest`](https://github.com/DoSomething/rogue/blob/0974d680e5c89e44cd805a61d22b8a01514e0060/tests/Http/Web/GroupTest.php#L1) & [`PostTest`](https://github.com/DoSomething/rogue/blob/0974d680e5c89e44cd805a61d22b8a01514e0060/tests/Http/PostTest.php#L1) for a relatively …
=> Clubs Create & Edit Web Forms 

app/Http/Controllers/ClubsController.php, app/Http/Transformers/ClubTransformer.php, docs/endpoints/README.md, docs/endpoints/clubs.md, routes/api.php, tests/Http/ClubTest.php
This pull request adds basic index & show API endpoints for Clubs.
👀 This should be pretty straightforward!
This is following by example from our other resources particularly Groups (https://github.com/DoSomething/rogue/pull/1031). We'll need a `name` regex filter a la [groups](https://github.com/DoSomething/rogue/blob/b691ac2bbd2c95306ddd3041ff296252845a0617/app/Http/Controllers/GroupsController.php#L37-L39). I'll save that for a follow-up PR.
Eep! the [failing build](https://app.circleci.com/pipelines/github/DoSomething/rogue/914/workflows/5bedfe6c-9d36-44fb-ae43-7b604a6d0f6f/jobs/998) is because we're using the Clubs factory in our tests that we only define in #1107 so this will only pass pending merging that PR and rebasing.
References [Pivotal …
=> Clubs API Endpoints

app/Http/Controllers/Web/GroupTypesController.php, app/Http/Transformers/GroupTransformer.php, app/Http/Transformers/GroupTypeTransformer.php, app/Models/Group.php, app/Models/GroupType.php, database/factories/ModelFactory.php, database/migrations/2020_08_25_000000_drop_state_from_groups_table.php, database/migrations/2020_08_25_000100_drop_filter_by_state_from_group_types_table.php, docs/endpoints/group-types.md, docs/endpoints/groups.md, resources/views/group-types/create.blade.php, resources/views/group-types/edit.blade.php, tests/Http/Web/GroupTypeTest.php
This pull request drops the respective fields from the `groups` and `group_types` tables, now that they've been deprecated by `location` and `filter_by_location` (refs https://github.com/DoSomething/graphql/pull/270)
👀 
🔥 
=> Drop deprecated state and filter_by_state fields

app/Http/Controllers/ClubsController.php, docs/endpoints/clubs.md, tests/Http/CampaignTest.php, tests/Http/ClubTest.php
This pull request allows us to filter Clubs by the `name` field via the `/clubs` index API endpoint. 
👀 
This follows https://github.com/DoSomething/rogue/pull/1048 by example since we're imitating this filter. 
I did deviate though in using the [SQL `'LIKE'` operator](https://www.w3schools.com/sql/sql_like.asp). The reason we didn't use `LIKE` for Groups was because of case-sensitivity (see https://github.com/DoSomething/rogue/pull/1048#discussion_r443850722), but I discovered that [we use](https://github.com/DoSomething/rogue/blob/45dbce64312e55f09b87e5395d34860d1291c687/config/database.php#L54) `utf8_unicode_ci` collation for our SQL database in Rogue which means we're automatically getting case insensitive querying! ([TIL](https://www.webucator.com/how-to/how-check-case-sensitivity-sql …
=> Add name filter to Clubs index

app/Http/Controllers/GroupsController.php, tests/Http/GroupTest.php
This pull request fixes the syntax errors that are thrown when a special character is included in the `name` filter of a Groups index query, with a big thanks to @mendelB for the insights in #1114  
👀 
🌵 
References [Pivotal #174472802](https://www.pivotaltracker.com/story/show/174472802).
=> Fixes Groups search by name

app/Console/Commands/ImportGroupsCommand.php, tests/Console/ImportGroupsCommandTest.php, tests/Console/example-groups.csv
This pull request modifies the `ImportGroupsCommand` to convert any uppercase city names to Title Case, e.g. ("San Francisco" instead of "SAN FRANCISCO")
:eyes:
Our source file for a new group type randomly contains uppercase city values, and it seemed easy enough to handle the cleaning up the data within the command.
References [Pivotal #174829345](https://www.pivotaltracker.com/story/show/174829345).
=> Adds formatting check to Group Import console command

app/Services/GraphQL.php
This pull request adds `apollographql-client-name` (per [Pivotal #174634307](https://www.pivotaltracker.com/story/show/174634307)) and `authorization` headers to our GraphQL client.
See below.
Per [Pivotal #174338924](https://www.pivotaltracker.com/story/show/174338924), we'll need to append a user's Club ID to their signups and posts if applicable. We'll need to check Northstar for this information. The `club_id` field is [gated](https://github.com/DoSomething/northstar/blob/e8032fdd7aa68a8504f54974a5801fa6a7a39534/app/Http/Transformers/UserTransformer.php#L68-L76) and thus wouldn't be accessible via the anonymous GraphQL queries we generally make from this application.
My first thought was to use our [`Registrar`](https://github.com/DoSomething/rogue/blob/d0ba62091d319e03670ea62cf5e9f0e3 …
=> Add authorization to GraphQL Client

.env.example, app/Observers/PostObserver.php, app/Observers/SignupObserver.php, app/Providers/AppServiceProvider.php, config/features.php, tests/Http/PostTest.php, tests/Http/SignupTest.php, tests/WithMocks.php
This pull request appends the user's `club_id` to their signups and posts. (Branching off of #1120).
commit-by-commit.
1. Is this implementation via a new `SignupObserver` sound?
2. Do you agree with the execution of the GraphQL query (colocated in the SignupObserver) and its mocks?
3. Is it safe to assume that we can simply grab the `club_id` from the post's signup instead of making the GraphQL query ourselves (e.g. what if the signup has no club_id erroneously, we then wouldn't attach a user's `club_id` to the signups posts! But I figured that edge case didn't warrant a separate GraphQL query).
4. Any concerns that making a GraphQL query while saving the signup will disrupt our traffic/bandwidth/devopswords?
So in our initial implementation of the GraphQL client, we discussed …
=> Add User's Club Id to Signups and Posts

resources/assets/pages/ShowSchool.js
This pull request updates the GraphQL query for a school to use `location` instead of the deleted `state` field. 
* 👀 
* Spot check a school page, e.g. http://rogue.test/schools/4809500
🙈 
References https://github.com/DoSomething/graphql/pull/270.
=> Fixes School page

app/Http/Controllers/ActionStatsController.php, tests/Http/ActionStatsTest.php
This pull request fixes a bug introduced in #1123: when additionally filtering by `location` as well as `group_type_id` (which can be done in the leaderboard by selecting a location), an error is thrown: ` Integrity constraint violation: 1052 Column 'location' in where clause is ambiguous`
#1123 joins the `action_stats` table on the `groups` table -- both tables have a `location` column. This PR manually constructs the filters in a `GET /action-stats` index query to specify the table name of any potentially ambigious columns we may be filtering by.
👀 
What I'm puzzled about is a related separate ambiguous error we're seeing in Slack:
```
production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select * from `action_stats` inner …
```
=> Fixes bug when filtering Action Stats by location

app/Jobs/Job.php, app/Jobs/Middleware/CustomerIoRateLimit.php, app/Jobs/RejectPost.php, app/Jobs/SendPostToCustomerIo.php, app/Jobs/SendReviewedPostToCustomerIo.php
This pull request updates Rogue to send `campaign_review` events directly to Customer.io (rather than routing them through Blink). I've created a [job middleware](https://laravel.com/docs/6.x/queues#job-middleware) to handle configuring this rate limiter since it's a little verbose & we do it for every Customer.io job. I've also cleaned up our job classes to extend the abstract `Job` class (where we add traits & defaults) so we don't have to do the same setup for every single job.
It may be easiest to review this commit-by-commit!
One more job after this & then I'm done! I'll also make similar cleanups in Northstar.
References [Pivotal #174827028](https://www.pivotaltracker.com/story/show/174827028).
=> Send 'campaign_review' events directly to Customer.io & clean up jobs.

app/Jobs/Middleware/CustomerIoRateLimit.php, app/Jobs/Middleware/GambitRateLimit.php, app/Jobs/SendSignupToCustomerIo.php, app/Jobs/SendSignupToGambit.php, app/Managers/SignupManager.php, app/Models/Group.php, app/Models/Post.php, app/Models/Signup.php, app/Services/Gambit.php, config/features.php, config/services.php, tests/Unit/Models/SignupModelTest.php, tests/WithMocks.php
This pull request updates Rogue to send signup events directly to Customer.io and Gambit, rather than routing this event through Blink. These API calls power email & SMS transactional messages when a user signs up for a campaign.
I've broken this into individual commits for each portion of this task.
This is blocked from merge/deploy until I make some some configuration changes to add Gambit environment variables & feature flag to each environment. I'm preparing that change now and will update this note when it's ready.
This reduces complexity and will help us save on Heroku costs in the future. 💰 
References [Pivotal #174827024](https://www.pivotaltracker.com/story/show/174827024).
=> Send signups directly to Customer.io & Gambit.

app/Services/Gambit.php
This pull request adds some error handling for the 422 errors we're getting on this endpoint:
```
Oct 08 11:39:12 dosomething-rogue app/queue.1: [2020-10-08 15:39:12] production.ERROR: Client error: `POST https://gambit-conversations-prod.herokuapp.com/api/v2/messages?origin=signup` resulted in a `422 Unprocessable Entity` response: 
```
These are thrown whenever a user signs up for a campaign, but _doesn't_ have a mobile on their profile. Since this is not a "real" error that should fail the job & be retried, we'll catch it here and only throw if it's another 4xx status.
👀
We'll probably get a quick spike of errors tomorrow AM unless I sneak in a deploy before then, but no harm done if so!
References [Pivotal #](https://www.pivotaltracker.com/story/show/174827024).
=> Silence 422 exceptions returned from this endpoint.

app/Services/Gambit.php
This pull request properly catches the 422's being thrown by Gambit here when a user without a mobile number signs up for a campaign. The previous fix in #1131 didn't work because the `$response` variable was not defined yet when Guzzle throws the exception, so instead you have to grab it from the exception itself.
For reference, here's [Guzzle's 'Exceptions' documentation](http://docs.guzzlephp.org/en/stable/quickstart.html#exceptions).
Third times the charm! I've hooked up my local to Gambit Staging & confirmed this fix actually works. 😅
References [Pivotal #174827024](https://www.pivotaltracker.com/story/show/174827024).
=> Properly catch the unexpected 422s here.

app/Models/Post.php, tests/Unit/Models/PostModelTest.php
This pull request fixes an issue where `$campaign` not existing causes `implode` to pout when it's passed `null`. As a quick fix, we'll use the `?:` operator to pass an empty array in this scenario.
👀
This is happening because we're relying on the `optional()` helper's fallback behavior, and not the "empty" array provided by this field's accessor. (I also considered using a `$campaign ? … : null` ternary, but that made this take up multiple lines.)
References [Pivotal #175209573](https://www.pivotaltracker.com/story/show/175209573) and [this Slack thread](https://dosomething.slack.com/archives/CUQMTP0RM/p1602278321008400?thread_ts=1602278269.008300&cid=CUQMTP0RM).
=> Fix issue with 'campaign_cause' transformer.

app/Http/Controllers/ClubsController.php, app/Http/Transformers/ClubTransformer.php, app/Models/Club.php, docs/endpoints/clubs.md, tests/Http/ClubTest.php
This pull request adds cursor ('after') pagination to the Clubs API index endpoint.
Follows #1049 by example.
👀 
This will allow us to implement a web index page for clubs using cursor pagination via GraphQL as we've done for e.g. Groups in #1052 
References [Pivotal #174301487](https://www.pivotaltracker.com/story/show/174301487).
=> Clubs Cursor Pagination

docs/features/clubs.md, resources/assets/Application.js, resources/assets/components/CampaignsTable.js, resources/assets/components/ClubsTable.js, resources/assets/components/GroupsTable.js, resources/assets/components/utilities/ErrorBlock.js, resources/assets/pages/ClubIndex.js, resources/assets/pages/ShowClub.js, routes/web.php
This pull request adds index `/clubs` and show `/clubs/:id` pages for the Clubs resource via React.
https://github.com/DoSomething/rogue/commit/9bc1df30fd230fdfd633f18801561b0e23fe8e0a extracts a repeated bit of logic for error blocks into a new utility component.
I followed existing pages by example notably the [`CampaignsTable`](https://github.com/DoSomething/rogue/blob/863e71736c188c41c25cb2fbbc8c41b5e0747710/resources/assets/components/CampaignsTable.js), [`GroupsTable`](https://github.com/DoSomething/rogue/blob/863e71736c188c41c25cb2fbbc8c41b5e0747710/resources/assets/components/GroupsTable.js), [`GroupTypeIndex`](https://github.com/DoSomething/rogue/blob/863e71736c188c41c25cb2fbbc8c41b5e0747710/resources/assets/pages/GroupTypeIndex.js), and …
=> Add Clubs Index & Show Pages

resources/views/layouts/nav.blade.php
This pull request adds a link in the navigation bar to the new clubs page added in #1136 
👀 
https://www.pivotaltracker.com/story/show/174301487/comments/218827256
I suppose at some point it could be worth adding a dropdown or index page linking to the various resources available on Rogue that have no direct links as of now.
References [Pivotal #174301487](https://www.pivotaltracker.com/story/show/174301487).
=> Add Navigation Link to Clubs Page

resources/assets/components/ClubsTable.js
This pull request fixes the Club index table to render the Club's `leaderId` instead of the nested leader resource, if the resource is unavailable.
👀 
The leaderId is a required field and must be a valid Northstar ID. However 
1. We don't validate this against NS, it really only needs to be a valid Mongodb ID
2. The user can be deleted and we don't remove the leader id from the club
I noticed that the table was breaking on production since presumably we're being met by one of these scenarios.
I think this is edge-casey enough, for now, to simply safely render the leader ID instead. But perhaps we should think about adding clearing the Leader ID from the club if the user is deleted? And/or properly validate the Leader ID against Northstar?
References [Pivotal #]().
=> Render Club Leader ID Safely

app/Http/Controllers/ActionStatsController.php, app/Models/Traits/HasCursor.php, app/helpers.php, tests/Http/ActionStatsTest.php
This pull request fixes the ` Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous ` error that occurs if querying the `GET /action-stats` index endpoint with `filter[group_type_id]` and `cursor[after]` query parameters set, by specifying the table name of our base model in the `HasCursor` trait, per @DFurnes's helpful comment in https://github.com/DoSomething/rogue/pull/1125#issuecomment-702849789.
It also cleans up the `ActionStatsController` per https://github.com/DoSomething/rogue/pull/1125#discussion_r498941457, so any other endpoints that may end up joining on other tables won't suffer from the same ambiguous column errors.
👀 
Question for @DFurnes -- in https://github.com/DoSomething/rogue/pull/1125#issuecomment-702850642 you mention adding a simple test to …
=> Fix cursor pagination errors for Action Stats index endpoint

resources/assets/components/ClubsTable.js, resources/assets/pages/ShowClub.js
This pull request follows up #1138 to do the same for the Clubs show page. I... totally meant for this to be a follow-up and didn't just completely overlook this on the previous pass.
I also quickly fixed the Clubs Table where we were displaying the leader first name instead of the display name.
👀 
see #1138 
References [Pivotal #]().
=> Clubs Leader Patch v2

resources/assets/components/PostsTable.js, resources/assets/components/ReviewablePost.js, resources/assets/components/SignupsTable.js, resources/assets/pages/ShowSignup.js
This pull request surfaces the Club ID on Signup & Post index tables and individual views. Per https://github.com/DoSomething/graphql/pull/285 & https://github.com/DoSomething/graphql/pull/284
👀 
These tables are getting a lil crowded?
Admin convenience!
References [Pivotal #174934297](https://www.pivotaltracker.com/story/show/174934297).
📸 
- [Signup Table](https://user-images.githubusercontent.com/12417657/96305474-ecc45680-0fcb-11eb-97b3-cb109ca50ecc.png)
- [Signup view](https://user-images.githubusercontent.com/12417657/96305494-f352ce00-0fcb-11eb-8d9f-1611ab08eb50.png)
- [Post view](https://user-images.githubusercontent.com/12417657/96305546-10879c80-0fcc-11eb-9fa4-98780bc35d8b.png)
- [Post table](https://user-images.githubusercontent.com/12417657/96305565-17aeaa80-0fcc-11eb-8393-4b5d …
=> Display Club in Signup & Post Views & Tables

app/Services/Gambit.php
This pull request handles `400 Bad Request` errors from Gambit, which we've been seeing pile up in our "failed jobs" table and continually get retried every morning. Since these are all due to "not currently reachable" errors for users who can't receive SMS messages, there's no reason to mark these as failed jobs.
👀
See [recent Rogue errors](https://my.papertrailapp.com/groups/10447062/events?focus=1255803625465982976&q=%28sender%3Adosomething-rogue%20%28production.ERROR%20OR%20status%3D5%29%29%20%20OR%20%28sender%3Afastly%20status%3D5%20app%3Ddosomething-rogue%29) and [this Slack thread](https://dosomething.slack.com/archives/CUQMTP0RM/p1602598318001900).
References [Pivotal #175287738](https://www.pivotaltracker.com/story/show/175287738).
=> Handle undeliverable 'bad requests'.

app/Managers/PostManager.php, app/Managers/SignupManager.php, docs/endpoints/posts.md, docs/endpoints/signups.md
This pull request removes the unused `dont_send_to_blink` parameters from signup & post endpoints. These are no longer accurate (it should really be `dont_send_to_customer_io`), and [no longer used anywhere](https://github.com/search?q=org%3ADoSomething+dont_send_to_blink&type=code) (aside from a very old Ashes script).
If we need to exclude a set of posts from messaging in the future, we can do so with Customer.io trigger rules.
👀
Thanks @aaronschachter for flagging this in https://github.com/DoSomething/rogue/pull/1143#discussion_r510333090!
N/A
=> Remove unused 'dont_send_to_blink' parameters.

app/Models/Campaign.php, tests/Unit/Models/CampaignTest.php
This pull request adds a computed `has_website` attribute to the payload generated by the `toSearchableArray` method on Campaigns (for Algolia / Laravel Scout) so that we can filter for website campaigns via Algolia.
👀 
[Algolia specifies](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-null-or-missing-attributes/) two methods to filter by a missing/null attribute (which we're doing here -- a campaign with a null `campaign_contentful_id` is not a website campaign and vice versa).
The simpler of the two approaches seemed to be to simply add a computed attribute (the other method being to use a new `_tags` array for a built-in "faceted search"). And this is consistent with the existing `hasWebsite` filter [in …
=> Campaign 'Searchable' payload - Add has_website computed attribute for filtering

app/Models/Campaign.php, tests/Unit/Models/CampaignTest.php
This pull request adds a new `is_evergreen` computed boolean attribute to the Campaign `toSearchableArray` payload for Algolia/Scout determining if the campaign is evergreen i.e. has an end date.
Is this descriptive naming helpful or should this simply be called `has_end_date`?
I noticed a bug with the way we filter for open/closed campaigns [in GraphQL](https://github.com/DoSomething/graphql/blob/d57d4e6f08996b4614387fe2fff0438f408b678c/src/dataSources/Algolia.js#L49-L65) via Algolia.
Since the `end_date` [could be a `null` value](https://github.com/DoSomething/rogue/blob/5129bf34de477124a593c9a2e8fa561b3956e09b/app/Http/Controllers/Web/CampaignsController.php#L29), we're running a filter on a nullable field which will cause the filtering to fail.
Algolia [doesn't …
=> Campaign Algolia/Scout payload - add is_evergreen attribute

app/Models/Campaign.php
…ing/rogue/pull/1147#discussion_r526454442
This pull request follows up on #1147 & #1146 to formalize the two computed attributes we added for Algolia/Scout as attributes on all Campaigns per this feedback https://github.com/DoSomething/rogue/pull/1147#discussion_r526454442
👀 
This will allow us to utilize this logic consistently for Customer.io, or an HTTP transformer. 
I followed the steps outlined [here](https://laravel.com/docs/7.x/eloquent-mutators#accessors-and-mutators) and [here](https://laravel.com/docs/7.x/eloquent-serialization#appending-values-to-json) in the Laravel docs. 
Now we can simply include these attributes in our [list of attributes](https://github.com/DoSomething/rogue/blob/5bab690de97d73211bd0819636dc1a0f8ff81a60/app/Models/Campaign.php#L358-L372) we pull from the …
=> Formalize Computed Algolia Campaign Attributes

app/Models/Campaign.php, tests/Unit/Models/CampaignTest.php
This pull request limits the amount of actions sent to the Algolia/Scout payload for indexing to 20. This addresses an edge case, where some of our campaigns exceed the permitted entry size limit in Algolia due to an overwhelming amount of associated actions.
Does this solution sound good for now? I opted to apply a global rule instead of addressing the two faulty campaigns specifically since it felt a bit cleaner and technically, could prevent this bug in the future.
The full context is in the thread of the attached Pivotal Story.
TL;DR:
We noticed the Laravel Scout import of our Campaigns into Algolia would fail after the first batch ("chunk") of 500 campaigns. Turns out the second batch would fail due to an entry size exceeding the size limit permitted for our Algolia plan -- …
=> Campaign Algolia/Scout Payload - Limit the amount of Actions indexed

app/Models/Campaign.php, tests/Unit/Models/CampaignTest.php
This pull request adds a new computed `is_group_campaign` attribute to the Campaign model and sends this attribute along to Algolia.
👀 
This will allow us to filter for group / non-group campaigns via GraphQL / the Algolia API
References [Pivotal #175358477](https://www.pivotaltracker.com/story/show/175358477).
=> Algolia Campaign is_group_campaign Computed Attribute

resources/views/actions/create.blade.php, resources/views/actions/edit.blade.php
This pull request removes the restriction from the volunteer credits option on an action for non-admin users! We also add a link to documentation that explains when the volunteer credit should be checked.
👀 
Now that we're doing a full launch of the volunteer credit program, we want to allow access to anyone who needs to create the appropriate labels for new actions and campaigns.
References [Pivotal #173898146](https://www.pivotaltracker.com/story/show/173898146).
=> Volunteer Credits Access on Actions

resources/assets/components/ReviewablePost.js
This pull request displays the new Post **Hours Spent** field for admins trhough the `ReviewablePost` component.
👀 
Staff will be able to see and evaluate this field when reviewing posts.
References [Pivotal #176369788](https://www.pivotaltracker.com/story/show/176369788).
=> Display Post Hours Spent Field for Admins

app/Models/Post.php
So we don't send over 0.0 for null values
This pull request updates the `hours_spent` field in the customer.io payload on Posts to only cast itself as a `float` _if_ the value exists. 
👀 
A quick addendum to #1156 so we don't send over `0.0` for `null` values.
References [Pivotal #176369835](https://www.pivotaltracker.com/story/show/176369835).
=> Update Post Hours Spent Customer.io Value

composer.json
This pull request adds the [gettext](https://www.php.net/manual/en/intro.gettext.php) PHP extension. This should address the [following errors](https://my.papertrailapp.com/groups/10447062/events?q=%28sender%3Adosomething-rogue+%28production.ERROR+OR+status%3D5%29%29++OR+%28sender%3Afastly+status%3D5+app%3Ddosomething-rogue%29) we're seeing on Rogue since the latest deploy:
```
[15-Jan-2021 16:26:25 UTC] [2021-01-15 16:26:25] production.ERROR: Call to undefined function bindtextdomain() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function bindtextdomain() at /app/vendor/sokil/php-isocodes/src/TranslationDriver/GettextExtensionDriver.php:12) 
```
See Heroku's [PHP Extension …
=> Add 'gettext' extension.

app/Console/Commands/BackfillHoursSpentOnPosts.php, tests/Console/BackfillHoursSpentOnPostsTest.php
This pull request adds a console command to backfill older posts with the informally stored `"hours"` field in the `details` over to the new formal `hours_spent` column.
👀 
I figured the `LIKE %hours%` was an easy way to filter for this one. We use some logic to ensure we're updating correctly on the `hours` field despite the fuzziness of this filter. This worked well when I queried against the QA database. Some other results were returned (like some "email" field with "hours" in it), but these are filtered away in the command logic.
We first started informally storing the "Volunteer Hours" Photo RB field in the Post details to enable shipping this feature before the new year https://github.com/DoSomething/phoenix-next/pull/2471. We've started storing to our new `hours_spent` field #1154, …
=> Command to backfill hours_spent on posts

resources/assets/helpers.js
This pull request adds a new `unrealistic-hours` tag for posts.
👀 
We've added the new Hours Spent field on Posts #1154, #1155. We've seen some unrealistic values being reported by members. This gives admins the opportunity to tag posts rejected for this reason. (And ultimately will allow us to inform the user with the context for the rejection via sending these tags to customer.io)
References [Pivotal #176421331](https://www.pivotaltracker.com/story/show/176421331).
=> Add Unrealistic Hours Tag for Posts
