.styleci.yml
server.php

Add style ci

---

Capfile
composer.json
composer.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
lib/capistrano/tasks/laravel.rake

I've added the appropriate Capistrano files to enable deployment of this app via Jenkins
Use Jenkins to do a deployment - https://jenkins.dosomething.org/job/Rogue%20Deployment/
what else?
Fixes https://github.com/DoSomething/devops/issues/154
The deployment currently only deploys `rogue-capify` for the moment. As soon as this is tested and merged in, any branch can be deployed.

Rogue capify

---

composer.json
composer.lock
config/app.php
config/aws.php
config/filesystems.php
config/laravel-backup.php
config/slack.php

I've added the [Laravel Backups package](https://docs.spatie.be/laravel-backup/v3/introduction) and its dependencies (AWS, S3, Slack notifications) so that we can use `php artisan` commands to more easily backup the database and files from the Rogue app. This is a proof of concept, and I'd like to eventually put these packages into each Laravel app that we currently have and any future ones.  It's currently set up to backup both locally and to send the backups to s3.  
At the moment, the settings will put a notification in the Slack #devops room when the backup has failed and when an unhealthy backup is found. We can add additional notifications for positive outcomes in the future if desired. By adding `slack` in the notifications events, you can test out the Slack notification for …

Laravel backups

---

.env.example

Updates the .env.example file to accurately represent what needs to be configured for app to work.
Add new values in .env file, run `phpunit` and make sure all tests pass.
Refs updates made in #25

updates .env.example

---

app/Jobs/SendReportbackToPhoenix.php
app/Services/ReportbackService.php

Made changes I missed in this [PR](https://github.com/DoSomething/rogue/pull/35#discussion-diff-78449531) 
Same as how to test in #35 
Fixes (see above)

gets rid of extra code

---

tests/ReportbackApiTest.php
tests/TestCase.php

Added 4 new tests!
- `testPostingReportbackWithNormalOldEmoji`
- `testPostingReportbackWithNormalNewEmoji`
- `testPostingReportbackWithEncodedOldEmoji`
- `testPostingReportbackWithEncodedNewEmoji`
Also added some helper methods in `TestCase.php` in order to condense the tests that exist and make writing future ones easier. These were incorporated into the tests that already existed as well.
Make sure I did the encoded emoji correctly please! I followed the same style to test submitting a reportback as happens in `testCreatingNewReportback` which I think should be what we want here.
Also make sure when I condensed the existing tests I didn't inadvertently change what they are testing.
no issue created as of now

tests for submitting reportbacks with emojis

---

app/Services/Phoenix.php
composer.json
composer.lock
config/app.php
config/services.php

Updates Rogue to use the latest Gateway package. 
👀 
To get this update after pulling, make sure to run `composer update` on your local. 
None 
cc: @katiecrane

updates to use latest Gateway package

---

issue_template.md

Adds the issue template from phoenix so we can write better issues. We can always update this, but I find it helpful.

issue_template.md

---

app/Http/Controllers/Auth/AuthController.php
app/Http/Controllers/ReportbacksController.php
app/Http/Controllers/UsersController.php
app/Http/Kernel.php
app/Http/Middleware/Authenticate.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Http/routes.php
app/Models/User.php
config/auth.php
config/services.php
database/factories/ModelFactory.php
database/migrations/2016_10_13_170448_update_users_table_for_northstar_users.php
resources/views/layouts/master.blade.php
resources/views/layouts/nav.blade.php
resources/views/pages/home.blade.php
resources/views/reportbacks/index.blade.php
tests/UserTest.php

Adds login functionality to Rogue through Gateway which authenticates users. Users that login are stored in the `users` table with a role. I set up so middleware that looks for `admin` and `staff` roles on routes.
* Update the user table to remove unused columns since we are authenticating in Northstar.
* Note: I left the `id` field in the user table because Gateway was having issues creating a user without an `id` column on the `users` table. This seems like a Laravel requirement even though all we care about is `northstar_id`
* Implements Gateway authentication in Rogue
* Defines middleware
if you pull down rogue and either have it point to northstar-qa you should be able to go through the login flow. 
1) I added some tests but I am having issues with how to test this stuff. Trying to …

User authentication

---

config/deploy.rb
lib/capistrano/tasks/laravel.rake

I've fixed the issue that was preventing `php artisan migrate` from running
This branch with the changes has been deployed to Rogue via Jenkins here - https://jenkins.dosomething.org/view/All/job/Rogue%20Deployment/38/console  
The `npm run build` task is temporarily commented out because it was causing the following error both in dev and production:  
Is `npm run build` still the correct command to run?  
```
> @ build /home/vagrant/sites/rogue
> npm run clean && npm run modernizr && NODE_ENV=production webpack
> @ clean /home/vagrant/sites/rogue
> rm -rf public/dist
> @ modernizr /home/vagrant/sites/rogue
> modernizr -c node_modules/@dosomething/forge/modernizr.json -d public/dist/modernizr.js
sh: 1: modernizr: not found
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" …
```

Add migrate

---

config/deploy/staging.rb
config/deploy/thor.rb

This PR adds Thor and QA/Staging as deploy targets. The Jenkins job has been updated with the appropriate vars. 
Try deploying on Jenkins
Fixes https://github.com/DoSomething/devops/issues/213

Adding QA and Thor deploy targets

---

app/Services/AWS.php
config/filesystems.php

Pull the S3 bucket from the config with `config('filesystems.disks.s3.bucket')` the same way we get the public url.
Just make sure it ends up building the correct url.
Fixes #63

pull s3 bucket from config

---

documentation/README.md

add a readme to the doc folder
👓 
it's much easier to read when it's all in one place
Fixes #🎨

add a readme to the documentation folder

---

.env.example
app/Http/Kernel.php
app/Http/Middleware/AuthenticateApi.php
app/Http/routes.php
documentation/README.md

it does the thing that's in the title
`POST` and `PUT` routes require an api key now. 
- can you send a `POST` request without keys? nope? GOOD 
I have still have to build the corresponding phoenix work for this
Fixes #https://trello.com/c/uJssCEtG/100-as-a-developer-i-want-to-create-an-authenticating-api-request-for-rogue-users-3-of-3

Added api auth to all post/put routes in the api.

---

app/Models/Event.php
app/Models/Events.php
app/Models/Photo.php
app/Models/Review.php
app/Models/Signup.php
composer.lock
database/migrations/2016_12_01_210658_create_events_table.php
database/migrations/2016_12_01_222513_create_signups_table.php
database/migrations/2016_12_01_224917_create_photos_table.php
database/migrations/2016_12_02_153413_create_reviews_table.php

Creates `events`, `signups`, `photos`, and `reviews` tables/models in rogue
Run migrations, get new tables? great.
[Tech spec](https://docs.google.com/document/d/1JMlUHbXMe3Iyeo-tl3oXUJ98J5kWpeNew8JFI9f_Wdg/edit)
Fixes #79

New rogue tables

---

app/Services/AWS.php
app/Services/ReportbackService.php

- allow `gif` file types
- add a param to the array to not force forwards back to phoenix
👀 
NO
Fixes #the issue from phoenix

Updates for migration script

---

app/Services/ReportbackService.php

update my previous PR that didn't check if things were set
👍 
I'm a dummy!
fixes #phoenix deploys (hopefully)

check if isset so it can still forward

---

config/app.php

Changes log from `single` to `daily` so we can check the Rogue logs by date and debug faster. 
👀 
Fixes #92

changes log from single to daily

---

readme.md

adds some much needed changes to this repository. 
:eagle: 
Fixes #💅

repos need emojis

---

documentation/README.md
documentation/endpoints/activity.md

- Added missing ``` in `activity.md`
- Added info. about `/activity` and `/signups` to the README file
:eyes:

Documentation Update 

---

app/Models/Event.php
app/Models/Post.php
app/Models/Reaction.php
app/Models/Review.php
app/Models/Signup.php
database/factories/ModelFactory.php
database/migrations/2017_03_20_201416_remove_event_id_from_posts_table.php
database/migrations/2017_03_20_202344_drop_event_id_from_reviews.php
database/migrations/2017_03_20_202631_drop_event_id_from_signups.php
database/migrations/2017_03_20_202956_add_id_columns_posts_and_reviews.php
database/migrations/2017_03_20_204228_drop_events_table.php
database/migrations/2017_03_20_205359_create_new_events_table_schema.php
database/seeds/ActivitySeeder.php
database/seeds/DatabaseSeeder.php

This PR updates the DB schema to so that we can set up a polymorphic relationship between events and other models. 
This change required a few steps:
* Remove the `event_id` from other tables as it had a foreign key restraint and these tables don't need to own events.
* Add unique identifiers to other tables that will be used as the `eventable_id` on the polymorphic columns on the event table
* Drop the old events table to make room for an entire new one. 
* create a new `events` table with polymorphic column to hold the relationships and a `content` column that will hold json strings of the content associated with the event. 
* define the relationship on the models. 
* update model factories and seeders.  
It should be safe to go commit by commit. 
⚠️  This breaks everything ⚠️ 
The PR …

Polymorphic events

---

app/Http/Controllers/Auth/AuthController.php
app/Http/Controllers/CampaignsController.php
app/Http/routes.php
resources/assets/app.js
resources/assets/components/CampaignInbox/index.js
resources/assets/components/InboxItem/index.js
resources/views/pages/campaign_inbox.blade.php

1. Creates a new route to hit the inbox for a given campaign run which hits `show` in `CampaignsController.php`. A query is run to get all the signups for that run that also have pending Posts. The relevant signups and their Posts and their Post's content is returned.
2. Passes that data to React which reformats it a bit and displays some relevant data!
🎨  🚨  At this stage this is going to be incomplete and have some hacky elements, but I'd love to set us up so that we don't just have to tear it all down later and do some crazy refactoring. I also have never done this before so I don't have the best idea of what that would entail, so feel free to leave lots of comments!
React is real cool.
Fixes #174

pending reportback page start

---

resources/assets/components/CampaignInbox/index.js
resources/assets/components/InboxItem/index.js

Styles everything closer to the wireframe. I'm not sure how to deal with matching the styles that are in the wireframe but not in Forge (gray buttons that turn either green or red on click, 3 columns, that box that the quantity is in) and so any ideas on that or if we shouldn't worry about it yet would be appreciated!
🎨 👀

Add buttons and style page more

---

resources/assets/components/InboxItem/index.js

Include the Post ID, Post source, and the time the Post was submitted with each item in the inbox.
👀 
We already had this information available to React.
Fixes #181

Inlude meta data on inbox page

---

documentation/endpoints/activity.md
documentation/endpoints/posts.md
documentation/endpoints/signups.md

Updates some of the response documentation to match what we are returning now that the db schema has changed.

Documentation updates

---

documentation/endpoints/reportbacks.md

Updated the docs for the work in https://github.com/DoSomething/rogue/pull/199
Is this what it does?

Documentation for the gallery endpoint

---

app/Http/Controllers/Api/ReportbackController.php
documentation/README.md

Added a check to see if there are filters at all before we check to see what they are. Updated the main documentation page to link to the documentation for this endpoint.
Will this work with filters and will no filters?
Fixes #202

In GET /reportbacks endpoint, check for filters before using

---

app/Http/Transformers/ReportbackTransformer.php

Adds kudos data as placeholder so JS works in Phoenix to power the gallery with Rogue! 
👀 
Need this extra data in order to merge https://github.com/DoSomething/phoenix/pull/7343

adds kudos data as placeholder

---

app/Http/Controllers/CampaignsController.php
resources/assets/components/InboxItem/index.js

Just a few changes to use the new and improved schema for the Inbox page so it doesn't error out.
Does this match up with the schema?
Made this a separate PR because I think it would be cool to merge it before Sprint Demos today so that we can show it live on staging!

Inbox page updates to new schema

---

database/migrations/2017_04_06_174417_drop_reportbacks_items.php

Trashes the tables we don't use any more!
Fixes #195 
.

Remove old reportback tables

---

resources/assets/app.scss
resources/assets/components/InboxItem/index.js

🎨 🎨 🎨 ❗️ 
This is what it looks like now:
1. There are two new button options to get the green and red buttons. 
2. There is an option to have a `container__block` be a third of the page instead of a half.
3. There is a fun new option called `quantity` that makes everything bold and purple and puts it in a purple box oOoOoOo
The other thing I did was to apply these new styles where they needed to be used.
🎨 👀 Did I CSS right?
Fixes #213

Get the reportback inbox closer to the mocks

---

resources/assets/components/InboxItem/index.js

On the inbox view, adds a link under the large thumbnail of a post to see the original photo
Fixes #223

Link to original photo on the inbox page

---

resources/assets/app.scss
resources/assets/components/InboxItem/index.js
resources/assets/components/StatusButton/index.js
resources/assets/components/StatusButton/status-button.scss

* Creates a new `StatusButton` component that can handle making status updates to the `InboxItem`
* Moves styling for this component into it's own partial.
Everything stays the same but starts to extract some of the logic. 
Right now, the `InboxItem` is in control of it's own local state and the status buttons will update that. 
If I am understanding this stuff correctly, when we move to redux we can start thinking about a global state for the app that has the status for each item on the page. The status buttons could just update the state of the item they are attached to. 
Fixes #222

Status button Component

---

app/Http/Controllers/CampaignsController.php
app/Services/CampaignService.php
resources/assets/components/CampaignInbox/index.js
resources/assets/components/InboxItem/index.js
resources/views/pages/campaign_inbox.blade.php

Adds campaign title to the header. Adds nouns and verbs after quantity for Posts.
1. Does everything look right on the page
2. Does the way that the campaign data gets passed around make sense?
I don't think so!
Fixes #227

Display campaign info on campaign inbox page

---

app/Http/Controllers/CampaignsController.php
app/Models/Post.php
app/Models/Signup.php
composer.json
composer.lock
config/app.php
config/tagging.php
database/migrations/2014_01_07_073615_create_tagged_table.php
database/migrations/2014_01_07_073615_create_tags_table.php
database/migrations/2016_06_29_073615_create_tag_groups_table.php
database/migrations/2016_06_29_073615_update_tags_table.php

This starts the backend work of setting up the tagging system in rogue. 
I decided, and this could be up for debate, to use a third party package: [Laravel Tagging](https://github.com/rtconner/laravel-tagging)
This could be overly complicated for what we need, but it is easy to implement and gives us the functionality we need out of the box. This also allows us the flexibility to how we want the administration experience of tags to be i.e. do we want a form to add more tags? Or just a field where admins can use custom tags?
I also really like it because we can define the tags on the frontend and tag items on the fly  for now without too much investment if the tagging experience isn't working out. 
Commit-by-commit .
Fixes #233

Laravel tagging

---

app/Http/Controllers/Api/ReportbackController.php
documentation/endpoints/reportbacks.md

Changes query to pull `accepted` posts instead of `approved` in the `GET /reportbacks` endpoint and updates documentation.
👀 
Needed for Rogue to power gallery work

pulls accepted posts instead of approved

---

tests/CampaignTest.php

Adds tests for the campaign overview page. 
pull down branch, run tests, things should pass. 
I messed up the other branch I was working on by committing a bunch of deleted debugbar files that had recently been ignored. So I just created this new branch with the changes I wanted to introduce. 
Fixes #228

Add campaigns tests

---

app/Http/Controllers/Api/ReviewsController.php
app/Http/Requests/ReviewsApiRequest.php
app/Http/routes.php
documentation/endpoints/reviews.md

1. Added a new route for this endpoint
2. Added a new controller for this endpoint (it is almost identical to [the web Reviews Controller](https://github.com/DoSomething/rogue/blob/master/app/Http/Controllers/ReviewsController.php))
Are there any parts here that are specific to the web controller and should not be in the API one? I've tested it and as far as I can tell everything is working properly.
In order to keep all data on posts up to date via the keeper upper, we also need to be able to update their statuses as they are reviewed.
Fixes #268

/reviews to be used by keeper upper

---

app/Http/Controllers/Api/ActivityController.php
app/Http/Transformers/PostTransformer.php

This pull request eager loads posts on the activity endpoint so that we don't end up with N+1 queries per request, since that is a lil' performance bummer.
👀
🥞
References #280.

Eager load posts on the activity endpoint.

---

package.json
resources/views/layouts/master.blade.php
webpack.config.js

This pull request is just a lil' chore – it updates Rogue to use Webpack 2 with our [updated config](https://github.com/DoSomething/webpack-config/releases/tag/v2.0.0). This gives us faster & smaller builds, more reliable source maps, and better cache busting in production.
👀
Heads up, you'll have to `npm install` before doing any client-side work for the first time.
🍃

Update to Webpack 2.

---

documentation/endpoints/reportbacks.md

Added documentation for the `/reportbacks` endpoint that I forgot to include in [this PR](https://github.com/DoSomething/rogue/pull/297)! 
👀

adds tagged array to reportbacks endpoint documentation

---

Procfile

I've added a Procfile to support Heroku deploys for Rogue
You can view the Rogue app on Heroku here - https://dashboard.heroku.com/pipelines/289a727e-1b35-401e-8c80-4b0bf6dd4a77
Adding this file in won't make any changes to any current deploys we have. I currently have https set up on Heroku, but that seems to break the CSS, so we can turn that off for the time being as well.

Initial procfile

---

app/Http/Transformers/ReportbackTransformer.php

One more thing! We need the `campaign_id` so we can add campaign object in Phoenix here.
👀
🐦
References DoSomething/phoenix#7456.

Return the campaign ID so we can fill it in on Phoenix.

---

documentation/endpoints/reportbacks.md

`/reportbacks` documentation was out of date - this PR updates it. 
👀

updates /reportbacks documentation

---

resources/assets/app.scss
resources/assets/components/InboxItem/index.js

A small visual tweak to the inbox, just some more padding and a border between the items.
Look at it and make sure I didn't fuck up anything.
Just trying to take a little pressure off the devs by fixing up a couple small visual quirks before launch!

Luke adds a border

---

app/Http/Controllers/CampaignsController.php
app/Services/Registrar.php
resources/assets/components/InboxItem/index.js

Ran into an issue on thor where I got a "Whoops something went wrong" error. Looks like the issue was that we were trying to find a user in northstar and they weren't found. This caused things to break because we had no safety checks and expected the user to always be there. 
This PR adds checks that we have a user. 
👀 
Not sure why we are sometimes not finding users in Northstar, should we look into this further?
Fixes 🐛

User not found bug

---

resources/assets/components/InboxItem/index.js

I made a dumb mistake on the frontend that isn't allow our npm build to complete. Looks like I have to wrap all user elements in a div in order for the conditional to work...
👀 
Going to create a card to refactor the InboxItem component. It is a bit hefty on the markup and I think we can break it up into smaller components.
Fixes 🐛

Wrap user info in div

---

app/Http/Controllers/Api/ReportbackController.php

This improves performance of this endpoint pretty dramatically on my local – from 10s to 0.6s when using the Thor database dump. The improvement comes from switching to using Eloquent's query builder rather than a plain database query (with joins and selects).
:eyes:
When using eager loading to get a relationship, Laravel makes a second query `select * from signups where signups.id in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)` to grab the related items (rather than a `join`). Since we were doing the same thing via the "raw" database query builder and a `join` (which could affect the number of results), it wasn't able to optimize this.
The original "pagination" query:
```sql
select count(*) as aggregate from `posts` inner join `signups` on `signups`.`id` = `posts`.`signup_id` …
```

Use Eloquent query to improve pagination performance.

---

app/Http/Controllers/Api/ReportbackController.php
app/Models/Post.php
app/Repositories/PostRepository.php
config/debugbar.php
database/migrations/2017_07_31_153255_add_campaign_id_to_posts.php
tests/CampaignTest.php
tests/PostApiTest.php

Ugh, here we are again – this pull request re-applies the changes from #334 and reverts the temporary changes made in #336. I think that handles it. 😤
Give it a glance, but there's no new changes being introduced here.
See #336 for details on why this went wrong the first time. 💣
References #325.

Re-re-re apply those `campaign_id` changes.

---

resources/assets/helpers.js

https://github.com/DoSomething/rogue/pull/337/files#r131244968
^meant to do this in this PR but the changes didn't get saved I guess
👀 
I done goofed

Re-arrange getEditedImageUrl

---

.styleci.yml
app/Models/Signup.php
app/Services/CampaignService.php
database/factories/ModelFactory.php
resources/views/pages/campaign_overview.blade.php
tests/Http/Api/ActivityApiTest.php
tests/Http/Api/PostApiTest.php
tests/Http/Api/ReactionsApiTest.php
tests/Http/Api/SignupApiTest.php
tests/Http/CampaignTest.php
tests/Http/PostTest.php
tests/Http/ReviewsTest.php
tests/Http/TagsTest.php
tests/Http/UserTest.php
tests/TestCase.php
wercker.yml

This pull request adds some useful test helpers & reformats tests a bit for readability.
Here's some highlights:
🔏 Adds an `actingAsAdmin` helper since this is a really common scenario. ae72f2f
🗑 Extracts a `seeSoftDeletedRecord` helper from the existing assertions in the tests. 27910c1
⏱ Adds a `mockTime` helper which allows us to manipulate the current time for tests without dropping `sleep()` calls and actually slowing things down. c702559
🏭 Adds some model state factories (for admin users & accepted/rejected posts). f29a85a, 011df7e
A few fixes to broken tests:
📊 Fixed `getPostTotals` to send expected parameter and assert against expected return value.  I think this just hadn't been updated when that method was changed at some point. 0ad5178
🔒 Updated the homepage test to not …

Add some useful test helpers & consistently format tests.

---

app/Exceptions/Handler.php

Adds `PRODUCTION_ERROR_MESSAGE` to Handler.php 
👀

adds PRODUCTION_ERROR_MESSAGE

---

app/Http/Controllers/UsersController.php
app/Http/routes.php
app/Services/Registrar.php
resources/assets/app.js
resources/assets/components/UserOverview/index.js
resources/assets/helpers.js
resources/views/layouts/nav.blade.php
resources/views/search/search.blade.php
resources/views/users/index.blade.php
resources/views/users/show.blade.php

Going to start splitting up user search into different PRs. This PR just implements basic user-search functionality and takes you to a user page that will eventually list out the campaigns that the user is signed up for. 
The search functionality is ported over from aurora/gladiator. Nothing super fancy or react-heavy happening here, we just make a call to Northstar to find the user based on the given input. Also note, this doesn't handle multiple user results well at all. So I will make a note to tackle that separately.
A gif of it: 
I think you can go commit-by-commit but the order might feel a little off. The big things to note are new routes to direct folks to the right pages, new react components to handle the page display, and some little helpers to display things nicely.
Getting a …

Part 1: User search

---

app/Http/Controllers/CampaignsController.php

Campaign inbox page is broken on Thor because it can't find the user. This add a check to see if the user exists first so it doesn't error out anymore. 
👀 
@DFurnes and I chatted and we're thinking it might be just because the environments weren't refreshed at the same time.

first checks if user exists

---

resources/assets/components/InboxItem/index.js

Removes detail layer when grabbing post that was removed from [this PR](https://github.com/DoSomething/rogue/pull/348). 
You should now be able to review a post. 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/150263615

fixes bug for reviewing posts

---

resources/assets/components/InboxItem/index.js
resources/assets/helpers.js

- Fixes bug to look for caption when a caption doesn't exist. 
- Adds helper method to first check if a caption exists and if not, sets caption to be `null`.
👀

adds displayCaption helper

---

app/Exceptions/Handler.php
app/Http/Controllers/Controller.php
app/Http/Kernel.php
app/Models/User.php
app/Providers/AuthServiceProvider.php
app/Providers/BroadcastServiceProvider.php
app/Providers/EventServiceProvider.php
app/Providers/RouteServiceProvider.php
app/Services/CampaignService.php
app/Services/Phoenix.php
app/Services/Registrar.php
composer.json
composer.lock
config/app.php
config/broadcasting.php
config/queue.php

This pull request updates Rogue to use Laravel 5.3, following the steps in the [Upgrade Guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0).
👀 ➕🚥 
I decided to tackle this because Laravel 5.3 handles multiple guards a lot more gracefully, which is helpful for the Northstar authentication work, and because we should really do this anyways! 😄 
[#150310367](https://www.pivotaltracker.com/story/show/150310367)

Update to Laravel 5.3.

---

app/Http/Controllers/Api/ReportbackController.php
app/Models/Post.php
tests/Http/Api/ReportbackApiTest.php
tests/Http/TagsTest.php

- Added the `withoutTag` scope to Posts. It accepts on parameter (a tag slug) and your query will not include Posts that have that tag.
- Very basic test of `/reportbacks`
- Added a tag test to make sure the `withoutTag` scope works
Will these tests pass on Thor?
Last bit of tagging cleanup!
:cowboy_hat_face:

Reportback test

---

documentation/README.md
package.json
resources/assets/components/CampaignSingle/index.js
resources/assets/components/PagingButtons/index.js

Fixes pagination bug on campaign single view page. Now, when you click the "next >" or "< previous" buttons, they load the posts as expected instead of rendering the json from the API. 
BONUS: fixes formatting on README page. 
Go to the campaign single view page and click on next and previous buttons and make sure it works as expected. 
This will only work and can't be merged until the gateway-js fix in [this PR](https://github.com/DoSomething/gateway-js/pull/12). 
After this is merged, we'll want to update our gateway-js `package.json` version to `1.1.4` and run an `npm install`. (In your Rogue directory, `vi package.json`, update the version, and then run `npm install`). 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/150491403

Pagination on Campaign Single View 

---

package.json

Updates gateway-js version to `v1.1.5` since there was a bug in `v1.1.4` (thanks @weerd !) 
👀 
This should hopefully get [pagination](https://github.com/DoSomething/rogue/pull/387) to work!

updates gateway-js version

---

app/Http/Controllers/Traits/PostRequests.php
app/Models/Post.php
composer.lock
documentation/endpoints/posts.md
resources/assets/components/CampaignSingle/index.js
resources/assets/components/PostFilter/index.js

This PR allows adds the `filter[tag]=[tag_slug]` to query the `/posts` endpoint by a certain tag. 
With this, we can now filter posts by a specific tag. 
On the campaign single view page, try to filter by a tag! Make sure the responses are what you expect (posts with that specific tag). 
Fixes https://www.pivotaltracker.com/n/projects/2019429

Filter posts by tag

---

resources/assets/components/CampaignInbox/index.js
resources/assets/components/CampaignSingle/index.js

Looks like I might have broken deletion a little when I did some refactoring. This fixes it by grabbing the delete method correctly. 
👀

Fix deleting posts

---

app/Http/Controllers/CampaignsController.php
resources/assets/components/CampaignInbox/index.js
resources/assets/components/CampaignSingle/index.js
resources/assets/components/WithReviewing/index.js
resources/assets/utilities/MountContainer.js
resources/views/pages/campaign_inbox.blade.php
resources/views/pages/campaign_single.blade.php

Refactors both the `CampaignInbox` and `CampaignSingle` components to use a new `withReviewing()` [Higher Order Component (HoC)](https://facebook.github.io/react/docs/higher-order-components.html).
The `withReviewing()` component is basically a function that takes in another component and renders it on the page. But what this allows us to do is to set state for the app in this HoC and define the functions that will manipulate the state in it. We can then pass it down to the children components. So it allows us to share a lot of the functionality between components that do reviewing. 
The `withReviewing` HoC basically just loads in a set of posts and allows you to review them. When filtering or paginating, we just give it a new set of posts to work with. 
So now when we load one of these …

Reviewing HoC

---

package.json
test.js
wercker.yml

- Adds Jest and Babel Jest to Rogue
- Sets up a test to make sure it is properly set up. 
👀  and run `npm test`. Tests should work and pass: 
Fixes https://www.pivotaltracker.com/n/projects/2019429/stories/150971771

Adds Jest to Rogue

---

composer.lock
resources/assets/components/WithReviewing/index.js

Uses the web route `/posts` to grab posts on the frontend because that request would be authenticated through the session and able to grab more user info then we are able to by making the direct unauthenticated request to northstar.
👀  You should be able to see user info on posts now. 
Fixes [#151024546](https://www.pivotaltracker.com/story/show/151024546)

User info bug

---

.env.example

Updates `.env-example` with an example `APP_URL` setting so it is clear that this needs to be set. 
👀 
I am using `http://rogue.app` as the example to be consistent with Homestead documentation, but since this is based largely on how the user configures their environment we could do something like `APP_URL=YourLocalApp.url`
No ticket, but will help with an easier setup process.

Update APP_URL example

---

package.json
resources/assets/_mocks_/fileMock.js
resources/assets/app.js
resources/assets/components/MultiValueFilter/__snapshots__/test.js.snap
resources/assets/components/MultiValueFilter/index.js
resources/assets/components/MultiValueFilter/test.js

- Writes a snapshot test for the `MultiValueFilter` component to make sure the front end renders what we expect. 
- Writes a test to make sure the button becomes active when clicked. 
- Run `npm test` and all tests should pass!
Writes `MultiValueFilter` test in [this Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/150341644).

MultiValueFilter Jest Tests

---

resources/assets/components/MultiValueFilter/test.js
resources/assets/components/ReviewBlock/__snapshots__/test.js.snap
resources/assets/components/ReviewBlock/test.js
resources/assets/components/StatusButton/index.js
resources/assets/components/StatusButton/status-button.scss

Adds Jest tests for the `ReviewBlock` component: 
- Snapshot test to make sure the review block renders "Accept", "Reject", and "Delete" buttons. 
- Snapshot test to make sure the review block renders the Tag buttons for an accepted post.
- Test to make sure that "Accept" button is active when clicked. 
- Test to make sure that "Reject" button is active when clicked. 
- Test to makes ure that tag buttons are active when clicked. 
- Updates button classes to make more sense (i.e. instead of `-accepted accepted` it is now `-accepted is-selected`). Also consolidates some repeptitive css code into one class. 
Make sure all tests are passing and that the login in the tests make sense! 
Fixes `ReviewBlock` tests in https://www.pivotaltracker.com/n/projects/2019429/stories/150341644

ReviewBlock Jest tests

---

resources/assets/components/Users/UserInformation.js

I introduced a bug in my last PR where I wasn't checking if the user object was empty properly. 
I was using `length` to check for emptiness but `user` is an object not an array. 
This should update that and fix issues of us seeing "User Not Found" everywhere 😬 
👀 
Fixes 🐛

Check for empty user properly

---

app/Http/Controllers/Traits/TransformsRequests.php
resources/assets/components/SignupCard/index.js

Fixes two issues related to updates made to the `/activity` endpoint and to showing campaign run information on signup cards. 
* The `/activity` endpoint was updated to use fractal's collection class as `FractalCollection` but I did not update how we were instantiating that class so it took into account the new class name. Not sure how this worked at all in my testing. 
* We were unable to render some `SignupCard`s because there are cases were we can not grab the campaign information. So we need to make sure we have a `campaign` object before trying to use any of it's expected values. 
Go to a user page, and it should load. 
Fixes https://www.pivotaltracker.com/story/show/151604916

User page error

---

app/Services/ExportService.php

Before we add all the actual data to the exported CSV file, we stick in a row with the column headers so everyone knows what all these numbers are!
The headers:
`Campaign ID | Campaign Run ID | Northstar ID | First Name | Email | Mobile | Age`
Do these titles make sense?
[Pivotal card](https://www.pivotaltracker.com/n/projects/2019429/stories/151763613)

Add column titles to export csv

---

app/Repositories/PostRepository.php
app/Services/PostService.php

- Always return a signup when updating a signup or creating another post for a signup so it is consistent. 
👀 
Fixes this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151852854)

Always return signup when updating a signup or creating another post for a signup

---

package-lock.json
package.json
resources/assets/components/ReviewBlock/__snapshots__/test.js.snap
resources/assets/components/ReviewBlock/index.js
resources/assets/components/StatusButton/index.js
resources/assets/components/WithReviewing/index.js

Makes it look like this! I copied how we do this for Tags!
Does this look okay for now? Any JS edits?
I haven't yet figured out how to fix the buttons changing size, but it's the end of the sprint so I wanted to go ahead and push up what I had in case we decide this is okay for now.
[Pivotal Card](https://www.pivotaltracker.com/story/show/150986287)

Loading spinner on review buttons

---

package.json
resources/assets/components/Post/__snapshots__/test.js.snap
resources/assets/components/Post/test.js

Added a snapshot test for Posts. I only passed the attributes necessary for the tests to pass.
Is there anything else on the Post on the frontend that we should be testing? The only other thing I can think of is rotating the image but I'm not sure that that's something we want to test with this. Should I add tests for different values of `showQuantity` and `allowHistory`?
[Pivotal card](https://www.pivotaltracker.com/story/show/151647046)

Add snapshot test for Posts

---

config/deploy.rb

When the app gets deployed, some pointers are still referencing the old deploy. 
Once we deploy, we should see that PHP errors from missing files are eliminated.
These errors are cascading and causing issues with Gambit as well
Fixes #

Keeping more releases to prevent PHP errors

---

lib/capistrano/tasks/laravel.rake

Adds `within "#{release_path}" do` to the queue task. 
Fixes 🐛

Add release path

---

.env.example
README.md
app/Console/Commands/SetupCommand.php
app/Console/Kernel.php
composer.json
composer.lock

I made a [little package](https://github.com/DFurnes/environmentalist) over the weekend that lets us create "setup scripts" relatively easily. This allows us to quickly set up the application without having to follow a ton of steps.
Try it out & see if you run into issues!
Specifically, we always had an implied "set your Northstar env vars" step that was never documented. This makes that step clear without having to add a ton of stuff to the README.
N/A

Add "rogue:setup" command.

---

app/Http/Controllers/Three/PostsController.php
app/Http/routes.php
documentation/README.md
documentation/endpoints/posts.md
tests/Http/Three/PostTest.php

- Creates `GET /api/v3/posts` and `GET /api/v3/posts/:post_id` endpoints 
- Creates tests to make sure those both work
- Updates documentation 
- Hit both of those endpoints and they should work! 
- Make sure all tests pass 
Fixes the first task in this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151852968)
- [X ] Documentation added for new features/changed endpoints.

Creates GET /api/v3/posts and GET /api/v3/posts/:post_id endpoints 

---

composer.lock
resources/assets/components/Post/index.js
resources/assets/components/Post/test.js
resources/assets/components/ReviewBlock/__snapshots__/test.js.snap
resources/assets/components/ReviewBlock/test.js

I was starting on Jest testing for the `WithReviewing` HoC and noticed some warnings that have popped up in our tests because of the work I did in #477 to add proptype validation to our components. 
This PR seems to clean those up.
:eyes: 
* Tests should pass without warning
* I wasn't sure the appropriate way to mock functions that are required by some components, so I just defined them, had them return `true`, and passed them into the component that requires it. Since these are just snapshot tests, it doesn't seem like matters what these functions do, as long as we pass them into the component since the proptype validation requires them. 
Here are the warnings I was seeing without this.
https://cl.ly/1w360Y2L091k
https://cl.ly/2O263h2S2A1d
Errors

Fix frontend tests

---

app/Console/Commands/ImportSignupsCommand.php

Now, accept a url to a csv instead of a path to a csv.
Better logging! Most of the output now goes straight into the regular logs. Everything is prefixed with `rogue:signupimport:` so it is less confusing.
[Documentation](https://docs.google.com/document/d/1RYCJOcxBIyHLRVfSWCSzS95yP9ZEcOakVRHJD1NHXjs/edit)
👀  Can we do this on Thor and on Prod?

rogue:signupimport - Use a link to a file and better logging

---

app/Services/ExportService.php
resources/assets/components/UserExport/index.js

Updates the signup export to only export web signups. 
Also cleans up some JS in the export component. 
👀 
Here is the slack thread for more context https://dosomething.slack.com/archives/C0YGXUE01/p1510584771000035
Fixes 🐛

Web only export

---

resources/assets/components/Table/CampaignRow.js
resources/assets/components/Table/table.scss

Updates the styling of tables to look more like @lkpttn 's design:
👀 
Here are what the new tables look like:
Campaign overview: 
Close up:
History Modal:
Fixes this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151762747)

Updated Styling for Tables

---

CODEOWNERS

This should allow us to [automatically request reviews](https://github.com/blog/2392-introducing-code-owners) from @DoSomething/team-bleed on pull requests made to this repository! (We'll see...!)
[https://git.io/vFXjf](https://git.io/vFXjf) 👀
We always assign the same people to PRs, let's make that easier!
N/A

Adding OWNERS file.

---

resources/assets/_mocks_/__mockData__/campaign.json
resources/assets/_mocks_/__mockData__/events.json
resources/assets/_mocks_/__mockData__/posts.json
resources/assets/components/MultiValueFilter/test.js
resources/assets/components/Post/index.js
resources/assets/components/Quantity/index.js
resources/assets/components/WithReviewing/index.js
resources/assets/components/WithReviewing/test.js
resources/assets/utilities/RogueClient.js
resources/assets/utilities/__mocks__/RogueClient.js

First round of tests for the `WithReviewing` HoC. 
This is a relatively large PR, but the bulk of the work is in `resources/assets/components/WithReviewing/test.js`
everything else is just setting up some mock json responses, mocking calls to `RogueClient.js` and some style clean up. 
👀 
This doesn't cover all the methods that `WithReviewing` provides but this PR was getting large and I also wanted to get some eyes on my progress so flags can be raised earlier than later .
Addresses https://www.pivotaltracker.com/story/show/151647077

WithReviewing tests

---

package-lock.json
package.json

Update to our latest [Webpack config](https://github.com/DoSomething/webpack-config/releases/tag/v3.0.0) and [Babel config](https://github.com/DoSomething/babel-config/releases/tag/v2.0.0).
The build should work! (It doesn't right now, looking into some Jest issues.)
References DoSomething/devops#351.
[#153056938](https://www.pivotaltracker.com/story/show/153056938)

Update Webpack & Babel configs.

---

package-lock.json

I forgot to update `package-lock.json` in #509.
👀 
🤦‍♂️
[Slack](https://dosomething.slack.com/archives/C0YGXUE01/p1511291319000306)

Update npm dependencies.

---

Procfile
composer.json

This pull request adds a [`release` task](https://devcenter.heroku.com/articles/release-phase) to the Procfile to run migrations & a [PHP build step](https://devcenter.heroku.com/articles/php-support#build-behavior) to download the public key from Northstar. (This seems to be the only way to do this, since things from the release step don't seem to persist on the filesystem).
👀
The `gateway:key` command is necessary for Rogue Thor to accept OAuth tokens! Otherwise it 500s when it can't find the `public.key` file to validate a token with.
[#152602162](https://www.pivotaltracker.com/story/show/152602162) / DoSomething/devops#352

Run migrations & fetch public key on new releases.

---

app/Http/Controllers/Three/PostsController.php
app/Http/Controllers/Three/SignupsController.php
app/Http/Requests/PostRequest.php
app/Http/Requests/Three/PostRequest.php
app/Http/Transformers/Three/PostTransformer.php
app/Models/Post.php
app/Repositories/Three/PostRepository.php
app/Repositories/Three/SignupRepository.php
app/Services/Three/PostService.php
app/Services/Three/SignupService.php
app/helpers.php
documentation/README.md
documentation/endpoints/posts.md
documentation/endpoints/v3/posts.md
documentation/endpoints/v3/signups.md
tests/Http/Three/PostTest.php
tests/Http/Three/SignupTest.php

- Updates `POST v3/posts` endpoint to store quantity on the post.
- Updates `PATCH v3/posts` endpoint to not try to update quantity and allows you to update quantity.
- Updates Post transformer to return quantity for the post.
- [Updates SignupController@store to incldue authorization logic.](https://www.pivotaltracker.com/n/projects/2019429/stories/153365833)
- [Updates PostController@store to allow user tokens.](https://www.pivotaltracker.com/n/projects/2019429/stories/153365724)
- [Updates PostController@update to include authorization logic.](https://www.pivotaltracker.com/n/projects/2019429/stories/153365782)
- Only allows admins to be able to do this. 
- Updates Signup and Post tests. 
- Adds test to make sure only admins can update a post. 
- Check to make …

v3/posts update and Start of OAuth updates to v3 endpoints

---

Procfile
app/Http/Controllers/PagesController.php
app/Http/Controllers/Three/PostsController.php
app/Http/Controllers/Three/ReactionController.php
app/Http/Controllers/Three/SignupsController.php
app/Http/Controllers/Traits/TransformsRequests.php
app/Models/Post.php
app/Providers/AppServiceProvider.php
composer.json
composer.lock
routes/api.php
routes/web.php
tests/Http/TagsTest.php
tests/Http/Three/PostTest.php
tests/Http/Three/SignupTest.php

A few more performance improvements:
🏷 Eager loads the `tags` on posts, so that we don't have the ol' N+1 query problem. ([Before](https://user-images.githubusercontent.com/583202/33785726-58fd4bf0-dc34-11e7-8c8a-07e71d2334e5.png), [After](https://user-images.githubusercontent.com/583202/33788227-0d6b8a98-dc3f-11e7-8330-c906cb581967.png))
💵 Caches routes & config when compiling the app. I also switched these commands to run in a "warmup" task so they also run on environment variable changes (as suggested [here](https://stackoverflow.com/a/35862183/811624)).
⬆️ Updated dependencies, including the latest version of Laravel Debugbar. Since it now registers with package discovery, I've removed the line we'd use to register it in AppServiceProvider.
📄 Forces cursor pagination on the v3 routes …

More performance improvements.

---

Procfile

We need queueing support for Rogue. In Heroku, you have to add a `queue` line to the Procfile to support this.
Submit a reportback to see if you receive an email.

Adding queueing functionality for Heroku

---

.user.ini

This should increase the limit on file uploads/request payloads on Heroku instances.
We can check this with a `php -i` on Heroku after deploying.
Here's some details from [Heroku's documentation](https://devcenter.heroku.com/articles/custom-php-settings#php-runtime-settings).
Fixes #

Increase request limits on Heroku dynos.

---

Procfile
app/Http/Controllers/PagesController.php
routes/web.php

Two changes:
🦅 Updates the `Procfile` to use a relative path for the [`public` directory](https://github.com/DoSomething/rogue/tree/master/public), like [in the docs](https://devcenter.heroku.com/articles/deploying-php#configuring-the-document-root).
ℹ️ Adds a temporary route so we can inspect what `phpinfo` looks like when on Heroku.
👀
[Slack Conversation](https://dosomething.slack.com/archives/C0YGXUE01/p1513195567000692)
N/A

Some Heroku debugging!

---

app/Http/Controllers/PagesController.php
routes/web.php

Confirmed that we're seeing the expected `post_max_size ` and `upload_max_filesize `!
:x:
N/A
N/A

Remove temporary debug route.

---

Procfile

This pull request swaps out Apache for Nginx on our heroku instances.
👀
[Heroku documentation](https://devcenter.heroku.com/articles/custom-php-settings#how-applications-are-launched-during-dyno-boot)
N/A

Use nginx on Heroku.

---

public/nginx_app.conf

This adds a [custom nginx config file](https://devcenter.heroku.com/articles/custom-php-settings#nginx) so that we can use nginx on Heroku!
Does this make sense based on the nginx config we've used elsewhere?
My initial stab at this in #546 ended up with a 404 page on rogue-thor.dosomething.org. 💥
N/A

Add an nginx config file.

---

nginx.conf

Nginx is giving us the old `413 Request Entity Too Large`. Stop that!
🍶 
🎎
N/A

Allow larger requests through nginx.

---

nginx.conf

This should allow Heroku to read the correct `client_max_body_size` value.
🍔
Found by @sheyd in this [Stack Overflow answer](https://stackoverflow.com/a/37284909/811624)!
N/A

Fix 'client_max_body_size' for Heroku.

---

nginx.conf

This now seems to be working correctly! I've successfully [uploaded an 8.9MB image](https://rogue-thor.dosomething.org/api/v3/posts/392799) on Thor:
```json
{
"data": {
"id": 392799,
"signup_id": 301838,
"northstar_id": "5543dfd6469c64ec7d8b46b3",
"quantity": 0,
"media": {
"url": "https://rogue-thor.dosomething.org/images/392799?time=1513267464",
"original_image_url": "https://ds-rogue-thor.s3.amazonaws.com/uploads/reportback-items/301838-d0304c056a2eca655c4e2d2a1d3e932d-1513267462.jpeg?time=1513267464",
"caption": "test"
},
"tags": [],
"reactions": {
"reacted": false,
"total": null
},
"status": "pending",
"source": "paw",
"remote_addr": "207.110.19.130",
"created_at": "2017-12-14T16:04:22+00:00",
"updated_at": "2017-12-14T16:04:22+00:00"
}
}
```
The `index` directive fixes the 403 errors …

Reset things so they don't 403.

---

app/Http/Kernel.php
composer.json
composer.lock
resources/assets/components/Signup/index.js
resources/views/layouts/master.blade.php

- Exposes token in front end.
- Adds ability for admin to delete a signup.
- Updates latest gateway version.
When an admin deletes a signup, the page will look like this: 
Then, when you refresh the page, since the signup doesn't exist anymore, the standard Laravel "Page Not Found" page will pop up:
@lkpttn let me know if you want me to change anything about this! 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/152487740) Pivotal Ticket.

Adds ability to delete a signup in Rogue admin UI

---

routes/web.php

The [default "unauthenticated" handler](https://github.com/laravel/framework/blob/6d1f0695a95a507772d205987895720341fd4d2d/src/Illuminate/Foundation/Exceptions/Handler.php#L216-L221) in Laravel looks for a named `login` route. This creates one so that these continue to work as they did [before](https://github.com/DoSomething/rogue/blob/1a5db305e47934714583b0fc6d6b63f51d04383d/app/Exceptions/Handler.php#L88-L95).
👀
References my cleanup in #562.
N/A

Add named 'login' route.

---

app.json

* Reformated the `app.json` file so it was valid JSON
* Added config props that state we should pull these value from the `rogue-staging` parent app.
👀 
Once this is merged in, I will try out a dummy review app to see if this is correct. There might need to be updates unless we catch anything glaring now!
Jumped on this, because I think it will help our testing for some future work. 
I am debating whether these review apps should inherit from `rogue-thor` instead of staging since no one really uses staging, but one thing that is cool about using staging is that we can add a `postDeploy` script that can seed our DB with test data which might be nice for low-level testing. 
Fixes https://www.pivotaltracker.com/story/show/153318354

Configure app.json for review apps

---

app.json

I accidentally merged in a PR too soon and the JSON in `app.json` wasn't valid so this fixes that. 
Also addresses some comments left in the previous PR after merging: https://github.com/DoSomething/rogue/pull/565
👀 
I ran it through a JSON linter and it seems to be valid.

Remove weird AWS vars and don't enable blink on review apps

---

resources/views/pages/faq.blade.php

- Adds updates on tags and link to Reportback Reviewing 101 guide
👀 
Here are updated screenshots! 
cc @ngjo @lkpttn 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154000562) Pivotal Story.

updates faq page with new info. on tags and link to Reportback Reviewing 101 guide

---

app/Http/Requests/Three/PostRequest.php
app/Repositories/Three/PostRepository.php
documentation/endpoints/v3/posts.md
tests/Http/Api/ActivityApiTest.php
tests/Http/Api/PostApiTest.php
tests/Http/Three/PostTest.php

- Adds three new unit tests based on [Gambit Flow](https://github.com/DoSomething/gambit-campaigns/wiki/Rogue) to ensure that when we deploy, we're not breaking Gambit! 
- `/activity?filter[northstar_id]=123&filter[campaign_run_id]=456` test 
- test for submitting multiple posts to `/v2/posts`
- test for submitting multiple posts to `/v3/posts`
- Allows you to create a post to the `POST /v3/posts` endpoint without a `quantity`
Make sure all tests pass! 
Did I cover all the tests that we need? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/152980920) Pivotal Card.
cc @aaronschachter

Gambit unit tests

---

app/Http/Controllers/Three/SignupsController.php
tests/Http/Three/PostTest.php
tests/Http/Three/SignupTest.php

- Updates SignupController@update to include authorization logic.
- Only allows admins and owner of signup to update signup. 
- Updates tests. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/153365904) Pivotal Card.

Update SignupController@update to include authorization logic.

---

app/Http/Controllers/Three/SignupsController.php

Adds middleware back that only allows an admin to delete a signup deleted in [this PR](https://github.com/DoSomething/rogue/pull/588/files). 
👀

Adds middleware back that only allows an admin to delete a signup

---

documentation/endpoints/reactions.md

-Forgot to update the documentation for the changes made in [this PR](https://github.com/DoSomething/rogue/pull/587)! 
👀

Updates POST /api/v3/post/:post_id/reactions documentation

---

database/migrations/2018_01_26_211937_make_bucket_and_details_columns_nullable.php

When I added these columns, I didn't make them `nullable` because I figured we would need them. But we won't always need them and now that I am digging into storing things in these columns, tests are mad about these columns not being nullable. 
So this PR makes them nullable. 
👀 
Fixes 🐛

Add migrations to make new post columns nullable

---

resources/views/pages/import.blade.php

Adds a little message to the upload form that Jen is the only one to use this feature. 
👁 
Check my grammar...I do not have good grammar and I also am a typo queen 👑 
We are still testing this feature and do not want folks using it in the meantime. 
\

Add a message that Jen is the only one to use this

---

app/Http/Controllers/Three/TagsController.php
app/Models/Post.php
app/Repositories/Three/PostRepository.php
database/factories/ModelFactory.php
documentation/README.md
documentation/endpoints/v3/tags.md
routes/api.php
tests/Http/Three/TagsTest.php

- Adds `/v3/posts/:post_id/tags` RESTful endpoints:
- `POST /v3/posts/:post_id/tags` 
- `DELETE /v3/posts/:post_id/tags` 
- Adds testing
- Adds documentation
- 👀 
Right now, we should only need the POST and DELETE endpoints. An index, show, and update methods are not useful to us right now. 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154640911) Pivotal Card.

Adds `/v3/posts/:post_id/tags` RESTful endpoints

---

app/Jobs/SendDeletedPostToQuasar.php
app/Jobs/SendPostToQuasar.php
app/Jobs/SendSignupToQuasar.php

This was supposed to be included in https://github.com/DoSomething/rogue/pull/603
This will trigger when we `SendDeletedPostToQuasar::dispatch($postId)` in the Post Services.
[Card](https://www.pivotaltracker.com/story/show/153611842)

Add SendDeletedPostToQuasar job

---

app/Http/Transformers/Three/SignupTransformer.php
app/Http/Transformers/Three/UserTransformer.php
app/Http/Transformers/UserTransformer.php
documentation/endpoints/activity.md
documentation/endpoints/v3/signups.md
tests/Http/Three/SignupTest.php

- Adds ability to access user info. with `?include=user param ` on v3 signups endpoint.
- Adds tests.
👀 
We need more user info. for the leaderboard! 
Is needed for [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154579464) Pivotal card so we can list user name in the leaderboard.

/v3/signups?include=user param 

---

app/Jobs/ImportTurboVotePosts.php
composer.lock

When importing a TurboVote CSV, if a campaign ID or Campaign Run ID is not found in the provided referral code for a record, we will fallback to Grab The Mic (campaignID:8017, campaignRunID:8022).
👀 
There is a chances that someone my register on turbovote instance but we lose the campaign information. We want to just attribute everything to Grab the Mic. 
Fixes https://www.pivotaltracker.com/story/show/155128844

Add campaign fallbacks

---

app/Jobs/ImportTurboVotePosts.php

* Manually up the time out limit when the script runs to hopefully kill some of the timeouts we have seen when working with large files. 
* I was logging each TV record and these records had user information we probably don't want in the logs #GDPR so this removes that from the logs. 
👀 
🐛

Import enhancements

---

docs/README.md

The root readme was holding content from the API specific readme. This updates that. 
👀

Update root readme

---

docs/development/deployments.md

Updates the deployment documentation to include 👻 test step.

Update deployment workflow instructions

---

app/Jobs/SendSignupToBlink.php

Remove a double log that is happening!
👀 
Just a lil error.

Remove extra log

---

app/helpers.php

It allows us to see if a client has the right scope to see `pending` posts
👀

Allow admin clients to see pending posts

---

composer.lock

- Runs `composer update` to get in a regular habit of doing this so we get the latest security release! 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156433191) Pivotal Card.

Runs composer update so we get the latest security release 

---

resources/assets/utilities/RogueClient.js

-Updates `RogueClient` to use v3 endpoints
👀 
Fixes fourth task in [this](https://www.pivotaltracker.com/n/projects/2019429/stories/155907208) Pivotal Card

Updates RogueClient to use v3 endpoints

---

app/Http/Controllers/PostsController.php

- Adds staff (in addition to admin or user who owns the post) to update a post. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156633114) Pivotal Card.

Allows staff to update posts

---

app/Http/Controllers/PostsController.php
app/Http/Controllers/ReviewsController.php
app/Http/Controllers/TagsController.php

- Allows staff to review and tag a post.
- Also updates `PostsController` to use `is_staff_user()` helper (suggestion from @sbsmith86 [here](https://github.com/DoSomething/rogue/pull/667#discussion_r180554588)!). 
👀 
Fixes 🐛 

Allow Staff to Review and Tag a Post 

---

README.md
app/Http/Controllers/ReviewsController.php
app/Http/Controllers/TagsController.php

- Removes space between `admin` and `staff`, which was causing errors and threw `403` error
- Updates `README.md` so links work
👀 
Fixes typo in #669 

Review bug

---

.styleci.yml
app/Http/Controllers/PostsController.php
app/Http/Requests/PostRequest.php
tests/Http/PostTest.php

1) Allows you to pass status when updating a post
2) Conditionally validates status based on post `type`
👀

Status Validation Update

---

resources/assets/components/Post/__snapshots__/test.js.snap
resources/assets/components/Post/index.js
resources/assets/components/Post/post.scss

-Adds Frontend Updates to Posts So It's Easier to Review/Debug: 
- Adds `signup_id` to the inbox on the post
- Adds `signup_source` to the inbox on the post
- Clarify that `source` on the post right now is the `post_source`
- Adds a line between the posts
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156290535) Pivotal Card.

Adds Frontend Updates to Posts So It's Easier to Review/Debug

---

composer.json

- Adds `php artisan cache:clear` to `composer.json` to clear cache when we deploy 
👀 
- Adds this to check that everything is still working as expected after #679 
Related to [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156929053) Pivotal Card.

Clears cache when we deploy

---

resources/assets/components/Post/__snapshots__/test.js.snap
resources/assets/components/Post/index.js
resources/assets/components/Post/test.js
resources/assets/helpers.js

- Photo Caption is not being pulled correctly and is blank in Rogue - this PR fixes that!
- This PR also deletes unused `displayCaption` helper now that we've moved to using the v3 endpoint, the result is normalized when we grab posts. 
- Updates Jest test. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156813946) Pivotal Card.

Fixes bug to display post text properly and deletes unused helper

---

resources/assets/components/Post/index.js

- Fixes bug to have name or mobile to signup page. 
👀 
We now want to pull `signup.id` since we are using `v3` endpoints and information is returned differently from `v2` endpoints. 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156670843) Pivotal Card.

Fixes bug to link to Signup page 

---

composer.lock

Runs `composer update` so we get security releases regularly! 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157288532) Pivotal Card.

Runs composer update

---

tests/Http/PostTest.php

- Adds unit test to make sure a `text` post is correctly created. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157202065) Pivotal Card.

Adds text post unit test

---

app/Http/Middleware/CheckRole.php
composer.json
composer.lock
database/factories/ModelFactory.php
tests/Http/PostTest.php
tests/Http/TagsTest.php

- Adds tests to make sure hidden post logic is working - admins and owners should be returned hidden posts (posts tagged as "Hide In Gallery." Anonymous users shouldn't be able to see hidden posts when hitting `GET /v3/posts`.
- Updates TagsTests to tag with `->tag();` instead of via the API.
- Updates `composer.json` to use latest Gateway release.
All tests should pass!
Writes tests for work done in #694 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157481061) Pivotal Card.

Hidden Posts tests

---

app/Http/Controllers/PostsController.php
app/Managers/PostManager.php
app/Repositories/PostRepository.php
app/Services/AWS.php

Logging a bunch throughout the posts route to debug issues we are seeing in heroku.

Log messages throughout post route

---

app/Auth/CustomGate.php
app/Http/Controllers/PostsController.php
app/Policies/PostPolicy.php
app/Providers/AppServiceProvider.php
app/Providers/AuthServiceProvider.php
database/factories/ModelFactory.php
tests/Http/PostTest.php

- Adds Post Permission Policies for `show` and `update` methods. 
- Adds `CustomGate` so we can send an anonymous `user` to the policy.
- Updates the Post Model Factory to create a `northstar_id`
- Deletes some tests that are redundant. 
👀 
All tests should pass. 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/156700437) Pivotal Card. 

Post Permission Policies

---

app/Console/Commands/UpdateSignupAndOrPostField.php

Updates to add `$logfreq` to scope to the `UpdateSignupAndOrPostField` command.
👀 
Fixes mistake in #713 

Updates to add $logfreq to scope

---

app/Console/Commands/UpdateSignupAndOrPostField.php
app/Managers/PostManager.php
app/Managers/SignupManager.php

- updates Signup/PostManger to have option to not log when sending to Quasar
- updates `UpdateSignupAndOrPostField` command to not log when updating Signup/Post in Quasar
👀 
Goes along with [this discussion](https://github.com/DoSomething/rogue/pull/714#issuecomment-393259907).

updates Signup/PostManger to have option to not log when sending to Quasar

---

composer.json
composer.lock

Updates gateway version to `^1.14.9`
👀 

Updates gateway version to ^1.14.9

---

app/Http/Requests/Legacy/Two/PostRequest.php
tests/Http/Legacy/Two/PostApiTest.php

adds file validation to v2 post request
👀 
Will this break anything by adding the `image` to the validation? 
Fixes errors we were seeing in [Papertrail](https://dosomething.slack.com/archives/C0YGXUE01/p1527729205000183)

adds file validation to v2 post request

---

app/Console/Commands/BulkAcceptPosts.php
app/Console/Commands/BulkReviewPosts.php
app/Console/Commands/UpdateSignup.php
app/Models/Post.php
resources/assets/components/CampaignSingle/index.js
resources/assets/components/Post/__snapshots__/test.js.snap
resources/assets/components/Tags/index.js
resources/views/pages/faq.blade.php

- Adds the `bulk` tag
- Writes script to bulk review and tag posts constrained by the provided parameters
- To bulk approve all `text` posts under a campaign and tag as `Bulk` and `Hide In Gallery` run: `php artisan rogue:bulkreviewposts {campaign_id} pending accepted --type=text --logfreq=1000 --tag=bulk --tag=hide-in-gallery`
- All text posts in that campaign should be `accepted` and tagged as `Bulk` and `Hide In Gallery`
- Make sure _only_ `text` posts are updated! 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157777047) Pivotal Card.

Bulk Accept Post Command

---

app/Console/Commands/BulkReviewPosts.php

Changes accept to review in Bulk Review Posts script. 
👀 
This is super tiny but driving me crazy! Also, important for the script to have accurate logging - if we are bulk rejecting, we don't want to cause any confusion from this message saying that it is bulk accepting! 

changes accept to review in Bulk Review Posts script 

---

composer.lock
package-lock.json

Runs `npm update` and `composer update`
👀 

Runs npm update and composer update

---

app/Console/Commands/BulkReviewPosts.php
app/Events/PostTagged.php
app/Jobs/SendPostToCustomerIo.php
app/Listeners/SendTaggedNotification.php
app/Managers/PostManager.php
app/Models/Post.php

Adds log param whether or not to log when post is sent to Customer.io and when post is tagged
👀 
When running on Thor, I realized this was logging each time when it was sent to Customer.io. We probably don't want this and want to turn on/off with `log` flag. 
Also, it logged each time the post was tagged. This PR also hides this behind a flag so the logs don't clog!

Adds log param whether or not to log when post is sent to Customer.io and when post is tagged

---

resources/assets/components/Signup/index.js

adds the rotate button to the signup page
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157408403) Pivotal Card.

adds the rotate button to the signup page

---

package.json

Removes gitbook-cli which was causing us some issues on local homestead builds. 
👀 
Fixes issue with local development. 
🐛 

remove gitbook cli

---

app/Http/Controllers/Legacy/Web/ImagesController.php
resources/assets/components/Signup/index.js

Adds Rotate function to Signup Component so that you can successfully rotate an image on the signup page! 
👀 
This work to add rotation to the signup page was started in #729
Finishes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157408403) Pivotal Card

Adds Rotate function to Signup Component 

---

app/Console/Commands/BulkReviewPosts.php

sends variables through to chunk part of query in BulkReviewPosts command
👀 
Fixes mistake in #735 

sends variables through to chunk part of query 

---

resources/assets/components/Signup/index.js

Updates the Signup Component so you can now update a post's quantity from there. 
👀 
Does this work as we expect? Does this update the post quantity and the overall signup quantity as we expect? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/157094042) Pivotal Card.

Update quantity on Signup Page

---

Procfile

Updates the queue worker command in the Procfile to run the correct queue on SQS

Update queue worker to run the sqs queue

---

docs/README.md
docs/development/developer_onboarding.md

fixes link to docs and adds the new northstar qa url to the documentation
👀 

add new qa northstar url and fix link to docs

---

.env.example
app/Console/Commands/SetupCommand.php
database/faker/FakerNorthstarId.php

Just updating our default environment to have the correct Northstar & Aurora URLs.
👀
N/A
References DoSomething/devops#383 and DoSomething/devops#388.

Update environments in setup command/default environment.

---

app/Listeners/SendTaggedNotification.php
app/Models/Post.php
resources/assets/components/CampaignSingle/index.js
resources/assets/components/Post/__snapshots__/test.js.snap
resources/assets/components/Tags/index.js

This PR adds the Good For Brand and Group Photo tags!
👀 
@lkpttn do the images below look okay?
Fixes [#159005089](https://www.pivotaltracker.com/story/show/159005089)

Adds Good For Brand and Group Photo tags

---

resources/assets/components/Post/__snapshots__/test.js.snap
resources/assets/components/Post/index.js

adds post type to meta data in Rogue admin 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/160097604) Pivotal Card.

adds post type to meta data in Rogue admin 

---

package-lock.json
package.json

runs npm update to (hopefully) get rid of potential security risk that github has flagged
👀 

runs npm update to get rid of potential security risk 

---

app/Console/Commands/GDPRComplianceCommand.php
app/Console/Commands/ImportSignupsCommand.php
composer.json
composer.lock
wercker.yml

Upgrades php version to 7.2.0
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/159005701) Pivotal card.

Upgrades php version to 7.2.0

---

resources/assets/components/CampaignSingle/index.js

Adds new(ish) tags to filter bar: 
- Irrelevant 
- Inappropriate
- Unrealistic Quantity
- Test
- Incomplete Action 
- Are these all showing up in the filter bar? 
- When clicked, does the filter bar filter correctly? 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/154973569) Pivotal Card.

Adds new(ish) tags to filter bar

---

app/Http/Controllers/Auth/AuthController.php

After login to Rogue, redirects to intended page instead of always redirecting to `/campaigns`. (This code was taken from [Next](https://github.com/DoSomething/phoenix-next/blob/master/app/Http/Controllers/AuthController.php)!) 
- When not logging in, visit `/signups/1`
- Log in. 
- You should be taken to `/signups/1` instead of `/campaigns`
This was a feature request from @aaronschachter in the Rogue Technical Happiness Survey! :) 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/161121809) Pivotal Card.

After login to Rogue, redirects to intended page instead of always /campaigns 

---

app/Http/Controllers/Auth/AuthController.php

Gets rid of uneeded code from #774 from @DFurnes 's [comment](https://github.com/DoSomething/rogue/pull/774#discussion_r226754749)
👀 
It didn't actually push the changes in #774 and I merged too quickly! 
Fixes #774 

Gets rid of uneeded code from #774

---

package-lock.json
package.json

runs `npm update` to get rid of potential security updates alert in Github.
👀 

runs npm update to get rid of potential security updates alert in Github 

---

app/Http/Controllers/Legacy/Web/CampaignsController.php
app/Models/Campaign.php
database/factories/ModelFactory.php
database/migrations/2018_11_10_161359_add_cause_to_campaigns_table.php
package-lock.json
resources/views/campaign-ids/create.blade.php
resources/views/campaign-ids/edit.blade.php
resources/views/campaign-ids/index.blade.php
resources/views/campaign-ids/show.blade.php
tests/Http/CampaignTest.php

- Adds cause to campaign creation in Rogue: 
- adds `cause` column in the `campaigns` table.
- adds a cause drop down to Rogue frontend when creating and editing a campaign. 
- adds cause field to index page and show views. 
- adds backend work to categorize campaign cause when creating and editing a campaign. 
- Updates tests. 
- Frontend enhancement: 
- keeps old values in the create campaign form if validation fails (previously, it deleted the values in the form when submitted when validation failed and error message would pop up - user would have to re-write title, cause, start/end date). 
👀 
Fixes 1st and 4th task in [this](https://www.pivotaltracker.com/n/projects/2019429/stories/161604438) Pivotal Card. …

Adds cause to campaign creation in Rogue 

---

resources/assets/components/Post/index.js
resources/assets/components/Signup/index.js

Updates metadata to show full date timestamp for Signups and Posts to include time in the date. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/158628533) Pivotal Card.

Adjusts meta data to show full date timestamp

---

app/Models/Post.php
app/Models/Signup.php
database/migrations/2018_12_05_155452_add_source_as_index_to_signups_and_posts_tables.php
docs/endpoints/posts.md
docs/endpoints/signups.md

- Updates GET /v3/posts and GET /v3/signups endpoints to be able to filter by source. 
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/162448781) Pivotal Card. 
cc @aaronschachter 

Updates GET /v3/posts and GET /v3/signups endpoints to be able to filter by source

---

resources/views/campaign-ids/create.blade.php

I fixed another typo!
`campagin` => `campaign`

Fixes a typo

---

resources/views/campaign-ids/index.blade.php

I fixed a typo!
Rrrrrrrreading

Fixes typo on campaign ID listing view

---

resources/views/campaign-ids/create.blade.php

Updates internal campaign name placeholder to mimic naming convention outlined in [this doc](https://docs.google.com/document/d/1wIShshIhs9X6XEj1nUE1ZRcaRh9J52uyc8tqwQbMP7o/edit#).
👀 

Updates internal campaign name placeholder to mimic naming convention 

---

tests/Http/SignupTest.php

Adds `campaign_run_id` in the `testNotCreatingDuplicateSignups` test to get it passing. 
do all tests pass? 

Updates testNotCreatingDuplicateSignups test to get it to pass

---

app/Http/Controllers/Legacy/Two/PostsController.php

I was too hasty in #804 and didn't catch this other missing import.  Confirming _for reals_ that this route now renders correctly. 😇
```
curl -I "http://rogue.test/api/v2/posts?include=signup"
HTTP/1.1 200 OK
``
Are there other imports I'm missing in here? Hopefully not. 🙃 
References #804.
N/A

Import missing Post class to legacy PostsController.

---

app/Http/Transformers/CampaignTransformer.php
docs/endpoints/campaigns.md
docs/endpoints/posts.md

Returns dates as a string in campaign transformer 
Is the date returned as a string and not an object? 
Fixes issue in [this comment](https://github.com/DoSomething/rogue/pull/776#discussion_r239979680)

Returns dates as a string in campaign transformer 

---

database/migrations/2019_01_16_174349_add_actions_table.php

Adds the `actions` table for Post Metadata work (second thing on checklist [here](https://github.com/orgs/DoSomething/teams/team-bleed/discussions/32)).
👀 
Are all columns accurate? Did I miss any columns? Are there any missing or unnecessary indexes?  
Fixes part of [this](https://www.pivotaltracker.com/n/projects/2019429/stories/163124121) Pivotal Card.

Adds actions table - part of Post Metadata work

---

app/Http/Controllers/Legacy/Web/ActionsController.php
tests/Http/ActionTest.php

- Adds logic to not create duplicate action if an action already exists (by matching `name`, `campaign_id`, and `post_type`
- Adds test for this.
👀 

Adds logic to not create duplicate actions 

---

composer.json
composer.lock

Enable CORS for Rogue's API.
👀 
Fixes first checkbox in [this](https://www.pivotaltracker.com/n/projects/2019429/stories/163460749) Pivotal Card.

Enable CORS for Rogue's API.

---

app/Repositories/PostRepository.php
docs/endpoints/posts.md

Throws 500 error code if no action is found and logs what is going on (before it was throwing a misleading `404` error code since we were using `findOrFail`). 
- Try to create a post via the `POST /api/v3/posts` endpoint with an `action` that doesn't exist. 
- You should receive a `500` error code with this message in response: `"No action found.",`. 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164286560) Pivotal Card.

Throws 500 error code and adds logging if no action is found

---

database/migrations/2019_02_27_201348_increase_text_character_count_in_posts_table.php

adds migration to increase a post's text character limit from 255 to 500
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/163867787) Pivotal Card.

adds migration to increase a post's text character limit from 255 to 500

---

app/Http/Requests/PostRequest.php

Increases text maximum character limit to 500 in Post Request.
Can you submit a text reportback with up to 500 characters in the `text` response?
Finishes up work in #840 

increases text maximum character limit to 500 in Post Request

---

docs/endpoints/posts.md

updates documentation for character limit for a post's text 
👀 
Documentation update for #845 

updates documentation for character limit for a post's text 

---

docs/endpoints/posts.md

updates documentation for dimension requirements on photo posts
👀 

updates documentation for dimension requirements on photo posts

---

composer.lock
package-lock.json
package.json
resources/assets/components/CampaignIdSingle/index.js
resources/assets/components/Table/CampaignIdRow.js

Uses [date-fns](https://date-fns.org/v1.30.1/docs/format) to format dates so it shows up as valid dates in Chrome and Safari.
👀 
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164282296) Pivotal Card.

Uses date-fns to format dates so it shows up as valid dates in Chrome and Safari 

---

resources/assets/components/CampaignIdSingle/index.js
resources/assets/components/Table/CampaignIdRow.js

Updates formatting - things were breaking on QA and I realized I was using the wrong formatting! More from the [docs](https://date-fns.org/v1.9.0/docs/format). 
👀 
Fixes mistake in #855 

Date fns update

---

composer.lock
package-lock.json
package.json
resources/assets/components/CampaignIdSingle/index.js
resources/assets/components/Table/CampaignIdRow.js

Updates to correct version of date-fns and uses combination of format and parse to get correct date
Everything working correctly in Safari and Chrome?
Fixes mistake in #856 

Updates to correct version of date-fns and uses combination of format and parse to get correct date

---

app/Http/Requests/PostRequest.php

Adds `status` validation rules for `phone-call` posts.
👀 
cc @sohaibhasan @mjain-1 for how we will be accepting statuses for this type of post! More info in the [tech spec](https://docs.google.com/document/d/1aDNLKZ6BPto65Ce5RDJkXf8LpKGIFdftO13WgZgkO48/edit#)
Work done for [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164476751) Pivotal card.

Adds phone-call status validation rules

---

app/Http/Controllers/Legacy/Web/ActionsController.php
app/Http/Controllers/Legacy/Web/CampaignIdsController.php
app/Models/Action.php
app/PostType.php
docs/endpoints/actions.md
resources/assets/components/Action/action.scss
resources/assets/components/Action/index.js
resources/assets/components/CampaignIdSingle/index.js
resources/assets/components/Signup/index.js
resources/views/actions/create.blade.php
resources/views/actions/edit.blade.php
resources/views/campaign-ids/edit.blade.php
routes/web.php

- Adds Edit and Delete Functionality for Actions: 
- Edit and Delete buttons only show up if a campaign is not yet live: 
- When you click on the "EDIT ACTION" button, it takes you to this form: 
- Pressing the "Delete Action" button deletes the action and removes from the page with React. 
- Updates all forms to keep old form values if there are validation errors. 
- Updates `GET /api/v3/actions` to be able to filter by `campaign_id` 
- Updates `DELETE /actions/:id` to return a response 
- Updates documentation. 
- Updates bug with dates to show what it is intended instead of `updated_at` dates. 
Can you update and a delete an action? 
If the campaign has already started, do these buttons still show up? 
While coding this, found a bug on https://activity.dosomething.org/campaign-ids page …

Adds Edit and Delete Functionality for Actions

---

resources/assets/components/Action/index.js
resources/assets/components/CampaignIdSingle/index.js
resources/assets/components/Table/CampaignIdRow.js

Fixes Date Bug for Campaign Ids - incorrect dates were being displayed. This updates using the correct formatting to make sure the date in the DB is the same that is being displayed. 
👀 
Documentation for the formatting [here](https://date-fns.org/v1.30.1/docs/format)!
Fixes [this](https://www.pivotaltracker.com/n/projects/2019429/stories/164637404) Pivotal Card.

Fixes Date Bug for Campaign Ids - incorrect dates were being displayed

---

docs/endpoints/posts.md

This PR updates the endpoint documentation for `posts` to specify the new `location` filter.
👀 
🌵 
Refs [Pivotal Tracker ID #164737236](https://www.pivotaltracker.com/story/show/164737236)

Updating the API endpoint docs to include the new location filter.

---

composer.lock
package-lock.json

upgrades `just-extend` and runs `composer update` per [this](https://github.com/dosomething/rogue/network/alert/package-lock.json/just-extend/open) Github security alert. 
👀 

upgrades just-extend and runs composer update

---

app/Http/Controllers/PostsController.php
app/Policies/PostPolicy.php
app/Repositories/PostRepository.php

Moves review gate to Posts Controller to allow script to bulk approve. Also, per @DFurnes 's comment below, this logic should actually live in the Posts Controller anyway since the repository should really only be responsible for storing or retrieving data.
👀 
References change made [here](https://github.com/DoSomething/rogue/pull/859/commits/7533ec2513919d7ecebb5670397a5c66cb1206c6). 
Needed for [this](https://www.pivotaltracker.com/n/projects/2019429/stories/165090581) Pivotal Card.

Moves review gate to Posts Controller to allow script to bulk approve

---

resources/assets/components/StatusButton/status-button.scss

This is just a very quick follow-up to #869 while I was working in this component. It fixes a slight visual bug where the buttons would shift & resize when clicked on, and what seems to be a Forge bug with the "inline" form button text being improperly vertically aligned.
Look at it! 👁 
We should obviously fix the Forge pattern too, but I just wanted a quick fix here.
N/A

Fix visual bugs on "outlined button".

---

app/Providers/AppServiceProvider.php
package-lock.json
package.json
resources/assets/components/Action/index.js
resources/assets/components/CampaignIdSingle/index.js
resources/assets/components/CampaignSingle/index.js
resources/assets/components/Signup/index.js
resources/assets/components/WithReviewing/index.js
resources/assets/components/WithReviewing/test.js
resources/views/layouts/master.blade.php

This pull request updates dependencies (notably, Webpack 4 for less buggy re-builds) and adds the ability for admins to edit in-progress actions (which we'll want for [#165160940](https://www.pivotaltracker.com/story/show/165160940)).
As part of that, I updated this app's `window.AUTH` to be an object (filled in by a [view composer](https://laravel.com/docs/5.6/views#view-composers)) so that we'd have access to the user's role. This follows the same approach we've used in Phoenix.
I think everything's good, but can't hurt to click around on QA a bit before we deploy this!
nah.
[#165160940](https://www.pivotaltracker.com/story/show/165160940)

Update dependencies & allow admins to edit actions. 

---

resources/views/campaign-ids/create.blade.php
resources/views/forms/select.blade.php

This pull request removes the old "Cause" dropdown from the campaign creation form. I've also included a tiny fix from my WIP branch for ensuring the placeholder value will be displayed for drop-downs on "fresh" forms. ☑️ 
👀
Whoops! This was mistakenly left on the form in #875.
Fixes #

Fix campaign creation!

---

app/Http/Controllers/Legacy/Web/CampaignIdsController.php
app/Http/Requests/PostRequest.php
app/Models/Campaign.php
app/Types/ActionType.php
app/Types/Cause.php
database/factories/ModelFactory.php

This pull request does a little final cleanup for the new metadata work:
🔇 Removes the `label` method from `ActionType` since it's already defined in `Type`. e1767a8
💉 Extracts a `Cause` type from the field in the `Campaign` model for consistency. 00c81eb
🌮 Use `PostType` when validating post requests. fdcd838
👀 
Consistency!
N/A

One last clean-up pass on new metadata.

---

resources/views/pages/faq.blade.php

This PR updates the FAQ page!
👁 
The content has been sourced from [this doc](https://docs.google.com/document/d/1FaS8tVAptQqhOizVDThv7u1beDe4AcPVKYFhVx0BP80/edit?ts=5cdef6f0#)
[Pivotal ID#165938663](https://www.pivotaltracker.com/story/show/165938663)

Update FAQ Page

---

app/Types/PostType.php
composer.lock

Adds `email` post type to PostType.php for SoftEdge integration.
Can users create actions that are `email` post types? 
Can you create a post that is an `email` post type?
Work needed for [this Pivotal card](https://www.pivotaltracker.com/n/projects/2019313/stories/165974086).

adds email to PostType

---

resources/assets/components/SignupCard/index.js

This pull request updates the `SignupCard` (only used on `UserOverview`) to build the URL based on the response format from `v3/signups`. This fixes a regression introduced in #892.
👀
🐛
References [this Slack bug report](https://dosomething.slack.com/archives/C0YGXUE01/p1562779407002700).

Update SignupCard to use v3 SignupTransformer format.

---

app/Http/Requests/PostRequest.php
app/Models/Post.php
app/Repositories/PostRepository.php
composer.json
composer.lock
database/migrations/2019_09_09_201626_add_postal_code_to_posts.php

This pull request adds support for storing zip-codes (well, postal codes!) on posts. This will be filled in by Phoenix (coming soon!) based on the work done in DoSomething/infrastructure#203.
I also updated our [`sokil/php-isocodes`](https://github.com/sokil/php-isocodes) dependency, which will hopefully make it nice and easy to enable support for the newer Kenyan county codes [once that's fixed upstream](https://www.pivotaltracker.com/story/show/168387140/comments/206486550).
👀
📮
[#168320231](https://www.pivotaltracker.com/story/show/168320231)

Add support for storing zip-code on posts.

---

jest-setup.js
package-lock.json
package.json

This is just a quick dependency update to [React 16](https://reactjs.org/blog/2017/09/26/react-v16.0.html), [Enzyme 3](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md), and [Husky 3](https://github.com/typicode/husky/blob/master/CHANGELOG.md#300).
We didn't actually need to update all that much!
This gets us inline with other applications, and is necessary for another PR I've got in the works.
N/A

Update to React 16, Enzyme 3, and Husky 3.

---

app/Jobs/RejectPost.php
app/Providers/ModelServiceProvider.php

Just style ci changes
do the style ci tests

more style ci changes

---

app/Console/Commands/DeleteUsersCommand.php
app/Http/Controllers/Legacy/Web/ImagesController.php
app/Http/Controllers/PostsController.php
app/Http/Controllers/ReviewsController.php
app/Http/Controllers/SignupsController.php
app/Http/Controllers/TagsController.php
app/Managers/PostManager.php
app/Providers/RouteServiceProvider.php
app/Services/Fastly.php
config/services.php
tests/Http/PostTest.php

This pull request includes some more cleanup. 🍃
Commit-by-commit! 👁
This is just some more follow-up from #916. My goal is to remove more "old" unused functionality to simplify things & continue to unify places that we use different approaches.
N/A

More cleanup!

---

composer.lock

This pull request updates dependencies & "locks in" the change I made in #921.
Well, hopefully everything works this time!
See [Heroku's documentation](https://devcenter.heroku.com/articles/php-support#using-optional-extensions), which I blatantly ignored the first time!
References #921.

Update dependencies & Heroku extensions.

---

app/Http/Controllers/Web/ImagesController.php

This pull request adjusts our cache headers to try to fix [an issue where responses from this endpoint had usually short TTLs in Fastly](https://dosomething.slack.com/archives/C0YGXUE01/p1573490566073600). I've swapped from `Cache-Control: s-max-age` to `Surrogate-Control`, and use a separate `Cache-Control: no-cache` to tell browsers that they must re-validate before serving from cache...
Does this seem sensible? If so, let's try it out!
Here's [Fastly's cache header documentation](https://docs.fastly.com/en/guides/cache-control-tutorial) and MDN's [`Cache-Control` documentation for browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) for context on why I chose to try these cache headers.
I'll make a ticket in a sec! …

Adjust cache headers to try to fix short Fastly TTL.

---

app/Models/Traits/HasCursor.php

This pull request fixes an issue where campaigns with no pending posts wouldn't ever appear if they weren't on the first page of results. This meant that campaign leads could not find campaigns that had not launched yet (or for whatever other reason had no pending posts).
The actual change is pretty small, but I also did another pass on comments on this query.
This was a funny bug – it turns out that [you can't do a `WHERE column = NULL` query in SQL](https://stackoverflow.com/a/9581790), and so our second case here was failing (and so once we hit all the campaigns with no pending posts at the end of this list, we couldn't continue paginating through them).
This adjusts the query to check `WHERE ($column = $sortCursor OR $column IS NULL) AND id > $id` instead, so that we still get those …

Fix issue with cursor pagination and null values.

---

.github/PULL_REQUEST_TEMPLATE.md

This pull request fixes the "What's this PR do?" heading to be consistent with the others.
🔠
References #961.
N/A

Fix inconsistent heading in PR template.

---

.styleci.yml
app/Models/ActionStat.php
app/Services/Fastly.php
app/helpers.php
docs/endpoints/events.md
package-lock.json
resources/assets/components/Campaign/index.js
tests/Http/SignupTest.php
tests/WithMocks.php

This pull request updates the endDate field in the Campaign page so that it is looking for the correct property name `endDate` vs `end_date`
👀 
All of the other file changes are coming from styleCi spacing failures.
References [Pivotal #170090422](https://www.pivotaltracker.com/story/show/170090422).

Updating End Date Field on Campaign Page

---

app/Models/Campaign.php
app/helpers.php

This pull request adds a helper function to help DRY #978 a bit
👀 
Aaron [pointed this out](https://github.com/DoSomething/rogue/pull/978#pullrequestreview-339507973) on my last PR.
References [Pivotal # 170090422](https://www.pivotaltracker.com/story/show/170090422).

Quick clean up for adding a helper function

---

tests/Console/example-delete-input.csv

This pull request removes an unused test file left behind in #989.
👀
References [Pivotal #170953002](https://www.pivotaltracker.com/story/show/170953002).

Cleanup: Remove old example CSV.

---

resources/views/pages/faq.blade.php
resources/views/pages/home.blade.php

Change the help message from #team-product to #help-product

Updated the the product slack channel name

---

app/Http/Requests/PostRequest.php

This pull request updates the validation rule for the status of a `voter-reg` post, per changes in https://github.com/DoSomething/chompy/pull/153.  Refs https://github.com/DoSomething/northstar/pull/1005
👀 
🌵 
References [Pivotal #171737617](https://www.pivotaltracker.com/story/show/171737617).

Adds new values for voter-reg post status validation

---

.env.example
composer.json
composer.lock
config/scout.php

This pull request adds the initial setup for Laravel Scout, so we can begin indexing our campaign data in Algolia.
👀 
References [Pivotal #172660182](https://www.pivotaltracker.com/story/show/172660182).

Adding Laravel Scout

---

app/Http/Controllers/GroupTypesController.php
docs/endpoints/README.md
docs/endpoints/group-types.md
routes/api.php
tests/Http/GroupTypeTest.php

This pull request adds a show endpoint for the `GroupType` resource introduced in #1026.
👀 
🧄 
References [Pivotal #172688197](https://www.pivotaltracker.com/story/show/172688197).

Adds GET /api/v3/group-types/:id

---

app/Http/Controllers/GroupsController.php
app/Http/Transformers/GroupTransformer.php
app/Models/Group.php
database/migrations/2020_06_01_000000_create_groups_table.php
docs/endpoints/README.md
docs/endpoints/groups.md
routes/api.php

This pull request adds a `Group` model, and related `GET /api/v3/groups` and `GET /api/v3/groups/:id` endpoints.
👀 
The [technical spec](https://docs.google.com/document/u/1/d/1Uv08So_A-SOxty5XfYPcq3SxrFV5B41FsM63D4ECPKA/edit) goes into detail on how this resource will be used.
References [Pivotal #172541936](https://www.pivotaltracker.com/story/show/172541936)

Adds Group model and GET /api/v3/groups endpoint

---

app/Http/Controllers/Web/GroupTypesController.php
app/Http/Controllers/Web/GroupsController.php
tests/Http/Web/GroupTest.php

This pull request fixes up validation TODOs from #1033 and #1030, and adds some basic test coverage that was missing in #1033 
👀 
🏺 
Last PR for [Pivotal #172541916](https://www.pivotaltracker.com/story/show/172541916).

Adds tests for Group web controller + fixes validation TODOs

---

package-lock.json
resources/views/campaigns/create.blade.php
resources/views/campaigns/edit.blade.php
resources/views/forms/select.blade.php

This pull request adds an `isOptional` flag to the form select blade template to decide whether the disabled attribute is added to the default option.
👀 
For most of the dropdowns on the site, we want to be able to require a user to select an option and use the default as strictly a placeholder. In the case of the groupType dropdown, we are adding the ability for users to deselect a group type if needed.
References [Pivotal # 173454237](https://www.pivotaltracker.com/story/show/173454237).

Removing Disabled Attribute on Form Dropdowns to allow for deselecting

---

app/Models/Club.php
database/migrations/2020_08_14_000000_create_clubs_table.php

This pull request adds a [migration](https://laravel.com/docs/6.x/migrations) and model for a new Clubs table.
commit-by-commit for a touch of annotation for some of the columns. But this should be pretty straightforward! You can run the migration locally, create a club and rollback to validate:
```
$ php artisan migrate
$ php artisan tinker
$ >>> Rogue\Models\Club::create(['name' => 'Test Club', 'leader_id' => '123', 'location' => 'US-NY', 'city' => 'NYC'] )
=> Rogue\Models\Club {#4388
name: "Test Club",
leader_id: "123",
location: "US-NY",
city: "NYC",
updated_at: "2020-08-17 14:18:43",
created_at: "2020-08-17 14:18:43",
id: 1,
}
> exit
$ php artisan migrate:rollback
```
We're making Club official!
References [Pivotal #174299924](https://www.pivotaltracker.com/story/show/174299924). …

Add Clubs Table

---

composer.json
composer.lock

Reverts DoSomething/rogue#1104, now that our dev database has been seeded with sample voter registration `action-stats`: https://activity-dev.dosomething.org/actions/30.

Revert "Moves faker out of dev dependencies"

---

app/Services/Gambit.php

This pull request fixes a typo'd import in #1129.
This fixes a [typo I made](https://github.com/DoSomething/rogue/pull/1129#issuecomment-705849122). You can see the actual namespace [here](https://github.com/guzzle/guzzle/blob/c3927bc669178cd051d1bee595387ef80f31acd8/src/Exception/ClientException.php).
I wonder if we can set up a linter rule to check this? I'm surprised it didn't error out!
References [Pivotal #174827024](https://www.pivotaltracker.com/story/show/174827024).

Fix Guzzle import.

---

docs/README.md
docs/features/clubs.md
routes/web.php

This pull request
Adds a new `/features` directory to our documentation for documenting Rogue specific 'features' beyond the typical API endpoint documentation
Adds some documentation around the Clubs feature
https://github.com/DoSomething/rogue/commit/f88ab4fe20b80f56a5490117cadf7f93e83b927c I snuck this in because I bumped into this route randomly but it doesn't actually exist
Is this a good idea? 
Does this just belong in Phoenix and forget it?
I called this `/features` but this could also be something like `/resources` or whatnot
👁️ The documentation itself (I tried to strike some balance between technical and human friendly)
I didn't feel like this mapped neatly to a doc in Phoenix, but felt like this could use 📜 
More to come on the Phoenix side of things though to document the …

Clubs Documentation

---

docs/features/algolia.md

This pull request adds some documentation around our Algolia campaigns index.
👀 
I used some of [@weerd's notes](https://gist.github.com/weerd/b1a3eb6640072410e4e1010d2bf8aac3) as reference.
References [Pivotal #175981104](https://www.pivotaltracker.com/story/show/175981104).

Add some Algolia documentation
